- hatari/fix-name-conflicts.patch
- hatari/riscv64.patch
This patch is ugly. `REG_A0` is already defined in `sys/ucontext.h` on RISC-V.
Request for better workaround.
> addpkg: hatari

- microsoft-gsl/riscv64.patch
The two things being tested here are deprecated and already removed in the master branch.
> addpkg: microsoft-gsl

- clpeak/riscv64.patch
This patch applies unreleased changes fixing krrishnarraj/clpeak#73.
Could get upstreamed to Arch Linux.
> addpkg: clpeak

- gf2x/riscv64.patch
URL patch could get upstreamed to Arch Linux.
> addpkg: gf2x

- java-rxtx/fix-format-security.patch
- java-rxtx/fix-riscv64-build.patch
- java-rxtx/riscv64.patch
`fix-format-security.patch` could get upstreamed to Arch Linux.
Upstream source is **NO LONGER MAINTAINED**.
> addpkg: java-rxtx

- qt5-webkit/riscv64.patch
1. Reference https://github.com/qtwebkit/qtwebkit/pull/982 ,set `-DTHREADS_PREFER_PTHREAD_FLAG=ON` .
2. Since
```
/build/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/assembler/MacroAssembler.h:64:2: error: #error "The MacroAssembler is not supported on this platform."
64 | #error "The MacroAssembler is not supported on this platform."
```
so set `-DENABLE_JIT=OFF`.
> addpkg: qt5-webkit

- libltc/riscv64.patch
Force `-j1` to avoid conflict `mv` operations.
> addpkg: libltc

- spectmorph/riscv64.patch
Submitted a PR to upstream: https://github.com/swesterfeld/spectmorph/pull/13
The checksum of `spectmorph-0.5.2.tar.bz2` has changed.
> addpkg: spectmorph

- gist/riscv64.patch
Arch Linux use `ruby-ronn-ng` instead of `ruby-ronn` now. The build script should make a small change.
The original `PKGBUILD` also failed in `x86_64`.
Upstream Bug Report: https://bugs.archlinux.org/task/73170
> addpkg: gist

- efitools/efitools-1.9.2-riscv64_build.patch
- efitools/riscv64.patch
Add riscv64 build support.
If build failed with error:
```
objcopy -j .text -j .sdata -j .data -j .dynamic -j .dynsym \
-j .rel -j .rela -j .rel.* -j .rela.* -j .rel* -j .rela* \
-j .reloc -O binary HelloWorld.so HelloWorld.efi
openssl req -new -x509 -newkey rsa:2048 -subj "/CN=DB/" -keyout DB.key -out DB.crt -days 3650 -nodes -sha256
Generating a RSA private key
...+++++
...............................................+++++
writing new private key to 'DB.key'
-----
sbsign --key DB.key --cert DB.crt --output HelloWorld-signed.efi HelloWorld.efi
Invalid PE header magic
make: *** [Make.rules:130: HelloWorld-signed.efi] Error 1
```
`sbsigntools` should be patched first. See #524
> addpkg: efitools

- qt5-base/riscv64.patch
Note that removal of `libfbclient` from `makedepends` might be unnecessary. Currently working on building `libfbclient` on RISC-V.
> updpkg: qt5-base

- dtc/riscv64.patch
> upgpkg: dtc 1.6.1-3

- portmidi/0001-fix-build-with-Werror-format-security.patch
- portmidi/riscv64.patch
upstream's commit https://github.com/mixxxdj/portmidi/commit/7c82f8873962045d2aa6b1e02e1431c073ec13b4 may fix build with `-Werror-format-security`, but without a tag release.
> addpkg: portmidi

- nodejs-lts-gallium/riscv64.patch
6 test cases will fail in QEMU, but can pass on SiFive Unmatched boards.
```
test/parallel/test-child-process-spawn-argv0.js
test/parallel/test-dgram-multicast-set-interface.js
test/parallel/test-memory-usage.js
test/parallel/test-memory-usage-emfile.js
test/parallel/test-setproctitle.js
test/parallel/test-worker-memory.js
```
> addpkg: nodejs-lts-gallium

- python-pytest-flake8/riscv64.patch
upstream pr has force pushes, which break the checksum.
https://github.com/tholo/pytest-flake8/pull/82#issuecomment-999525745
> addpkg: python-pytest-flake8

- trash-cli/riscv64.patch
Package [python-six](https://archlinux.org/packages/extra/any/python-six/) is no longer a dependencies of [python-packaging](https://archlinux.org/packages/extra/any/python-packaging/) in official testing repo.
python-setuptools -> python-packaging -> python-six
So `python-six` is missing in checkdepends now.
See also: 
https://github.com/andreafrancia/trash-cli/blob/6af27f3f1dd79a2b0989db618be9f10215c230c8/requirements-dev.txt#L1-L3
> addpkg: trash-cli

- glibc/riscv64.patch
- Add `!lto` option to fix `getcontext.S` compilation failed
- Trim `-Wp,-D_FORTIFY_SOURCE=2` from `CFLAGS` to get rid of `error: inlining failed in call to ‘always_inline’ ‘syslog’: function not inlinable` (see https://bugs.archlinux.org/task/73530)
> updpkg: glibc

- python-mtrpacket/riscv64.patch
`gnu-netcat` does not work properly on `riscv64` architecture, causing the 2nd test case to fail. This is not related to `qemu`.
> addpkg: python-mtrpacket

- rime-luna-pinyin-bootstrap/PKGBUILD
rime-luna-pinyin and rime-stroke have circular dependency.
Using yaml data only for bootstrap.
> addpkg: rime-luna-pinyin-bootstrap

- alertmanager/riscv64.patch
```
flag provided but not defined: -flto
```
> addpkg: alertmanager

- rust/riscv64.patch
`rust-1.56.0`:
* Update to 1.56.0 (critical version for edition2021)
* LLVM13 rebuild
This patch is based on following `PKGBUILD` file:
https://github.com/archlinux/svntogit-packages/blob/1398be71b3b05a8be83cede23a64bdf2d0d1f99e/trunk/PKGBUILD
Note:
* This patch requires `llvm12-libs`
* `makedepends` won't contain `llvm12-libs` in 1.58.0 update
> updpkg: rust

- python-cucumber-tag-expressions/riscv64.patch
- Arch Linux x86_64 status is [out of date](https://archlinux.org/packages/community/any/python-cucumber-tag-expressions/).
- Upstream change url from https://github.com/cucumber/tag-expressions-python to https://github.com/cucumber/tag-expressions
- This patch needs to be used on current trunk (https://github.com/archlinux/svntogit-community/commit/29f21c5803115c1d4d92e75ea49bdb60d7f1188d).
- checkdeps (python-pytest-html) need rebuild first.
> addpkg: python-cucuber-tag-expressions

- mixxx/0000-fix-unsupported-tests.patch
- mixxx/riscv64.patch
Currently, it's not possible for us to tweak the way `NaN`s are handled.
See also: https://github.com/ospray/rkcommon/issues/7
> addpkg: mixxx

- gn/riscv64.patch
ld can't link soft-float modules with double-float modules with lto enabled. This package can be built with the lto option off. But lto is not the main reason for the build failure. So this patch can be removed when lto is correctly handling the float module.
> addpkg: gn

- gnome-passwordsafe/remove-incorrect-i18n.merge_file-argument.patch
- gnome-passwordsafe/riscv64.patch
Note: The latest upstream release changed the project name from "Passwordsafe" to "Secrets" which may cause the package name of archlinux to become the latter one.
> addpkg: gnome-passwordsafe

- gjs/riscv64.patch
According to upstream [hacking guide](https://gitlab.gnome.org/GNOME/gjs/-/blob/1.70.1/doc/Hacking.md#valgrind), running the test suite under Valgrind's memcheck tool should use args `--setup=valgrind`, but it doesn't actually do this in tests on official x86_64 repository. [FS#73716](https://bugs.archlinux.org/task/73716)
> addpkg: gjs

- linuxsampler/riscv64.patch
LTO plugin for clang is broken. Disable it.
> fixpkg: linuxsampler

- js91/riscv64.patch
- js91/tests-skip-some-tests-on-rv64.patch
1. Refer to [js78](https://github.com/felixonmars/archriscv-packages/pull/87) to determine mozconfig options .
2. Refer to [this](https://sources.debian.org/patches/mozjs78/78.4.0-2/tests-Use-DEB_HOST_ARCH_BITS-to-skip-some-tests-on-64-bit.patch/) to skip some tests.(Some tests need to be skipped on 64-bit architectures.)
> Addpkg: js91

- xdg-desktop-portal-bootstrap/PKGBUILD
My fault :cry: 
Build order: `xdg-desktop-portal-bootstrap` -> `xdg-desktop-portal`
> xdg-desktop-portal-bootstrap: fix dir

- menu-cache-bootstrap/PKGBUILD
Build order: `menu-cache-bootstrap` -> `libfm` -> `menu-cache`
> addpkg: menu-cache-bootstrap

- scummvm/riscv64.patch
LTO disabled due to:
```
g++: fatal error: Killed signal terminated program lto1
compilation terminated.
lto-wrapper: fatal error: /usr/bin/g++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```
> addpkg: scummvm

- valgrind/riscv64.patch
Uses the working branch at https://github.com/petrpavlu/valgrind-riscv64/
It's not feature complete but should save us quite some patches.
> addpkg: valgrind

- muse/riscv64.patch
Disabled LTO due to the following errors:
```
(trimmed)
/usr/bin/ld: driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::latencyCompWriteOffsetMidi(bool) const'
/usr/bin/ld: libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::fileName() const'
/usr/bin/ld: driver/libmuse_driver.so: undefined reference to `MusECore::MidiDevice::canDominateEndPointLatencyMidi(bool) const'
/usr/bin/ld: libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::pluginID()'
/usr/bin/ld: libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::readConfiguration(MusECore::Xml&, bool)'
/usr/bin/ld: libmuse_lv2host_module.so: undefined reference to `MusECore::SynthIF::setOn(bool)'
/usr/bin/ld: driver/libmuse_driver.so: undefined reference to …
```
> addpkg: muse

- flac/riscv64.patch
See https://bugs.archlinux.org/task/71468
The assigned arch pkg repo maintainer has abandoned this task for over half a year, so I think it might be better for us to patch this temporarily despite waiting for his patch.
> addpkg: flac

- sfizz/riscv64.patch
Leaf package `vst3sdk` needs to be built before building this package. `vst3sdk`'s status is stalled; it does not depend on `gtkmm3` any more, and could be built directly from source.
> upgpkg: sfizz

- npm/riscv64.patch
The `node ./bin/npm-cli.js install --ignore-scripts --no-audit` command is provided in `Makefile`. In practice, this `Makefile` target might cause the test to fail (in a vague way) if it didn't install dependencies correctly.
This PR attempts to make sure dependencies are correctly installed in `prepare()` stage.
> addpkg: npm

- non-sequencer/riscv64.patch
FS#72109
> Also note that `CXXFLAGS+=" -std=c++14"` must be appended before waf configure to make it work. Otherwise, g++ will complain:
>
> ```
> ../sequencer/src/grid.H:127:11: error: reference to ‘data’ is ambiguous
> 127 | const data * volatile _rd;
>     |       ^~~~
> ```
>
> This is caused by `using namespace std;` and `std::data`.
This identifier occurs in such a great amount of files, that simply renaming the `data` identifier becomes too risky.
> addpkg: non-sequencer

- gcc/riscv64.patch
Package `libisl`, required by `libgccjit`, needs to be built before attempting to build `gcc`. It is marked as `#ready` now.
> upgpkg: gcc

- gauche-bootstrap-riscv64/PKGBUILD
**Build order:**
`gauche-bootstrap-riscv64` -> `gauche`.
**Notes:**
Due to this program's incorrect determination of argv[0], building in QEMU is not supported.
> addpkg: gauche-bootstrap-riscv64

- prometheus-blackbox-exporter/riscv64.patch
This patch fix the -flto flag not found issue.
Notice:
- One of the test needs to resolve ipv6.google.com, so a proper resolver is required.
> addpkg: prometheus-blackbox-exporter

- firefox/makotokato-riscv64-support-and-zenithal-backported.patch
- firefox/riscv64.patch
Remove the code `Add toolchain prefix to strip` from `makotokato-riscv64-support-and-zenithal-backported.patch`, because the `strip` option is turned on in `moz.configure`.
> updpkg: firefox to 98.0

- python-behave/riscv64.patch
- depends: python-cucumber-tag-expressions #618 should build first.
- checkdeps: python-pytest-html, python-pytest-metadata should rebuild first.
> addpkg: python-behave

- llvm/riscv64.patch
Backport for Rust 1.59.0
Related PR:
Divergence: https://github.com/rust-lang/llvm-project/pull/121
Direct cause for build failure on RISC-V: https://github.com/rust-lang/stdarch/pull/1271 , https://github.com/rust-lang/stdarch/pull/1278
> addpkg: llvm

- nx/1023.patch
- nx/riscv64.patch
1. Split patches from riscv64.patch.
2. Remove duplicate patches.
> updpkg: nx to 3.5.99.26

- wit/riscv64.patch
This should fix the below error.
```text
/usr/bin/ld: /tmp/lto-llvm-d65f10.o: can't link soft-float modules with double-float modules
```
> addpkg: wit

- libretro-sameboy/riscv64.patch
This should fix the linker error:
1. /usr/bin/ld: warning: LLVM gold plugin: <unknown>:0:0: loop not unrolled:
the optimizer was unable to perform the requested transformation; the
transformation might be disabled or specified as part of an unsupported
transformation ordering
2. /usr/bin/ld: /tmp/lto-llvm-2e9ce6.o: can't link soft-float modules with
double-float modules
> addpkg: libretro-sameboy

- miniserve/riscv64.patch
There are multiple ring denpendencies in miniserve. And the `[patch]`
manifest section can help us overwrite all the dependency.
This patch declare that we're patching the source crates.io. This can
effectively add the git source of `ring` to the crates.io registry.
Whenever crates.io is queried for versions of `ring` it will return the
git source.
Reference:
----------
* https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html
> upgpkg: miniserve

- stylua/riscv64.patch
This should fix the `error: Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu".` error.
> addpkg: stylua

- riscv64.patch
This should fix the `error: Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu".` error.
> addpkg: selene-linter

- rustypaste-cli/riscv64.patch
This patch fix two issue:
* error: Error loading target specification: Could not find specification
for target "riscv64-unknown-linux-gnu".
* ring: thread 'main' panicked at 'called `Option::unwrap()` on a `None`
value'
> addpkg: rustypaste-cli

- nodejs-lts-gallium/riscv64.patch
6 test cases will fail in QEMU, but can pass on SiFive Unmatched boards.
See #582
> upgpkg: nodejs-lts-gallium

- sympol/riscv64.patch
Fix uninstalled dependency: `bliss` and bump pkgrel to 10.1
`namcap` reports reference to `libbliss.so` from `libsympol.so.0.1.9`
> fixpkg: sympol

- difftastic/riscv64.patch
Fixed error: `Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu".`
> addpkg: difftastic

- step-ca/riscv64.patch
This patch resolves the following test error:
```
panic: test timed out after 10m0s
```
The tests in [github.com/smallstep/certificates/kms/pkcs11/pkcs11_test.go](https://github.com/smallstep/certificates/blob/dc9db5fbbad2d722b553beaa49775b88e6342f90/kms/pkcs11/pkcs11_test.go) are time-costly. Sometimes they reach the time limit of 10 minutes.
> addpkg: step-ca

- cargo-msrv/riscv64.patch
This patch resolves the following build error:
```
Caused by:
process didn't exit successfully: `/build/cargo-msrv/src/cargo-msrv-0.15.1/target/release/build/ring-59766f52eca1bd5e/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> upgpkg: cargo-msrv

- golang-github-nfnt-resize/riscv64.patch
This patch resolves the following build error:
```
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
FTR: Upstream PR: nfnt/resize#70; Bug report to Arch Linux: [FS#74310](https://bugs.archlinux.org/task/74310)
> addpkg: golang-github-nfnt-resize

- cargo-nextest/riscv64.patch
This patch resolves the following build error:
```
Caused by:
--- stderr
```
> addpkg: cargo-nextest

- songrec/riscv64.patch
This patch resolves the following build error:
```
Caused by:
--- stderr
```
> addpkg: songrec

- linux/riscv64.patch
Turns out that the timestamp of `.config` means nothing (because echo actually does not work either). `make olddefconfig` only calls `scripts/kconfig/conf` and does not touch any other thing.
Revert to doing a `make mrproper` for now.
> upgpkg: linux

- element/riscv64.patch
- qemu-user-blacklist.txt
<details>
<summary>Fixed lock-free static assertion errors</summary>
```
In file included from ../libs/JUCE/modules/juce_core/juce_core.h:224,
from ../libs/JUCE/modules/juce_graphics/juce_graphics.h:57,
from ../libs/JUCE/modules/juce_gui_basics/juce_gui_basics.h:56,
from ../libs/JUCE/modules/juce_audio_processors/juce_audio_processors.h:56,
from ../libs/jlv2/modules/jlv2_host/jlv2_host.h:60,
from ../libs/compat/JuceHeader.h:17,
from ../src/ElementApp.h:21,
from ../src/engine/AudioEngine.h:22,
from ../src/session/Session.cpp:20:
../libs/JUCE/modules/juce_core/memory/juce_Atomic.h: In instantiation of ‘juce::Atomic<Type>::~Atomic() [with Type = bool]’:
../src/engine/Transport.h:33:13:   required from here
../libs/JUCE/modules/juce_core/memory/juce_Atomic.h:58:43: error: static assertion …
```
> addpkg: element

- wakatime/riscv64.patch
Arch Linux has upgraded wakatime so that https://github.com/wakatime/wakatime-cli/pull/645.patch is no longer needed.
> upgpkg: wakatime

- eva/riscv64.patch
Fixed error: `Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu".`
> addpkg: eva

- libretro-dolphin/riscv64.patch
Fixed error:
```
/usr/bin/ld: /tmp/lto-llvm-f63000.o: can't link soft-float modules with double-float modules
/usr/bin/ld: failed to merge target specific data of file /tmp/lto-llvm-f63000.o
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
> fixpkg: libretro-dolphin

- nsjail/riscv64.patch
After the official Arch Linux repository upgraded this package, the patch and compilation no longer work.
This PR fixed both.
> upgpkg: nsjail

- av1an/fix-ffmpeg-sys.patch
- av1an/riscv64.patch
This patch upgrade the ffmpeg-next version to 5.0.3, which also upgrade
the ffmpeg-sys-next crate to 5.0.1. And it can improve clang-sys compatibility
with riscv64 system libraries.
> addpkg: av1an

- libgweather-4/riscv64.patch
~~1. There have been problems with `pylint` while it's (probably?) worthless to check for linting when packaging.~~ (fixed in #1092)
2. Increased test timeout (qemu is slow, give it more time) (it's taking 41secs avg on my Laptop)
> addpkg: libgweather-4

- sheldon/riscv64.patch
Fixed error: `error: Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu".`
> addpkg: sheldon

- lldb/riscv64.patch
Not bumping `pkgrel` since rebuild is not required, and we can rebuild when the next release / upstream `pkgrel` bump happens.
> upgpkg: lldb

- qemu-user-blacklist.txt
Stuck in 'Test #20: testsshagent' in QEMU, but can pass on Unmatched boards.
No need to patch.
> addpkg: keepassxc

- pipe-rename/riscv64.patch
Fixed error: `Error loading target specification: Could not find specification for target "riscv64-unknown-linux-gnu"`
> addpkg: pipe-rename

- .github/workflows/test.yml
- test.sh
Starting from today (15/4/2022), the sync script is aware of repos/
branch and won't use trunk anymore. Patches in this repository is
now defined as patches for stable repos (core, extra, community)
instead of trunk or testing/staging repos.
> Test repos branch instead of trunk

- libsecp256k1/riscv64.patch
Fixed x86_64 asm check in upstream: https://github.com/bitcoin-core/secp256k1/pull/1104
> addpkg: libsecp256k1

- hck/fix-libz-ver.patch
- hck/riscv64.patch
This patch fix two error. One is the rustc could not find specification for target "riscv64-unknown-linux-gnu" error.
Another one is related to the libz-sys version. Zlib fixes cmake arch detection in [zlib-ng #942], and the crate libz-sys update the zlib binding in [version 1.1.4]. However, the hck is using the 1.1.3 version and causing itself can't be compiled in RISC-V.
[zlib-ng #942]: https://github.com/zlib-ng/zlib-ng/commit/81f1c8a41bd1427707f402450de8820816760fca
[version 1.1.4]: https://github.com/rust-lang/libz-sys/commit/5c4704efa6ae73a95c3c6e1ccf4bd212f927be7a
> addpkg: hck

- gdk-pixbuf2/fix-timeout.patch
- gdk-pixbuf2/riscv64.patch
- qemu-user-blacklist.txt
This patch add gdk-pixbuf2 into noqemu list and increase the timeout limit for "pixbuf-randomly-modified" test.
This package can't be built in qemu user environment. The "pixbuf-randomly-modified" test randomly modifies the file and then tries to load it. This test process needs vast amounts of RAM and then the test will be killed by the SIGKILL signal.
It can be built successfully on Unmatched board, but we still can't pass the "picbuf-randomly-modified" test. This time the failure is caused by timeout. 500s is a reasonable value for the Unmatched performance.
> addpkg: gdk-pixbuf2

- qt6-base/riscv64.patch
Add compilation flag to disable `forkfd_pidfd`.
> addpkg: qt6-base

- findomain/riscv64.patch
This PR fixed error:
```
Caused by:
process didn't exit successfully: `/build/findomain/src/Findomain-8.1.0/target/release/build/ring-923f77b482ab3681/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Closes #732 as outdated.
> addpkg: findomain

- echoping/riscv64.patch
Investigation from [FS#73709](https://bugs.archlinux.org/task/73709):
> `echoping` fails to build from source due to a configure check breaking when LTO is enabled so `libm` is not added to the libs to link to.
Disabling LTO for `echoping` to fix that.
> addpkg: echoping

- cmake/fix-openmp-find-path.patch
- cmake/riscv64.patch
The `NO_DEFAULT_PATH` option in `FindOpenMP.cmake` is causing cmake not able to correctly find paths and libraries of openmp. Disabling this.
> addpkg: cmake

- qemu-user-blacklist.txt
A test in package tmuxp will run into infinite loop. The test,
"test_automatic_rename_option", use the pane name as loop break
condition. However in the QEMU environment, the name of the pane will
always be "qemu-riscv64-static", no matter what program user is using.
Upstream report:
https://github.com/tmux-python/tmuxp/issues/620#issuecomment-1102074020
> Update noqemu list

- python-gdstk/riscv64.patch
By default gcc uses `-ffp-contract=fast` which causes precision lost in tests. This patch disables this behavior.
> addpkg: python-gdstk

- firefox/Remove-VideoFrameSurfaceVAAPI-and-use-VideoFrameSurface-only.patch
- firefox/makotokato-riscv64-support-and-zenithal-backported.patch
- firefox/riscv64.patch
1. firefox build error: undefined reference to `mozilla::VideoFramePool::~VideoFramePool()`,see https://bugzilla.mozilla.org/show_bug.cgi?id=1758610 .
2. this patch use `hw_device_ctx`,and `hw_device_ctx` was imported in https://phabricator.services.mozilla.com/D141831 .
3.Combine the patches above into one patch.
> Updpkg: firefox to 99.0.1

- trivy/fix-libc.patch
- trivy/riscv64.patch
Package trivy's dependencies modernc.org/libc and modernc.org/sqlite add riscv64 support in later version. This patch replace them with the correct version.
> addpkg: trivy

- cargo-spellcheck/riscv64.patch
This patch fixes the target issue related to rustc and build error from ring.
```
Caused by:
--- stderr
```
```
Caused by:
process didn't exit successfully: …
```
> addpkg: cargo-spellcheck

- rustup/riscv64.patch
The following linking error no longer occurs after disabling LTO.
```
error: linking with `cc` failed: exit status: 1
|
= note: "cc" "/build/rustup/src/rustup-1.24.3/target/release/deps/rustup_init-0609a9a7d297ef04.rustup_init.a668c382-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/build/rustup/src/rustup-1.24.3/target/release/deps" "-L" "/usr/lib" "-L" "/build/rustup/src/rustup-1.24.3/target/release/build/ring-a26af6b5394ccfd1/out" "-L" "/build/rustup/src/rustup-1.24.3/target/release/build/sys-info-5d227f125ca2d25a/out" "-L" "/usr/lib" "-L" "/build/rustup/src/rustup-1.24.3/target/release/build/zstd-sys-fdff5888885359a8/out" "-L" "/usr/lib/rustlib/riscv64gc-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustccxgqK7/libzstd_sys-a1b7546eb81175df.rlib" …
```
> upgpkg: rustup

- diskonaut/fix.patch
- diskonaut/riscv64.patch
This patch fix three error:
1. The [target specification issue].
2. Crate libc can not be compiled due to symbol missing.
This is fixed in [rust-lang/libc PR #2668], and release in 0.2.118
version.
3. Test failure
Some tests of diskonaut depend on the previous events. It take a snapshot of the TUI pixels output, then compare those snapshot pixel by pixel to determine if the cli is working correctly. However those test are not reliable. If the previous event took too long to finish, the TUI output will not match what is expected. The current workaround is to increase the event interval. One second interval is enough for all event to finish its jobs.
Tested in 5950x QEMU environment.
[target specification issue]: https://github.com/felixonmars/archriscv-packages/issues/670#issuecomment-10256 …
> addpkg: diskonaut

- deja-dup/fix-testsuite.patch
- deja-dup/riscv64.patch
This patch will fix the duplicate testsuite.
Upstream:
https://gitlab.gnome.org/World/deja-dup/-/commit/60856db2ca1b37079e9a7a2e1cbbbc9d2dcb43fa
> addpkg: deja-dup

- qemu-user-blacklist.txt
The test `sanity-test` fails in QEMU, but passes on board.
> addpkg: wayland

- git-cliff/riscv64.patch
This package require `ring` in 0.7.0. This patch replace the `ring` crate with riscv64 compatible version.
> upgpkg: git-cliff 0.7.0-1

- qemu-user-blacklist.txt
The test `memcached_udp` fails in QEMU, but passes on board.
> addpkg: libmemcached-awesome

- gnu-efi/riscv64.patch
`systemd` currently fails compilation with the following errors:
```
[138/2371] Generating src/boot/efi/linuxriscv64.elf.stub with a custom command
FAILED: src/boot/efi/linuxriscv64.elf.stub
/usr/bin/cc -o src/boot/efi/linuxriscv64.elf.stub -fuse-ld=bfd -L /usr/lib -nostdlib -T /usr/lib/elf_riscv64_efi.lds -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Wl,--warn-common -Wl,-Bsymbolic -z nocombreloc /usr/lib/crt0-efi-riscv64.o -shared -Wl,--defsym=EFI_SUBSYSTEM=0xa -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow …
```
> addpkg: gnu-efi

- trivy/riscv64.patch
It's recommended to build this package on board, since the go build process often falls asleep in QEMU and never wake up.
> upgpkg: trivy 0.27.0-1

- trivy/riscv64.patch
This package might fall asleep in QEMU.
> upgpkg: trivy 0.27.1-1

- typescript-language-server/riscv64.patch
The tests no longer fail after increasing the tests' timeout.
Previous error log:
```
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
> addpkg: typescript-language-server

- typescript-language-server/riscv64.patch
- typescript-language-server/typescript-language-server-mocha-timeout.patch
This change fixes timeout in pre- and post-test hook.
> fixpkg: typescript-language-server

- mesa/riscv64.patch
- Ignore useless package functions
- Reduce context to 1 to avoid tracking `pkgver` and `pkgrel`
- Turn off useless parts (GL on D3D12 makes no sense outside WSL, and Gallium Nine is useless without WINE)
> upgpkg: mesa

- mold/riscv64.patch
Fixed error:
```
Testing debug-macro-section ... mold: fatal: library not found: gcc_s
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.linux:6: elf/debug-macro-section.sh] Error 1
make[1]: *** Waiting for unfinished jobs....
```
Based on the previous patch, this PR disabled the test `debug-macro-section`.
> upgpkg: mold

- angle-grinder/riscv64.patch
This patch fixes the target issue from Rust and build errors from crate [`jemallocator`](https://crates.io/crates/jemallocator).
> addpkg: angle-grinder

- gcc/riscv64.patch
Adapt to gcc 12.1.0-1
Patches added in #1050 are removed because of the new release.
> updpkg: gcc

- test.sh
This patch update the condition logic. Script will try cd into `$REPO-x86_64` only now.
> Lock the arch value to x86_64

- gitlab-exporter/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
> addpkg: gitlab-exporter

- busybox/riscv64.patch
Make it dynamic for now as https://github.com/sabotage-linux/kernel-headers does not support RISC-V yet.
> addpkg: busybox

- wolfssl/riscv64.patch
EdDSA448 requires SHAKE256 which requires SHA-3.
SHA-3 is default enabled in x86_64/aarch64 but not enabled in riscv64 by the CMakeLists.
https://github.com/wolfSSL/wolfssl/blob/v5.3.0-stable/CMakeLists.txt#L506-L513
> addpkg: wolfssl

- go-ipfs/riscv64.patch
The checksum in `go.sum` is mismatched after running `go mod edit -replace`, so `go mod download` should be run to update `go.sum`.
Also, we only need `go mod download` to download dependencies to local cache, instead of using `go mod vendor` to make a vendored copy of dependencies.
> upgpkg: go-ipfs 0.12.2-1

- qemu-user-blacklist.txt
Stuck in `check()` with qemu-user.
> addpkg: libsecret to qemu-user blacklist

- dracut-hook/60-dracut-remove.hook
- dracut-hook/90-dracut-install.hook
- dracut-hook/PKGBUILD
- dracut-hook/dracut-install
- dracut-hook/dracut-remove
We need this pacman hook to generate initramfs by dracut automatically.
Get from AUR (https://aur.archlinux.org/packages/dracut-hook).
Test in rootfs and qemu-img generator.
> addpkg: dracut-hook

- cargo-audit/riscv64.patch
- qemu-user-blacklist.txt
Fixed error:
```
Caused by:
--- stderr
```
and this package will stuck in test `advisories_found_exit_error` in qemu-user:
```
thread 'advisories_found_exit_error' panicked at 'error waiting for subprocess to terminate: operation timed out: operation timed out after 1800 …
```
> addpkg: cargo-audit

- openjade/riscv64.patch
This package failed to build because the config.guess and config.sub are
too old to recognize RISC-V.
> addpkg: openjade

- qemu-user-blacklist.txt
`check()` failed at 52-basic-load because qemu-user doesn't support
seccomp syscall, and `prctl(PR_SET_SECCOMP, SECCOMP_MODE_FILTER, )`
also failed. You can check the result by setting QEMU_STRACE. The
result is (Function not implemented) and (Invalid argument).
What's more, the package can pass `check()` in a RSIC-V board. So
I think it's proper to add libseccomp to qemu-user-blacklist.txt.
> upgpkg: libseccomp to 2.5.4

- mumble/riscv64.patch
lib32-gcc-libs is not available in riscv64 arch. Delete this dependency will not affect the build process.
> addpkg: mumble

- mesa-amber/riscv64.patch
This package failed because intel dri drivers cannot be used in riscv64,
reference: #1326 . After disabling intel dri drivers, mesa-amber can be
built normally.
> addpkg: mesa-amber

- libxxf86vm/riscv64.patch
This package failed to build because config.guess and config.sub bundled
in release tarball are too old. So force autoreconf in prepare() should
solve this problem.
Also, a bug has been filed to upstream.
https://bugs.archlinux.org/task/74869
> addpkg: libxxf86vm

- libxtst/riscv64.patch
This package failed to build because config.guess and config.sub bundled
in release tarball are too old. So force autoreconf in prepare() should
solve this problem.
Also, a bug has been filed to upstream.
https://bugs.archlinux.org/task/74868
> addpkg: libxtst

- sentry-cli/riscv64.patch
Before running the command_update test, sentry-cli will first try to get
list of filename from the github release page and get version information
with current arch and platform string as pattern.
However this project didn't officially support RISC-V. So there are no
file named `sentry-cli-riscv64-riscv64`.[^1]
Since they skip execution in their integration test[^2], it is ok to skip
the test here too.
Ref:
[1]: https://github.com/getsentry/sentry-cli/blob/master/src/api.rs#L1084
[2]: https://github.com/getsentry/sentry-cli/blob...
.../3beed9b6affd0f22e60dbae823a7ae1374c6f975/src/commands/update.rs#L40
> addpkg: sentry-cli

- libxv/riscv64.patch
This package failed to build because config.guess and config.sub bundled
in release tarball are too old. So force autoreconf in prepare() should
solve this problem. A makedepends is added due to requirements of
autoreconf.
Also, a bug has been filed to upstream.
https://bugs.archlinux.org/task/74866
> addpkg: libxv

- kubie/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
> upgpkg: kubie

- cups/riscv64.patch
The current config.guess file is outdated. This patch is a temporary
workaround. And it should be removed after the [upstream] update the guess
file.
ref:
[upstream]: https://github.com/OpenPrinting/cups/issues/404
> addpkg: cups

- libvorbis/riscv64.patch
Force `-j1` to avoid racing on moving the `.Tpo` file.
> addpkg: libvorbis

- qemu-user-blacklist.txt
Some tests fail in qemu-user, because they try to execute a non-existent command and expect an error occur, but since the implementation bug of qemu-user, spawning a non-existent command returns a `Ok` instead of a `Err`.
MRE:
```rust
fn main() {
let mut process = std::process::Command::new("nonexistcommand");
println!("result: {:?}", process.spawn());
}
```
qemu-user RISC-V returns: `result: Ok(Child { stdin: None, stdout: None, stderr: None, .. })`
x86_64 returns: `result: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })`
Board RISC-V returns: `result: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })`
<details><summary><b>Failed tests</b></summary>
```
failures:
---- overlays::remove_overlay_discard_decl stdout ----
=== stderr
Error: …
```
> upgpkg: nushell

- libc++/libc++abi-fix-demangler-for-long-double.patch
- libc++/riscv64.patch
This patch fixes the test failure in libc++abi's demangler.
> addpkg: libc++

- backuppc/riscv64.patch
This package contains outdated config.guess file and couldn't correctly
guess system type. This patch is a temporary workaround that copy the
local config.guess file into project.
> addpkg: backuppc

- qemu-user-blacklist.txt
The ninja package can be passed on the real RISC-V board.
It's the problem of qemu-user.
So added it to the blacklist.
Details:
I attempted run the PKGBUILD, and failed in the `check()` function.
`[15/22] CXX build/missing_deps_test.o`
`[16/22] CXX build/manifest_parser_test.o`
`[17/22] CXX build/graph_test.o`
`[18/22] CXX build/util_test.o`
`[19/22] CXX build/subprocess_test.o`
`[20/22] CXX build/test.o`
`[21/22] CXX build/build_test.o`
`[22/22] LINK ninja_test`
`==> ERROR: A failure occurred in check().`
`    Aborting...`
`==> ERROR: Build failed, check /var/lib/archbuild/extra-riscv64/tinysnow/build`
Then, I read the `check()` function, its content as below:
`check() {`
`   cd ninja-$pkgver `
`   python ./configure.py`
`   ./ninja ninja_test`
`   ./ninja_test`
`}`
Then I located the …
> added ninja to qemu-user-blacklist.

- perl-file-rsyncp/riscv64.patch
Fixed config.guess.
This package contains outdated config.guess file and couldn't correctly
guess system type. This patch is a temporary workaround that copy the
local config.guess file into project.
This is the same problem as some previous packages.
Ref: https://github.com/felixonmars/archriscv-packages/pull/1313.
Build passed.
> addpkg: perl-file-rsyncp

- terraform/riscv64.patch
This PR uses `go get -u` rather than patch of `go.mod` and `go.sum` to upgrade the dependency, to avoid patch fails.
> upgpkg: terraform 1.2.2-1

- freeradius/riscv64.patch
Fixed error `checking build system type... ./config.guess: unable to guess system type` by cherry-picking an upstream unreleased commit that updated the `config.guess` file.
> addpkg: freeradius

- qemu-user-blacklist.txt
Test `googletest-port-test` failed in QEMU but passed on board, seems to be caused by
```cpp
// Returns the number of active threads, or 0 when there is an error.
size_t GetThreadCount() {
const std::string filename =
(Message() << "/proc/" << getpid() << "/stat").GetString();
return ReadProcFileField<size_t>(filename, 19);
}
```
always returns 0 in QEMU.
> addpkg: gtest to qemu user blacklist

- cargo-hakari/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
> addpkg: cargo-hakari

- nettle/riscv64.patch
This package previously failed because of Valgrind. According to #896,
Valgrind is premature. So we can disable Valgrind temporarily.
> addpkg: nettle

- openipmi/riscv64.patch
Fixed config.guess.
This package contains outdated config.guess file and couldn't correctlyguess system type. 
This patch is a temporary workaround that copy the local config.guess file into project.
This is the same problem as some previous packages.
Ref: https://github.com/felixonmars/archriscv-packages/pull/1313.
Build passed.
> addpkg: openipmi

- qemu-user-blacklist.txt
- tpm2-tools/riscv64.patch
This patch backports changes which has been made in trunk. Those changes
disable lto, backport 2 patches to fix unit tests and other improvement.
This patch also add tpm2-tools to qemu-user-blacklists because of error
listed below.
```
Starting the simulator
Attempting to start simulator on port: 63821
swtpm: seccomp_load failed with errno 125: Operation canceled
Could not start simulator at port: 63821
```
It seems that this error occurred because qemu-user didn't support
seccomp.
> addpkg: tpm2-tools

- selene-linter/riscv64.patch
Fixed error:
```
Caused by:
process didn't exit successfully: `/build/selene-linter/src/selene-0.18.1/target/release/build/ring-64bec00ece0b4e9b/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> upgpkg: selene-linter

- bigsh0t/remove-march-and-disable-sse.patch
- bigsh0t/riscv64.patch
1. Bigsh0t package's [rel-2.5](https://bitbucket.org/leo_sutic/bigsh0t/commits/dd6b0f7f29775e896bc526570240f39a3860ae19#chg-CMakeLists.txt) defined options --march=navite and enabled SSE. 
2. The main branch has code that checks the intel CPU, Used to determine if the SSE option should be turned on.
PS: just wait for a new rel and this patch will be obsolete.
> addpkg: bigsh0t

- libepoxy/riscv64.patch
This patch fixes a wrapper for `dlsym()` in test, which hard-coded the glibc ABI version that libdl uses.
Upstream PR: anholt/libepoxy#270
> addpkg: libepoxy

- qemu-user-blacklist.txt
This package can be built successfully on a real board without any patch. When
building with qemu-user, failing tests are listed below.
- test_cmd_line
- test_no_std_streams
- test_no_stdin
- test_faulthandler
- test_register_chain
- test_posix
- test_chown
- test_fchown
- test_lchown
- test_close_file
- test_fexecve
- test_subprocess
- test_restore_signals
I'm not sure why they fail currently.
> addpkg: python

- bigsh0t/disable-sse.patch
- bigsh0t/riscv64.patch
[upstream](https://bugs.archlinux.org/task/75054) fixed `march=native` .
update `disable-sse.patch`
> updpkg: bigsh0t

- cclive/riscv64.patch
- cclive/update-configure-ac.patch
This patch does two things.
- Update configure.ac to make it compatible with autotools 1.16 in order
to execute `autoreconf -fiv`
- Fix the trivial issue with config.guess and config.sub
The second issue is configure.ac is outdated. According to the release
notes of autotools 1.14[1]
- The next major Automake version (2.0) will unconditionally activate
the 'subdir-objects' option.  In order to smooth out the transition,
we now give a warning (in the category 'unsupported') whenever a
source file is present in a subdirectory but the 'subdir-object' is
not enabled.
The current configure.ac lacks the 'subdir-objects' option, which will
throw an error due to '-Werror' option.
FYI, I have sent an e-mail to cclive-devel mailing list to inform the maintainers
this issue, although it haven't …
> addpkg: cclive

- cclive/update-configure-ac.patch
Fix patch. Remove excess blank spaces to match with checksum.
> upgpkg: cclive

- nextcloud-app-notify_push/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
and added sleep to fix test failures on slow machines (upstream [PR](https://github.com/nextcloud/notify_push/pull/171)).
> addpkg: nextcloud-app-notify_push

- taplo-cli/riscv64.patch
Fix `cargo`.
Removed the parameter `--target "$CARCH-unknown-linux-gnu"`
There is a confusion after successfully packed a binary package.
That is the end of std out lying some error info, and I dont know if it has a problem.
The wiki also guides us to remove the parameter.
If something needs to be improved, can ask me directly.
Please check.
Build passed.
Std out end lines:
`Checking taplo-cli-0.6.7-1-riscv64.pkg.tar.zst`
`==> Running checkpkg`
`error: target not found: taplo-cli`
`==> WARNING: Skipped checkpkg due to missing repo packages`
> addpkg: taplo-cli.

- trojan/riscv64.patch
Dependency `netcat` is actually `gnu-netcat`, which doesn't work properly on `RISC-V` architecture (Not related to `QEMU`). Replace it with `openbsd-netcat` could fix the problem of test `LinuxSmokeTest-basic` stuck.
MRE for `gnu-netcat` problem:
```bash
#!/bin/bash
function wait_port() {
until nc -z 127.0.0.1 "$1"; do
sleep 0.1
done
}
python3 -m http.server 10081 &
wait_port 10081
```
> addpkg: trojan

- coreutils/fix-test-getlogin.patch
- coreutils/riscv64.patch
- qemu-user-blacklist.txt
This package fails to build on a riscv64 real hardware due to the same
reason on x86_64. The test-getlogin doesn't handle the case
/proc/self/loginuid is -1. After being reported to the upstream gnulib,
a patch to resolve this issue has been merged on master.
Ref: https://lists.gnu.org/archive/html/bug-gnulib/2022-06/msg00001.html
I also filed a bug on ArchLinux bug tracker which backports the patch to
resolve the issue of FTBFS.
Ref: https://bugs.archlinux.org/task/75112
Currently, I'm not sure why some unit tests fail when running with
qemu-user. Failing tests are listed below.
- FAIL: tests/misc/tac-2-nonseekable.sh
- FAIL: tests/tail-2/follow-stdin.sh
> addpkg: coreutils

- progpick/riscv64.patch
`rustc` recognizes target `riscv64gc-unknown-linux-gnu` instead of `riscv64-unknown-linux-gnu`. This patch prevents the specified target triple from being passed to `cargo` to build this package.
> addpatch: progpick

- opencv/riscv64.patch
Fixed rotten patch. Disable LTO as it will cause error
```
/tmp/ccMBUcPI.ltrans3.ltrans.o: in function `.L1231':
<artificial>:(.text._ZN2cv8datasets9TR_svtImp8xmlParseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERSt6vectorINS_3PtrINS0_6ObjectEEESaISD_EE.constprop.0+0x394): relocation truncated to fit: R_RISCV_PCREL_HI20 against `.LC19'
collect2: error: ld returned 1 exit status
```
This problem will be reported to upstream `gcc` later.
> upgpkg: opencv

- qemu-user-blacklist.txt
These tests fail on qemu-user, but can pass on a RISC-V board.
```text
---- common::util::tests::test_check_coreutil_version stdout ----
run: id --version
run: no test name --version
thread 'common::util::tests::test_check_coreutil_version' panicked at 'assertion failed: `(left == right)`
left: `Err("uutils-tests-warning: no coreutils version string found for reference coreutils 'no test name --version'")`,
right: `Err("uutils-tests-warning: 'no test name' No such file or directory (os error 2)")`', tests/common/util.rs:1738:9
---- test_install::test_install_and_strip_with_non_existent_program stdout ----
current_directory_resolved: 
run: /build/uutils-coreutils/src/coreutils-0.0.14/target/release/coreutils install -s --strip-program /usr/bin/non_existent_program helloworld_linux …
```
> Add uutils-coreutils to qemu-user-blacklist

- qemu-user-blacklist.txt
`t/9.t:233:13` called fork() 🍴 while qemu-user hates forking.
`fork()` was reported successful but actually, it's not.
> qemu-user-blacklist: add glib-perl

- gcc11/riscv64.patch
Verified it works now. `libatomic.a` is a symlink to latest gcc lib.
> upgpkg: gcc11 11.3.0-4

- maturin/add-riscv64-support.patch
- maturin/riscv64.patch
add-riscv64-support.patch was backported from
https://github.com/PyO3/maturin/pull/1001
> upgpatch: maturin

- .github/workflows/rotten.yml
- find-rotten
Permission of default actions token needs to be rw.
A demo is at https://github.com/Xeonacid/archriscv-packages/pull/3. It includes the commit of this CI change because the action ran on the `actions-rmvpatch` branch (head branch of this PR) for the test instead of `master`. The action should work fine on `master`.
I leave `qemu-user-blacklist.txt` unchanged for now since it's not easy to examine whether there has been a rmvpatch PR for the package, and it may cause many conflicts if multiple packages are to be removed at the same time.
> ci: create pr for dropped packages in Arch

- gnuchess/riscv64.patch
This package's `config.guess` is too old, and the truth will be reported to upstream.
BTW, after `autoreconf`, it occurs a new error. That is lacking of `help2man` dependency, so add it to `makedepends` to avoid the same error on other machines.
Build passed.
> addpkg: gnuchess

- ldc-bootstrap/disable-static-NaN-tests.patch
- ldc-bootstrap/gdc_phobos_path.patch
- ldc-bootstrap/gdmd.PKGBUILD
- ldc-bootstrap/riscv64.patch
Build steps: `gdmd.PKGBUILD` -> `ldc(riscv64.patch based on default ldc PKGBUILD)`.
After these use the produced ldc package to rebuild ldc formally with https://github.com/felixonmars/archriscv-packages/pull/1444.
> addpkg: ldc-bootstrap

- qemu-user-blacklist.txt
- tbb/riscv64.patch
Fixed rotten patch.
Test 23 `test_task_group` will get stuck in QEMU, but pass on real boards.
> upgpatch: tbb

- libicns/riscv64.patch
The message of guess file too old will be reported to upstream.
> addpkg: libicns

- cargo-tauri/riscv64.patch
Removed `--target "$CARCH-unknown-linux-gnu"`.
After fixing, it occurred `ring` dependency error, so this patch contains two fixing places.
Build passed.
> addpkg: cargo-tauri

- mold/riscv64.patch
Environment variables used to set C and C++ compilers have been renamed in test cases.
> updpatch: mold

- wxsqlite3/riscv64.patch
The message of guess file too old will be reported to upstream.
Note:
There are some so name difference. Here is the info:
`usr/lib/libwxcode_gtk3u_wxsqlite3-3.0.so                      | usr/lib/libwxcode_gtk3u_wxsqlite3-3.2.so`
`usr/lib/libwxcode_gtk3u_wxsqlite3-3.0.so.0                    | usr/lib/libwxcode_gtk3u_wxsqlite3-3.2.so.0`
`usr/lib/libwxcode_gtk3u_wxsqlite3-3.0.so.0.0.0                | usr/lib/libwxcode_gtk3u_wxsqlite3-3.2.so.0.0.0`
`==> WARNING: Sonames differ in wxsqlite3!`
`libwxcode_gtk3u_wxsqlite3-3.0.so=0-64                         | libwxcode_gtk3u_wxsqlite3-3.2.so=0-64`
> addpkg: wxsqlite3

- rustup/riscv64.patch
This package can now be built without disabling LTO.
> upgpatch: rustup

- libafterimage/riscv64.patch
Fixed error:
```
checking build system type... ./config.guess: unable to guess system type
This script, last modified 2005-02-10, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
ftp://ftp.gnu.org/pub/gnu/config/
If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
config.guess timestamp = 2005-02-10
uname -m = riscv64
uname -r = 5.18.7-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000
/usr/bin/uname -p = unknown
/bin/uname -X     = 
hostinfo               = …
```
> upgpatch: libafterimage

- carla/carla-riscv64-portable.patch
- carla/riscv64.patch
EEL doesn't have a native RISC-V implementation, so add `EEL_TARGET_PORTABLE` to use the software-based one
> addpatch: carla

- ncnn/riscv64.patch
Disable RVV as upstream recommended for now. NCNN doesn't have proper
support for latest mainline GCC or Clang yet.
For GCC:
```
In file included from /build/ncnn/src/ncnn-20220721/src/layer.h:18,
from /build/ncnn/src/ncnn-20220721/src/layer/absval.h:18,
from /build/ncnn/src/build/src/layer/riscv/absval_riscv_rvv.h:18,
from /build/ncnn/src/build/src/layer/riscv/absval_riscv_rvv.cpp:15:
/build/ncnn/src/ncnn-20220721/src/mat.h:36:10: fatal error: riscv_vector.h: No such file or directory
36 | #include <riscv_vector.h>
|          ^~~~~~~~~~~~~~~~
```
For Clang:
```
In file included from /build/ncnn/src/build/src/layer/riscv/absval_riscv_rvv.cpp:15:
In file included from /build/ncnn/src/build/src/layer/riscv/absval_riscv_rvv.h:18:
In file included from …
```
> addpkg: ncnn

- syslog-ng/riscv64.patch
- syslog-ng/syslog-ng-remove-json-c-submodule.patch
Removed outdated submodule `json-c` in PR https://github.com/syslog-ng/syslog-ng/pull/4078.
> addpatch: syslog-ng

- openslide/riscv64.patch
Update config.guess to identify riscv64 platform.
Issue reported: https://github.com/openslide/openslide/issues/374
> addpkg: openslide

- elinks/riscv64.patch
Fixed error:
```
checking build system type... ./config/config.guess: unable to guess system type
This script, last modified 2004-09-07, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
ftp://ftp.gnu.org/pub/gnu/config/
If the version you run (./config/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
config.guess timestamp = 2004-09-07
uname -m = riscv64
uname -r = 5.18.6-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Wed, 22 Jun 2022 18:10:56 +0000
/usr/bin/uname -p = unknown
/bin/uname -X     = 
hostinfo               = …
```
> addpatch: elinks

- qemu-user-blacklist.txt
- shotgun/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
and removed it from qemu-black-list as it can now be built in QEMU.
> addpatch: shotgun

- jumpy/riscv64.patch
Fixed error:
```
Caused by:
--- stderr
```
> addpatch: jumpy

- typescript-language-server/riscv64.patch
- typescript-language-server/typescript-language-server-mocha-timeout.patch
The timeout for new versions is indicated in the new location `.mocharc.yaml`.
> upgpatch: typescript-language-server

- gcc-d-bootstrap/PKGBUILD
- gcc-d-bootstrap/gdc_phobos_path.patch
The package provides `gcc-d` to fulfill the `makedepends` of `gcc` for adding package `gcc-d` back.
> addpkg: gcc-d-bootstrap

- qemu-user-blacklist.txt
Shouldn't revert until qemu-user has its `/proc/cpuinfo` fixed.
Ref: https://github.com/facebook/rocksdb/pull/9366
> fixpkg: add rocksdb to qemu-user-blacklist

- gcc/riscv64.patch
* Adds `gcc-d` back
* `-D_FORTIFY_SOURCE=2` doesn't need to be removed now
> updpkg: gcc 12.1.1-4

- syft/fix-libc-deps.patch
- syft/riscv64.patch
Dep modernc.org/libc introduce rv64 support in v1.14.11.
This PR replace the libc and sqlite dependency version.
> addpatch: syft

- python-nodeenv/riscv64.patch
This patch applied a RISC-V support patch from [upstream] to fix the
path glob error.
[Upstream]: https://github.com/ekalinin/nodeenv/pull/313
> addpatch: python-nodeenv

- glibc/riscv64.patch
- qemu-user-blacklist.txt
This PR does two things.
- Remove changes "--disable-experimental-malloc" and "CPPFLAGS=${CPPFLAGS/-D_FORTIFY_SOURCE=2/}"
- Add glibc to qemu-user-black-list
The reason of first one is nobody can tell why we add those two changes, and if we delete those two changes, testsuite results are promising.
The reason of second one is there are 51 Failures when building in qemu-user while there are 18 Failures when building on real hardware.
14 of 18 failures are timeout.
- locale/tst-localedef-path-norm: timeout
- malloc/tst-malloc-too-large-malloc-hugetlb2: timeout
- nptl/tst-mutex10: timeout
- nss/tst-nss-files-hosts-getent: timeout
- nss/tst-nss-files-hosts-multi: timeout
- stdio-common/tst-vfprintf-width-prec: timeout
- stdio-common/tst-vfprintf-width-prec-alloc: timeout
- …
> updpatch: glibc

- qemu-user-blacklist.txt
Package can't be built in QEMU user due to the incorrect argv issue:
`Lisp error: (wrong-number-of-arguments (3 . 4) 2)`.
> noqemu: wanderlust

- gstreamermm/riscv64.patch
Apply an upstream PR to fix error:
```
/usr/include/glib-2.0/glib/gatomic.h:113:19: error: argument 2 of ‘__atomic_load’ must not be a pointer to a ‘volatile’ type
```
> addpatch: gstreamermm

- libarchive/0003-libarchive-Do-not-include-sys-mount.h-when-linux-fs..patch
- libarchive/riscv64.patch
Libarchive failed to build because of glibc 2.36 update. ArchLinux upstream fixed the issue in trunk. So, I backported the patch here. Upstream issue linked is listed below.
https://bugs.archlinux.org/task/75533
> addpatch libarchive

- qemu-user-blacklist.txt
This PR add rz-cutter into qemu blacklist. It build successfully without
any modification in unmatched board larvesta.
Qt program will meet "fatal error: 'stddef.h' file not found" when it is
built in qemu user. The QT QProcess spawned a llvm-config child process
during the build. But because of the qemu user only "forkfd_pidfd"
related issue, the llvm-config process will crash.
> noqemu: rz-cutter

- desmume/detect-arm-rather-than-exclude-x86-for-arm-specific-code.patch
- desmume/riscv64.patch
Fixed errors:
```
../desmume/desmume/src/libretro-common/features/features_cpu.c:321:31: error: ‘AT_HWCAP’ undeclared (first use in this function)
321 |    uint64_t hwcap = getauxval(AT_HWCAP);
|                               ^~~~~~~~
../desmume/desmume/src/libretro-common/features/features_cpu.c:321:31: note: each undeclared identifier is reported only once for each function it appears in
../desmume/desmume/src/libretro-common/features/features_cpu.c:323:23: error: ‘HWCAP_ARM_NEON’ undeclared (first use in this function)
323 |       return (hwcap & HWCAP_ARM_NEON) != 0;
|                       ^~~~~~~~~~~~~~
../desmume/desmume/src/libretro-common/features/features_cpu.c:325:23: error: ‘HWCAP_ARM_VFPv3’ undeclared (first use in this function)
325 |       return (hwcap & HWCAP_ARM_VFPv3) …
```
> addpatch: desmume

- qemu-user-blacklist.txt
This is a trivial issue. Qmake cannot run properly in qemu-user. I have successfully built this package on a real board.
> addpkg: mkvtoolnix

- postgresql/riscv64.patch
Disable LLVM JIT to workaround runtime errors:
FATAL:  fatal llvm error: Relocation type not implemented yet!
> addpatch: postgresql

- grafana-agent/riscv64.patch
- grafana-agent/support_go_1.19.patch
Here contains two patches:
One from modification of `PKGBUILD` called `riscv46`.
The other from upstream, which fixed the original error: `assume-no-moving-gc`.
Because upstream fixed this error without new release found, so I just change their modification into a patch then apply it in our packages.
Notice: in their modification, `go` need download new version, however, `build()` of `PKGBUILD` has a option `export GOPROXY=off`, which can lead this into failure, so I delete it.
If there is any wrong management, please fell free to tell me, thanks.
Build passed.
**Related issue and pull request:**
Issue: https://github.com/grafana/agent/issues/1983
PR: https://github.com/grafana/agent/pull/1985
**Original error message:**
```console
panic: Something in this program imports …
```
> addpkg: grafana-agent

- gnu-efi/riscv64.patch
This is an issue caused by binutils 2.39. Binutils 2.39 introduced new warning `ld: warning: t.so has a LOAD segment with RWX permissions`. According to an [issue](https://github.com/systemd/systemd/issues/23789) of systemd, they just silent the warning. So, I think it's not a big problem and we can silent the warning as well.
> updpatch: gnu-efi

- monero-gui/riscv64.patch
Disable LTO to bypass error:
```
/tmp/ccWy6leF.ltrans19.ltrans.o: in function `.L0 ':
<artificial>:(.text+0x1ad2): relocation truncated to fit: R_RISCV_JAL against symbol `mdb_stat' defined in text_env section in /tmp/ccWy6leF.ltrans22.ltrans.o
```
Just like we did for `opencv` in https://github.com/felixonmars/archriscv-packages/pull/1427.
> addpatch: monero-gui 0.18.1.0-1

- elfutils/elflint.patch
- elfutils/riscv64.patch
- elfutils/skip-run-backtrace-native.patch
- qemu-user-blacklist.txt
First, I met an issue recorded in https://sourceware.org/bugzilla/show_bug.cgi?id=29073. After backporting three mentioned commits, the issue is fixed.
Next, I met an issue recorded in https://sourceware.org/bugzilla/show_bug.cgi?id=29176. This issue also appears in x86_64 architecture. And I opened an issue https://bugs.archlinux.org/task/74875. In this PR, I just add a patch to make the test expected to fail.
Last, building failed with qemu-user because of three FAIL listed below.
```
FAIL: run-backtrace-dwarf.sh
============================
PTRACE_TRACEME failed: Function not implemented
/build/elfutils/src/elfutils-test-0.187/tests/backtrace-dwarf: unexpected wait status 65280
dwarf: no main
FAIL run-backtrace-dwarf.sh (exit status: 1)
FAIL: run-deleted.sh …
```
> addpatch: elfutils

- cifs-utils/cifs-utils.patch
invoke autoreconf with the `-f` option to update `config.guess` and `config.sub`
> addpatch: cifs-utils

- ocaml/riscv64.patch
frame pointers are x86_64 only.
Ref: https://github.com/ocaml/ocaml/blob/98392895940cc1c18534280ae001b70fa5bf24c2/configure.ac#L1925
> addpatch: ocaml

- qemu-user-blacklist.txt
Package falkon met the same "stddef.h not found" issue as PR #1586.
> noqemu: falkon

- prometheus-wireguard-exporter/riscv64.patch
The PKGBUILD patch fixes two issues:
1. rustc(1) recognizes `riscv64gc' instead of `riscv64'. It fixes the issue by substituting `riscv64' with `riscv64gc' in the `--target' argument if $CARCH is `riscv64'.
2. This package depends on `ring', which is not yet riscv64 ready. This patch works around this issue by forcing Cargo to use felixonmars/ring.
The patched version passes compiling and testing.
References:
1. https://github.com/felixonmars/archriscv-packages/commit/1e0a422d3e1a1b879b31988aada28441c5f25223
2. https://wiki.archlinux.org/title/Rust_package_guidelines#Prepare
3. https://github.com/felixonmars/archriscv-packages/wiki/%E6%88%91%E4%BB%AC%E7%9A%84%E5%B7%A5%E4%BD%9C%E4%B9%A0%E6%83%AF
> addpkg: prometheus-wireguard-exporter

- algol68g/fix-build-host.patch
- algol68g/riscv64.patch
Package algol68g have an old configure.ac file that doesn't recognize
riscv. This patch add a new prepare step to patch and reconfigure the
build script.
> addpatch: algol68g

- libffado/riscv64.patch
Scons build system invokes `/bin/sh admin/config.guess` directly.
```python
def ConfigGuess( context ):
context.Message( "Trying to find the system triple: " )
ret = check_output(("/bin/sh", "admin/config.guess")).rstrip()
context.Result( ret )
return ret.decode()
```
So, I replace it with config.guess bundled with system.
I also filed an issue to upstream.
https://sourceforge.net/p/ffado/mailman/ffado-devel/thread/CAEUwDuAJDjFfXuQRBrLpYd6N75ZgYj7P-EtK%2BrPupwVB3aRCSQ%40mail.gmail.com/#msg37694098
> addpatch: libffado

- lvm2/riscv64.patch
This is an issue about config.guess and config.sub. Added a dependency autoconf-archive because of AC_PYTHON_MODULE macro in configure.ac.
```
AC_PYTHON_MODULE([pyudev], [Required], python3)              
AC_PYTHON_MODULE([dbus], [Required], python3)
```
I have filed an issue to upstream bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=2118243
> addpatch: lvm2

- ppsspp/riscv64.patch
LTO is disabled because the follow errors are present with our
`-Wl,-plugin-opt=-target-abi=lp64d` hack:
```
/usr/bin/ld: error: LLVM gold plugin: linking module flags
'SmallDataLimit': IDs have conflicting values in
'lib/libspirv-cross-glsl.a.llvm.105712.spirv_glsl.cpp' and 'ld-temp.o'
```
Build patch upstreamed at https://github.com/hrydgard/ppsspp/pull/15862
> addpatch: ppsspp

- arrow/riscv64.patch
- qemu-user-blacklist.txt
- LTO is disabled for similar reason as #1620
- The `-DARROW_CPU_FLAG=riscv64` is no longer needed in a future version
containing https://github.com/apache/arrow/pull/13902
- Added to qemu-user-blacklist because QEMU doesn't support
madvise(WILLNEED) properly (this includes qemu-system, actually)
- `nocheck` is needed for now as `arrow-flight-test` is failing with the
current version but not on git master. Recheck on next release!
> addpatch: arrow

- mkinitcpio/riscv64.patch
Add a [patch](https://github.com/archlinux/mkinitcpio/pull/112) to support our gzipped kernel. Tested to work fine on both
qemu-system-riscv64 and HiFive Unmatched boards.
> addpatch: mkinitcpio

- mkinitcpio/riscv64.patch
Add another [patch](https://github.com/archlinux/mkinitcpio/pull/113) to include spi modules for `block` hook. This fixes SD
card boot for Hifive Unmatched board.
> updpatch: mkinitcpio

- dummyhttp/riscv64.patch
Fix error:
```
Caused by:
process didn't exit successfully: `/build/dummyhttp/src/dummyhttp-0.5.0/target/release/build/ring-86c85cc89dc3d48a/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> addpatch: dummyhttp 0.5.0-1

- cern-vdt/riscv64.patch
SSE is not supported except for x86_64.
> addpkg: cern-vdt

- efivar/riscv64.patch
Add two patches from upstream. One is to fix build issue with RISCV64, the other is to fix build issue with glibc 2.36. The later one is also needed in ArchLinux official repository. So, I also sent a patch to ArchLinux.
https://bugs.archlinux.org/task/75702
> addpatch: efivar

- system-config-printer/riscv64.patch
Fix `config.guess`.
But here is one point needs to be noticed:
After `autoupdate` and `autoreconf -fiv` it occurred the same error as `libopenraw`. That is lack of some m4 macros due to the old `config.guess`. 
So I referred the suggestion of `libopenraw`'s upstream: added `autoconf-archive`.
After this pull request I will issue the upstream to update files.
I don't know my management is correct or not.
If it is right, I think it can be added to the wiki to notify the later packagers: how to fix the bash script errors (If is m4 macros related) after `autoreconf -fiv`.
Build passed.
[Blog of fixing `libopenraw`](https://tinysnow.github.io/%E6%8A%80%E6%9C%AF/ArchRISC-V/Packages/libopenraw.html)
[`libopenraw's upstream`](https://gitlab.freedesktop.org/libopenraw/libopenraw/-/issues/11#note_14 …
> addpkg: system-config-printer

- autotiling-rs/riscv64.patch
Fix error:
```
Caused by:
--- stderr
```
> addpatch: autotiling-rs 0.1.3-1

- srs-state-threads/riscv-cpu-support.patch
- srs-state-threads/riscv64.patch
This patch adds RISC-V CPU support from upstream:
https://github.com/ossrs/state-threads/pull/28.
The README.md file was changed after the latest version and the
original patch can't be applied on it, so a modified local patch is also
submit here.
> addpatch: srs-state-thread

- srs/riscv64.patch
- srs/support-riscv.patch
Backport from https://github.com/ossrs/srs/pull/3115
> addpatch: srs 4.0_r2-2

- dante/riscv64.patch
Since the upstream has no source repo, so I have to send mail to remind them.
After merged, I intend to copy the patch link to show them.
Fixed `config.guess` trivial.
> addpkg: dante

- iftop/riscv64.patch
The upstream has maintain a self-owned gitlab instance.
And there is no entry point to approach their repo to report bug because of the lack of signing up page.
I will try my best to get another way.
Fixed `config.guess` trivial.
> addpkg: iftop

- qemu-user-blacklist.txt
Test "cmd/app/http_test" fail to pass on qemu-user.
But it successfully passes on RISC-V board.
It fails to create a new server due to the invalid listen address.
The address was created correctly but turned into the string
"passthrough:///:0\x00\x00\x00\x00\x00\x00" in [line 58].
The strings.Replace function has some unknown problem in qemu-user.
And it can work as expect if we flush the stdout:
```diff
+	os.Stdout.Sync()
grpcServer.grpcServerEndpoint = strings.Replace(grpcServer.grpcServerEndpoint, "::", "localhost", 1)
```
I am still digging the reason and trying to make a minimal reproducible code.
[line 58]: https://github.com/sigstore/fulcio/blob/v0.5.2/cmd/app/http_test.go#L58
> noqemu: fulcio

- firefox/riscv64.patch
1. Updpkg: firefox 104.0.1
2. Replace `firefox-disable-vet-hack.patch` with `firefox-riscv64-hack.patch`. from: https://github.com/gentoo/riscv/pull/8
3. set `MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=pip` to solve the problem of failed build environment detection. from: https://bugs.archlinux.org/task/75796
> Updpatch: firefox

- gnuradio/riscv64.patch
This package fails to build on x86_64 as well. The problem is the same which is lacking a makedepends.
More details here: https://bugs.archlinux.org/task/75819
> updpatch: gnuradio

- link-grammar/riscv64.patch
Fix `config.guess` trivial.
Notice: `m4` macros not found, so added `autoconf-archive` to `makedepends`.
> addpkg: link-grammar

- arti/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu"`, and after this it occurred `ring` fault, so fixed in passing.
> addpkg: arti

- drumgizmo/riscv64.patch
The patch `fix-missing-include.patch` has been fixed in upstream.
> upgpatch: drumgizmo 0.9.20-1

- fq/riscv64.patch
Upstream PR: wader/fq#420
This would prevent running `go test` with `-race` via `make test`, which is not supported on `linux/riscv64`.
> addpatch: fq

- freeipmi/riscv64.patch
Fix error:
```
checking build system type... ./config/config.guess: unable to guess system type
This script, last modified 2013-06-10, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
If the version you run (./config/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.
config.guess timestamp = 2013-06-10
uname -m = riscv64
uname -r = 5.19.2-arch1-2
uname -s = Linux …
```
> addpatch: freeipmi 1.6.10-1

- hplip/0028-Remove-ImageProcessor-binary-installs.patch
- hplip/riscv64.patch
This patch is taken from https://salsa.debian.org/printing-team/hplip/-/blob/debian/main/debian/patches/0028-Remove-ImageProcessor-binary-installs.patch
Since not linking this library won't cause any link error, I think it's safe to do so.
> addpatch: hplip

- gcc/riscv64.patch
Fix rotten.
There are quite a lot of FAILs, however it seems that ArchLinux doesn't care about them.
```
make -O -k check || true
```
> updpatch: gcc

- cardinal/riscv64.patch
explicitly pass library paths omitted by gcc to mold and disable/replace asm and simd optimizations to enable riscv64 build
> addpatch: cardinal

- distrobuilder/fix-static-declaration-of-lxd.patch
- distrobuilder/riscv64.patch
Tough work. Build passed.
1. The `fix-static-declaration-of-lxd` patch is from the upstream of `lxd`, which is really crashed in `distrobuilder` building proeessing.
2. Delete the exceeded and needless change in upstream's patch.
_i.e._ `lxd/main_checkfeature.go`(In `distrobuilder`, this file doesn't exist.)
3. Patch and this PR.
The patch file is altered by TinySnow.
Patch from origin upstream doesn't work.
- `lxd` issue: https://github.com/lxc/lxd/issues/10738
- `lxd` PR: https://github.com/lxc/lxd/pull/10756
> addpkg: distrobuilder

- libopenraw/riscv64.patch
Finally made it building passed after 3 month due to `llvm 13` updated.
**Note**
Because of `m4` macros not found, its `makedepends` was added `autoconf-archive`.
> addpkg: libopenraw

- lprint/riscv64.patch
The commit has been upstreamed but not released (yet).
Given its lastest release on 23 Dec, 2021, it seems unlikely that a new release may come in the near future.
> addpkg: lprint

- libva/riscv64.patch
Fixed outdated cherry-pick commit ID.
Upstream bug report: https://bugs.archlinux.org/task/75914
> addpatch: libva 2.15.0-6

- libretro-mupen64plus-next/riscv64.patch
Fixed: #1715 
* Fix no `-msse` and `-msse2` option on RISC-V issue
* Drop module `mupen64plus-rsp-paraLLEl` because it contains x64 specific simd code
* Add `-DNO_ASM` option into CFLAGS & CXXFLAGS to fix the link error
> addpatch: libretro-mupen64plus-next

- blacklist.txt
Although it's not relevant for RISC-V, it's mostly harmless to have a 50KiB package around to satisfy dependencies and it compiles just fine.
Just for reference, Arch Linux ARM also has this package.
> blacklist: remove dmidecode

- charm/riscv64.patch
The previous patch replaced an unmaintained dependency [`github.com/jacobsa/crypto`](https://github.com/jacobsa/crypto) with a reference to PR jacobsa/crypto#14 to support `linux/riscv64`. This change to the patch replaced the reference with another community-maintained successor [`github.com/aperturerobotics/jacobsa-crypto`](https://github.com/aperturerobotics/jacobsa-crypto).
FTR: upstream PR submitted at [charmbracelet/charm#178](https://github.com/charmbracelet/charm/pull/178).
> upgpatch: charm 0.12.4-1

- grafana-zabbix/riscv64.patch
- Add dependency `python3`
Dependency node-gyp will download pre-built library in x86_64. In riscv64 it has to build itself from source which requires python3 executable. But there is no python package provided in the original PKGBUILD.
- Move the build script from Makefile to PKGBUILD
Targets in Makefile doesn't handle all the platform. Maintainer hard code `amd64` suffix in `make build` and set environment `GOOS` to darwin, windows, openbsd...etc. It is not a proper way to run make build and make dist here.
Ref:
- https://github.com/alexanderzobnin/grafana-zabbix/blob/master/Makefile#L45
Addtional:
1. yarn install depends on network, so the make install command is flaky.
2. Test will fail with signal `SIGSEGV` in QEMU-user. It is caused by test framework jest. This problem can be …
> addpatch: grafana-zabbix

- cargo-binstall/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu"` and `ring` dependency error.
> addpkg: cargo-binstall

- gawk/0001-Fix-negative-NaN-issue-on-RiscV.patch
- gawk/riscv64.patch
- qemu-user-blacklist.txt
Backport one patch related to -NAN from upstream https://git.savannah.gnu.org/cgit/gawk.git/commit/?id=a3799ae3f5dd6648040d499224cc6dea61b355dd
Add gawk to qemu-user-blacklists.txt because of following failures:
```
make[3]: *** [Makefile:2219: pma] Error 137
make[3]: Leaving directory '/build/gawk/src/gawk-5.2.0/test'
make[2]: *** [Makefile:2206: pma-tests] Error 2
make[2]: Leaving directory '/build/gawk/src/gawk-5.2.0/test'
make[1]: *** [Makefile:805: check-recursive] Error 1
```
> addpatch: gawk

- slang/riscv64.patch
**Notice**
The normal fixing approach didn't work since it haven't  `configure.ac` file in its `src` directory.
Their `autotools` related files located at `autoconf` directory. In this directory, `autoreconf -fiv` went wrong.
So, copied files.
**Failed Log** (in `autoconf` dir)
```console
autoreconf: running: /usr/bin/autoheader --force
autoheader: error: cannot rename /tmp/arsWSSX0/ahvyjYuf/config.hin as src/config.hin: No such file or directory
autoreconf: error: /usr/bin/autoheader failed with exit status: 1
```
> addpkg: slang

- procs/riscv64.patch
- qemu-user-blacklist.txt
And this package can now be built in qemu-user environment, so remove it from qemu-user black list.
> upgpkg: procs 0.13.1-1

- qemu-user-blacklist.txt
A test will timeout in qemu-user but pass on real boards.
```
Error in green.test.test_integration.TestFinalizer.test_finalizer
Traceback (most recent call last):
File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib/python3.10/unittest/case.py", line 591, in run
self._callTestMethod(testMethod)
File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
method()
File "/build/python-green/src/green-3.4.3/green/test/test_integration.py", line 55, in test_finalizer
output = subprocess.run(
File "/usr/lib/python3.10/subprocess.py", line 503, in run
stdout, stderr = process.communicate(input, timeout=timeout)
File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
stdout, stderr = self._communicate(input, endtime, timeout) …
```
> addpkg: python-green to qemu-user black list

- python-pytest-plugins/riscv64.patch
Disable pypandoc as we currently cannot fix pandoc.
> addpatch: python-pytest-plugins

- haskell-blaze-html/riscv64.patch
Disable HTML Combinators regeneration on packaging to workaround GHCi segfault for now.
> addpatch: haskell-blaze-html

- ob-xd/riscv64.patch
- qemu-user-blacklist.txt
Replace the build option `-m64` to `-march=rv64gc`.
* Additional Notes
This package can't be built in qemu-user because the build file generator Projucer will stuck.
> addpkg: ob-xd

- haskell-xml-conduit/riscv64.patch
Disable doctest to workaround our GHCi crash
> addpatch: haskell-xml-conduit

- haskell-tasty-checklist/riscv64.patch
Disable doctests until we figure out our GHCi crash.
> addpatch: haskell-tasty-checklist

- haskell-gi/riscv64.patch
Disable doctests until we fix our GHCi crash
> addpatch: haskell-gi

- dhall/riscv64.patch
Disable doctests until we fix our GHCi crash.
> addpatch: dhall

- pythia8/riscv64.patch
Disable `root` support because it vendors LLVM 9. Revisit this when `root` got an updated LLVM:
https://github.com/root-project/root/pull/10294
> addpatch: pythia8

- hepmc/riscv64.patch
Disable `root` support because it vendors LLVM 9. Revisit this when `root` got an updated LLVM:
https://github.com/root-project/root/pull/10294
> addpatch: hepmc

- dhall-docs/riscv64.patch
Disable doctests until we fix our GHCi crash.
> addpatch: dhall-docs

- qemu-user-blacklist.txt
Subprocess `Odin2_LV2_lv2_ttl_generator` launched by `make` will stuck in qemu-user at build stage, but will pass on real boards.
> addpkg: odin2-synthesizer to qemu-user blacklist

- glib2/0001-increase-test-timeout-limit.patch
- glib2/riscv64.patch
Increase test timeout limit. However, sometimes tests still fail. I don't know why now :(
> addpatch: glib2

- blacklist.txt
The package i7z does not have hardware support for RISC-V.
It is a Intel/x86-specific CPU power state reporting tool.
> addpkg: i7z to blacklist

- iperf/riscv64.patch
config.guess and config.sub shipped by iperf are from 2015 and don't recognize riscv.
[Bug report has been submitted upstream](https://sourceforge.net/p/iperf2/discussion/general/thread/185790844e/)
> addpkg: iperf

- blacklist.txt
dosemu is a x86-only DOS emulator for linux.
Because it uses the host x86 processor for running the programs, only x86 and x86_64 processors are supported.
https://sourceforge.net/p/dosemu/code/ci/master/tree/INSTALL
> addpkg: dosemu to blacklist

- libjxl/riscv64.patch
Cherry-pick an upstream commit to fix the failure of test `JxlTest.RoundtripLargeFast`.
> upgpatch: libjxl 0.7.0-2

- rdiff-backup/riscv64.patch
After python-setuptools updated, the build-lib suffix is -cpython-310 now.
Ref:
* https://github.com/pypa/setuptools/commit/1c23f5e1e4b18b50081cbabb2dea22bf345f5894
* Upstream bug report: https://bugs.archlinux.org/task/76043
> fixpatch: rdiff-backup

- qemu-user-blacklist.txt
```
______________________ TestGetProcEnv.test_get_proc_ppid _______________________
self = <tests.unittests.test_util.TestGetProcEnv testMethod=test_get_proc_ppid>
def test_get_proc_ppid(self):
"""get_proc_ppid returns correct parent pid value."""
my_pid = os.getpid()
my_ppid = os.getppid()
>       self.assertEqual(my_ppid, util.get_proc_ppid(my_pid))
E       AssertionError: 7 != 0
tests/unittests/test_util.py:2465: AssertionError
------------------------------ Captured log call -------------------------------
2022-09-24 01:16:47 DEBUG     cloudinit.util:util.py:1474 Reading from /proc/3005/stat (quiet=True)
2022-09-24 01:16:47 DEBUG     cloudinit.util:util.py:1485 Read 117 bytes from /proc/3005/stat
2022-09-24 01:16:47 WARNING   cloudinit.util:util.py:2903 Unable to match parent pid of …
```
> addpkg: cloud-init to qemu-user blacklist

- balsa/riscv64.patch
`config.guess` and `config.sub` shipped in upstream released tar are from 2015 and can not recognize riscv.
This has been reported to upstream's [mailing list](https://mail.gnome.org/mailman/listinfo/balsa-list).
But it is now being held until the list moderator can review it for approval.
> addpkg: balsa

- doctest/riscv64.patch
Fix compile errors in downstream packages when comparing pointers.
Upstream PR: https://github.com/doctest/doctest/pull/699
> addpatch: doctest 2.4.9-1

- percona-server/riscv64.patch
- qemu-user-blacklist.txt
Adapt to upstream changes.
Adding this to `qemu-user-blacklist.txt` because it requires `-DWITH_LIBEVENT=bundled` to work on qemu-user. CMake config outputs under qemu are shown below.
**NOTE:** This should be built **single-threaded** because `clang` can easily cause an OOM when building it in parallel.
```
-- LIBEVENT_VERSION_STRING <jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
2.1.11-stable
-- LIBEVENT_VERSION (bundled) <jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
2.1.11
CMake Error at cmake/libevent.cmake:133 (MESSAGE):
LIBEVENT version must be at least 2.1, found <jemalloc>: MADV_DONTNEED …
```
> updpatch: percona-server

- blacklist.txt
x86_energy_perf_policy is only compatible with x86
compare linux-tools patch 70c606f
> addpkg: x86_energy_perf_policy to blacklist

- blacklist.txt
turbostat is only compatible with x86
compare linux-tools patch 70c606f
> addpkg: turbostat to blacklist

- handbrake/riscv64.patch
intel-media-sdk is unavailable on riscv
The nvidia video codec sdk is unavailable on riscv (including nvenc)
basically the same as ffmpeg 057be4d0c5eadc6d1df953485180ea64387f93fc
> addpkg: handbrake

- qemu-user-blacklist.txt
- tracker/riscv64.patch
- tracker/tracker-fix-slow-tests.patch
although tons of methods have been tried, the tracker test is still flaky:
among several runs, these failure combinations have been observed:
```
1.
34/43 data-sparql                           FAIL             11.08s   (exit status 133 or signal 5 SIGTRAP)
42/43 tracker-sparql-test                   FAIL              2.20s   (exit status 134 or signal 6 SIGABRT)
2.
34/43 data-sparql                           FAIL              8.78s   (exit status 133 or signal 5 SIGTRAP)
37/43 miner-miner-fs                        FAIL             39.02s   killed by signal 5 SIGTRAP
42/43 tracker-sparql-test                   FAIL              2.22s   (exit status 134 or signal 6 SIGABRT)
3.
38/43 miner-miner-fs                        FAIL             73.48s   killed by signal 5 SIGTRAP
42/43 …
```
> addpatch: tracker

- blacklist.txt
libmfx is part of intel-media-sdk and not compatible with riscv64
> addpkg: libmfx to blacklist

- go/riscv64.patch
Add a patch to fix go programs crashes under qemu-system due to sv57 incompatibilities.
> updpatch: go 2:1.19.1-1

- tracker3/riscv64.patch
the non-NULL terminated array causes an out-of-bound read
upstream: https://gitlab.gnome.org/GNOME/tracker/-/merge_requests/543
> addpatch: tracker3

- edac-utils/riscv64.patch
upstream's autoconf scripts are too old (from 2004), do `autoreconf` before compiling 
ref: https://github.com/grondo/edac-utils/pull/16
> addpkg: edac-utils

- linux-tools/riscv64.patch
- Enable cpupower (obsoletes #1766). It used to have some build failures but now works flawlessly.
- Add a patch for binutils 2.39
> updpatch: linux-tools 5.19-1.1

- vmpk/riscv64.patch
This PR remove the lto option because ld can't correctly found symbol with "lto" option on.
> addpatch: vmpk

- haskell-wreq/riscv64.patch
Disable doctests until we figure out our GHCi crash.
> addpatch: haskell-wreq

- haskell-swagger2/riscv64.patch
Disable doctests until we fix our GHCi crash.
> addpatch: haskell-swagger2

- qemu-system-makedepends-blacklist.txt
- qemu-user-makedepends-blacklist.txt
qemu-system-makedepends-blacklist: all because of sv57 at the moment. remove when sv57 is disabled in our kernels.
qemu-user-makedepends-blacklist: random deadlocks.
> add makedepends based blacklists

- crun/riscv64.patch
Disable criu support until upstream has support
(https://github.com/checkpoint-restore/criu/issues/1702)
> addpatch: crun

- nix-busybox/riscv64.patch
- Use glibc instead of musl because the kernel-headers-musl package is too old to support RISC-V
- Also fixed source url and reported at https://bugs.archlinux.org/task/76101
> addpatch: nix-busybox

- consul/riscv64.patch
Remove nodejs dependencies because they appear to be unused at the moment (and we don't have nodejs-lts-fermium).
> addpatch: consul

- cargo-pgx/riscv64.patch
Replace dependency `ring` with our patched version.
> upgpatch: cargo-pgx 0.5.0-1

- qemu-user-makedepends-blacklist.txt
It's been a long time not observing unrecoverable sleep under qemu-user for packages written in Rust. Try to remove it.
> Remove `rust` from qemu-user blacklist

- darcs/riscv64.patch
Disabled tests for now because of GHC segfaults and excessively slow (>3days per run).
> addpatch: darcs

- qemu-user-makedepends-blacklist.txt
Reverts felixonmars/archriscv-packages#1827
Unrecoverable sleeps still occur with *a* probability. Aggressively blacklist them from qemu-user because builds entering unrecoverable sleeps needs manual intervention to retry.
> Revert "Remove `rust` from qemu-user blacklist"

- xpra/riscv64.patch
- xpra/xpra-4.3.4-ffmpeg5_1_deprecated_channels.patch
Xpra consier all warning as Error. And ffmpeg has deprecate the usage of the channel field in AvCodecContext struct. So this package will FTBFS. Xpra upstream fix this issue in the master branch, but not tagged yet.
This PR upgrade the xpra to v4.3.4 (It's been flagged out-of-date on 2022-06-21), and backport the ffmpeg warning fix.
Arch Linux upstream report: https://bugs.archlinux.org/task/76030?project=5&string=xpra
> addpatch: xpra

- haskell-pgp-wordlist/riscv64.patch
Disable doctests because of our GHCi crashes.
> addpatch: haskell-pgp-wordlist

- haskell-network-byte-order/riscv64.patch
Disable doctests because of our GHCi crashes
> addpatch: haskell-network-byte-order

- rust/riscv64.patch
Non-trivial Change:
+ Reverts regressed commit causing ICE during bootstrap.
Reference:
+ Regressed PR: rust-lang/rust#99033
+ Commit: https://github.com/rust-lang/rust/commit/263edd43c5255084292329423c61a9d69715ebfa
+ Tracking Issue: rust-lang/rust#102155
> updpatch: rust 1.64.0

- haskell-pcg-random/riscv64.patch
> addpatch: haskell-pcg-random

- libffi/riscv64.patch
Upgrade to 3.4.3 and backport one patch to resolve check failures.
https://github.com/libffi/libffi/pull/738
> updpatch: libffi

- haskell-email-validate/riscv64.patch
> addpatch: haskell-email-validate

- haskell-validation-selective/riscv64.patch
Disable doctests until we fix our GHCi crash.
> addpatch: haskell-validation-selective

- haskell-relude/riscv64.patch
Disable doctest until we fix our GHCi crashes.
> addpatch: haskell-relude

- haskell-foldl/riscv64.patch
Disable doctests because of our GHCi crashes.
> addpatch: haskell-foldl

- haskell-prettyprinter/riscv64.patch
> addpatch: haskell-prettyprinter

- haskell-prettyprinter-ansi-terminal/riscv64.patch
Disable doctest because of our GHCi crash.
> addpatch: haskell-prettyprinter-ansi-terminal

- qemu-user-blacklist.txt
This package is exactly the same with libseccomp.
The error log under qemu-user is
```
Failed to set a seccomp profile on a worker thread
Failed to set a seccomp profile on a worker thread
Failed to connect to unix socket: memcached not running at t/misbehave.t line 17.
t/misbehave.t ............... 
Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 1/1 subtests 
```
Some strace results
```
11864 seccomp(0,1,0,0,0,115)-1 errno=38 (Function not implemented)
= -1 errno=38 (Function not implemented)
11864 seccomp(0,1,0,0,0,115) = -1 errno=38 (Function not implemented)
= 0
11864 mprotect(0x0000004020000000,135168,PROT_READ|PROT_WRITE) = 0
11864 mmap(NULL,135168,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) = 0x0000004025379000
11864 prctl(38,1,0,0,0,274948237176) = 0
11864 …
```
> qemu-user-blacklist: add memcached

- dsniff/riscv64.patch
Dsniff also fails to build from source on x86_64. So, I updated debian patch and removed one redundant patch of ArchLinux. "--with-libtirpc" won't be needed because of updated debian patches.
When reporting to ArchLinux Upstream, I noticed loqs reported the problem before. Our ideas are just the same. So, I added my patch to flyspray.
Link to flyspray: https://bugs.archlinux.org/task/72121
> addpatch: dsniff

- haskell-pretty-simple/riscv64.patch
Disable doctests due to our GHCi crashes.
> addpatch: haskell-pretty-simple

- postgrest/riscv64.patch
> addpatch: postgrest

- marisa/riscv64-marisa_word_size.patch
- marisa/riscv64.patch
update patch for https://github.com/s-yata/marisa-trie/issues/40
It can not pass test (`make check`) in riscv64 without the patch.
```
========================================
marisa 0.2.6: tests/test-suite.log
========================================
.. contents:: :depth: 2
FAIL: base-test
===============
base-test.cc:14: TestTypes(): 21: Assertion `MARISA_WORD_SIZE == (sizeof(std::size_t) * 8)' failed.
FAIL base-test (exit status: 255)
```
> updpatch: marisa

- exiv2/exiv2-fix_test_failure.patch
- exiv2/riscv64.patch
the `char` type on RISC-V is unsigned where the failed test assumed it to be signed[1]
apply a patch similar to what GUIX has done[2].
[1] https://github.com/Exiv2/exiv2/issues/933
[2] https://github.com/guix-mirror/guix/commit/b8df15b748024128e09cebb4d7ebae42be5df788
> addpkg: exiv2

- systemd/riscv64.patch
See also:
+ https://wiki.archlinux.org/title/Meson_package_guidelines#Using_arch-meson_wrapper_script
+ https://github.com/archlinux/svntogit-packages/blob/packages/meson/trunk/arch-meson
+ https://github.com/systemd/systemd/commit/55b5daf9b2b7e0c8b77de4f87986832447e72b84 (not appliable because of missing source file; waiting for this to be bpo into `systemd-stable` before we can enable LTO)
Sonames differ in systemd.
> fixpkg: systemd

- opl-synth/riscv64.patch
Replaced `-m64` compile argument with `-march=rv64gc`.
> addpatch: opl-synth 2.2-1

- ansible-lint/riscv64.patch
Validity check fails.
ArchLinux upstream link https://bugs.archlinux.org/task/76261
> addpatch: ansible-lint

- clang/riscv64.patch
Adding a patch that is necessary for further compiling & testing the `mesa` package.
Still, 4 tests are failing, remaining unaffected by this patch. They may need more investigation if keep occuring when we upgrade to clang 15.
```
FAIL: Clang-Unit :: Interpreter/./ClangReplInterpreterTests/IncrementalProcessing.InstantiateTemplate (25720 of 29882)
******************** TEST 'Clang-Unit :: Interpreter/./ClangReplInterpreterTests/IncrementalProcessing.InstantiateTemplate' FAILED ********************
Script:
--
/build/clang/src/clang-14.0.6.src/build/unittests/Interpreter/./ClangReplInterpreterTests --gtest_filter=IncrementalProcessing.InstantiateTemplate
--
Note: Google Test filter = IncrementalProcessing.InstantiateTemplate
[ RUN      ] IncrementalProcessing.InstantiateTemplate
Hard-float …
```
> addpkg: clang

- opencv/riscv64.patch
Disabling LTO is still required to workaround that linker error.
> upgpatch: opencv 4.6.0-5

- qemu-user-blacklist.txt
Test `s2n_mem_usage_test` failed in QEMU but passed on real boards.
```
103/222 Testing: s2n_mem_usage_test
103/222 Test: s2n_mem_usage_test
Command: "/build/s2n-tls/src/s2n-tls-1.3.24/build/bin/s2n_mem_usage_test"
Directory: /build/s2n-tls/src/s2n-tls-1.3.24/tests/unit
"s2n_mem_usage_test" start time: Oct 24 15:52 CST
Output:
----------------------------------------------------------
NOTE: Some details are omitted, run with S2N_PRINT_STACKTRACE=1 for a verbose backtrace.
See https://github.com/aws/s2n-tls/blob/main/docs/USAGE-GUIDE.md
FAILED test 3552
vm_data_after_free_handshake <= vm_data_after_handshakes is not true  (/build/s2n-tls/src/s2n-tls-1.3.24/tests/unit/s2n_mem_usage_test.c:231)
Error Message: 'no error'
Debug String: 'Error encountered in …
```
> addpkg: s2n-tls to qemu-user-blacklist

- qemu-system-makedepends-blacklist.txt
After https://github.com/felixonmars/archriscv-packages/pull/1868 our qemu-system instances have sv57 disabled. These packages are buildable again.
> Remove sv57-related packages from blacklist

- systemd/riscv64.patch
The `riscv_flush_icache` patch has already been included in the upstream release.
lto would work in v252, hopefully.
> upgpatch: systemd 251.7-1

- jupyter_console/riscv64.patch
FTBFS due to lack of dependency. Upstream ArchLinux has fixed in trunk.
Upstream link: https://bugs.archlinux.org/task/76288
> addpatch: jupyter_console

- meson/riscv64.patch
Remove not ported checkdeps on jdk8, mono, cuda; and valgrind because the port is incomplete and breaks here.
Still require `--nocheck` for now because rustc crashes:
```
FAILED: rust-program
rustc -C linker=cc --color=always --crate-type bin -g --crate-name
rust_program --emit dep-info=rust-program.d --emit link -C lto -o
rust-program '../test cases/rust/1 basic/prog.rs'
/usr/lib/librustc_driver-14b3d28b40883067.so(+0x720538)[0x4002f55538]
[0x4002826000]
/usr/lib/libLLVM-14.so(+0x10c62cc)[0x40075122cc]
ninja: build stopped: subcommand failed.
```
> addpatch: meson

- golang-github-davecgh-go-spew/riscv64.patch
Arch Linux bug report: https://bugs.archlinux.org/task/73665
> addpatch: golang-github-davecgh-go-spew 1.1.1-2

- d-stdx-allocator/riscv64.patch
- d-stdx-allocator/support-riscv64.patch
Upstream PR: https://github.com/dlang-community/stdx-allocator/pull/35.
Requires latest `meson` to build.
> addpkg: d-stdx-allocator

- pixman/riscv64.patch
Cherry-pick an upstream unmerged MR [Revert "Fix signed-unsigned semantics in reduce_32" ](https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/69) to fix test timeout and failure.
```
30/33 scaling-test          FAIL            565.63s   exit status 1
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
scaling test failed! (checksum=54B264D2, expected D3589272)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```
> upgpatch: pixman 0.42.0-1

- bzip3/riscv64.patch
`/usr/bin/ld: /tmp/lto-llvm-cca3ab.o: can't link soft-float modules with double-float modules`
Solution is taken from [here](https://riscv-notes.sh1mar.in/docs/record/lto#%E5%85%B6%E4%BB%96).
> addpatch: bzip3

- wasmtime/riscv64.patch
This patch fixes the following issue:
```
Caused by:
--- stderr
```
> addpatch: wasmtime 2.0.1-1

- ltrace/riscv64-support.patch
- ltrace/riscv64.patch
Backport the [upstream RISC-V support] to Arch Linux 0.7.3 version.
Current status: built successfully, test will fail but will not hang. But the test fail is expected (The x86_64 PKGBUILD just add `|| true` at the end of `make test`).
[upstream RISC-V support]: https://gitlab.com/cespedes/ltrace/-/merge_requests/4
> addpatch: ltrace

- limesuite/limesuite-march-native.patch
- limesuite/riscv64.patch
LimeSuite enables `-march=native` by default. This patch adds a check. If compiler supports `-march=native`, we can enable it by default. This patch has been merged upstream.
Upstream link: https://github.com/myriadrf/LimeSuite/pull/370
> addpatch: limesuite

- qemu-user-blacklist.txt
Package test acquired hardware is not available in QEMU-user.
> noqemu: gssdp

- jrnl/riscv64.patch
ArchLinux bug tracker: https://bugs.archlinux.org/task/76363
Since ArchLinux maintainer didn't react to this bug for a long time, I created this PR.
> addpatch: jrnl

- qemu/riscv64.patch
Disable lto since it fails with:
```text
[1474/2930] Linking target qemu-aarch64
FAILED: qemu-aarch64 
c++  -o qemu-aarch64 libcommon.fa.p/hw_core_cpu-common.c.o libcommon.fa.p/hw_core_machine-smp.c.o libcommon.fa.p/cpus-common.c.o libcommon.fa.p/page-vary-common.c.o libcommon.fa.p/disas_riscv.c.o libcommon.fa.p/accel_accel-user.c.o libcommon.fa.p/common-user_safe-syscall.S.o libcommon.fa.p/common-user_safe-syscall-error.c.o libqemu-aarch64-linux-user.fa.p/linux-user_aarch64_signal.c.o libqemu-aarch64-linux-user.fa.p/linux-user_aarch64_cpu_loop.c.o libqemu-aarch64-linux-user.fa.p/target_arm_cpu.c.o libqemu-aarch64-linux-user.fa.p/target_arm_crypto_helper.c.o libqemu-aarch64-linux-user.fa.p/target_arm_debug_helper.c.o libqemu-aarch64-linux-user.fa.p/target_arm_gdbstub.c.o …
```
> addpatch: qemu 7.1.0-10

- libluv/riscv64.patch
Use lua51 instead of luajit because it doesn't support RISC-V (https://github.com/LuaJIT/LuaJIT/issues/628)
Unfortunately we are not getting flags correctly from luarocks. Setting all variables to avoid using default (5.4) lua installation.
> addpatch: libluv

- qemu/riscv64.patch
Restore bundled seabios & edk2 files and put them into corresponding subpackages, because they don't build on riscv64 currently.
> updpatch: qemu

- gnutls/riscv64.patch
Temporarily disable parallel check because of serv-udp.sh.
Upstream report: https://bugs.archlinux.org/task/76577
> addpatch: gnutls

- cargo-c/riscv64.patch
Remove `--target` option to fix the target not found issue
> addpatch: cargo-c

- arch-audit/riscv64.patch
Disable LTO because it caused symbols used in the patched `ring` cannot be found.
> addpatch: arch-audit 0.1.20-1

- toolbox/riscv64.patch
This patch import the upstream patch to use dynamic linker in RISC-V. Also upgrade the package `golang.org/x/sys` to v0.2.0 to get riscv64 sys/unix implementation.
> addpatch: toolbox

- krita/riscv64.patch
The RISC-V support MR is merged and release in new version: https://invent.kde.org/graphics/krita/-/merge_requests/1416.
This patch also remove the make-depend XSIMD. XSIMD is an optional dependency for krita. And its RISC-V support is still under progress: https://github.com/xtensor-stack/xsimd/issues/503. Krita can work without it so it is fine to remove it.
> updpatch: krita

- netcdf-openmpi-bootstrap/PKGBUILD
This package provides `netcdf-openmpi` for package `pnetcdf-openmpi`. And the `pnetcdf-openmpi` package can be used for building the `netcdf-openmpi` itself.
Modifications:
==============
1. Becasue of the bug mentioned in [netcdf-c #2500], BYTERANGE feature is closed.
2. Close the pnetcdf feature and remove the pnetcdf makedepends.
[netcdf-c #2500]: https://github.com/Unidata/netcdf-c/issues/2500
Build Sequence:
===============
1. netcdf-openmpi-bootstrap
2. pnetcdf-openmpi
3. netcdf-openmpi
Additional Info:
================
All the three packages mention above needs `--nocheck`. This is because there are always some bug in shared memory from openmpi. All tests except openmpi parallel tests passed successfully. hdf5-openmpi [ignore] the failure too. So no check to bypass those parallel …
> addpkg: netcdf-openmpi-bootstrap

- netcdf-openmpi-bootstrap/PKGBUILD
Provides the original package to satisfy dependency.
> updpatch: netcdf-openmpi-bootstrap

- qt6-quick3dphysics/riscv64.patch
fix a rotten patch (its sha256sums has changed)
> fixpatch: qt6-quick3dphysics

- buddy/riscv64.patch
Uptream url: https://sourceforge.net/p/buddy/patches/7/.
> addpkg: buddy

- golang-github-yuin-goldmark/riscv64.patch
This patch multiplies test timeouts in `extra_tests.go` by 10 with `sed`.
A proposed PR to read test timeout multiplier from environment variable is at yuin/goldmark#337.
> addpatch: golang-github-yuin-goldmark 1.4.13-2

- httrack/riscv64.patch
Notice: used `autoconf-archive` makedepends.
Upstream URL: https://forum.httrack.com/readmsg/41135/index.html.
> addpkg: httrack

- yabause-qt/riscv64.patch
Upstream used `-O0` to prevent GCC from performing strict aliasing optimizations. Without `-freorder-blocks`, GCC generates an unlinkable ELF file, causing the package fails to build. This patch substitutes `-O0` with `-fno-strict-aliasing` to make the compilation work as intended. You may refer to upstream patch Yabause/yabause#444 for details.
> updpatch: yabause-qt 0.9.15-3

- yabause-gtk/riscv64.patch
This patch is identical to #1983. The following description is copied from it.
---
Upstream used `-O0` to prevent GCC from performing strict aliasing optimizations. Without `-freorder-blocks`, GCC generates an unlinkable ELF file, causing the package fails to build. This patch substitutes `-O0` with `-fno-strict-aliasing` to make the compilation work as intended. You may refer to upstream patch Yabause/yabause#444 for details.
> updpatch yabause-gtk 0.9.15-3

- golang-github-yuin-goldmark/riscv64.patch
Increase test timeout multiplier from 10 to 20.
> fixpatch: golang-github-yuin-goldmark 1.4.13-2

- xorg-fonts-type1/riscv64.patch
Fix config.guess issue. Upstream report
https://gitlab.freedesktop.org/xorg/font/xfree86-type1/-/issues/1.
This patch also add additional make-depends `xorg-font-util` for the
autoreconf step.
> addpatch: xorg-fonts-type1

- xorg-fonts-cyrillic/riscv64.patch
https://gitlab.freedesktop.org/xorg/font/winitzki-cyrillic/-/issues/1.
This patch add additional make-depends: xorg-font-util. It is required
when we run autogen.
> addpatch: xorg-fonts-cyrillic

- xorg-fonts-75dpi/riscv64.patch
https://gitlab.freedesktop.org/xorg/font/adobe-75dpi/-/issues/1
> addpatch: xorg-fonts-75dpi

- ophcrack/riscv64.patch
Fix config.guess issue. Reported to upstream at https://gitlab.com/objectifsecurite/ophcrack/-/issues/9
> addpatch: ophcrack

- echoping/riscv64.patch
FYI: echoping is no longer maintained (see https://framagit.org/bortzmeyer/echoping)
> updpatch: echoping

- ecryptfs-utils/riscv64.patch
https://bugs.launchpad.net/ecryptfs/+bug/1997796
> addpatch: ecryptfs-utils

- rhythmbox/riscv64.patch
Package rhythmbox needs 40secs(qemu-user)~52secs(VisionFive) to finish
the test on our RISC-V machine. The default 30secs timeout is not
enough. This patch add timeout multiplier option `-t` to increase
timeout by 5 times.
> addpatch: rhythmbox

- cjs/riscv64.patch
One of the test from the cjs package require 28secs(qemu-user 5950x) ~
33secs(VisionFive) to finish, and the default timeout(30secs) is not
enough. This patch add timeout multiplier with `-t` option to increase
timeout by 5 times.
> addpatch: cjs

- coin-or-clp/coin-or-cgl/riscv64.patch
Fix the config.guess issue. BTW, the coin-or-clp in current repo link
to the libcholmod.so.3 file, but the latest suitesparse package provide
libcholmod.so.4 now. So the coin-or-clp package should be built before
this package.
> addpatch: coin-or-cgl

- bitwarden-cli/riscv64.patch
This patch remove all the electron dependencies and the husky installer.
Bitwarden-cli is part of the bitwarden/client project. It share
dependencies with other application. And the electron dependencies is
for desktop/Android version. Besides, electron is currently unusable on
RISC-V platform.
The husky installer is a git hook util implemented by nodejs. It is only
used for dev environment.
> addpatch: bitwarden-cli

- js102/riscv64.patch
- js102/tests-skip-some-tests-on-rv64.patch
Skip some tests on 64-bit architecture. Same as: https://github.com/felixonmars/archriscv-packages/commit/badeec697832d979dead2c66d3a4a172ee78d7fb
> addpatch: js102

- linux-tools/riscv64.patch
Patch `linux-tools-binutils-2.39.patch` merged upstream.
> updpkg: linux-tools

- gjs/riscv64.patch
gjs needs ~26secs to finish its test in VisionFive, ~33secs in QEMU
System. So double the default timeout should be enough.
> addpatch: gjs

- bnfc/riscv64.patch
> addpatch: bnfc

- python-sphinx_rtd_theme/fix-for-new-nodejs.patch
- python-sphinx_rtd_theme/riscv64.patch
Fix rotten and webpack4 issue.
The latest Node.js contains some breaking change for webpack4. This PR
add env `NODE_OPTIONS=--openssl-legacy-provider` as a workaround for the
`Error: error:0308010C:digital envelope routines::unsupported` issue.
> fixpatch: python-sphinx_rtd_theme

- rust-bindgen/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu"` issue.
> addpkg: rust-bindgen

- libiec61883/riscv64.patch
Update autotools aux files.
Upstream report was sent, but was not listed in maillist archive for unknown reason.
And the third-party Archive shows that there are still emails in June this year, but sourceforge's own archive shows that the last email was sent in 2006.[^1][^2]
[^1]: https://sourceforge.net/p/linux1394/mailman/linux1394-devel/
[^2]: https://marc.info/?l=linux1394-devel
> addpatch: libiec61883

- xpra/riscv64.patch
Xpra fail to run package step on our machines because it only wait 30
seconds for `pandoc` to finish. This PR increase the timeout to 300
seconds to ensure pandoc will not be killed by timeout.
> upgpatch: xpra

- db5.3/riscv64.patch
Fix the config.guess issue. Upstream report:
https://community.oracle.com/tech/developers/discussion/4509264/fail-to-build-berkeley-db-on-risc-v/p1?new=1
> addpatch: db5.3

- db/riscv64.patch
https://community.oracle.com/tech/developers/discussion/4509264/fail-to-build-berkeley-db-on-risc-v/p1?new=1
> addpatch: db

- stfl/riscv64.patch
According to the author's tweet(https://twitter.com/oe1cxw/status/906550696971046914),
she lost control of the original domain.
The upstream domain has been changed to clairexen.net.
The sha256 of the file has not changed.
Upstream bug report: https://bugs.archlinux.org/task/76958
> addpatch: stfl

- glade/riscv64.patch
Package glade require ~43secs to finish `add-child` test in VisionFive.
So add 5 mutiplier should be enough.
> addpatch: glade

- enscript/riscv64.patch
fix config.guess, upstream report: https://savannah.gnu.org/bugs/index.php?63591
> addpatch: enscript

- ncspot/riscv64.patch
* Remove the `--target` argument to fix the target triple
issue.
* Patch the `ring` crate source to our modified version
> addpatch: ncspot

- rust-rage/fix_rage_deps.patch
- rust-rage/riscv64.patch
[pprof-rs](https://github.com/tikv/pprof-rs) master branch add support for riscv64, but not released yet
> addpkg: rust-rage

- vaultwarden/riscv64.patch
The Cargo.toml file already has key `patch.crates-io`. This patch attach
the ring patch to the existing `patch.crates-io` key.
> upgpatch: vaultwarden

- go/riscv64.patch
Remove the sv57 patch since we have done this in kernel.
This might fail randomly on Unmatched board. Just retry it. I would need to make a further diagnosis later.
> upgpatch: go 2:1.19.5-1

- qemu-user-blacklist.txt
New pandoc PKGBUILD invokes the non-suid version of bwrap, which qemu-user doesn't seem to support:
```
bwrap: Creating new namespace failed, likely because the kernel does not
support user namespaces.  bwrap must be installed setuid on such
systems.
```
> qemu-user-blacklist: add pandoc

- gnome-control-center/riscv64.patch
Backport upstream patch: https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/1632
> addpatch: gnome-control-center

- aarch64-linux-gnu-binutils/riscv64.patch
$pkgdir/usr/etc/gprofng.rc does not exist on riscv64 platform.
> addpkg: aarch64-linux-gnu-binutils

- libcerf/riscv64.patch
Disable `-march=native` flag by using `-DPORTABLE=ON` flag according to the author's suggestion.
Upstream report: https://bugs.archlinux.org/task/77321
> addpatch: libcerf

- typos/riscv64.patch
Removing `--target` resolves the error below.
```
Caused by:
--- stderr
```
> addpatch: typos 1.13.9-1

- felix-rs/riscv64.patch
Removing `--target` resolved the error below.
```
Caused by:
--- stderr
```
> addpatch: felix-rs 2.2.3-1

- python-locket/riscv64.patch
This PR increase the time.sleep duration because the tests need more
time on our machine to finish the subprocess io jobs.
> addpatch: python-locket

- flex/riscv64.patch
Replace config.guess and config.sub with current versions to recognize riscv64.
This problem is already [fixed upstream](https://github.com/westes/flex/commit/0954f389d3eb50f0d39eba06eb0f2730d2ad3d50) and the git master builds on riscv64, but the current release tarball is from 2017.
> addpkg: flex

- php-legacy/riscv64.patch
- php-legacy/zend-concat-test.patch
This PR fix the Zend/tests/concat_003.test timeout.
Changes have been submitted to upstream. https://github.com/php/php-src/pull/10541
> addpkg: php-legacy

- qemu-user-blacklist.txt
QMake `system()` does not work under qemu-user which will cause
`Variable QMAKE_CXX.CPMILER_MACROS` is not defined issue.
> noqemu: qscintilla

- cargo-spellcheck/riscv64.patch
cargo-spellcheck introduce new dependency perf-event-open-sys which
doesn't have riscv64 binding. This commit change its source to my
patched version.
> upgpatch: cargo-spellcheck

- cargo-msrv/riscv64.patch
The package cargo-msrv has hard-coded rustc version into its tests to
feed rustup, but unfortunately, this version does not have RISC-V
support, causing all tests that rely on rustup to fail.
This issue has been reported to the upstream, for now we should just
ignore those tests and wait for the upstream to develop a new MSRV
searching implementation.
> updpatch: cargo-msrv

- qemu-user-blacklist.txt
Some tests fail in qemu-user but pass just fine on riscv hardware.
```
============================================================================
Testsuite summary for GNU M4 1.4.19
============================================================================
============================================================================
```
> addpkg: m4 to qemu-user-blacklist

- jumpy/riscv64.patch
Fixed rotten.
`echo -e "ring = { git = 'https://github.com/felixonmars/ring', branch = '0.16.20' }" >> Cargo.toml`
This line is a little different from previous, because the src has `[patch.crates-io]`.
So simply added it to the file's last line, which is also `[patch.crates-io]` located.
> updpatch: jumpy

- mitmproxy/riscv64.patch
- mitmproxy/skip-wg-test-client.patch
The wireguard test only check the system but didn't check the architecture.
Because the binary file is hardcoded in the test, I added the architecture check to skip the wireguard test on non-x86 machine.
Upstream report: https://github.com/mitmproxy/mitmproxy/pull/5953
> addpkg: mitmproxy

- grafana-zabbix/riscv64.patch
This patch add openssl workaround for webpack4.
Details:
https://github.com/felixonmars/archriscv-packages/pull/2044#issuecomment-1342245343
> upgpatch: grafana-zabbix

- libotf/riscv64.patch
Fix config.guess could not guess build type issue. This issue has been
reported to upstream via Email.
> addpatch: libotf

- patch-linux-config.sh
Copy config from Arch upstream to Linux source tree, then run `make olddefconfig` in **RISC-V environment**, then run this script to apply our modifications, check new option in config and add them to configs array, then run `make olddefconfig` in **RISC-V environment**.
To avoid polluting the patch, you must run `make olddefconfig` in the RISC-V environment to get the same compiler support options.
> chore: add new linux config maintain tool

- libavc1394/riscv64.patch
Fix config.guess could not guess build type issue. This project had
closed the issue ticket, so it is no longer possible to report this issue
to them.
> addpatch: libavc1394

- afpfs-ng/riscv64.patch
Fix config.guess could not guess build type issue.
Upstream had archived the project, so it is currently impossible to
submit this issue to upstream.
> addpatch: afpfs-ng

- libdv/riscv64.patch
Fix the config.guess could not guess build type issue.
The bug report tickets had been closed, so it is currently impossible to
report the issue to them.
> addpatch: libdv

- staticcheck/riscv64.patch
This patch resolves test timeout.
> addpatch: staticcheck 2023.1.2-1

- neovide/riscv64.patch
- neovide/skia_native_build.patch
This patch allows skia-bindings to compile natively on a previously unsupported architecture.
> addpkg: neovide

- aarch64-linux-gnu-gcc-bootstrap/PKGBUILD
This package provides a bootstrap compiler for 'aarch64-linux-gnu-gcc'.
This bootstrap compiler is also needed for compiling 'aarch64-linux-gnu-glibc', which depends on 'aarch64-linux-gnu-gcc'
> addpkg: aarch64-linux-gnu-gcc-bootstrap

- transmission/riscv64.patch
The original PKGBUILD link `transmission` to the system b64 library.
However, the system b64 library did not handle the data type correctly
and broke the base64 test on riscv64. This commit removes the libb64
dependency and links transmission to its forked version of the b64
library.
> addpatch: transmission

- cargo-generate-rpm/riscv64.patch
- qemu-user-blacklist.txt
Rust `std::process::Command` will never panic in QEMU user that cause
test bugs in this package. To demonstrate the issue, consider following
Rust code:
```rust
let process = Command::new("/usr/bin/non-exist-program").spawn();
assert!(process.is_err());
```
The above example will never panic in qemu user.
This commit fixes the rustc target triple issue and adds the package to
the qemu user blacklist.
Signed-off-by: Avimitin <dev@avimit.in>
> addpatch: cargo-generate-rpm

- gnupg/riscv64.patch
Fix old config.guess.
Note for reviewers: Arch's `prepare()` will apply all patches with .patch extension, so we don't need to patch manually.
> upgpatch: gnupg 2.2.41-1

- opengv/riscv64-no-march-native.patch
- opengv/riscv64.patch
Upstream PR: https://github.com/laurentkneip/opengv/pull/119
This package is compiled using `-march=native`, which I filed a [bug report](https://bugs.archlinux.org/task/77824) for Arch Linux x86_64.
> addpatch: opengv

- menu-cache/riscv64.patch
Upstream hasn't been updated for 6 years so I guess there is not need to report to upstream.
> addpatch: menu-cache

- libreoffice-still/add-rv64-support.patch
- libreoffice-still/riscv64.patch
This commit backport upstream RISC-V support.
Modified libraries:
* solenv: add riscv64 build config
* bridges: backport riscv64 cpp_uno implementation
* jvmfwk: add riscv64 build target
* firebird: add riscv64 implementation
> addpatch: libreoffice-still

- devtools-riscv64/PKGBUILD
- devtools-riscv64/pacman-extra-riscv64.patch
`pacman` actually checks for valid architecture, and uses the output of `uname()` for `auto`. This didn't break our regular packaging because pacman only checks for the specified targets to install, and `base` / `base-devel` are `any` packages and passes the check. It unfortunately breaks when, for example, trying to run `pacstrap` with it as an alternative pacman conf and specified anything that isn't an `any` package.
While it may sound an out-of-scope usage, I think we should not rely on the undocument fact that architecture checks are only done for the specified targets. `handle->architectures` being `x86_64` only is a problem on its own and _might_ break elsewhere too. So let's just be specific here.
> devtools-riscv64: restore force architecture

- firefox/riscv64.patch
`lld` and `jit` are already supported, enable them. 
Package `wasi` is ready, enable wasi support
> updpatch: firefox 110.0.1

- rosenpass/oqs-sys-add-cmake-flag.patch
- rosenpass/riscv64.patch
This patch overrides `oqs-sys` CMake options by patch its `build.rs`.
I've submitted an issue to discuss potential RISC-V support for liboqs: https://github.com/open-quantum-safe/liboqs/issues/1416
> addpatch: rosenpass

- presage/riscv64.patch
Fixed rotten.
The previous error seems not existing. However, it comes `config.guess`.
So rewrite the patch.
Upstream url: https://sourceforge.net/p/presage/bugs/17/.
> updpatch: presage

- qemu-user-blacklist.txt
```
Test suite test-pandoc: RUNNING...
test-pandoc: /proc/self/exe: readSymbolicLink: does not exist (No such file or directory)
```
> qemu-user-blacklist: add haskell-pandoc

- qt6-webengine/qt6-webengine-chromium-riscv64.patch
- qt6-webengine/riscv64.patch
It seems like one part of the patch has been upstream-ed, plus the source hash change.
> fixpatch: qt6-webengine

- web-ext/riscv64.patch
- web-ext/web-ext-no-jit.patch
- Disable V8's buggy JIT that makes eslint and babel fail <https://github.com/babel/babel/issues/15501>
- Upstream bug report: https://bugs.chromium.org/p/v8/issues/detail?id=13836
- Increase test timeout
> addpatch: web-ext

- rust/riscv64.patch
> upgpatch: rust

- percona-server/riscv64.patch
Added RISC-V memory barrier, `xchg` and `cpu_pause`.
Upstream: https://github.com/percona/percona-server/pull/5030
> upgpatch: percona-server

- xtrabackup/riscv64.patch
Similar to [percona-server](https://github.com/felixonmars/archriscv-packages/pull/2390), added RISC-V memory barrier, `xchg` and `cpu_pause`.
Upstream: https://github.com/percona/percona-xtrabackup/pull/1443
> upgpatch: xtrabackup

- luajit/riscv64.patch
Previous patch is not able to work in most environments. According to upstream maintainer, we should use clang to avoid some issues with ffi. Also disable LTO and use default target instead of amalg. Detailed bug reported for further investigation.
> fixpkg: luajit

- webkit2gtk/fix-riscv64-build.patch
- webkit2gtk/riscv64.patch
Backported riscv64 build fix from master, with modification
Source: https://commits.webkit.org/261498@main
> addpatch: webkit2gtk

- wpewebkit/fix-riscv64-build.patch
- wpewebkit/riscv64.patch
Backported riscv64 build fix from master, with modification
Source: https://commits.webkit.org/261498@main
(FYI this package is independent of webkit2gtk, but currently shares the same package and WebKit version with it.)
> addpatch: wpewebkit

- nodejs/nodejs-v8-jit-fix.patch
- nodejs/riscv64.patch
Apply the fix patch for v8 JIT issues.
The patch from nodejs/node#47399 won't apply to node 19.8.1 so we need to store a patch in our repo.
> upgpatch: nodejs

- ghidra/add-riscv64-build.patch
- ghidra/riscv64.patch
Add riscv64 build support. Compiles statically-linked protobuf build-time to match the Java library version.
> addpatch: ghidra

- java-openjfx/add-riscv64-build.patch
- java-openjfx/riscv64.patch
Enable riscv64 build.
- Also applied loongarch64 patch so that we can use the provided scaffold for porting.
- Uses Gradle wrapper since Gradle 8.x breaks the build.
> addpatch: java-openjfx

- ldc/riscv64.patch
ldc released initial riscv support in the latest version. This PR
remove all the old patches.
Notice: this package require extra `llvm14` dependency for rebuild.
> upgpatch: ldc

- python-whatthepatch/increase-test-timeout.patch
- python-whatthepatch/riscv64.patch
`test_huge_patch` timed out on both qemu-user and real hardware. Since it is purely for ensuring performance, it is safe to increase its timeout.
> addpatch: python-whatthepatch

- libsoup3/riscv64.patch
- Backport fix for HTTP/2 regression on platforms with unsigned char. Source: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/361
- Extend test timeout.
> addpatch: libsoup3

- bitwarden-cli/riscv64.patch
Remove the postinstall script entry instead of passing `--ignore-scripts` to `npm ci` because `--ignore-scripts` skips the build of the `argon2` dependency.
Remove the build dir of `argon2` dependency before packaging so that our package won't contain rubbish.
> upgpatch: bitwarden-cli

- xine-lib/riscv64.patch
Update config.guess and it has been reported to upstream.
https://sourceforge.net/p/xine/tickets/18/
Fix checksums in PKGBUILD and it has been reported to arch.
https://bugs.archlinux.org/task/78169
> addpkg: xine-lib

- couchdb/riscv64.patch
Fixed `package()` error.
The origin PKGBUILD file hardcoded the version number. While building, system can't find the files.
I can't find some bash variables can replace the version number, ($pkgver is not corresponding) so I just fix it to right one. However it's also hardcoding.
I don't know whether this dispose is appropriate or not, if exists better one, please teach, thanks.
Build passed.
> addpkg: couchdb

- gnu-netcat/riscv64.patch
Fixed `config.guess` error.
upstream: https://sourceforge.net/p/netcat/bugs/68/.
Because it seems that the sourceforge repo has not been maintained for a long time, sent a mail at the same time.
> addpkg: gnu-netcat

- onednn/riscv64.patch
Use sequential CPU runtime since it is the only supported one on riscv64.
> addpatch: onednn

- deno/riscv64.patch
- Patch rusty_v8 to allow passing custom GN arguments, as well as disabling printing GN arguments (it segfaults, but it is trivial for now since it only affects printing arguments, not generating) [1]
- Use system clang, lld, gn and ninja to build V8 from scratch, since there's no riscv64 prebuilt libraries available.
- Enable `v8_enable_shared_ro_heap`. This is intentially disabled by upstream [2], but we need to wait for pointer compression to meet rusty_v8's requirement [3] and disable it
[1]: https://github.com/denoland/rusty_v8/pull/1209
[2]: https://github.com/denoland/rusty_v8/blob/5dce1eaeef6457b7571b12c9c6170a362a62bb38/.gn#L52
[3]: https://github.com/denoland/rusty_v8/blob/5dce1eaeef6457b7571b12c9c6170a362a62bb38/src/binding.cc#L2907
> addpatch: deno

- .github/workflows/test.yml
See https://github.com/felixonmars/archriscv-packages/issues/2501
I want to add breezy to CI dependencies.
I added devtools to CI dependencies instead and removed git and subversion which are covered by devtools.
> fixci: use devtools in makedeps

- coin-or-coinutils/riscv64.patch
Update config.guess&config.sub
Upstream updated it in master branch but did not in 2.11.8 release.
> addpkg: coin-or-coinutils

- coin-or-cbc/riscv64.patch
Update config.guess which has been updated by upstream in the master branch https://github.com/coin-or/Cbc/commit/f30b1f4ad9326dc76cc8af715bb3cff109925447 but not in the latest release.
> addpkg: coin-or-cbc

- qt6-base/riscv64.patch
Revert [upstream upgpkg](https://github.com/archlinux/svntogit-packages/commit/395c189970fe5b20e7f84ecd60a3bf57c34ac7d9) since `-mno-direct-extern-access` is not available on riscv64.
> addpatch: qt6-base

- python-xarray/riscv64.patch
Apply the patch that prevents casting from NaN to integers, which is also used in OpenSUSE:
https://build.opensuse.org/package/view_file/openSUSE:Factory:RISCV/python-xarray/NaT.patch?expand=1
> addpatch: python-xarray

- transcode/riscv64.patch
- Fixed `config.guess`. (The [upstream](http://www.transcoding.org/) seems to disappear.)
- Removed the flag `--enable-mmx` of the execution of `configure` script.
> addpkg: transcode

- neko/riscv64.patch
This package is deprecated upstream, but still required by Haxe.
Upstream: https://github.com/HaxeFoundation/neko/pull/285
> addpatch: neko

- jupyter-nbclient/riscv64.patch
The test is failing on riscv64 linux boards because the KeyboardInterrupt happens too soon. (before the program enters the infinite loop)
Upstream PR: https://github.com/jupyter/nbclient/pull/285
> addpatch: jupyter-nbclient

- python-eventlet/riscv64.patch
Fix rotten.
The updated version now includes the greendns patch.
> updgpatch: python-eventlet 0.33.3-1

- influx-cli/riscv64.patch
Fixed hard-code `amd64` architecture to `riscv64`  in `package()` function of PKGBUILD to let system find the files.
Build passed.
> addpkg: influx-cli

- pari/riscv64.patch
The first build needs `nocheck`.
See #2571 for more context.
> addpatch: pari

- cjdns/cjdns-add-riscv64-support.patch
- cjdns/libsodium-fix-rust-c-target.patch
- cjdns/riscv64.patch
- Replace riscv64gc with riscv64 in TARGET and HOST (that passes into C compilation) in `libsodium-sys`
- Enable riscv64 build in `cjdns_sys`
> addpatch: cjdns

- java8-openjdk-bootstrap/PKGBUILD
- java8-openjdk-bootstrap/install_jdk8-openjdk-bootstrap.sh
- java8-openjdk-bootstrap/install_jre8-openjdk-bootstrap-headless.sh
- java8-openjdk-bootstrap/install_jre8-openjdk-bootstrap.sh
Cross compile openjdk8 (with zero jvm) from x86_64.
The java8-openjdk-add-riscv-support.patch is taken from https://gitee.com/misaka00251/openjdk-1.8.0/blob/master/add-riscv-support.patch
We may try to enable the JIT later, using this patch: https://gitee.com/misaka00251/openjdk-1.8.0/blob/nobisheng/riscv64.patch , or this repo: https://github.com/zhangxiang-plct/jdk8u
After cross compiling the bootstrap packages, java8-openjdk can be bootstrapped on riscv64.
I tested the final packages by building and testing `java-commons-lang` package. Only one test failed with timeout. Previously building this package with jdk19 failed with 96 failures.
(https://archriscv.felixc.at/.status/log.htm?url=logs/java-commons-lang/java-commons-lang-3.12.0-1.log). So this may suggest the riscv jdk19 is buggy.
> addpkg: java8-openjdk-bootstrap

- sequoia-wot/riscv64.patch
`ring👿` is no longer a denepdency. 😇😇😇
> upgpatch: sequoia-wot

- opus/riscv64.patch
- Disable intrisics
- Increase test timeout due to poor software codec performance
> addpatch: opus

- qemu-user-blacklist.txt
rlimit does not seem to work properly in qemu-user, causing test-stack-overflow to eat a lot of memory and test-out-of-memory to fail.
There is a changed line of "glib-perl" because a previous modification didn't keep this file sorted.
> qemu-user-blacklist: add guile{,2.2}

- qemu-user-blacklist.txt
Previously I made a mistake in #2590 (Thanks to @Xeonacid for pointing it out).
I documented it in the wiki so that the same mistake won't happen again: 
https://github.com/felixonmars/archriscv-packages/wiki/%E6%88%91%E4%BB%AC%E7%9A%84%E5%B7%A5%E4%BD%9C%E4%B9%A0%E6%83%AF/_compare/cfb40bf1d5f7126614ac0cc07d3faf64bff36913...1a4509a878c0da84d3f591b74743b21a5f15d41b
> fix: name ordering

- meson/riscv64.patch
* REQUIRES SKIPPING CHECKS because `ldc` is not ready yet
* Some other tests also fails because of outdated `gobject-introspection`, but this package depends on `meson`, forming a circular dependency. So just skip the test for now.
> updpkg: meson 1.1.0

- java17-openjfx/add-riscv64-build.patch
- java17-openjfx/riscv64.patch
Backported java-openjfx's riscv64 patch.
> addpatch: java17-openjfx

- surge-xt/riscv64.patch
- surge-xt/surge-xt-juce-riscv.patch
- surge-xt/surge-xt-riscv.patch
Backport from patches:
https://github.com/surge-synthesizer/surge/pull/6722
https://github.com/surge-synthesizer/sst-plugininfra/pull/37
https://github.com/surge-synthesizer/JUCE/pull/3
Luajit is disabled as this package vendored the source of a old version of Luajit inside its repo.
> addpatch: surge-xt 1.1.2-1

- jumpy/riscv64.patch
- fix ring issue
- update mimalloc to 0.1.36 to fix https://github.com/purpleprotocol/mimalloc_rust/issues/92
- upstreamed: https://github.com/fishfolk/jumpy/pull/776
> upgpatch: jumpy

- gnu-efi/riscv64-fix-build.patch
- gnu-efi/riscv64.patch
BOOLEAN isn't a macro anymore and CHAR8 should be typedef-ed
> fixpatch: gnu-efi

- libretro-play/add-riscv64-build.patch
- libretro-play/riscv64.patch
- Add platform flags for riscv64.
- Provide generic fallback for functions based on their SSE version, using `simde`.
> addpatch: libretro-play

- python-wxpython/riscv64.patch
This package cannot be built because it uses some deprecated setuptools options. This problem occurs on x86_64 as well and I reported to ArchLinux at https://bugs.archlinux.org/task/78517 . This patch backports commit from upstream.
> addpatch: python-wxpython 4.2.0

- python-jupyter-client/riscv64.patch
Deselect a failing test that seems to be inappropriately constructed.
This test is added in https://github.com/jupyter/jupyter_client/pull/877. Its code is not platform dependent but upstream claims that it only works with cpython on ubuntu in ci.
Close #2519
> addpatch: python-jupyter-client

- devtools-riscv64/PKGBUILD
- devtools-riscv64/pacman-extra-riscv64.patch
sogrep-riscv64 is not upgraded. Let's have a working devtools first and upgrade it later.
> upgpkg: devtools-riscv64 1:1.0.0+patch1-1

- lurk/riscv64.patch
- nix: Add `nix::sys::ptrace::{get,set}regs` for newer platforms that does not support `PTRACE_{GET,SET}REGS`
(https://github.com/nix-rust/nix/pull/2044)
- syscalls: Add riscv32 and riscv64 syscall support (https://github.com/jasonwhite/syscalls/pull/37)
- lurk: Add syscalls groups (taken from strace) and parameter lists for riscv64 (will upstream when nix's PR is merged)
> addpatch: lurk

- evemu/riscv64.patch
Upstream url: https://gitlab.freedesktop.org/libevdev/evemu/-/issues/5.
> addpkg: evemu

- rust/bump-bootstrap-cc.patch
- rust/riscv64.patch
* Bump dependency `cc-rs` of `bootstrap` for musl-gcc to work correctly.
> updpatch: rust 1.69.0

- java-commons-lang/riscv64.patch
Upstreamed to arch bug tracker(new comment with updated patch): https://bugs.archlinux.org/task/78492#comment218243
> upgpatch: java-commons-lang

- symengine/riscv64.patch
The patch was removed in 679c516 since Arch Linux once disabled LLVM [1]. Now Arch Linux has reenabled LLVM [2]. This PR restores `riscv64.patch`.
[1]: https://gitlab.archlinux.org/archlinux/packaging/packages/symengine/-/commit/2925cd00f62556cda5457263db2b1e28c4a5b011
[2]: https://gitlab.archlinux.org/archlinux/packaging/packages/symengine/-/commit/5aedc08fae864dde8cd5039c9d72d597d58ebe95
> addpatch: symengine 0.10.1-1

- libjxl/riscv64.patch
Use .diff instead of .patch to ensure content is unchanged.
> updpatch: libjxl 0.8.1-2

- cargo-edit/riscv64.patch
`ring` dependency is excluded from unsupported platforms.
Test case depends on Cargo's output, which differs from 1.68 to 1.69. This PR should be merged after successfully building Rust 1.69.
> upgpatch: cargo-edit 0.11.11-1

- coin-or-osi/riscv64.patch
The most recent release does not yet contain the new upstream version of `config.guess`.
It has already been updated in https://github.com/coin-or/Osi/commit/79167ab9a4487b5a1f88ec4fdfd4ed529a1c31ff .
> addpatch: coin-or-osi

- glusterfs/riscv64.patch
tcmalloc on platforms other than x86_64 has caused [problems][1], which causes libvirt's tests to fail:
```
TEST: virdrivermoduletest
3) Test driver "storage"                                             ... libvirt:  error : internal error: Failed to load module '/home/hacker/libvirt/src/libvirt-9.3.0/build/src/libvirt_storage_backend_gluster.so': /usr/lib/libtcmalloc_minimal.so.4: cannot allocate memory in static TLS block
```
Fedora [has it disabled][2] for those platforms, so we disable it too.
[1]: https://github.com/gluster/glusterfs/issues/2913
[2]: https://src.fedoraproject.org/rpms/glusterfs/blob/rawhide/f/glusterfs.spec#_78
> addpatch: glusterfs

- deno/riscv64.patch
- Upstream merged rusty_v8 patch.
- Remove `v8_enable_shared_ro_heap=true` since they relaxed configuration restrictions; see https://github.com/denoland/rusty_v8/commit/07f2e9f3b63ada1a4cd3205a5b13f2ba25cd2ca6.
> upgpatch: deno 1.33.2-1

- python-gdstk/riscv64.patch
Fix FMA test failure directly instead of using `-ffp-contract=off`.
Upstream: https://github.com/heitzmann/gdstk/pull/177
> updpatch: python-gdstk 0.9.30-2

- ocaml/riscv64.patch
OCaml 5.0.0 temporarily disabled native compiler support for riscv64. It is added back in an alpha version of 5.1.0.
> updpatch: ocaml 5.0.0-1

- ocaml/riscv64.patch
Backport RISC-V native-code compiler support from 5.1.0-alpha2 (since most OCaml packages seem to depend on it)
> updpatch: ocaml 5.0.0-1.1

- libdc1394/riscv64.patch
Fix config.{guess,sub}. Upstreamed to libdc1394-devel mailing list.
Unblocks opencv.
> addpatch: libdc1394

- qemu-user-blacklist.txt
The stddef.h issue no longer occurs.
> qemu-user-blacklist: remove pyside{2,6}

- abletonlink/riscv64.patch
Fix floating point test failure. Upstreamed to https://github.com/Ableton/link/pull/134.
Supersedes #1717.
> addpatch: abletonlink

- arduino/arduino-add-riscv64-support.patch
- arduino/riscv64.patch
- Patch build.xml to add riscv64 support
- No prebuilt astyle and listSerialPortsC available so we build them ourselves.
- Pin the source to a commit because upstream didn't create new tags for them.
- I prefer not to upstream the patch as upstream previously didn't accept the powerpc port.
> addpatch: arduino

- qemu-user-blacklist.txt
`test_radio_dish` always times out on qemu-user, while passes on Unmatched.
> qemu-user-blacklist: add zeromq

- qemu-user-blacklist.txt
Tests segfault on qemu-user:
```
tests/test_xmlsec.py::TestModule::test_reinitialize_module PASSED        [  0%]
tests/test_constants.py::test_transform_str[__Transform('aes128-cbc', 'http://www.w3.org/2001/04/xmlenc#aes128-cbc', 16)] Fatal Python error: Segmentation fault
```
> qemu-user-blacklist: add python-xmlsec

- sccache/riscv64.patch
Disable `dist-server` feature as it is currently only supported on x86_64.
> updpatch: sccache 0.5.3-1

- avr-gcc/riscv64.patch
use bfd because we don't have gold in our binutils.
Fixes arduino sketch compiling error.
> addpatch: avr-gcc

- gcc/riscv64.patch
Fix libasan error for downstream projects such as Go.
Discussion: https://github.com/golang/go/issues/57691
> updpatch: gcc 13.1.1-1.1

- qemu-user-blacklist.txt
It's obvious from the log: https://archriscv.felixc.at/.status/log.htm?url=logs/python-setproctitle/python-setproctitle-1.3.2-2.log
> qemu-user-blacklist: add python-setproctitle

- python-websockets/python-websockets-float-timeout-factor.patch
- python-websockets/riscv64.patch
- Allow the timeout factor to be float: https://github.com/python-websockets/websockets/pull/1371
- The patch needs to be stored in our repo because the patch of the PR won't apply to v10.4.
- Set timeout factor to 1.1 to make the tests pass on riscv64 boards. (As suggested in https://github.com/python-websockets/websockets/issues/1026)
> addpatch: python-websockets

- startup-notification/riscv64.patch
upstream url: https://gitlab.freedesktop.org/xdg/startup-notification/-/issues/5.
> addpkg: startup-notification

- systemd/riscv64.patch
Add workaround for the following error:
```
error while loading shared libraries: cannot make segment writable for relocation: Error 38
```
Could be related to GCC 13 & text relocations.
Possibly related too:
```
systemd W: ELF file ('usr/lib/systemd/systemd-logind') has text relocations.
systemd W: ELF file ('usr/lib/systemd/systemd-networkd') has text relocations.
```
> updpatch: systemd 253.5-1.1

- himalaya/riscv64.patch
Fixed rotten patch due to version update.
> updpatch: himalaya

- xosd/riscv64.patch
The [upstream](https://sourceforge.net/projects/libxosd/) does not have a ticket tracker to create a bug report.
> addpkg: xosd

- libcaca/riscv64.patch
Fix instruction detection.
The patch is upstreamed as https://github.com/cacalabs/libcaca/pull/76.
> addpatch: libcaca

- haskell-tasty/riscv64.patch
Don't depend on unbounded-delays for riscv64.
Upstreamed as https://github.com/UnkindPartition/tasty/pull/371
> addpatch: haskell-tasty

- python-llvmlite/riscv64.patch
Skip MCJIT related tests. Upstream issue about riscv64 support: https://github.com/numba/llvmlite/issues/923
> addpatch: python-llvmlite

- fwupd/riscv64.patch
Disable unsupported plugins for riscv64.
> addpatch: fwupd

- libosmosdr/riscv64.patch
Upstream patch: https://bugs.archlinux.org/task/77787
> addpatch: libosmosdr 0.1.r10.gba4fd96-2

- rust/riscv64.patch
- update rotten patch
- jemalloc patch is no longer needed
> updpatch: rust 1:1.70.0-1

- hplip/riscv64.patch
> updpatch: hplip 1:3.23.5-1

- openrct2/riscv64.patch
Fix 64-bit platform check. Upstreamed to https://patch-diff.githubusercontent.com/raw/OpenRCT2/OpenRCT2/pull/20498.diff.
> addpatch: openrct2

- binutils/riscv-dynamic-tls-reloc-pie.patch
- binutils/riscv-pr22263-1.patch
- binutils/riscv64.patch
Avoid unsupported reloc type in RISC-V.
See also:
https://sourceware.org/pipermail/binutils/2023-May/127302.html
https://sourceware.org/pipermail/binutils/2023-May/127653.html
> addpatch: binutils

- nodejs-lts-gallium/riscv64.patch
Fix rotten. Needs nocheck as usual.
> upgpatch: nodejs-lts-gallium

- opencv/riscv64.patch
> updpatch: opencv 4.7.0-13

- silicon/riscv64.patch
Backport string pointer fix from https://github.com/Aloxaf/silicon/commit/f666c95d3dab85a81d60067e2f25d29ee8ab59e7.
> addpatch: silicon

- linux/riscv64.patch
- Add patch from @XieJiSS to fix seccomp issue
> updpatch: linux 6.4.2.arch1, fix seccomp

- code/riscv64.patch
- Add missing riscv64 definition.
- Skip browser downloads(they are not used at all).
- Skip electron binary download. (No upstream binary available)
- Create a zipped electron22 and put it in the cache to make the build process happy.
- Build all native node extensions in debug mode to avoid segfaults and strange behaviors.
- This bug needs further investigation.
> addpatch: code

- cardinal/riscv64.patch
- riscv support patch has been merged upstream and released.
- GCC 13 issue has been reported as https://bugs.archlinux.org/task/79062
> updpatch: cardinal 23.02-2

- openblas/riscv64.patch
- Fix riscv64 detection in cmake (https://github.com/xianyi/OpenBLAS/pull/4137)
- Fix INTERFACE64 (to be upstreamed)
> updpatch: openblas 0.3.23-3

- python-pyarrow/riscv64.patch
- riscv support patch has been merged upstream
- checksum mismatch reported as https://bugs.archlinux.org/task/79069
> updpatch: python-pyarrow 10.0.1-2

- stratisd/riscv64.patch
Replace libmount with https://github.com/liushuyu/libmount, which includes several fixes.
> addpatch: stratisd

- sequoia-chameleon-gnupg/riscv64.patch
> updpatch: sequoia-chameleon-gnupg 0.3.2-1

- qemu-user-blacklist.txt
Check failed on qemu-user while passed on real hardware:
```
mtest.c:50: mdb_env_open(env, "./testdb", MDB_FIXEDMAP , 0664): Operation not supported
```
> qemu-user-blacklist: add lmdb

- dive/riscv64.patch
Go's -race is not supported on riscv64.
> addpatch: dive
