felixonmars/archriscv-packages

arrow/riscv64.patch

updpkg: arrow

---

ghidra/riscv64.patch

upgpatch: ghidra

---

deno/riscv64.patch

upgpatch: deno

---

libisofs/riscv64.patch

fix `config.guess`.
An email has been sent to the upstream mailing list.

addpkg: libisofs

---

libburn/riscv64.patch

fix `config.guess`.
An email has been sent to the upstream mailing list.

addpkg: libburn

---

svelte-language-server/increase-test-timeout.patch
svelte-language-server/riscv64.patch

updpkg: svelte-language-server

---

rust-bindgen/riscv64.patch

updpatch: rust-bindgen

---

gcc12/libitm-riscv64.patch
gcc12/riscv64.patch
gcc12/unfilter-default-library-path.patch

Reused previous gcc patch with modifications.

addpatch: gcc12

---

typst/riscv64.patch

updpatch: typst 1:0.6.0-1

---

0ad/add-riscv64-support.patch
0ad/riscv64.patch

- Patch SpiderMonkey using old js78 patches
- Enable riscv64 build

addpatch: 0ad

---

neko/riscv64.patch

updpatch: neko 2.3.0-8

---

namcap/fix-riscv64-test.patch
namcap/riscv64.patch
namcap/support-other-arches.patch

updpatch: namcap 3.4.2-1

---

thunderbird/riscv64.patch

updpatch: thunderbird 102.12.0-2

---

cargo-depgraph/riscv64.patch

upgpatch: cargo-depgraph

---

chromium/riscv-crashpad.patch
chromium/riscv64.patch

Switch to upstream crashpad patch, which is significantly better than our current patch.
https://chromium-review.googlesource.com/c/crashpad/crashpad/+/4581050

upgpatch: chromium

---

onefetch/riscv64.patch

updpatch: onefetch 2.18.1-1

---

mesa/riscv64.patch

updpatch: mesa 23.1.3-1

---

python-rpds-py/riscv64.patch

addpatch: python-rpds-py 0.8.8-1

---

nvchecker/riscv64.patch

Fix version mismatch. See https://github.com/lilydjwg/nvchecker/pull/231.

addpatch: nvchecker

---

vaultwarden/riscv64.patch

updpatch: vaultwarden 1.29.0-1

---

xtrabackup/riscv64.patch

updpatch: xtrabackup 8.0.33_27-3

---

cargo-cyclonedx/riscv64.patch

addpatch: cargo-cyclonedx

---

qt6-quick3dphysics/riscv64.patch

upgpatch: qt6-quick3dphysics

---

gifski/riscv64.patch

updpatch: gifski 1.11.0-1

---

gstreamer/riscv64.patch

updpatch: gstreamer 1.22.5-1

---

cargo-insta/riscv64.patch

addpatch: cargo-insta

---

java17-openjdk/riscv64.patch

updpatch: java17-openjdk 17.0.8.u7-1

---

percona-server/riscv64.patch

updpatch: percona-server 8.0.33_25-3

---

mame/riscv64.patch

Fix `relocation truncated to fit`.

addpatch: mame

---

jenkins/riscv64.patch
jenkins/use-system-yarn.patch

Use exec-maven-plugin to execute system Yarn.

addpatch: jenkins

---

wldash/riscv64.patch
wldash/update-nix.patch

Update `nix` and its dependants.

addpatch: wldash

---

cargo-deny/riscv64.patch

Upstream added `ring` dependency.

updpatch: cargo-deny 0.14.0-1

---

cargo2junit/riscv64.patch

addpatch: cargo2junit

---

gopass/riscv64.patch

Related upstream PRs:
- https://github.com/gen2brain/shm/pull/7
- https://github.com/gopasspw/gopass/pull/2633

addpatch: gopass

---

bam/add-riscv-defines.patch
bam/riscv64.patch

Add platform definition for riscv64.

addpatch: bam

---

teeworlds/add-riscv-defines.patch
teeworlds/allow-riscv64-build.patch
teeworlds/riscv64.patch

Allow build on `unknown` architecture.

addpatch: teeworlds

---

graphviz/riscv64.patch

updpatch: graphviz 8.1.0-2

---

mesa/riscv64.patch

updpatch: mesa 1:23.1.5-1

---

aarch64-linux-gnu-binutils/riscv64.patch

upgpatch: aarch64-linux-gnu-binutils

---

electron22/electron22-riscv-sandbox.patch
electron22/riscv64.patch

- Fix sandbox patch. Our code-oss can run without the `--no-sandbox` flag after this.

upgpatch: electron22

---

libredefender/riscv64.patch

Apply upstream char fix. Supersedes #384.

addpatch: libredefender

---

zettlr/riscv64.patch

upgpatch: zettlr

---

electron24/REVERT-problematic-signal-handling-workaround.patch
electron24/electron24-riscv-sandbox.patch
electron24/riscv64.patch

Same as previous electron25 PR.

uppatch: electron24

---

chromium/riscv64.patch

upgpatch: chromium 116.0.5845.96-1

---

python-whatthepatch/riscv64.patch

upgpatch: python-whatthepatch

---

webrtc-audio-processing/riscv64.patch

updpatch: webrtc-audio-processing 0.3.1-4

---

ghidra/riscv64.patch

updpatch: ghidra 10.3.3-1

---

open-isns/riscv64.patch

addpkg: open-isns

---

glibc/riscv64.patch

updpatch: glibc 2.38-3

---

tailwindcss-language-server/riscv64.patch

- Upgrade esbuild to support RISC-V
- Upgrade node-gyp to avoid strange errors

addpatch: tailwindcss-language-server

---

libretro-play/add-riscv64-build.patch
libretro-play/riscv64.patch

updpatch: libretro-play 7863-1

---

stratisd/riscv64.patch

updpatch: stratisd 3.5.8-1

---

difftastic/riscv64.patch

updpatch: difftastic 0.51.1-3

---

hatari/fix-rega0-for-riscv.patch
hatari/riscv64.patch

Fix duplicate REG_A0. Patch taken from Debian.

addpatch: hatari

---

felix-rs/riscv64.patch

updpatch: felix-rs 2.8.1-1

---

skate/riscv64.patch

Replace unmaintained github.com/jacobsa/crypto with github.com/aperturerobotics/jacobsa-crypto. See also https://github.com/charmbracelet/charm/pull/178.

addpatch: skate

---

neovide/riscv64.patch
neovide/skia_native_build.patch

Switch to a cleaner approach to patch skia-bindings.

updpatch: neovide 0.11.1-1

---

rio/riscv64.patch

- Fix broken rust target.
- Workaround rustc bug: https://github.com/rust-lang/rust/issues/110224

addpatch: rio

---

heh/riscv64.patch

addpatch: heh

---

libatasmart/riscv64.patch

Update the outdated config.guess file.
Upstream report: https://github.com/Rupan/libatasmart/issues/10

addpatch: libatasmart

---

0ad/riscv64.patch

Fix libatomic issue on riscv64 platform.
Upstream report: https://code.wildfiregames.com/D5127

updpatch: 0ad

---

opencv/riscv64.patch

updpatch: opencv 4.8.0-5

---

element.io/riscv64.patch

- Fix rotten
- Make the patch less prone to rot.

upgpatch: element.io

---

libretro-play/add-riscv64-build.patch
libretro-play/riscv64.patch

updpatch: libretro-play 7935-1

---

openblas/riscv64.patch

updpatch: openblas 0.3.24-2

---

wezterm/riscv64.patch

updpatch: wezterm 20230712.072601.f4abf8fd-1

---

plumber/riscv64.patch

updpatch: plumber 2.5.2-1

---

cantor/riscv64.patch

updpatch: cantor 23.08.1-1

---

rust-rage/riscv64.patch

updpatch: rust-rage 0.9.2-2

---

ffmpeg/riscv64.patch

updpatch: ffmpeg 2:6.0-11

---

stylua/riscv64.patch

updpatch: stylua 0.18.2-1

---

deepin-clone/riscv64.patch

Upstreamed: https://github.com/linuxdeepin/deepin-clone/pull/43

addpatch: deepin-clone

---

opencv/riscv64.patch

updpatch: opencv 4.8.0-6

---

cargo-hack/riscv64.patch

addpatch: cargo-hack

---

openrct2/riscv64.patch

updpatch: openrct2 0.4.6-1

---

eslint/riscv64.patch

updpatch: eslint 8.49.0-1

---

deepin-draw/riscv64.patch

Upstreamed: https://github.com/linuxdeepin/deepin-draw/pull/83

addpatch: deepin-draw

---

zlib-ng/riscv64.patch

Disable RVV according to https://github.com/zlib-ng/zlib-ng/blob/57a2ed9e503bfeb92577c87aa49b9b0727d97120/arch/riscv/README.md

addpatch: zlib-ng

---

fwupd/riscv64.patch

updpatch: fwupd 1.9.5-2

---

qemu-user-blacklist.txt

qemu-user-blacklist: add libmp4v2

---

qt6-webengine/riscv64.patch

updpatch: qt6-webengine 6.5.2-3

---

postgresql/riscv64.patch

Fix rotten.
Note that it may crash in the tests but it's not reliably reproducible.

updpatch: postgresql 15.4-2

---

evcxr_repl/riscv64.patch

addpatch: evcxr_repl

---

pre-commit/riscv64.patch

Upstreamed to https://github.com/pre-commit/pre-commit/pull/3011.

addpatch: pre-commit

---

python-osqp/riscv64.patch

addpatch: python-osqp 0.6.2.post9-1

---

sensors-applet/riscv64.patch

Disable nvidia proprietary driver support.

addpatch: sensors-applet

---

mate-sensors-applet/riscv64.patch

Disable nvidia proprietary driver support.

addpatch: mate-sensors-applet

---

mangohud/riscv64.patch

Disable nvidia proprietary driver support.

addpatch: mangohud

---

conky/riscv64.patch

Disable nvidia proprietary driver support.

addpatch: conky

---

dhall-docs/riscv64.patch

updpatch: dhall-docs 1.0.11-35

---

bandwhich/riscv64.patch

addpkg: bandwhich

---

eza/riscv64.patch

addpkg: eza

---

qt6-quick3dphysics/physx-rv64.patch
qt6-quick3dphysics/riscv64.patch

upgpatch: qt6-quick3dphysics 6.5.3-1

---

stylelint/modify-time-limit.patch
stylelint/riscv64.patch

upgpatch: stylelint 15.10.3-1

---

percona-server/riscv64.patch

Fix rotten and make it less prone to rot.

upgpatch: percona-server

---

python-executing/riscv64.patch

updpatch: python-executing 2.0.0-1

---

daktilo/riscv64.patch

addpkg: daktilo

---

srsgui/riscv64.patch

Upstream PR: https://github.com/srsran/srsGUI/pull/21
Arch bug report: https://bugs.archlinux.org/task/79885

addpatch: srsgui 2.0-3

---

b3sum/riscv64.patch

updpkg: b3sum

---

gitlab/riscv64.patch

Fix checksum mismatch on source file ffd057b399c1f68d43a68b960dd9bdf7a29fdd09.patch
bug report: https://bugs.archlinux.org/task/79869
Update config.guess and config.sub in gem rbtrace of dependency ruby2.7. There has been an issue about this problem.
https://github.com/tmm1/rbtrace/issues/73

addpkg: gitlab

---

kubo/riscv64.patch

upgpatch: kubo 0.23.0-1

---

python-gdstk/riscv64.patch

upgpatch: python-gdstk 0.9.41-1

---

maturin/riscv64.patch

updpatch: maturin

---

oxyromon/riscv64.patch

addpkg: oxyromon

---

toolbox/riscv64.patch

updpatch: toolbox 0.0.99.4-2

---

firefox/riscv64.patch

Re-enable optimization with only necessary options removed or disabled.

updpatch: firefox 118.0.1-1

---

gnome-applets/riscv64.patch

[Arch bug report](https://bugs.archlinux.org/task/79903)

addpatch: gnome-applets 3.46.0-1

---

python-mitmproxy-rs/riscv64.patch

upgpatch: python-mitmproxy-rs 0.3.11-1

---

cargo-semver-checks/riscv64.patch

upgpatch: cargo-semver-checks 0.24.0-1

---

gcc12/riscv64.patch

upgpatch: gcc12

---

ollama/riscv64.patch

Checksum mismatch reported at https://bugs.archlinux.org/task/79911

addpatch: ollama 0.1.1-2

---

hplip/riscv64.patch

updpatch: hplip 1:3.23.8-1

---

fwupd/riscv64.patch

updpatch: fwupd 1.9.6-1

---

firefox-developer-edition/riscv64.patch

addpatch: firefox-developer-edition 119.0b7-1

---

mesa/riscv64.patch

updpatch: mesa 1:23.2.1-2

---

amdvlk/riscv64.patch

updpatch: amdvlk 2023.Q3.3-1

---

krita/riscv64.patch

upgpatch: krita 5.2.0-2

---

mangohud/riscv64.patch

upgpatch: mangohud 0.7.0-2

---

jenkins/riscv64.patch
jenkins/use-system-yarn.patch

updpatch: jenkins 2.427-1

---

python-mechanize/fix-test_Cookie_iterator.patch
python-mechanize/riscv64.patch

https://bugs.archlinux.org/task/79953

addpatch: python-mechanize 1:0.4.8-2

---

renderdoc/riscv64.patch

upgpatch: renderdoc 1.29-1

---

inxi/riscv64.patch

Checksum mismatch reported at: https://bugs.archlinux.org/task/79926

addpatch: inxi 3.3.30-1

---

java8-openjdk/riscv64.patch

updpatch: java8-openjdk 8.382.u05-1

---

prusa-slicer/riscv64.patch

upgpatch: prusa-slicer

---

molecule-plugins/riscv64.patch

https://bugs.archlinux.org/task/79964

addpatch: molecule-plugins 23.5.0-1

---

calibre/fix-stbsp__uintptr.patch
calibre/riscv64.patch

Fix nothing/stb uintptr issue. Merge after python-mechanize patch.

addpatch: calibre 6.28.1-2

---

warzone2100/riscv64.patch

https://bugs.archlinux.org/task/79965

updpatch: warzone2100 4.3.5-2

---

haskell-typst/riscv64.patch

https://github.com/jgm/typst-hs/pull/16

addpatch: haskell-typst 0.3.1.0-16

---

unixodbc/riscv64.patch

Fix config.guess. I sent an email to the maintainer about updating it in release tarballs.

addpatch: unixodbc

---

pyalpm/riscv64.patch

Update upstream PR: https://gitlab.archlinux.org/archlinux/pyalpm/-/merge_requests/19

upgpatch: pyalpm

---

python-pytoolconfig/riscv64.patch

[Arch bug report](https://bugs.archlinux.org/task/79988)

addpatch: python-pytoolconfig 1.2.5-3

---

virt-viewer/riscv64.patch

fix source url
[upstream bug report](https://bugs.archlinux.org/task/79994)

addpatch: virt-viewer

---

greetd/riscv64.patch

addpatch: greetd 0.9.0-3

---

qt6-quick3dphysics/riscv64.patch

upgpatch: qt6-quick3dphysics 6.6.0-1

---

ollama/riscv64.patch

upgpatch: ollama 0.1.3-1

---

keycloak/riscv64.patch

upgpatch: keycloak

---

electron25/riscv64.patch

upgpatch: electron25

---

boost/riscv64.patch

Fix missing asm functions in boost context lib.
Upstream bugs:
- boostorg/context: https://github.com/boostorg/context/issues/243
- b2: https://github.com/bfgroup/b2/issues/340
Upstream PR: https://github.com/bfgroup/b2/pull/341

addpatch: boost

---

libotr/riscv64.patch

Update the outdated config scripts.
I've tried to notify the upstream via their OTR-dev mailing list.

addpatch: libotr

---

greetd-tuigreet/riscv64.patch

addpatch: greetd-tuigreet 0.8.0-2

---

findomain/riscv64.patch

upgpatch: findomain

---

greetd-regreet/riscv64.patch

addpatch: greetd-regreet 0.1.1-1

---

stylelint-config-recommended/riscv64.patch

Fix `engines.test.js`, cherry-pick: https://github.com/stylelint/stylelint-config-recommended/commit/6e5406eec487a4f698379ef0a15de412c9365455

addpatch: stylelint-config-recommended 13.0.0-1

---

xtrabackup/riscv64.patch

upgpatch: xtrabackup

---

felix-rs/riscv64.patch

upgpatch: felix-rs 2.9.0-1

---

watchbind/riscv64.patch

addpatch: watchbind 0.1.19-1

---

jellyfin-ffmpeg/riscv64.patch

Disable cuda and Nvidia codec.

addpatch: jellyfin-ffmpeg 6.0.6-2

---

normaliz/riscv64.patch

Apply upstream commit using NoLLL option: https://github.com/Normaliz/Normaliz/commit/132415b96c57f6dc4d45fb4e8de62bdc8df18dae
See also: https://github.com/Normaliz/Normaliz/issues/407

addpatch: normaliz 3.10.1-2

---

symengine/riscv64.patch

upgpatch: symengine 0.11.1-2

---

coin-or-coinutils/riscv64.patch

Fix rotten patch, and make it less likely to rot.

upgpatch: coin-or-coinutils 2.11.10-1

---

amdvlk/riscv64.patch

Fix rotten patch and make it less likely to rot.

upgpatch: amdvlk 2023.Q4.1-1

---

cargo-shuttle/riscv64.patch

Specify the version of ring during cargo update

upgpatch: cargo-shuttle 0.30.1-1

---

code/riscv64.patch

- Fix native node module rebuild hack.
- Add a comment about updating the hack.

upgpatch: code

---

upx/riscv64.patch

Apply upstream commit to fix cast-align error: https://github.com/upx/upx/commit/38a676f6f78e82ca0c2f08ef16446bc3e66cd453
Upstream: https://github.com/upx/upx/issues/730

addpatch: upx 4.2.0-1

---

yazi/riscv64.patch

Build against infiWang/LuaJIT.

updpatch: yazi 0.1.5-1

---

python-clarabel/riscv64.patch

Remove Rust target in `cargo fetch`.

addpatch: python-clarabel

---

hashdeep/riscv64.patch

Update config.{guess,sub}. Upstreamed to https://github.com/jessek/hashdeep/issues/414.

addpatch: hashdeep

---

neovide/riscv64.patch

updpatch: neovide

---

coin-or-cbc/riscv64.patch

upgpatch: coin-or-cbc

---

jenkins/riscv64.patch
jenkins/use-system-yarn.patch

updpatch: jenkins

---

libgsf/riscv64.patch

updpatch: libgsf

---

smartdns/riscv64.patch

https://github.com/pymumu/smartdns/pull/1538

addpkg: smartdns

---

libfreexl/riscv64.patch

(Due to some irreversible mistakes caused by my last commit, I have re-submitted this.)
This is the link, and I have already explained the reason to them:https://www.gaia-gis.it/fossil/freexl/tktview/b008c4acc2dfe73aef096bf2e9e1cbff337a6c94

addpkg: libfreexl

---

paperkey/riscv64.patch

Update config.{guess,sub}. Upstreamed to https://github.com/dmshaw/paperkey/issues/12

addpatch:paperkey

---

skktools/riscv64.patch

I am in contact with the upstream, and I will comment on the results here

addpkg:skktools

---

qemu-user-blacklist.txt

Test segfault only in qemu-user.

qemu-user-blacklist.txt: add cherrytree

---

paccat/riscv64.patch

addpatch: paccat

---

cargo-show-asm/riscv64.patch

addpatch: cargo-show-asm 0.2.21-2

---

vaultwarden/riscv64.patch

Specify version of ring during cargo update

updpatch: vaultwarden 1.30.0-1

---

jupymake/riscv64.patch

updpatch: jupymake 0.9-19

---

keycloak/riscv64.patch

updpatch: keycloak

---

github-cli/githubcli-prompt-sleep.patch
github-cli/riscv64.patch

- Fix check fail, upstreamed to github-cli: https://github.com/cli/cli/issues/8300

addpatch: github-cli

---

selene/riscv64.patch

- Specify the updated version of ring as 0.16.20, since there are multiple ring versions in the lock file.

updpatch: selene

---

pngquant/riscv64.patch

updpatch: pngquant

---

cargo-binstall/riscv64.patch

Specify the updated version of ring

updpatch: cargo-binstall 1.4.5-1

---

python-pbr/riscv64.patch

updpatch: python-pbr

---

nomad-driver-lxc/riscv64.patch

Update nomad to v1.3.0 (https://github.com/hashicorp/nomad-driver-lxc/issues/33).

addpatch: nomad-driver-lxc 0.3.0-3

---

nushell/riscv64.patch

updpatch: nushell 0.87.0-1

---

cantor/riscv64.patch

updpatch: cantor 23.08.3-2

---

rspamd/riscv64.patch

addpatch: rspamd 3.7.3-1

---

qemu-user-blacklist.txt
sshx/riscv64.patch

- use patched ring.
- check fail in qemu-user.

addpatch: sshx

---

ogre-next/riscv64.patch

updpatch: ogre-next 2.3.3-1

---

skia-sharp/riscv64.patch

addpatch: skia-sharp

---

rspamd/riscv64.patch

Add a patch to fix https://github.com/rspamd/rspamd/issues/4701

updpatch: rspamd 3.7.4-1

---

cargo-crev/riscv64.patch

updpatch: cargo-crev 0.25.5-1

---

log4cpp/riscv64.patch

Upstream report available at https://sourceforge.net/p/log4cpp/bugs/157/

addpatch: log4cpp

---

pcre2/riscv64.patch
pcre2/sljit-sv48-sv57.patch

Upstream sljit PR has settled and fixed an additional crash. Let's apply the new patch.

updpatch: pcre2

---

just/riscv64.patch

updpatch: just

---

cargo-depgraph/riscv64.patch

updpatch: cargo-depgraph 1.6.0-1

---

python-awscrt/fix-timeout.patch
python-awscrt/riscv64.patch

Fix check fail, upstreamed to aws-crt-python: https://github.com/awslabs/aws-crt-python/issues/535

addpatch: python-awscrt

---

gitlab/riscv64.patch

upgpatch: gitlab 16.6.1-1

---

ocaml-pp/riscv64.patch

Add missing dependency: ocaml
Upstream: https://gitlab.archlinux.org/archlinux/packaging/packages/ocaml-pp/-/merge_requests/1

addpatch: ocaml-pp 1.1.2-6

---

wvstreams/riscv64.patch

updpatch: wvstreams 4.6.1-21

---

cargo-clone/riscv64.patch

addpatch: cargo-clone

---

telegram-desktop/riscv64.patch
telegram-desktop/tdesktop-scudo-rv-fix.patch

Fix scudo crashes on riscv64 sv39. Thanks @Icenowy for the patch.

addpatch: telegram-desktop

---

boost/riscv64.patch

- Fix patch(https://github.com/bfgroup/b2/pull/341) hash, (this patch is still required)

updpatch: boost

---

amdvlk/riscv64.patch

updpatch: amdvlk

---

openssl/riscv64.patch

updpatch: openssl

---

cargo-dist/riscv64.patch

updpatch: cargo-dist 0.6.0-1

---

arti/riscv64.patch

updpatch: arti 1.1.11-1

---

qt6-webengine/riscv64.patch

upgpatch: qt6-webengine 6.6.1-2

---

xtrabackup/riscv64.patch

- Fix rotten and make patch name more unique

updpatch: xtrabackup

---

dra/riscv64.patch

- Bump sct from 0.7.0 to 0.7.1. The pr has created to: https://github.com/devmatteini/dra/pull/172
- Fix rotten.

updpatch: dra

---

cargo-semver-checks/riscv64.patch

updpatch: cargo-semver-checks 0.26.0-3

---

pueue/riscv64.patch

Bump `ring` from 0.16 to 0.17. The pr has created to: https://github.com/Nukesor/pueue/pull/484

updpatch: pueue

---

helm/add-riscv64-build.patch
helm/riscv64.patch

updpatch: helm 3.13.3-1

---

ghidra/riscv64.patch

updpatch: ghidra

---

surge-xt/riscv64.patch

- Fix rotten and make it less likely to be
- Remove unneeded patches

updpatch: surge-xt

---

cctag/riscv64.patch

addpatch: cctag

---

gfold/riscv64.patch

updpatch: gfold

---

telegram-desktop/riscv64.patch

updpatch: telegram-desktop 4.13.0-1

---

d-containers/riscv64.patch

updpatch: d-containers 0.8.0-9

---

postgresql/riscv64.patch

Fix rotten.
LLVM JIT still not working.

upgpatch: postgresql 16.1-4

---

linux-sophgo/PKGBUILD

Update to latest commit for proper pcie (ethernet adapter was broken).

updpkg: linux-sophgo 6.1.61-3

---

gitoxide/riscv64.patch

updpatch: gitoxide 0.33.0-1

---

electron24/riscv64.patch

updpatch: electron24 24.8.8-2

---

rust/pin-cc-to-1-0-77.patch
rust/riscv64.patch

updpatch: rust 1.75.0-1

---

python-clevercsv/riscv64.patch

addpatch: python-clevercsv 0.8.0-2

---

atuin/riscv64.patch

- Fix rotten
- ring issue upstreamed (https://github.com/rrrodzilla/rusty_paseto/issues/30)

updpatch: atuin 17.2.1-1

---

vaultwarden/riscv64.patch

updpatch: vaultwarden 1.30.1-1

---

neovide/riscv64.patch

updpatch: neovide 0.12.1-1

---

elf2nucleus/riscv64.patch

addpatch: elf2nucleus

---

telegram-desktop/riscv64.patch

updpatch: telegram-desktop 4.14.3-1

---

ruby-x25519/riscv64.patch

updpatch: ruby-x25519 1.0.10-2

---

arch-audit/riscv64.patch

updpatch: arch-audit 0.1.20-2

---

telegram-desktop/riscv64.patch

updpatch: telegram-desktop 4.14.4

---

opencv/riscv64.patch

updpatch: opencv 4.9.0-1

---

go/riscv64.patch

updpatch: go 1.21.6-1

---

materialx/riscv64.patch

https://github.com/mitsuba-renderer/nanogui/pull/156

addpatch: materialx 1.38.8-8

---

hm/riscv64.patch

updpatch: hm 18.0-1

---

starship/riscv64.patch

Fix flaky test (Upstream: https://github.com/starship/starship/pull/5685).

updpatch: starship 1.17.1-1

---

nodejs/riscv64.patch

Same as https://github.com/felixonmars/archriscv-packages/pull/3443

addpatch: nodejs

---

sccache/riscv64.patch

upgpatch: sccache 0.7.6-1

---

mesa/riscv64.patch

updpatch: mesa 1:23.3.4-1

---

deno/riscv-v8.patch
deno/riscv64.patch

- Apply V8 patch, same as Chromium
- Update value-trait and simd-json so they can use fallback, non-SIMD method

updpatch: deno 1.40.1-1

---

libreoffice-still/add-rv64-support.patch
libreoffice-still/firebird-riscv64-support.patch.1
libreoffice-still/riscv64.patch

Refresh riscv64 support patches.

updpatch: libreoffice-still 7.5.9-2

---

wezterm/riscv64.patch

https://github.com/wez/wezterm/commit/a51c6a2638dac7d2cbde13afe51c11adf96895c9

updpatch: wezterm 20240128.202157.1e552d76-1

---

obs-studio/riscv64.patch

updpatch: obs-studio 30.0.2-3

---

sensors-applet/riscv64.patch

Make it less likely to be rotten.

upgpatch: sensors-applet 1:3.0.0-1

---

mame/riscv64.patch

updpatch: mame 0.262-1

---

firefox/riscv64.patch

updpatch: firefox 122.0-1

---

openblas/riscv64.patch

updpatch: openblas 0.3.26-3

---

ruff/riscv64.patch

- remove unneeded ring patch
- fix rust target triple in `package_ruff`, upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/ruff/-/merge_requests/1

updpatch: ruff 0.2.0-1

---

linuxsampler/riscv64.patch

updpatch: linuxsampler 2.3.0-2

---

ghidra/add-riscv64-build.patch
ghidra/riscv64.patch

Apply usage of compiled protobuf binary in new modules.

updpatch: ghidra 11.0.1-1

---

linux-firmware/riscv64.patch

updpatch: linux-firmware 20240115.9b6d0b08-2

---

qt6-doc/add-riscv64-support.patch
qt6-doc/riscv64.patch

Add some riscv64 conditions to Qt WebEngine's Chromium source to make build pass.

addpatch: qt6-doc

---

go/riscv64.patch

Previous fixes upstreamed and released.

updpatch: go 2:1.22.0-1

---

vaultwarden-web/remove-electron.patch
vaultwarden-web/riscv64.patch

Remove Electron from package.json, as it is not needed in this build.

addpatch: vaultwarden-web 2024.1.2-3

---

glad/riscv64.patch

Remove unavailable dependencies.

addpatch: glad 2.0.4-1

---

restic/riscv64.patch

Tweak Go package guidelines
Upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/restic/-/merge_requests/1

addpatch: restic 0.16.4-1

---

syncthing/riscv64.patch

Tweak Go package guidelines
Upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/syncthing/-/merge_requests/1

addpatch: syncthing 1.27.3-1

---

devtools-riscv64/PKGBUILD
devtools-riscv64/makepkg-riscv64.patch

Build after devtools 1:1.1.0-3 upgrade.

upgpatch: devtools-riscv64 1:1.1.0+patch1-1

---

pacman/riscv64.patch

upgpatch: pacman 6.0.2-9

---

rust/riscv64.patch

upgpatch: rust 1.76.0-1

---

rocminfo/riscv64.patch

updpatch: rocminfo 6.0.0-1

---

nushell/riscv64.patch

updpatch: nushell 0.90.1-1

---

yazi/riscv64.patch

Upgrade luajit-src-rs to match upstream.

updpatch: yazi 0.2.3-3

---

staticcheck/riscv64.patch

updpatch: staticcheck 2023.1.7-1

---

cern-vdt/riscv64.patch

updpatch: cern-vdt

---

nodejs-lts-iron/riscv64.patch

updpatch: nodejs-lts-iron

---

ffmpeg/riscv64.patch

Add a patch to fix build with latest vulkan-headers.
Credits: https://aur.archlinux.org/packages/ffmpeg-full#comment-960118

updpatch: ffmpeg 2:6.1.1-6

---

atuin/riscv64.patch

Upstreamed merged test-timeout.patch.

updpatch: atuin 18.1.0-1

---

python-nodeenv/riscv64.patch

updpatch: python-nodeenv 1.8.0-2

---

libreoffice-fresh/riscv64.patch

updpatch: libreoffice-fresh 24.2.1-3

---

qt6-webengine/riscv64.patch

updpatch: qt6-webengine

---

pacman/riscv64.patch

updpatch: pacman 6.1.0-3

---

pacman/riscv64.patch

drop unsupported flags. Fix for #3613

upgpatch: pacman 6.1.0-3

---

electron29/Debian-fix-rust-linking.patch
electron29/riscv64.patch

addpatch: electron29 29.1.4-1

---

starship/riscv64.patch

* Fix rotten.
* Need to be build with `pacman 6.1.0` to use vcs checksum.

upgpatch: starship 1.17.1-2

---

bin86/riscv64.patch

updpatch: bin86 0.16.21-5

---

fwupd/riscv64.patch

updpatch: fwupd 1.9.15-1

---

binaryen/riscv64.patch

Disable -Wuninitialized on riscv64. Upstream: https://github.com/WebAssembly/binaryen/pull/6410

addpatch: binaryen 117-1

---

pixi/riscv64.patch

https://github.com/prefix-dev/pixi/pull/1045

addpatch: pixi 0.17.1-2

---

obs-studio/riscv64.patch

updpatch: obs-studio 30.1.0-1

---

libmpd/riscv64.patch

Update config.{sub,guess}. Sending the update request to Qball (email in source tarball).

addpatch: libmpd 11.8.17-6

---

libisoburn/riscv64.patch

Update outdated config.{sub,guess}. Since there are no public issue platform (as their Gitea is private), an email requesting updating the files is sent to one of the maintainers, Thomas Schmitt.

addpatch: libisoburn 1.5.6-1

---

ffmpeg/riscv64.patch

Cherry pick done in Arch upstream.

updpatch: ffmpeg 2:6.1.1-7

---

mesa/0002-add-llvm-orcjit.patch
mesa/0004-llvmpipe-linkage.patch
mesa/riscv64.patch

updpatch: mesa 1:24.0.3-2

---

typescript/remove-dprint.patch
typescript/riscv64.patch

updpatch: typescript 5.4.3-1

---

gitlab/riscv64.patch

updpatch: gitlab 16.10.0-1

---

chromium-bsu/riscv64.patch

https://sourceforge.net/p/chromium-bsu/mailman/message/58752419/

addpatch: chromium-bsu 0.9.16.1-2

---

starship/riscv64.patch

Added workaround for buggy RVV detection in zlib-ng, see https://github.com/zlib-ng/zlib-ng/issues/1705

addpatch: starship

---

lucky-commit/riscv64.patch

updpatch: lucky-commit 2.2.3-1

---

opencv/riscv64.patch

Fix rotten patch and make it less likely to rot

updpatch: opencv 4.9.0-3

---

kexec-tools/riscv64.patch

updpatch: kexec-tools 2.0.28-1

---

mame/riscv64.patch

updpatch: mame 0.264-1

---

libreoffice-fresh/riscv64.patch

updpatch: libreoffice-fresh 24.2.2-1

---

plumber/riscv64.patch

updpatch: plumber 2.6.1-1

---

go/riscv64.patch

upgpatch: go 2:1.22.2-1

---

libretro-dolphin/riscv64.patch

Remove -Wl,-plugin-opt=-target-abi=lp64d

updpatch: libretro-dolphin

---

gn/riscv64.patch

updpatch: gn

---

opensubdiv/riscv64.patch

updpatch: opensubdiv 3.6.0-1

---

helm/riscv64.patch

updpatch: helm 3.14.3-1

---

ldc/riscv64.patch

Update LLVM version to 17, adding `llvm16-libs` to makedepends to bootstrap

updpatch: ldc 3:1.37.0-1

---

linuxsampler/riscv64.patch

updpatch: linuxsampler 2.3.1-1

---

materialx/riscv64.patch

updpatch: materialx 1.38.9-2

---

primecount/riscv64.patch

updpatch: primecount 7.13-1

---

webkit2gtk-4.1/fix-ftbfs-riscv64.patch
webkit2gtk-4.1/riscv64.patch
webkit2gtk/fix-ftbfs-riscv64.patch
webkit2gtk/riscv64.patch
webkitgtk-6.0/fix-ftbfs-riscv64.patch
webkitgtk-6.0/riscv64.patch
wpewebkit/fix-ftbfs-riscv64.patch
wpewebkit/riscv64.patch

See https://bugs.webkit.org/show_bug.cgi?id=271371

updpatch: webkit2gtk{,-4.1}, webkitgtk-6.0, wpewebkit 2.44.1-1

---

materialx/riscv64.patch

updpatch: materialx 1.38.10-2

---

cantor/riscv64.patch

updpatch: cantor 24.02.2-2

---

stylelint/riscv64.patch

updpatch: stylelint 16.4.0-1

---

libcaca/riscv64.patch

Fix rotten and make it less likely to be

updpatch: libcaca

---

devtools-riscv64/.SRCINFO
devtools-riscv64/PKGBUILD
devtools-riscv64/makepkg-riscv64.patch

upgpkg: devtools-riscv64 1:1.2.0+patch1-1

---

openmpi/riscv64.patch

updpatch: openmpi 5.0.3-1

---

srslte/riscv64.patch

This package needs to be built with `--nocheck` for now.

addpatch: srslte

---

rust/riscv-target-abi-fix.patch
rust/riscv64.patch

updpatch: rust 1:1.78.0-1

---

nodejs-lts-hydrogen/riscv64.patch

updpatch: nodejs-lts-hydrogen 18.20.2-3

---

cloudflared/riscv64.patch

Upstream applied previous fix.

updpatch: cloudflared 2024.4.0-1

---

cups/riscv64.patch

Add missing header.
[Upstream MR](https://gitlab.archlinux.org/archlinux/packaging/packages/cups/-/merge_requests/1)

upgpatch: cups 1:2.4.8-1

---

protobuf/riscv64.patch

Upstreamed as
https://gitlab.archlinux.org/archlinux/packaging/packages/protobuf/-/issues/3

addpatch: protobuf 25.3-4

---

metasploit/riscv64.patch

fixpatch: metasploit 6.4.7-1

---

symengine/riscv64.patch

updpatch: symengine 0.12.0-1

---

java21-openjdk/bootstrap-using-jdk22.patch
java21-openjdk/riscv64.patch

Bootstrap Java 21 using Java 22.

addpatch: java21-openjdk 21.0.3.u9-1

---

fwupd/riscv64.patch

updpatch: fwupd 1.9.20-1

---

rapidjson/riscv64.patch

updpatch: rapidjson 1.1.0-6

---

python-eventlet/riscv64.patch

updpatch: python-eventlet

---

apache-orc/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/apache-orc/-/merge_requests/2

addpatch: apache-orc

---

rocm-llvm/riscv64.patch

updpatch: rocm-llvm 6.0.2-1

---

python-uhi/riscv64.patch

Disable root until we have it.

addpatch: python-uhi 0.4.0-3

---

python-aiohttp/riscv64.patch

updpatch: python-aiohttp 3.9.5-1

---

adios2/riscv64.patch

Apply workaround from
https://github.com/GTkorvo/dill/issues/50#issuecomment-2155263724

addpatch: adios2 2.10.1-1

---

root/riscv64.patch

addpatch: root

---

sh4d0wup/riscv64.patch

updpatch: sh4d0wup 0.9.3-1

---

cinnamon-session/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/cinnamon-session/-/merge_requests/1

addpatch: cinnamon-session 6.2.0-1

---

cinnamon-screensaver/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/cinnamon-screensaver/-/merge_requests/1

addpatch: cinnamon-screensaver 6.2.0-1

---

chromium/riscv-ffmpeg.patch
chromium/riscv-sandbox.patch
chromium/riscv-v8-fix-perf-regression.patch

I forgot to upload some modified patches.

fixpatch: chromium

---

systemd/riscv64.patch

Backport https://github.com/systemd/systemd/pull/33404

upgpatch: systemd 256.1-1

---

ffmpeg/riscv64.patch

updpatch: ffmpeg 7.0.1-1

---

nodejs/riscv64.patch

Perf regression fix landed in 22.4.0: https://github.com/nodejs/node/releases/tag/v22.4.0

updpatch: nodejs

---

js80p/riscv64.patch

add missing fix for package phase

fixpatch: js80p

---

element.io/riscv64.patch

updpatch: element.io

---

lurk/riscv64.patch

Upstreamed to https://github.com/JakWai01/lurk/pull/44 following nix-rust release

updpatch: lurk 0.3.5-1

---

helm/add-riscv64-build.patch
helm/riscv64.patch

updpatch: helm 3.15.3-1

---

libb2/riscv64.patch

updpatch: libb2 0.98.1-3

---

xsettings-client/riscv64.patch

Request for updating config.{guess,sub} sent to yocto@yoctoproject.org.

addpatch: xsettings-client 0.10-10

---

xvidcore/riscv64.patch

Request for updating config.{guess,sub} sent to xvid-devel@xvid.org.

addpatch: xvidcore 1.3.7-3

---

ltrace/fix-includes.patch
ltrace/riscv64.patch
ltrace/support-c-ebreak.patch

- Backport https://gitlab.com/cespedes/ltrace/-/merge_requests/21
- Fix missing includes and function arguments

updpatch: ltrace 0.7.3-5

---

dart/dart-riscv-no-cross.patch
dart/riscv64.patch

Bootstrap using #3915
Tested by building dart-sass

addpatch: dart 3.4.4-1

---

pioneer/riscv64.patch

Backport https://github.com/pioneerspacesim/pioneer/commit/8691843e152e1e3b7dc3fe7612a1b2ae777e5f30

addpatch: pioneer 20240314-5

---

opam/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/opam/-/merge_requests/2

addpatch: opam 2.2.0_2-2

---

vinagre/riscv64.patch

Upstreamed to https://gitlab.archlinux.org/archlinux/packaging/packages/vinagre/-/merge_requests/1.

addpatch: vinagre 1:3.22.0+r160+gc86e114-2

---

mplayer/riscv64.patch

updpatch: mplayer 38542-2

---

ghidra/riscv64.patch

updpatch: ghidra 11.0.3-1

---

deltachat-rpc-server/riscv64.patch

- Add fix for https://github.com/time-rs/time/issues/696
- Patch ring 0.16.20

addpatch: deltachat-rpc-server

---

mesa/riscv64.patch

Ensure patch apply order so it won't fail.

fixpatch: mesa 1:24.1.5-1

---

dfmt/riscv64.patch

Update the patch to fit the changes of upstream.

updpatch: dfmt 0.15.1-2

---

firefox/riscv64.patch

updpatch: firefox 128.0.3-1

---

firefox-developer-edition/riscv64.patch

updpatch: firefox-developer-edition 129.0b9-1

---

gcc/riscv64.patch

fixpatch: gcc

---

cunit/riscv64.patch

upstreamed: https://sourceforge.net/p/ya-cunit/bugs/2/

addpatch: cunit 2.1.3-4

---

pidgin-hotkeys/riscv64.patch

This issue was reported to https://sourceforge.net/p/pidgin-hotkeys/bugs/8/ .

addpatch: pidgin-hotkeys 0.2.4-6

---

xmlstarlet/riscv64.patch

The issue was reported via SourceForge dm which link was shown on their website.

addpatch: xmlstarlet 1.6.1-4

---

wol/riscv64.patch

The issue was reported to https://sourceforge.net/p/wake-on-lan/discussion/727278/thread/2c58c77d78/ .

addpatch: wol 0.7.1-10

---

xcb-util-xrm/riscv64.patch

The issue was reported to upstream in https://github.com/Airblader/xcb-util-xrm/issues/89 .

addpatch: xcb-util-xrm 1.3-3

---

protobuf/riscv64.patch

updpatch: protobuf 27.3-1

---

xcftools/riscv64.patch

Updated patch, and issue was reported via email.

updpatch: xcftools 1.0.7-10

---

vsqlite++/riscv64.patch

This issue was reported to https://github.com/vinzenz/vsqlite--/issues/37 .

addpatch: vsqlite++ 0.3.13-8

---

judy/riscv64.patch

The outdated configure file issue was reported to https://sourceforge.net/p/judy/bugs/31/ .

addpatch: judy 1.0.5-8

---

gpx-viewer/riscv64.patch

Upstreamed: https://bugs.launchpad.net/gpx-viewer/+bug/2077675

addpatch: gpx-viewer 0.4.0-5

---

av1an/riscv64.patch

Update to fit patch to upstream.

updpatch: av1an 0.4.3-1

---

helm/riscv64.patch

Update to fit the newest changes.

updpatch: helm 3.15.4-1

---

netdata/riscv64.patch

TODO: I have tried to fix the LIBSUBDIR part upstream, but it conflicts with the Arch patch... Both these two changes should be upstreamed properly.

updpatch: netdata 1.47.0-1

---

libotr/riscv64.patch

updpatch: libotr 4.1.1-5

---

mesa/riscv64.patch

updpatch: mesa 1:24.2.1-1

---

notification-daemon/riscv64.patch

The outdated configure file issue was not reported because it was abandoned.

addpatch: notification-daemon 3.20.0-6

---

nfacct/riscv64.patch

The outdated configure file issue was reported via email.

addpatch: nfacct 1.0.2-4

---

openmpi/riscv64.patch

Re-enable openucx since we have it.

updpatch: openmpi 5.0.5-1

---

firefox/riscv64.patch

updpatch: firefox 130.0-1

---

webkit2gtk-4.1/riscv64.patch
webkit2gtk/riscv64.patch
webkitgtk-6.0/riscv64.patch
wpewebkit/riscv64.patch

updpatch: webkit2gtk{,-4.1}, webkitgtk-6.0, wpewebkit 2.44.3-3

---

firefox-developer-edition/riscv64.patch

updpatch: firefox-developer-edition 131.0b2-1

---

curlftpfs/riscv64.patch

Upstreamed: https://sourceforge.net/p/curlftpfs/support-requests/8/

addpatch: curlftpfs 0.9.2-9

---

anthy/riscv64.patch

Upstream: https://osdn.net/projects/anthy/ticket/129476

addpatch: anthy 9100h-7

---

harper/riscv64.patch

Link: https://github.com/elijah-potter/harper/pull/157

addpatch: harper 0.10.0-1

---

jenkins/riscv64.patch

updpatch: jenkins 2.474-1

---

imagemagick/riscv64.patch

Disable libultrahdr until we have it.
(wishing well: https://github.com/plctlab/PLCT-Weekly/issues/829#issuecomment-2350097261)

addpatch: imagemagick 7.1.1.38-2

---

docker-scan/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/docker-scan/-/merge_requests/1

addpatch: docker-scan 0.26.0-2

---

python-blosc2/riscv64.patch

Remove pytorch until we have it.

addpatch: python-blosc2 2.7.1-2

---

qtile/riscv64.patch

See https://gitlab.archlinux.org/archlinux/packaging/packages/qtile/-/merge_requests/1

addpatch: qtile 0.28.1-1

---

libultrahdr/riscv64.patch

https://github.com/google/libultrahdr/pull/273
Using generic implementation currently.

addpatch: libultrahdr 1.1.1-2

---

redland/riscv64.patch

addpatch: redland 1.0.17-9

---

libva-vdpau-driver/riscv64.patch

Upstream: https://github.com/arekinath/libva-vdpau-driver/issues/2

addpatch: libva-vdpau-driver 0.7.4-7

---

zaz/riscv64.patch

Upstream: https://sourceforge.net/p/zaz/discussion/996643/thread/aed4e51e5b/

addpatch: zaz 1.0.1-3

---

xplc/riscv64.patch

Upstream: https://github.com/xplc/xplc/issues/6

addpatch: xplc 0.3.13-11

---

gstreamer/riscv64.patch

Needs nocheck for now because of circular rebuilds. Will revisit after those settled.

updpatch: gstreamer 1.24.8-1

---

yubikey-personalization/riscv64.patch

Upstream: https://github.com/Yubico/yubikey-personalization/issues/189

updpatch: yubikey-personalization 1.20.0-4

---

schroedinger/riscv64.patch

addpatch: schroedinger 1.0.11-7

---

electron28/riscv64.patch
electron29/riscv64.patch
electron30/riscv64.patch
electron31/riscv64.patch
electron32/riscv64.patch

fixpatch: electron{28,29,30,31,32}

---

magma/riscv64.patch

addpatch: magma 2.8.0-2

---

id3lib/riscv64.patch

Upstream: https://sourceforge.net/p/id3lib/bugs/214/

addpatch: id3lib 3.8.3-19

---

gts/riscv64.patch

Upstream: https://sourceforge.net/p/gts/bugs/74/

addpatch: gts 0.7.6.121130-4

---

gtkspellmm/riscv64.patch

Upstream: https://sourceforge.net/p/gtkspell/bugs/25/

addpatch: gtkspellmm 3.0.5-5

---

mhash/riscv64.patch

Upstream: https://sourceforge.net/p/mhash/bugs/44/

addpatch: mhash 0.9.9.9-6

---

libdbi/riscv64.patch

Upstream: https://sourceforge.net/p/libdbi/bugs/18/

addpatch: libdbi 0.9.0-6

---

nload/riscv64.patch

Upstream: https://github.com/rolandriegel/nload/issues/20

addpatch: nload 0.7.4-8

---

netcf/riscv64.patch

Couldn't report because of their misconfigured code hosting web server.

addpatch: netcf 0.2.8-9

---

bustle/longer-timeout.patch
bustle/riscv64.patch

Upstream: https://gitlab.gnome.org/World/bustle/-/issues/37

addpatch: bustle 0.10.0-1

---

pika-backup/longer-timeout.patch
pika-backup/riscv64.patch

Upstream: https://gitlab.gnome.org/World/pika-backup/-/issues/565

addpatch: pika-backup 0.7.4-1

---

python-wxpython/riscv64.patch

Apply fix for
https://gitlab.archlinux.org/archlinux/packaging/packages/python-wxpython/-/issues/1

addpatch: python-wxpython 1:4.2.1-2

---

dpdk/riscv64.patch

Upstream: https://bugs.dpdk.org/show_bug.cgi?id=1558

addpatch: dpdk 24.07-1

---

gtksourceview5/riscv64.patch

Upstream: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/379

addpatch: gtksourceview5 5.14.1-1

---

macchina/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/macchina/-/merge_requests/1

addpatch: macchina 6.2.1-1

---

cyme/riscv64.patch

Upstreamed: https://github.com/tuna-f1sh/cyme/pull/37

addpatch: cyme 1.8.4

---

decoder/riscv64.patch

Upstream: https://gitlab.gnome.org/World/decoder/-/issues/89

addpatch: decoder 0.6.0-2

---

gnome-calculator/riscv64.patch

Upstream: https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/434

addpatch: gnome-calculator 47.0-1

---

cargo-binstall/riscv64.patch

Upstreamed: https://github.com/cargo-bins/cargo-binstall/pull/1930

addpatch: cargo-binstall 1.10.7

---

libfprint/riscv64.patch

Upstream: https://gitlab.freedesktop.org/libfprint/fprintd/-/issues/174

addpatch: libfprint 1.94.8-1

---

citations/riscv64.patch

Upstream: https://gitlab.gnome.org/World/citations/-/issues/54

addpatch: citations 0.7.0-2

---

authenticator/riscv64.patch

Upstream: https://gitlab.gnome.org/World/Authenticator/-/issues/434

addpatch: authenticator 4.5.0-3

---

proxmark3/riscv64.patch

Upstreamed:
- https://github.com/RfidResearchGroup/proxmark3/pull/2577
- https://gitlab.archlinux.org/archlinux/packaging/packages/proxmark3/-/merge_requests/1

addpatch: proxmark3 4.18589

---

csvlens/riscv64.patch

Link: https://github.com/YS-L/csvlens/commit/002edebeda69b0b81b4fd4060e25e80c5a87f4da
Link: https://github.com/YS-L/csvlens/issues/101

addpatch: csvlens 0.10.1

---

geary/riscv64.patch

@qyl27 upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/geary/-/merge_requests/1

addpatch: geary 46.0

---

deepin-screen-recorder/deepin-screen-recorder-unqualified-id.patch
deepin-screen-recorder/riscv64.patch

upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/deepin-screen-recorder/-/merge_requests/2

addpatch: deepin-screen-recorder 5.12.15

---

libunicode/riscv64.patch

Link: https://github.com/contour-terminal/libunicode/issues/109

addpatch: libunicode 0.6.0

---

apparmor/riscv64.patch

Upstreamed: https://gitlab.com/apparmor/apparmor/-/issues/463

addpatch: apparmor 4.0.3

---

spike/riscv64.patch

upgpatch: spike 1.1.0-5

---

calf/riscv64.patch

updpatch: calf

---

gstreamer/riscv64.patch

updpatch: gstreamer 1.24.9-3

---

vault/riscv64.patch

Replace bolt with bbolt. This project also contains both Node.js and Go parts, so building on Unmatched is needed.

addpatch: vault 1.18.1-1

---

legba/riscv64.patch

Upgrade pavao to include https://github.com/veeso/pavao/commit/9d2bd6a828794acb20a1045d17971d50788dcbe9.

addpatch: legba 0.9.0-1

---

vaultwarden/riscv64.patch

Generate Rust bindgen for libmysqlclient at build time.

addpatch: vaultwarden 1.32.5-1

---

java8-openjdk/jdk8-riscv.patch
java8-openjdk/riscv64.patch

updpatch: java8-openjdk 8.432.u05-1

---

mate-sensors-applet/riscv64.patch

updpatch: mate-sensors-applet 1.28.0-3

---

vaultwarden-web/remove-electron.patch
vaultwarden-web/riscv64.patch

python is now needed cause of leak of prebuild of node-gyp

updpatch: vaultwarden-web 2024.6.2c-1

---

mermaid-cli/riscv64.patch

Upstreamed:
https://gitlab.archlinux.org/archlinux/packaging/packages/mermaid-cli/-/merge_requests/1

addpatch: mermaid-cli 11.4.0-2

---

libreoffice-fresh/riscv64-support.patch
libreoffice-fresh/riscv64.patch

Refresh patch; ~~disable poppler patch since 24.11 changed back the behaviour~~.

updpatch: libreoffice-fresh 24.8.3-1

---

chromium/riscv64.patch

Roll chromium to 131.0.6778.108 (trivial)

updpatch: chromium 131.0.6778.108-1

---

mesa/riscv64.patch

updpatch: mesa 1:24.3.1-3

---

x86_64-linux-gnu-gcc-bootstrap/PKGBUILD

A bare gcc compiler to compile target glibc stubs

addpkg: x86_64-linux-gnu-gcc-bootstrap 14.2.0-1

---

x86_64-linux-gnu-glibc-headers/PKGBUILD

Target glibc headers and stubs

addpkg: x86_64-linux-gnu-glibc-headers 2.40-1

---

dioxus-cli/riscv64.patch

Extra make depends are required for aws-lc

addpkg: disxus-cli 0.6.0-1

---

x86_64-linux-gnu-gcc/PKGBUILD

Full cross-compiler for x86_64

updpkg: x86_64-linux-gnu-gcc 14.2.0-2

---

netdata/riscv64.patch

updpatch: netdata 2.0.3-1

---

resources/riscv64.patch

Upstreamed: https://github.com/nokyan/resources/issues/422

addpkg: resources 1.7.1-1

---

rocm-cmake/riscv64.patch

Fix check by removing -fstack-clash-protection.

addpatch: rocm-cmake 6.2.4-1

---

premake/riscv64.patch

fixpatch: premake 5.0.0-beta3-2

---

qemu-user-blacklist.txt

test timeout on qemu-user but fine on real hardware

qemu-user-blacklist: add libmodulemd

---

seaweedfs/riscv64.patch

addpatch: seaweedfs 3.80-1

---

python-pygit2/riscv64.patch

Fix iter, ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087432

addpatch: python-pygit2 1.16.0-3

---

python-tqdm/riscv64.patch

Remove keras from checkdep until we have it.

updpatch: python-tqdm 4.67.1-2

---

ollama/cpu-non-avx.patch
ollama/riscv64.patch

Fix CPU runner without any optimization like AVX. Upstreamed to https://github.com/ollama/ollama/pull/8224.

fixpatch: ollama 0.5.4-1

---

gobject-introspection/riscv64.patch

_glibver has to follow glib2 version in repo.

addpatch: gobject-introspection 1.82.0-2

---

protobuf/riscv64.patch

updpatch: protobuf 29.2-1

---

stalwart-mail-old-upgrade/riscv64.patch

Same as e52829825958e02c9b8713f61eec2f13a7e9abcb

addpatch: stalwart-mail-old-upgrade 0.8.5-1

---

chromium/riscv64.patch

Roll chromium to 131.0.6778.204 (trivial)

updpatch: chromium 131.0.6778.204-1

---

python-poetry-core/riscv64.patch

Reported at https://gitlab.archlinux.org/archlinux/packaging/packages/python-poetry-core/-/issues/2

addpatch: python-poetry-core 1.9.1-1

---

blacklist.txt

blacklist: remove Intel GPU packages

---

blacklist.txt

https://github.com/felixonmars/archriscv-packages/tree/master/dart

blacklist: remove dart

---

ncspot/riscv64.patch

addpatch: ncspot 1.2.1-1

---

musl/riscv64.patch

updpatch: musl 1.2.5-2

---

python-executing/riscv64.patch

`nocheck` for now for bootstrapping.

updpatch: python-executing 2.1.0-2

---

libfabric/riscv64.patch

Upstream: https://github.com/ofiwg/libfabric/pull/10691

updpatch: libfabric 2.0.0-1

---

adios2/riscv64.patch

updpatch: adios2 2.10.2-6

---

libfbclient/riscv64.patch

Add riscv `#define`
https://github.com/FirebirdSQL/firebird/pull/8382

addpatch: libfbclient 5.0.1.1469-1

---

opensbi/PKGBUILD

Add missing makedep on python.

fixpkg: opensbi 1.6-1

---

vtk/riscv64.patch

updpatch: vtk 9.4.1-2

---

onnxruntime/riscv64.patch

updpatch: onnxruntime 1.19.2-3

---

refind/add_riscv_support.patch
refind/riscv64.patch

https://sourceforge.net/p/refind/discussion/general/thread/acd89b2d43/

updpatch: refind 0.14.2-1

---

.github/workflows/test.yml
uasm/riscv64.patch

addpatch: uasm

---

postgresql/riscv64.patch

Link: https://github.com/postgres/postgres/commit/8108674f0e5639baebcf03b54b7ccf9e9a8662a2

updpatch: postgresql 17.2-1

---

python-mitmproxy-rs/riscv64.patch

Fix aya build: https://github.com/aya-rs/aya/pull/1139

addpatch: python-mitmproxy-rs 0.11.4-1

---

qemu-user-blacklist.txt

the test `TestRandomURLMultiThreaded` timeout on qemu-user with around 5s, but 50ms on real riscv devices

qemu-user-balcklist: add aws-sdk-cpp

---

cataclysm-dda/riscv64.patch

updpatch: cataclysm-dda 0.H-3

---

mission-center/khronos-egl.patch
mission-center/riscv64.patch

Update libc, upstreamed to https://gitlab.com/mission-center-devs/mission-center/-/merge_requests/255.

addpatch: mission-center 0.6.2-3

---

electron32/riscv64.patch
electron33/riscv64.patch

Disable PGO as we don't have an easy way to download PGO profile from google.

updpatch: electron3{2,3}

---

electron31/riscv64.patch

updpatch: electron31 31.7.7-1

---

veracrypt/riscv64.patch

https://github.com/veracrypt/VeraCrypt/pull/1479

addpatch: veracrypt 1.26.18-1

---

qaseprite/riscv64.patch

https://github.com/aseprite/laf/pull/129

addpatch: qaseprite 1.0.1-2

---

presenterm/riscv64.patch

https://github.com/orhun/sixel-rs/pull/6

upgpatch: presenterm 0.10.0-2

---

vim-jedi/riscv64.patch
vim-jedi/test-signature.patch

fix test failed. upstreamed: [jedi-vim](https://github.com/davidhalter/jedi-vim/issues/1134)

addpatch: vim-jedi 0.11.2-3

---

maelstrom/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/maelstrom/-/merge_requests/1

addpatch: maelstrom 0.12.0-1

---

python-pytorch/riscv64.patch

Skip the patch checksum as GitHub changes the commit hash bits all the time...

fixpatch: python-pytorch 2.6.0-2

---

ot-cryptid/riscv64.patch

Upstreamed: https://github.com/robbert-vdh/nih-plug/pull/95

updpatch: ot-cryptid 1.0.2-1

---

ot-urchin/riscv64.patch

Upstreamed: https://github.com/robbert-vdh/nih-plug/pull/95

updpatch: ot-urchin 1.0.2-1

---

libvolk/riscv64.patch

addpatch: libvolk 2:3.2.0-1

---

pypy3/missing-riscv64-macro-defined.patch
pypy3/riscv64.patch

addpatch: pypy3

---

bazel/bazel-riscv.diff
bazel/riscv64.patch

updpatch: bazel 8.1.0-1

---

libnfs/fix-cast-align-for-riscv64.patch
libnfs/riscv64.patch

Upstreamed: https://github.com/sahlberg/libnfs/pull/522
This patch is different with upstream. It contains other two PRs
So leave in this repo.

addpatch: libnfs

---

ginkgo-hpc/riscv64.patch

Disable CUDA.
Build after #4538 bumped.

addpatch: ginkgo-hpc 1.9.0-1

---

python-cppyy-cling/add-riscv64-support.patch
python-cppyy-cling/riscv64.patch

Upstreamed to https://github.com/wlav/cppyy-backend/pull/35.

addpatch: python-cppyy-cling 6.32.8-1

---

python-proton-vpn-local-agent/riscv64.patch

Link: https://github.com/aws/aws-lc-rs/issues/476

updpatch: python-proton-vpn-local-agent 1.4.3

---

pnpm/riscv64.patch

Link: https://github.com/pnpm/pnpm/issues/9188

updpatch: pnpm 10.5.2

---

kubie/riscv64.patch

addpatch: kubie 0.25.0-1

---

consul/riscv64.patch

Upstrmeamed: https://gitlab.archlinux.org/archlinux/packaging/packages/consul/-/merge_requests/2

updpatch: consul 1.20.4

---

keycloak/riscv64.patch
keycloak/use-system-node.patch

Refresh use-system-node.patch.

updpatch: keycloak 26.1.2-1

---

pycharm-community-edition/riscv64.patch

Build natives from source
Link: https://github.com/Glavo/JetBrains-IDE-Multiarch/issues/4

updpatch: pycharm-community-edition 2024.3.3

---

intellij-idea-community-edition/riscv64.patch

Build natives from source
Link: https://github.com/Glavo/JetBrains-IDE-Multiarch/issues/4

updpatch: intellij-idea-community-edition 2024.3.3

---

ldc/riscv64.patch

Backport upstream libatomic fix.

updpatch: ldc 3:1.40.0-2

---

leancrypto/fix-rvv-tests.patch
leancrypto/kyber-rvv-fix.patch
leancrypto/riscv64.patch

See https://github.com/smuellerDD/leancrypto/pull/19 and https://github.com/smuellerDD/leancrypto/pull/20.

addpatch: leancrypto 1.2.0-2

---

rdkit/riscv64.patch

Disable popcnt which requires Zbb extension.

addpatch: rdkit 2024.09.6-1

---

pacman/riscv64.patch

updpatch: pacman 7.0.0.r6.gc685ae6-2

---

elfutils/riscv64.patch

Use our debuginfod URL (experimental).

addpatch: elfutils 0.192-4.1

---

protobuf/riscv64.patch

credit: https://github.com/felixonmars/archriscv-packages/pull/4607
Co-authored-by: Chaiwat Suttipongsakul <cwt@bashell.com>

updpatch: protobuf 30.1-1

---

kodi-addon-inputstream-adaptive/riscv64.patch

Upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/kodi-addon-inputstream-adaptive/-/merge_requests/1/diffs

addpatch: kodi-addon-inputstream-adaptive 21.5.9-1

---

termscp/riscv64.patch

Add cmake and clang makedepends for aws-lc-rs.

addpatch: termscp 0.17.0-1

---

browserpass-firefox/riscv64.patch

addpatch: browserpass-firefox 3.9.0-2

---

afl++/riscv64.patch

https://github.com/AFLplusplus/AFLplusplus/pull/2348

addpatch: afl++ 4.31c-1

---

privoxy/riscv64.patch

updpatch: privoxy 4.0.0-1

---

arti/riscv64.patch

Forgot to add cmake and clang for awc-lc-sys binding generation.

addpatch: arti 1.4.2-1

---

electron33/riscv64.patch
electron34/riscv64.patch

updpatch: electron3{3,4}

---

hedgedoc/riscv64.patch

updpatch: hedgedoc 1.10.2-1

---

libreoffice-fresh/riscv64.patch

updpatch: libreoffice-fresh 25.2.2-2

---

libreoffice-still/riscv64-support.patch
libreoffice-still/riscv64.patch

Align patches with current libreoffice-fresh.

updpatch: libreoffice-still 24.8.6-2

---

cpu-x/fix-unknown-processor.patch
cpu-x/riscv64.patch

Backport https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/commit/2cde825ec67c5f7818846e83ffafa882117eed5b

addpatch: cpu-x 5.2.0-2

---

webkit2gtk-4.1/fix-typo-denormaldisabler.patch
webkit2gtk-4.1/riscv64.patch
webkit2gtk/fix-typo-denormaldisabler.patch
webkit2gtk/riscv64.patch
webkitgtk-6.0/fix-typo-denormaldisabler.patch
webkitgtk-6.0/riscv64.patch
wpewebkit/fix-typo-denormaldisabler.patch
wpewebkit/riscv64.patch

Fix build failure due to missing semicolon.

updpatch: {webkit{2gtk{,-4.1},gtk-6.0},wpewebkit} 2.48.1-1

---

python-psutil/psutil-riscv.patch
python-psutil/riscv64.patch

Upstreamed as https://github.com/giampaolo/psutil/pull/2550

addpatch: python-psutil 7.0.0-1

---

qt6-webengine/compiler-rt-riscv.patch
qt6-webengine/riscv-sandbox.patch
qt6-webengine/riscv64.patch

Update to Chromium 130 patches.

updpatch: qt6-webengine 6.9.0-3

---

maturin/extend-develop_pyo3_ffi_pure-test-timeout.patch
maturin/riscv64.patch

Remove ring patch, but need to raise timeout for a certain test: https://github.com/PyO3/maturin/pull/2553

updpatch: maturin 1.8.3-1

---

electron35/riscv64.patch

updpatch: electron35 35.1.5-1

---

glibc/riscv64.patch

Set bugurl to our repo so user facing bug won't distrub Arch Linux.

upgpatch: glibc 2.41+r9+ga900dbaf70f0-1

---

gcc/riscv64.patch

Set bugurl to our repo so user facing bug won't distrub Arch Linux.

upgpatch: gcc 14.2.1+r753+g1cd744a6828f-1

---

python-aiohttp/riscv64.patch

updpatch python-aiohttp 3.10.11-1

---

maxima/riscv64.patch

updpatch: maxima 5.47.0-21

---

rccl/riscv64.patch

Use git cherry-pick instead of patch.

upgpatch: rccl 6.3.3-1

---

deepin-voice-note/riscv64.patch

https://github.com/linuxdeepin/deepin-voice-note/pull/212

addpatch: deepin-voice-note 6.5.2-1

---

arrow/riscv64.patch

https://github.com/apache/arrow/issues/12681#issuecomment-2490255120

addpatch: arrow 19.0.1-7

---

hipblaslt/riscv64.patch

upgpatch: hipblaslt 6.3.3-1

---

boost/riscv64.patch

updpatch: boost 1.88.0-2

---

protobuf/riscv64.patch

updpatch: protobuf 30.2-1

---

electron36/Debian-fix-rust-linking.patch
electron36/riscv64.patch

See https://github.com/riscv-forks/electron/commit/12b986f8919dfc7396b26c9a4d32f34f1b5ac191 for more details

addpatch: electron36 36.2.0-1

---

qt6-webengine/riscv64.patch

updpatch: qt6-webengine 6.9.0-6

---

inputplumber/riscv64.patch

https://github.com/ShadowBlip/InputPlumber/pull/361

addpatch: inputplumber 0.57.1-1

---

mangohud/riscv64.patch

updpatch: mangohud 0.8.1-1

---

meson/riscv64.patch

Missing dependency added upstream.

updpatch: meson 1.8.0-1

---

amdvlk/riscv64.patch

CMake policy version bumped upstream.

updpatch: amdvlk 2025.Q2.1-1

---

mesa/riscv64.patch

Add patches for @Icenowy's GLVNDized PowerVR Driver. The first one was already merged and the second one should not affect other drivers.

updpatch: mesa 1:25.0.5-1.1

---

mesa-pvr-k1/PKGBUILD

It's a dirty combined package as of now.
Will split them properly after figuring out how to make it work as intended...

addpkg: mesa-pvr-k1 24.2.6603887+bianbu2.0.4-4

---

haskell-primitive-unaligned/riscv64.patch

updpatch: haskell-primitive-unaligned 0.1.1.2-67

---

handbrake/riscv64.patch

upgpatch: handbrake 1.9.2-3

---

hsa-rocr/riscv64.patch
hsa-rocr/rocr-unsupport.patch

Refresh and try to improve patch.

updpatch: hsa-rocr 6.4.0-1

---

hip-runtime/hip-runtime-clr-riscv-hard-float.patch
hip-runtime/riscv64.patch

updpatch: hip-runtime 6.4.0-1

---

rocm-opencl-runtime/riscv64.patch
rocm-opencl-runtime/rocm-opencl-runtime-clr-riscv-hard-float.patch

updpatch: rocm-opencl-runtime 6.4.0-1

---

rust/riscv64.patch

updpatch: rust 1:1.87.0-1

---

gcc13/riscv64.patch

updpatch: gcc13 13.3.1+r432+gfc8bd63119c0-3

---

zed/riscv64.patch

updpatch: zed 0.187.6-1

---

mesa/riscv64.patch

updpatch: mesa 1:25.1.1-1

---

megaglest/bump-cmake-minver.patch
megaglest/riscv64.patch

Upstream PR: https://gitlab.archlinux.org/archlinux/packaging/packages/megaglest/-/merge_requests/4

addpatch: megaglest 3.13.0-11

---

yodl/riscv64.patch

Add missing stdbool.h
https://gitlab.com/fbb-git/yodl/-/merge_requests/5

addpatch: yodl 4.05.00-14.05.00-1

---

protobuf/riscv64.patch

updpatch: protobuf 31.0-2

---

libaemu/riscv64.patch

Backport https://android.googlesource.com/platform/hardware/google/aemu/+/5eb26295f38f74a4b8fb76e4c416249b2ec2b808.

addpatch: libaemu 0.1.2-5

---

mesa/riscv64.patch

- Remove duplicated patch block
- Update patch hash

updpatch: mesa 1:25.1.3-3

---

xmlstarlet/riscv64.patch

updpatch: xmlstarlet 1.6.1-5

---

glusterfs/riscv64.patch

updpatch: glusterfs 1:11.1-5

---

hip-runtime/riscv64.patch

updpatch: hip-runtime 6.4.1-1

---

python-rencode/riscv64.patch

https://github.com/aresch/rencode/pull/37

addpatch: python-rencode 1.0.8-1

---

go/riscv64.patch

updpatch: go 2:1.24.5-1

---

buildbtw-poc/riscv64.patch

https://gitlab.archlinux.org/archlinux/packaging/packages/buildbtw-poc/-/merge_requests/1

addpatch: buildbtw-poc 0.0.0.r365.a20f466-1

---

chromium/compiler-rt-riscv.patch
chromium/riscv64.patch

- Refresh patches
- Regenerate ffmpeg patch
- Add new riscv-updater-138.patch to fix build error

updpatch: chromium 138.0.7204.49-1

---

chromium/riscv-sandbox.patch
chromium/riscv64.patch

- Refresh sandbox patch
- Tested on centiskorch

updpatch: chromium 138.0.7204.168-1

---

kleopatra/riscv64.patch

Update checksum. Reported at
https://gitlab.archlinux.org/archlinux/packaging/packages/kleopatra/-/issues/1

addpatch: kleopatra 25.04.3-1

---

go/riscv64.patch

updpatch: go 2:1.24.6-1

---

ncspot/riscv64.patch

aws-lc-sys needs cmake in riscv64 and cmake has version problem

updpatch: ncspot 1.3.0-1

---

gitlab/riscv64.patch

upgpatch: gitlab 18.1.1-3

---

linux-firmware/riscv64.patch

updpatch: linux-firmware 20250917-1

---

opensubdiv/riscv64.patch

updpatch: opensubdiv 3.6.1-2

---

python-mido/riscv64.patch

Backport https://github.com/mido/mido/commit/58d88dfcfb935aa341300c73f93272bc76038acf

addpatch: python-mido 1.3.3-3

---

nodejs/riscv64.patch

updpatch: nodejs 24.8.0-1

---

electron38/Debian-fix-rust-linking.patch
electron38/riscv64.patch

Changes compared to electron37:
https://github.com/riscv-forks/electron/commit/008625ad4a973b8c0986b88166ec4f8aff3b3b9e

addpatch: electron38 38.1.2-1

---

x86_64-linux-gnu-glibc/PKGBUILD

Update to match https://gitlab.archlinux.org/archlinux/packaging/packages/aarch64-linux-gnu-glibc/-/commit/83b3b43dce2920a345052331d8c3228888b3ac68

updpkg: x86_64-linux-gnu-glibc 2.41-1

---

x86_64-linux-gnu-gcc/PKGBUILD

Update from 14 to 15, matching https://gitlab.archlinux.org/archlinux/packaging/packages/aarch64-linux-gnu-gcc/-/commit/908a73d504d3c79efd558dc26ddd05731e1d91ad

updpkg: x86_64-linux-gnu-gcc 15.1.0-1

---

grub/riscv64.patch

updpatch: grub 2:2.12.r359.g19c698d12-1
