racket/riscv64.patch

updpatch: racket 8.9-2

---

java11-openjdk/riscv64.patch

updpatch: java11-openjdk 11.0.20.u8-2

---

toastify/riscv64.patch

`libc` hack is no longer needed.

updpatch: toastify 0.5.2-1

---

prusa-slicer/prusa-slicer-tbbfix.patch
prusa-slicer/riscv64.patch

Fix onetbb issue.
It seems that there are several PRs for upgrading TBB dependency in upstream repo but none got merged.

addpatch: prusa-slicer

---

consul/riscv64.patch

Fix module pathes by adding another replace directive, as explained in https://github.com/etcd-io/bbolt/issues/211#issuecomment-862161091

upgpatch: consul

---

gcc/riscv64.patch

Remove spec changes because subword AMOs are inlined now.

updpatch: gcc 13.2.1

---

libtg_owt/riscv64.patch

Add support for riscv and disable RVV.
Build `telegram-desktop` after rebuilding `libtg_owt`.

addpatch: libtg_owt 0.git23.a45d8b8-1

---

electron22/riscv64.patch

- Remove the offending compiler flag instead of unsetting all flags.
- Avoid clone the 1GB infra repo.

upgpatch: electron22

---

zcash/riscv64.patch

updpatch: zcash 5.3.0-2

---

zettlr/electron-packager-riscv64.patch
zettlr/riscv64.patch

- Fix config.guess of liblzma dependency of lzma-native dependency.
- Patch electron-packager to recognize riscv64 as a supported arch.
- Replace x64 with riscv64.
- Note that building this package will hit a makechrootpkg bug. We can use a patched build script here: /usr/local/bin/patched-riscv64-build on centiskorch
- Tested on centiskorch. It works fine even if electron24's sandbox is enabled.

addpatch: zettlr

---

code/riscv64.patch

- Use sha256sum instead of invoking node (Thanks Eric Long for pointing it out)
- Avoid using CARCH because it's techincally not actually CARCH.
- Fix checksum validation logic.

upgpatch: code

---

qemu-user-blacklist.txt

Some mold tests use qemu (insider qemu-user), and qemu would fail with:
ERROR:../qemu-8.0.3/accel/tcg/cpu-exec.c:1028:cpu_exec_setjmp: assertion failed: (cpu == current_cpu)

qemu-user-blacklist: add mold

---

qemu-user-blacklist.txt

`electron24 --version` fails in qemu-user:
clone: Invalid argument
Illegal instruction

qemu-user-blacklist: add zettlr

---

chromium/riscv-sandbox.patch
chromium/riscv64.patch
chromium/swiftshader-use-llvm16.patch

- Fix sandbox patch. After this, our chromium no longer crashes when opening https://vscode.dev
- Fix compliation errors by using bundled re2, as Arch already did with electrons.
- Use llvm16 because an upstream risc-v update breaks build with llvm10. (https://github.com/google/swiftshader/commit/b8f1a3ad5f9e077cd4c67e2f612e42bc8ef2fd30)

upgpatch: chromium

---

element.io/app-builder-lib+24.5.2.patch
element.io/builder-util+24.4.0.patch
element.io/element-desktop-riscv64-support.patch
element.io/riscv64.patch

- Skip electron, playwright browsers and sentry-cli downloads
- Use system p7zip, sentry-cli, electron25
- Build app-builder using my fork, patch previously upstreamed as https://github.com/develar/app-builder/pull/90
- Patching build recipes to add riscv64 support
- Patching electron-builder packages, patch previously upstreamed as https://github.com/electron-userland/electron-builder/pull/7646
- Make matrix-seshat use my fork of a higher version of rust-nix, which contains a hack that pretend its version as 0.14.1 so that cargo won't complain. `#[deny(unused)]` is removed from that crate to fix compliation errors that seems arising due to higher rust version.
- Tested on talonframe machine, it works fine. But it won't work on rvv0.7 machines.

addpatch: element.io

---

patch-linux-config.sh

`$2="y"` is assignment instead of comparison. This breaks reading anything from file that were set to "m" or "n".

patch-linux-config: fix awk compare

---

atuin/riscv64.patch

The package no longer depends on libsodium-sys.

updpatch: atuin 16.0.0-2

---

rust/bump-bootstrap-cc.patch
rust/riscv64.patch

- Bump bootstrap cc to 1.79, provided by vendor/

updpatch: rust 1:1.72.0-1

---

gcc/riscv64.patch

Cherry-pick fix for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110066 which breaks glibc's test suite.

updpatch: gcc 13.2.1-3.1

---

vnstat/riscv64.patch

Upstream does not want to update autotools: https://github.com/vergoh/vnstat/issues/239#issuecomment-1332795086

updpatch: vnstat 2.11-1

---

sbcl/riscv64.patch

sbcl can't bootstrap itself now, use clisp instead. 
[Related bug report](https://bugs.launchpad.net/sbcl/+bug/2031965)
Some tests are failing, see https://pb.mgt.moe/1kop

addpatch: sbcl 2.3.7-1

---

helm/add-riscv64-build.patch
helm/riscv64.patch

Fix check:
- Add riscv64 entry in plugin_test.go.
- Fork github.com/bugsnag/osext and fix dup2 issue.

addpatch: helm

---

highway/compile-only-emu128.patch
highway/riscv64.patch

- Disable LTO.
```
[  5%] Linking CXX shared library libhwy.so
lto1: fatal error: target specific builtin not available
compilation terminated.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
```
- Define `HWY_COMPILE_ONLY_EMU128` to force using scalar implementation only to work around RVV detection. Needs better solution for upstream.

addpatch: highway

---

plotutils/riscv64.patch

Update (somehow) outdated configuration files.
GNU plotutils hasn't been updated since 2009 and there's no way of upstreaming.

updpatch: plotutils 2.6-11

---

go/riscv64.patch

Workaround for AUIPC+JALR optimized as deadcode, which causes:
```text
github.com/aws/aws-sdk-go/aws/endpoints.init: missing section for github.com/aws/aws-sdk-go/aws/endpoints.map.init.0
github.com/aws/aws-sdk-go/aws/endpoints.init: reloc 62 (R_RISCV_PCREL_ITYPE) to non-elf symbol github.com/aws/aws-sdk-go/aws/endpoints.map.init.0 (outer=github.com/aws/aws-sdk-go/aws/endpoints.map.init.0) 1 (STEXT)
github.com/aws/aws-sdk-go/aws/endpoints.init: unreachable reloc 62 (R_RISCV_PCREL_ITYPE) target github.com/aws/aws-sdk-go/aws/endpoints.map.init.0
```
This workaround skips the check which would disable the deadcode optimization (in some cases). We should replace with a patch after upstream really fixes.
Packages like [pint](https://archriscv.felixc.at/.status/log.htm?url=logs/pint/pint-0.45.0- …

upgpatch: go 2:1.21.1-1

---

element.io/element-desktop-riscv64-support.patch
element.io/riscv64.patch

- Fix rotten patches.
- app-builder upstream merged my patch. Let's use upstream repo. But master branch is buggy, so I pinned it to the last good commit.
- Bug report: https://github.com/develar/app-builder/issues/92

upgpatch: element.io

---

systemd/riscv64.patch

- remove lib32-gcc-libs
- remove old workaround for binutils

updpatch: systemd 254.3-1

---

arrow/riscv64.patch

LTO is still broken:
```
/usr/bin/ld: error: LLVM gold plugin: linking module flags
'SmallDataLimit': IDs have conflicting values in
'CMakeFiles/arrow_acero_testing.dir/test_util_internal.cc.o' and
'ld-temp.o'
```

updpatch: arrow 13.0.0-4

---

yaml-cpp/riscv64.patch

cherry-pick patch to fix tests for unsigned char platforms

addpatch: yaml-cpp 0.8.0-1

---

qemu-user-blacklist.txt

g++ segmentation faults in qemu-user riscv64. But it doesn't fail on real riscv64 boards.
Bug report: https://gitlab.com/qemu-project/qemu/-/issues/1895
Minimal reproduction: https://gitlab.com/qemu-project/qemu/uploads/d63b1867a458a240ef0d90c760d76bc7/testcase.i

qemu-user-blacklist: add nodejs-lts-hydrogen

---

qemu-user-blacklist.txt

g++ segfaults in qemu.
To reproduce, run `g++ -std=gnu++20 -c neochat.i`.
neochat.i is a reduced version of the original ICE file.
Attachment: [neochat.i.zip](https://github.com/felixonmars/archriscv-packages/files/12642249/neochat.i.zip)

qemu-user-blacklist: add neochat

---

openssl/riscv64.patch

Reconfigure target platform from 'linux-generic64' to 'linux64-riscv64' within the OpenSSL 3 project. This adjustment is motivated by the significant presence of [RISC-V optimization codes](https://github.com/search?q=repo%3Aopenssl%2Fopenssl%20riscv64&type=code) embedded throughout the OpenSSL 3 codebase.

Switch OpenSSL target to 'linux64-riscv64' for RISC-V assembly

---

webkit2gtk-4.1/riscv64.patch
webkit2gtk/riscv64.patch
webkitgtk-6.0/riscv64.patch

Disable LTO:
```
[1364/6887] Linking CXX executable bin/LLIntSettingsExtractor
FAILED: bin/LLIntSettingsExtractor
: && /usr/bin/clang++ -fdiagnostics-color=always -fcolor-diagnostics -Wextra -Wall -pipe -Wno-noexcept-type -Wno-psabi -Wno-misleading-indentation -Wno-parentheses-equality -Qunused-arguments -Wundef -Wpointer-arith ...
ld.lld: error: linking module flags 'SmallDataLimit': IDs have conflicting values in 'Source/WTF/wtf/CMakeFiles/WTF.dir/./ASCIICType.cpp.o' and 'ld-temp.o'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

addpatch: webkit2gtk{,-4.1}, webkitgtk-6.0

---

clang15/riscv64.patch

checksum mismatch reported to Arch: https://bugs.archlinux.org/task/79752
`nocheck` is currently needed:
```
FAIL: Clang-Unit :: Interpreter/ExceptionTests/./ClangReplInterpreterExceptionTests/0/1 (16538 of 16669)
******************** TEST 'Clang-Unit :: Interpreter/ExceptionTests/./ClangReplInterpreterExceptionTests/0/1' FAILED ********************
Script(shard):
--
GTEST_OUTPUT=json:/build/clang15/src/clang-15.0.7.src/build/unittests/Interpreter/ExceptionTests/./ClangReplInterpreterExceptionTests-Clang-Unit-13886-0-1.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=1 GTEST_SHARD_INDEX=0 /build/clang15/src/clang-15.0.7.src/build/unittests/Interpreter/ExceptionTests/./ClangReplInterpreterExceptionTests
--
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up. …
```

addpatch: clang15 15.0.7-1

---

deepin-grand-search/riscv64.patch

Backport unreleased upstream commit:
https://github.com/linuxdeepin/dde-grand-search/commit/f66f34a8b0fb8852eb1d9e83ac05f89e2ba06cad

addpatch: deepin-grand-search

---

criu/riscv64.patch

Port upstream riscv64 support pull request: https://github.com/checkpoint-restore/criu/pull/2234
Applies loongarch64 support as well so patches don't fail.

addpatch: criu

---

amdvlk/riscv64.patch

Fix 64-bit detection on riscv64. Upstreamed to https://github.com/nothings/stb/pull/1517.

addpatch: amdvlk

---

vapoursynth-plugin-lsmashsource/riscv64.patch
vapoursynth-plugin-lsmashsource/use-simde.patch

addpatch: vapoursynth-plugin-lsmashsource

---

keycloak/riscv64.patch

- Replace EOL Node.js 16 with current version

updpatch: keycloak 22.0.3-1

---

cargo-modules/riscv64.patch

Remove parameter: `--target "$CARCH-unknown-linux-gnu"`.
Successfully built and checked.
Output `error: target not found: cargo-modules`
at the end (similar to #1417).

addpkg: cargo-modules

---

zbus_xmlgen/riscv64.patch

Remove parameter: `--target "$CARCH-unknown-linux-gnu"`.
Successfully built and checked.
Output `error: target not found: zbus_xmlgen`
at the end (similar to #1417).

addpkg: zbus_xmlgen

---

qemu-user-blacklist.txt

Test segmentation fault only happens in qemu-user.
```
7/7 Test #7: loading_from_clipboard_test ......***Exception: SegFault  0.34 sec
```

qemu-user-blacklist: add cockatrice

---

python-jupyter-sphinx/riscv64.patch

Fix check failure:
```text
[  100s] ==================================== ERRORS ====================================
[  100s] ____________________ ERROR collecting tests/test_execute.py ____________________
[  100s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/jupyter-sphinx-0.4.0/tests/test_execute.py'.
[  100s] Hint: make sure your test modules/packages have valid Python names.
[  100s] Traceback:
[  100s] /usr/lib64/python3.9/importlib/__init__.py:127: in import_module
[  100s]     return _bootstrap._gcd_import(name[level:], package, level)
[  100s] tests/test_execute.py:15: in <module>
[  100s]     from sphinx.testing.util import SphinxTestApp, assert_node, path
[  100s] E   ImportError: cannot import name 'path' from 'sphinx.testing.util' …
```

addpatch: python-jupyter-sphinx 0.4.0-2

---

maude/riscv64.patch

Update the outdated config.guess file.
Perhaps there is no need to report to upstream, because maude is going to use CMake instread of Autotools: https://github.com/SRI-CSL/Maude/pull/10 ?

addpkg: maude

---

fceux/riscv64.patch

Cherry-pick two of the upstream commits to make x86 `rdtsc` usage optional:
- https://github.com/TASEmulators/fceux/commit/396096223ec58ff7f437ec0de7275240946531c5
- https://github.com/TASEmulators/fceux/commit/d2ee6351c08518c866bb48d89f58a67bb36931fc

addpatch: fceux 2.6.6-1

---

python-mitmproxy-rs/riscv64.patch

Fix `ring` issue and add RISC-V 64 support for `protoc-bin-vendored` (Upstreamed to
https://github.com/stepancheg/rust-protoc-bin-vendored/pull/2)

addpkg: python-mitmproxy-rs

---

librustls/riscv64.patch

- Fix broken rust target.
- Fix ring issue.
- Fix `patchelf` target path in RV64: `riscv64gc` instead of `riscv64`.

addpkg: librustls

---

glibc/riscv64.patch

Fix rotten.
`nocheck` still needed:
```
XPASS: conform/UNIX98/ndbm.h/linknamespace
XPASS: conform/XOPEN2K/ndbm.h/linknamespace
XPASS: conform/XOPEN2K8/ndbm.h/linknamespace
XPASS: conform/XPG42/ndbm.h/linknamespace
UNSUPPORTED: elf/tst-env-setuid
UNSUPPORTED: elf/tst-env-setuid-tunables
XPASS: elf/tst-protected1a
XPASS: elf/tst-protected1b
FAIL: elf/tst-sprof-basic
UNSUPPORTED: elf/tst-valgrind-smoke
UNSUPPORTED: math/test-fesetexcept-traps
UNSUPPORTED: math/test-fexcept-traps
UNSUPPORTED: math/test-nearbyint-except-2
UNSUPPORTED: misc/tst-adjtimex
UNSUPPORTED: misc/tst-clock_adjtime
UNSUPPORTED: misc/tst-ntp_adjtime
UNSUPPORTED: misc/tst-rseq
UNSUPPORTED: misc/tst-rseq-disable
UNSUPPORTED: misc/tst-ttyname-namespace
UNSUPPORTED: nptl/test-cond-printers
UNSUPPORTED: …
```

updpatch: glibc 2.38-5

---

glibc/riscv64.patch

Fix rotten. New glibc fixes a local privilege escalation security issue.
No need to remove `package_lib32-glibc()` because makepkg will ignore it.

upgpatch: glibc

---

cppcheck/riscv64.patch

Improve cppcheck testcases on `unsigned char` platform.
Upstreamed: https://github.com/danmar/cppcheck/pull/5524

addpkg: cppcheck

---

java11-openjdk/riscv64.patch

upgpatch: java11-openjdk

---

libei/riscv64.patch

Disable Valgrind tests by removing valgrind from checkdepends.
Currently Valgrind won't work as on x86_64 due to lack of debuginfod server. Debug packages could be used, but I am afraid they are not included in the build environment.

addpatch: libei

---

libopenshot/riscv64.patch

- Fix rotten and make it less likely to rot.
- We can drop the `-fopenmp` change now. It compiles fun and all tests pass.

upgpatch: libopenshot

---

nushell/riscv64.patch

Disables `dataframe` feature that uses `simd-json`, which does not have fallback implementation and is hard to replace with something like `serde_json`.
See https://github.com/nushell/nushell/pull/9542.

updpatch: nushell 0.85.0-1

---

makedumpfile/riscv64.patch

Upstream added riscv support: https://github.com/makedumpfile/makedumpfile/commit/f777afbd7996d0aba7861f437b79f4dd7ab23019

addpatch: makedumpfile

---

p2pool/riscv64.patch

The author use plenty of casting like `(uint64_t*)arr` in which `arr` is a array of `uint8_t*`. Meanwhile, the author use compile option `Wcast-align` and `Werror`. I found it interesting that the warning isn't caused on x86_64 but it is on riscv64 so the build failed. So I use #pragma to block the warning temporarily from files which contain the type of cast. 
And there's another problem caused by cast-qual in the external project RandomX, which happens when cast from const to non-const. However it seems not necessary to remove the const qualifier, so I opened a issue: https://github.com/tevador/RandomX/issues/277 and the problem is fixed on the master branch. Maybe it will take effect in a future release.

addpkg: p2pool

---

qemu-user-blacklist.txt

On qemu-user:
```
FAIL!  : NeovimQt::TestQSettings::GuiFont() Compared values are not the same
Actual   (window.shell()->fontDesc()): "Monospace:h11"
Expected (fontDesc)                  : "DejaVu Sans Mono:h20"
Loc: [/usr/src/debug/neovim-qt/neovim-qt/test/tst_qsettings.cpp(106)]
```
All tests pass on unmatched.

qemu-user-blacklist: neovim-qt

---

obs-studio/riscv64.patch

`char` is unsigned on RISC-V and it's impl-defined for `char` to be signed or unsigned. Ensuring `utf8_char_t` to be signed to make comparison with zero works.

addpkg: obs-studio

---

afl/riscv64.patch

- Build without lib32-glibc
- Set `AFL_NO_X86`.
- Disable LTO.
I tried to fix LTO but encountered the following problem:
/usr/sbin/ld: error: LLVM gold plugin: linking module flags 'SmallDataLimit': IDs have conflicting values in '../afl-llvm-rt.o' and 'ld-temp.o'
It is also seen in https://github.com/civetweb/civetweb/issues/951 (no answer).

addpatch: afl

---

python-pyfakefs/riscv64.patch

Drop `tox` for check() due to [Python package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Check).
[Arch bug report](https://bugs.archlinux.org/task/79986)

addpatch: python-pyfakefs 5.3.0-1

---

python-llvmlite/riscv64.patch

OrcJIT is still in the experimental stage, and there are some issues where the OrcJIT test fails when tested on non-x86 platforms (e.g. Issue [numba#1000](https://github.com/numba/llvmlite/issues/1000)), so skip writing this test on non-x86 platforms.

upgpatch: python-llvmlite

---

diffoscope/riscv64.patch

Remove mono and fpc from checkdepends because they are currently not available for riscv64.
The relevant tests are skipped automatically.

addpatch: diffoscope

---

deepin-font-manager/riscv64.patch

Backport https://github.com/linuxdeepin/deepin-font-manager/commit/89c46df1de0012b609779f97d09dfdcd5a99e3b2
[Arch bug report](https://bugs.archlinux.org/task/80003)

addpatch: deepin-font-manager 6.0.1-1

---

libtheora/fix-linking-issue.patch
libtheora/riscv64.patch

Update the outdated config scripts and fix an under linking issue.
* Upstream issue: https://gitlab.xiph.org/xiph/theora/-/issues/2320
* Under linking was fixed at https://gitlab.xiph.org/xiph/theora/-/commit/b07a1d2ddfe8059f1682e01370f8d3b42791d181

addpatch: libtheora

---

luajit/riscv64.patch

- fix rotten
- update to upstream commit [172b660f2c0e75d64e85cd9b0df2ae14f1bde8eb](https://github.com/infiWang/LuaJIT/commit/172b660f2c0e75d64e85cd9b0df2ae14f1bde8eb)
- fetching source from github archive tarbar instead of repo commit

upgpatch: luajit

---

python-pygdbmi/riscv64.patch

Increase timeout duration. Upstreamed: https://github.com/cs01/pygdbmi/pull/103
I think 10 seconds is enough because successfully packaged on four boards (Unmatched, VisionFive, Milk-V Pionner, Lichee Pi 4A)

addpatch: python-pygdbmi 0.11.0.0-3

---

atuin/riscv64.patch

Specify that ring 0.16.20 to be updated because there are multiple versions (0.17.5) of ring in the lock file.

upgpatch: atuin

---

v2ray/riscv64.patch
v2ray/v2ray-kcpTest.patch
v2ray/v2ray-testTCPConn2-timeout.patch
v2ray/v2ray-testVMessKCP.patch

Resolved `go test` error; however, due to the current incompatibility of v2ray-core 5.7.0 with go version 1.21, the compilation is still failing.
This patch has been reported to the upstream as issue [v2ray/v2ray-core#2720](https://github.com/v2fly/v2ray-core/issues/2720)

upgpatch: v2ray

---

dsq/riscv64.patch

fix test.py fails on caching duration.
The author suggests that this test case can be safely disabled. see issue https://github.com/multiprocessio/dsq/issues/80

addpkg: dsq

---

jumpy/riscv64.patch

- There's no need to fix the version of `mimalloc`, as it was removed in upstream commit https://github.com/fishfolk/jumpy/commit/1343ad16a50603fc05b91e5d927cfd01c73d676f#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L92

updpatch: jumpy 0.8.2-1

---

coin-or-osi/riscv64.patch

- Fix rotten.
- Use system config.{guess,sub} instead of pulling them from web.

upgpatch: coin-or-osi

---

lurk/riscv64.patch

- Refresh riscv64 patches to keep in sync with x86_64's changes
- Add new syscalls: cachestat, riscv_flush_icache and riscv_hwprobe

updpatch: lurk 0.3.4-1

---

upx/riscv64.patch

Use cherry-pick instead of patch to avoid validity check failure

upgpatch: upx 4.2.0-1

---

libunwind/riscv64.patch

- Replace x86_64 with riscv in provides to match actual file name
- Update config.{guess,sub}. Upstreamed to https://github.com/libunwind/libunwind/issues/654.

addpatch: libunwind 1.7.2-1

---

python-zict/riscv64.patch

Backported map size fix from https://github.com/dask/zict/pull/111.

addpatch: python-zict 2.2.0-2

---

nodejs-lts-hydrogen/riscv64.patch

Backport `[riscv64] Fix the StaticStackFrameSize` to fix vite.
- Upstream issue: https://github.com/nodejs/node/issues/50503
- Upstream PR: https://github.com/nodejs/node/pull/50506

addpatch: nodejs-lts-hydrogen

---

rust-bindgen/riscv64.patch

Apply patch to fix https://github.com/rust-lang/rust-bindgen/issues/2677 for building mesa.

updpatch: rust-bindgen 0.69.0-1.1

---

libredefender/riscv64.patch

- use `[patch.'repo-url']` instead of `[patch.crates-io]` to override, as upstream uses dependency that isn't loaded from `crates-io`.
See https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#overriding-repository-url
- fixed `type mismatch` error, upstreamed: https://github.com/kpcyrd/clamav-rs/pull/1

updpatch: libredefender 0.7.0-1

---

qemu-user-blacklist.txt

Qemu 8.1.0 regression(2d708164): https://gitlab.com/qemu-project/qemu/-/issues/1908
JVM crash when starting gradle daemon in qemu-user: https://paste.rs/0ykPK

qemu-user-blacklist.txt: add gradle{,7}

---

deno/riscv64.patch

- Fix rotten
- Remove ring v0.16.20 patch as upstream is now using ring = "^0.17.0" (Successfully built without this)

updpatch: deno 1.38.0-1

---

nodejs/riscv64.patch

- Fix v8 compilation errors, upstreamed to nodejs: https://github.com/nodejs/node/pull/50552
- Remove the `-fno-strict-aliasing` flag addition. The relevant error no longer occurs. Actually, we never do this to nodejs-lts-hydrogen after nodejs 18 is packaged as nodejs-lts-hydrogen.

upgpatch: nodejs 21.1.0-1

---

rust-bindgen/riscv64.patch

- Fix rotten
- Upstream and Arch x86_64 released v0.69.1, which contains already merged patch: https://github.com/rust-lang/rust-bindgen/pull/2678, so no need for it. (Successfully built without this patch)

updpatch: rust-bindgen 0.69.1-1

---

code/riscv64.patch

Fix rotten.
Sometimes the `yarn install` step fails with weird node-gyp errors, which could be solved by retrying the build.

upgpatch: code 1.84.1-1

---

bitwarden/app-builder-lib+23.6.0.patch
bitwarden/bitwarden-napi-riscv64.patch
bitwarden/builder-util+23.6.0.patch
bitwarden/electron-builder+23.6.0.patch
bitwarden/riscv64.patch
qemu-user-blacklist.txt

- Patch napi binding file for riscv64 support. This could be removed
once upstream upgrades napi-rs to 3.0(which is not stable yet).
- Build app-builder riscv64 and use system 7za.
- Patch electron builder related packages for riscv64 support. Previous upstream
PR got rejected.
- Build native node module manually instead of using napi-rs/cli to
avoid hitting v8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=13930
- Add it to qemu-user-blacklist because `electron24 --version` can't run inside qemu-user.
- Other trival changes.
Note that this package can't be built on sg2042 because a strange SIGILL happens in node during the build.

addpatch: bitwarden

---

vue-language-server/increase-test-timeout.patch
vue-language-server/riscv64.patch

Increase timeout to pass test in `check()`.
Upstream: https://github.com/vuejs/language-tools/pull/3721.

addpatch: vue-language-server 1.8.22-1

---

bitwarden/app-builder-lib+23.6.0.patch
bitwarden/riscv64.patch
qemu-user-blacklist.txt

- Update app-builder-lib patch, which fixes my previous PR.
- Read electron version from `/usr/lib/electron$_electronversion/version` instead of `$(electron --version)`, which makes this package buildable in qemu-user. We are already patching this package after all, I believe this change could make our life easier :)
- Remove bitwarden from qemu-user-blacklist.

upgpatch: bitwarden

---

typst/riscv64.patch

add back rust target fix (>.<)

addpatch: typst

---

refind/riscv64.patch

- Fix rotten.
- Disable incorporating `.sbat` by `objcopy`, since there's no binutils support for `efi-*-riscv64` target.

updpatch: refind 0.14.0.2-1

---

qemu-user-blacklist.txt
zettlr/riscv64.patch

- Fix rotten and make it less likely to rot.
- Read electron version from `/usr/lib/electron$ver/version` and remove this package from qemu-user-blacklist.txt

upgpatch: zettlr

---

upx/riscv64.patch

Fix rotten by disabling self-pack tests.

updpatch: upx 4.2.1-1

---

guitarix/riscv64.patch

Remove unused `--disable-sse`, because upstream won't use `-msse` for non-x86 architectures: https://github.com/brummer10/guitarix/blob/efccbd14afb5a85be142319b94be088b9cf1d5fd/trunk/src/LV2/wscript#L6-L26
Make libsndfile as a dependency for both build and run. Arch: https://bugs.archlinux.org/task/80175

updpatch: guitarix 0.44.1-5

---

mirro-rs/riscv64.patch

- Fix `--target $CARCH-unknown-linux-gnu` issue.
- Flaky test will be fixed in future release (https://github.com/rtkay123/mirro-rs/pull/29).

addpatch: mirro-rs 0.2.1-1

---

hsa-rocr/riscv64.patch

Fix `rocm-dbgapi` compile error:
```text
In file included from /opt/rocm/include/hsa/amd_hsa_queue.h:47,
from /build/rocm-dbgapi/src/ROCdbgapi-rocm-5.7.1/src/queue.cpp:35:
/opt/rocm/include/hsa/hsa.h:93:2: error: #error "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
93 | #error "BIGENDIAN_CPU or LITTLEENDIAN_CPU must be defined"
|  ^~~~~
```

addpatch: hsa-rocr 5.7.1-1

---

qemu-user-makedepends-blacklist.txt

pcre2 JIT fails with segment fault in current qemu-user (v8.1.2), any use of it will fail in qemu.
also tidy the file.

qemu-user-makedepends-blacklist: add pcre2

---

rocminfo/riscv64.patch

- Remove unneeded c++ flag `-m64` for riscv64, see riscv-collab/riscv-gnu-toolchain#670

addpatch: rocminfo 5.7.1-1

---

rocm-smi-lib/riscv64.patch
rocm-smi-lib/rocm-smi-lib_fix-cxx-flags.patch

- remove unneeded c++ flag `-m64` and unsupported flags `-msse -msse2` for riscv64

addpatch: rocm-smi-lib

---

lftp/riscv64.patch

Original author contacted to update config.guess/config.sub. Added those two files and modified PKGBUILD zo perform autoupdate/autoreconf until that is done.

addpkg: lftp

---

rustypaste/riscv64.patch

- Remove 'ring patch' on v0.16.20, as upstream updated ring to v0.17.5. (Successfully built without 'ring v0.16.20 patch') 
This fix `error: There are multiple 'ring' packages in your project` in log.

updpatch: rustypaste 0.14.1-1

---

obs-studio/riscv64.patch

- Fix rotten.
- Disable obs-qsv11 due to arch-specific code (`cpuid.h`)

updpatch: obs-studio 30.0.0-1

---

qemu-user-makedepends-blacklist.txt

halting rust builds in qemu-user are rare now, try to unblock it.

qemu-user-makedepends-blacklist: remove rust/cargo

---

python-mitmproxy-rs/riscv64.patch

Remove `protobuf`: `python-mitmproxy-rs` no longer depends on it.
ring patch is still required.

updpatch: python-mitmproxy-rs 0.4.0-1

---

buildbot/riscv64.patch
qemu-user-blacklist.txt

- Increase test timeout of `start_test` by backporting upstream commit. We can probably remove this patch at the next release.
- Add to qemu blacklist because chromium can't execute in qemu: https://www.mail-archive.com/qemu-devel@nongnu.org/msg803994.html

addpatch: buildbot

---

rocm-opencl-runtime/riscv64.patch

Fix `immintrin.h` ENOENT.
Upstream: https://github.com/ROCm-Developer-Tools/clr/pull/35

addpatch: rocm-opencl-runtime 5.7.1-1

---

prusa-slicer/riscv64.patch

- Fix source path name. `TBB` -> `+TBB`

updpatch: prusa-slicer 2.7.0-1

---

qemu-user-makedepends-blacklist.txt

`deno` makes the rust deadlock nearly 100% reproducible on qemu-user. Adding back the blacklist entries.
This reverts commit 7a10432fbe6ba5959a8e7ac885a6032c8b110f81.

Revert "qemu-user-makedepends-blacklist: remove rust/cargo"

---

pcre2/riscv64.patch
qemu-user-makedepends-blacklist.txt

Apply a patch to fix sv48/sv57 crashes. Upstream hasn't confirmed the
fix [1] yet but at least the tests are passing now.
Thanks to @ksco !
[1] https://github.com/zherczeg/sljit/pull/223

addpatch: pcre2

---

pcre2/riscv64.patch
pcre2/sljit-sv48-sv57.patch
qemu-user-blacklist.txt

Applies updates from the sljit PR. `cockatrice` tests are also passing now with either qemu-user (sv48) or qemu-system (sv57).

updpatch: pcre2

---

flip-link/riscv64.patch

addpatch: flip-link 0.1.7-1

---

ot-urchin/riscv64.patch

- Fix broken cargo target
- Use forked repo to support riscv: https://github.com/aimixsaka/nih-plug/tree/riscv
- Upstreamed: https://github.com/robbert-vdh/nih-plug/pull/95

addpatch: ot-urchin 1.0.0-1

---

ot-cryptid/riscv64.patch

- Fix broken cargo target
- Use forked repo to support riscv: https://github.com/aimixsaka/nih-plug/tree/riscv_backport
- Upstreamed: https://github.com/robbert-vdh/nih-plug/pull/95

addpatch: ot-cryptid 1.0.1-3

---

librustls/riscv64.patch

Fix rotten. Successfully built without ring patch.

updpatch: librustls 0.12.0-1

---

qemu-user-blacklist.txt
qt6-webengine/riscv64.patch

- Fix rotten.
- Remove it from qemu-user-blacklist as the pcre2 bug has been fixed. But note that gn might hang in qemu-user.
- Add a hack that make the gn hang problem arise as early as possible so that we won't end up encountering the problem after the build is running for one day.
Edit: and use nodejs 20 instead of 21 to avoid another bug: node21 Z in qemu-user. Unfortunately we don't have other environments that could build this package reliably.

upgpatch: qt6-webengine 6.6.1-1

---

ocaml/riscv64.patch

Remove backported patches, since it has been released.

updpatch: ocaml 5.1.0-1

---

snapshot/fix-clippy-timeout.patch
snapshot/riscv64.patch

Fix `Cargo clippy` timeout error, upstreamed to snapshot: https://gitlab.gnome.org/GNOME/snapshot/-/issues/111

addpatch: snapshot

---

python-aiohttp/riscv64.patch

Skip `test_import_time`. This test doesn't affect functionality and the import time on RISC-V machines is much larger  (increasing timeout is not very feasible, upstream wants to find potential problems based on import time).

addpatch: python-aiohttp 3.9.1-1

---

gitoxide/riscv64.patch

Remove `ring@0.16.20` patch by updating indirect dependences (https://github.com/Byron/gitoxide/pull/1175).

addpatch: gitoxide 0.32.0-1

---

qemu-user-blacklist.txt

ICE because of stack overflow: https://gitlab.com/qemu-project/qemu/-/issues/1895
Could also be solved by exporting a large QEMU_STACK_SIZE value in makepkg config file.

qemu-user-blacklist.txt: add vbam

---

electron25/riscv64.patch

- Fix rotten and use nodejs-lts-iron.
- Drop support for building in Debug profile.

upgpatch: electron25

---

cdparanoia/riscv64.patch

- Fix rotten
- Successfully build without removing the `format-security` compiler flag

updpatch: cdparanoia

---

sysdig/riscv64.patch

Backport [RISC-V kmod support](https://github.com/falcosecurity/libs/pull/1181) for falcosecurity/libs

addpatch: sysdig 0.34.1-2

---

ldc/riscv64.patch

LDC is finally working again on riscv64. This is the first of two patches in order to realign LDC with current Arch environment.
- Link to LLVM 14 to match previously built version long ago. Will switch to LLVM 16 in the next patch.
- Add some temporary atomic hacks to make compiler happy, since previous GCC atomic hacks were replaced by actual upstream implementation.

updpatch: ldc 3:1.35.0-1

---

ldc/riscv64.patch

...and here comes the second part:
- Switch to LLVM 16, in line with Arch Linux.
- Remove all but one atomic hack. This is needed because the tests somehow requires double word atomic operations, which is not supported on riscv64.

updpatch: ldc 3:1.35.0-1.1

---

d-stdx-allocator/riscv64.patch

Fix rotten. (https://github.com/dlang-community/stdx-allocator/pull/35)

updpatch: d-stdx-allocator 3.0.2-21

---

distrho-ports/riscv64.patch
distrho-ports/use-simde.patch

Use simde to provide SSE2 intrinsics.

addpatch: distrho-ports 2021.03.15-3

---

wpewebkit/riscv64.patch

Disable LTO:
```
ld.lld: error: linking module flags 'SmallDataLimit': IDs have conflicting values in 'Source/WTF/wtf/CMakeFiles/WTF.dir/./ASCIICType.cpp.o' and 'ld-temp.o'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is probably the same issue as https://github.com/felixonmars/archriscv-packages/pull/3121.

addpatch: wpewebkit 2.42.4-1

---

tilix/riscv64.patch

LTO failed (both full and thin):
```
/usr/bin/ld: /tmp/lto-llvm-ea1ef0.o: can't link soft-float modules with double-float modules
/usr/bin/ld: failed to merge target specific data of file /tmp/lto-llvm-ea1ef0.o
```

addpatch: tilix 1.9.6-1

---

age-plugin-tpm/riscv64.patch

- patch [go-tpm-tools](https://github.com/google/go-tpm-tools) to support RISC V
- upstreamed: https://github.com/google/go-tpm-tools/pull/407
- check will timeout on luxio, while centiskorch is ok

addpatch: age-plugin-tpm

---

neovide/riscv64.patch

- Remove unneeded depends
- Remove ring 0.16 patch as upstream updated to 0.17
- Bump `rust-skia` to self-forked `0.68.0` [1] to catch up upstream [2]. This fix: 
```
warning: Patch `SOMETHING` was not used in the crate graph. 
Check that the patched package version and available features 
are compatible with the dependency requirements 
```
- Backport rust-skia/rust-skia#916 to fix rust-skia/rust-skia#913
- Remaining relevant pr/issue:
- https://github.com/google/skia/pull/146
- https://gitlab.archlinux.org/archlinux/packaging/packages/neovide/-/issues/1
[1]: https://github.com/aimixsaka/rust-skia/tree/riscv-skia-bindings-0.68.0
[2]: https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/Cargo.toml#L59C68-L59C68

updpatch: neovide 0.12.0-1

---

lychee/riscv64.patch

- Remove upstreamed patch
- Fix test_cookie_jar failure, upstream PR: https://github.com/lycheeverse/lychee/pull/1336
- Update ring fix. Upstream PR to get rid of ring 0.16.20: https://github.com/lycheeverse/lychee/pull/1337

updpatch: lychee 0.14.0-1

---

spring/add-missing-header.patch
spring/disable-streflop-for-cutils.patch
spring/riscv64.patch
spring/support-riscv64-build.patch
spring/use-simde.patch

- support riscv64
- add missing header
- disable streflop: https://springrts.com/mantis/view.php?id=1846
- remove arch-specific flags: https://springrts.com/mantis/view.php?id=1788
- use simde to provide SSE intrinsics

addpatch: spring 106.0-2

---

nodejs-lts-iron/riscv64.patch

Use clang instead of gcc to workaround the following two bugs:
- https://bugs.chromium.org/p/v8/issues/detail?id=13930
- https://bugs.chromium.org/p/v8/issues/detail?id=14547
Bisection of CFLAGS blames `-O2` flag for the bug. So another workaround is removing `-O2` from C{,XX}FLAGS. Not sure if the bug is caused by compiler bugs or UB in nodejs/v8 code, etc.

addpatch: nodejs-lts-iron

---

namcap/fix-riscv64-test.patch
namcap/riscv64.patch

- Fix rotten
- disable `test_elffiles.py : TestNoShadowStack` on architectures other than x86_64/i686, as `-fcf-protection` currently only works for i686 processor or newer

updpatch: namcap 3.5.2-1

---

nodejs-lts-hydrogen/riscv64.patch

Using clang results in build errors that would require extra patching to fix.
So I removed O2 from CFLAGS, as mentioned in https://github.com/felixonmars/archriscv-packages/pull/3443
This package still needs nocheck.

updpatch: nodejs-lts-hydrogen

---

jumpy/riscv64.patch

Update several dependencies to pull ring version to 0.17. Upstreamed to https://github.com/quinn-rs/quinn/pull/1751 and https://github.com/fishfolk/bones/pull/334.

updpatch: jumpy 0.10.0-1

---

cargo-semver-checks/riscv64.patch

Disable x86_64-specific tests on non-x86_64 platforms. 
upstreamed: https://github.com/obi1kenobi/cargo-semver-checks/pull/647

upgpatch: cargo-semver-checks 0.28.0-1

---

python-ansible-compat/riscv64.patch

Test compiles Rust code (possibly due to riscv64 prebuilt not available), add cargo to checkdepends

addpatch: python-ansible-compat 4.1.11-1

---

java11-openjdk/riscv64.patch

Enable Shenandoah GC since current patch supports it.

updpatch: java11-openjdk 11.0.22.u7-1

---

wasm-bindgen/riscv64.patch

Use system openssl instead of vendoring
[Upstreamed to Arch](https://gitlab.archlinux.org/archlinux/packaging/packages/wasm-bindgen/-/merge_requests/1)

upgpatch: wasm-bindgen 0.2.90-1

---

glibc/riscv64.patch

`--nocheck` still needed.
Place pkgname change at the bottom to avoid commit hash context.

upgpatch: glibc 2.38-8

---

gcc/riscv64.patch

Leave some `rm -f` multilib stuff that don't cause failures as-is, to make patch less likely to be rotten.

upgpatch: gcc 13.2.1-4

---

nodejs-lts-iron/riscv64.patch

Revert a v8 cherry-pick that targets v21 but incorrectly gets backported to v20.
Upstream PR:  https://github.com/nodejs/node/pull/51495

updpatch: nodejs-lts-iron

---

prometheus-postgres-exporter/riscv64.patch

`go test -race` unsupported on riscv.

addpatch: prometheus-postgres-exporter 0.15.0-2

---

docker/riscv64.patch

riscv go external linking needs `CGO_ENABLED=1` explicitly.

addpatch: docker 1:25.0.2-1

---

legba/riscv64.patch

Update pavao to add support for riscv64.
Upstream: https://github.com/veeso/pavao/pull/12

addpatch: legba 0.8.0-1

---

typescript/increase-timeout.patch
typescript/remove-dprint.patch
typescript/remove-typescript.d.ts-baseline-check.patch
typescript/riscv64.patch

Remove dprint from TypeScript's dependencies and building processes since dprint itself and its native plugins (non-WebAssembly ones) relies on prebuilt binaries.
Attempt to enable dprint using https://github.com/dprint/dprint/pull/820 and disable its native Prettier plugins (only used to format YAML files) did not succeed, as [dprint-plugin-typescript (a WebAssembly plugin) produced inconsistent typescript.d.ts between riscv64 and x86_64](https://gist.github.com/hack3ric/bd7dd2364cadba4b01d6c834396ad06f). It is probably caused by immature Cranelift JIT implementation on RISC-V. The difference is only cosmetic though, therefore we can safely ignore the test for now.

addpatch: typescript 5.3.3-1

---

lychee/riscv64.patch

- Remove ring fix
- Remove upstreamed patch
- Don't vendor openssl in check() to avoid https://github.com/alexcrichton/openssl-src-rs/issues/222 , upstreamed: https://gitlab.archlinux.org/archlinux/packaging/packages/lychee/-/merge_requests/1

updpatch: lychee

---

atuin/riscv64.patch

Remove ring patch and increase SQLite initialization timeout in tests. Upstreamed to https://github.com/atuinsh/atuin/pull/1703.

updpatch: atuin 18.0.0-1

---

devtools-riscv64/PKGBUILD
devtools-riscv64/makepkg-riscv64.patch

Remove unsupported `-Wl,-z,pack-relative-relocs` from LDFLAGS.

upgpatch: devtools-riscv64 1:1.1.0+patch2-1

---

hip-runtime-amd/hip-runtime-amd-rv64gc.patch
hip-runtime-amd/riscv64.patch

- Backport https://github.com/ROCm/clr/commit/12461dbd6a26e02d03b572399b6d629f44b0a318
- Disable precompiled header which hardcoded x86 assembly
- Let `llvm-mc` use lp64d ABI
- I'd like to upstream later. This needs a better way and some discussion with upstream, like adding arch-specific flags.

addpatch: hip-runtime-amd 6.0.0-1

---

python-libtmux/riscv64.patch

Upstream actively rejected the patch: https://github.com/tmux-python/libtmux/pull/529#issuecomment-1951212668

addpatch: python-libtmux 0.31.0.post0-1

---

openmpi/riscv64.patch

Build after #3533 (hip-runtime-amd) builds.

upgpatch: openmpi 5.0.2-2

---

rocm-hip-sdk/riscv64.patch

Only enable the split packages we can have currently, as our `rocm-llvm` is broken and we will not have the full sdk for a while.
This can unblock packages like `openmpi`.

addpatch: rocm-hip-sdk 6.0.0-1

---

rocm-llvm/riscv64.patch
rocm-llvm/rocm-llvm-riscv-uleb128.patch

Backport several LLVM commits to fix roctracer linking issue:
```
ld.lld: error: CMakeFiles/MatrixTranspose_ctest.dir/MatrixTranspose.c.o:(.debug_loclists+0x15): unknown relocation (60) against symbol .LVL103
ld.lld: error: CMakeFiles/MatrixTranspose_ctest.dir/MatrixTranspose.c.o:(.debug_loclists+0x15): unknown relocation (61) against symbol .LVL102
ld.lld: error: CMakeFiles/MatrixTranspose_ctest.dir/MatrixTranspose.c.o:(.debug_loclists+0x22): unknown relocation (60) against symbol .LVL105
ld.lld: error: CMakeFiles/MatrixTranspose_ctest.dir/MatrixTranspose.c.o:(.debug_loclists+0x22): unknown relocation (61) against symbol .LVL104
ld.lld: error: CMakeFiles/MatrixTranspose_ctest.dir/MatrixTranspose.c.o:(.debug_loclists+0x2f): unknown relocation (60) against symbol .LVL107
ld.lld: error: …
```

updpatch: rocm-llvm 6.0.0-2

---

helm/add-riscv64-build.patch
helm/riscv64.patch

riscv go external linking needs CGO_ENABLED=1 explicitly.

updpatch: helm 3.14.0-1

---

blacklist.txt

It is not open-source. https://github.com/ROCm/ROCm/issues/1781

blacklist: add hsa-amd-aqlprofile-bin

---

luajit/riscv64.patch

- Specify how to choose commit from https://github.com/infiWang/LuaJIT. See diff for detail.
- Make package version not necessarily align with Arch x86_64, for RISC-V-related commits need to be included.

updpatch: luajit 2.1.1702376626-1

---

espflash/riscv64.patch

Fix rotten. Upstream fixed ring, but new version has not been released yet.

updpatch: espflash 2.1.0-2

---

qemu-user-blacklist.txt

Arch removed `check()`: https://gitlab.archlinux.org/archlinux/packaging/packages/neovim-qt/-/commit/55a4a0c73d9ddc308448eb449e7202d31927042b

qemu-user-blacklist: remove neovim-qt

---

go/riscv64.patch

Backport https://go-review.googlesource.com/c/go/+/567375
Fixes the following error for many packages:
```text
failed to find text symbol for HI20 relocation at 16198024 (f72988)
github.com/aws/aws-sdk-go/aws/endpoints.init: unsupported obj reloc 62 (R_RISCV_CALL)/8 to runtime.morestack_noctxt
failed to find text symbol for HI20 relocation at 16198076 (f729bc)
github.com/aws/aws-sdk-go/aws/endpoints.init: unsupported obj reloc 62 (R_RISCV_CALL)/8 to regexp.MustCompile
failed to find text symbol for HI20 relocation at 16198096 (f729d0)
github.com/aws/aws-sdk-go/aws/endpoints.init: unsupported obj reloc 62 (R_RISCV_CALL)/8 to runtime.gcWriteBarrier2
failed to find text symbol for HI20 relocation at 16198128 (f729f0)
github.com/aws/aws-sdk-go/aws/endpoints.init: unsupported obj reloc 62 …
```

upgpatch: go 2:1.22.0-1

---

mkinitcpio/riscv64.patch

- Remove merged pci controller patch.
- Backport to fix bash-completion test.

updpatch: mkinitcpio 38-4

---

openmpi/riscv64.patch

Disable also openucc/openucx. Revisit when openucx updated to 1.16.0 with riscv64 support.

updpatch: openmpi 5.0.2-6

---

intellij-idea-community-edition/intellij-riscv64.patch
intellij-idea-community-edition/riscv64.patch

- Add patch to
1. add riscv64 support
2. get rid of JBR(which doesn't provide riscv64 prebuilts) completely
- Build native binaryies and libaries manually since no prebuilts available.
- Tested on centiskorch

addpatch: intellij-idea-community-edition

---

pycharm-community-edition/intellij-riscv64.patch
pycharm-community-edition/riscv64.patch

This PR is nearly identical to #3596, except that
Arch is using bundled JBR explicitly, but we have to use system JDK.
Tested on centiskorch

addpatch: pycharm-community-edition 2023.3.4-1

---

helm/riscv64.patch

- Arch x86_64 PM added `export CGO_ENABLED=1`

updpatch: helm 3.14.2-1

---

k9s/riscv64.patch

need to explicitly set `CGO_ENABLED=1` under riscv for external linking

addpatch: k9s

---

electron28/riscv64.patch
electron29/riscv64.patch

Fix sha256sums[0] with VCS source checksumming,
hopefully in a way that it won't become rotten on every future release.

updpatch: electron{28,29}

---

gopass/riscv64.patch

- Remove CGO_ENABLED=0 from Makefile. Upstreamed to https://gitlab.archlinux.org/archlinux/packaging/packages/gopass/-/merge_requests/1.
- Drop `go get` as upstream released fix.

updpatch: gopass 1.15.12-1

---

cloudflared/riscv64.patch

- ~~Drop `-extldflags` since Go linker on riscv64 does not support most of it~~
- Fix LDFLAGS issue. Upstreamed to https://gitlab.archlinux.org/archlinux/packaging/packages/cloudflared/-/merge_requests/1.
- Remove unsupported `-race` from go test

addpatch: cloudflared 2024.1.5-1

---

lcdproc/riscv64.patch

- Update config.{sub,guess}. Upstreamed to https://github.com/lcdproc/lcdproc/issues/212.
- Disable LTO due to lto-wrapper fails on unreachable x86 inline assembly:
```
In function ‘port_out’,
inlined from ‘t6963_low_dsp_ready’ at t6963_low.c:181:3:
port.h:351:9: error: impossible constraint in ‘asm’
351 |         __asm__ volatile ("outb %0,%1\n"::"a" (val), "d"(port)
|         ^
make[4]: *** [/tmp/cca6TJKK.mk:2: /tmp/ccT5025n.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
```

addpatch: lcdproc 0.5.9-9

---

pnpm/add-pnpm-linux-riscv64.patch
pnpm/loosen-engine-restriction.patch
pnpm/riscv64.patch

- Lift pnpm engine restriction for now (>=8.6.10 -> >=8)
- Add @pnpm/linux-riscv64 package. To be upstreamed.

addpatch: pnpm 8.15.2-2

---

azure-cli/riscv64.patch

Python package `cryptography` and `bcrypt` need to build from source since there are no riscv64 prebuilt available.

addpatch: azure-cli 2.58.0-1

---

geogram/geogram-riscv64.patch
geogram/impl-riscv-spinlocks.patch
geogram/libf2c-riscv-fpu-control.patch
geogram/riscv64.patch

Updated patch from #2084
https://github.com/BrunoLevy/geogram/pull/138
Patches are sent to upstream except impl-riscv-spinlocks.patch, because upstream now uses a portable spinlock implementation.

addpatch: geogram 1.8.3-1

---

rnnoise/riscv64.patch

- DIsable x86 SIMD
- Backport [Fix compilation errors](https://gitlab.xiph.org/xiph/rnnoise/-/merge_requests/5)

addpatch: rnnoise 1:0.2-1

---

ldc/riscv64.patch

Remove `llvm16-libs` from makedepends. Also remove `lld` since it is not used.

updpatch: ldc 3:1.37.0-1.1

---

js91/riscv64.patch

Enable LLD and JIT. PGO is still disabled since Rust 1.62.0 from Rustup does not contain `profile_builtins`.

updpatch: js91 91.13.0-2

---

ollama/riscv64.patch

Use current master branch of https://github.com/chewxy/math32 where stub_riscv64.s is disabled, enabling Go fallback.

addpatch: ollama 0.1.31-1

---

valgrind/riscv64.patch

Actual version is not changed (3.20.0).
- Tidy up patches, removing multilib `provides`
- Backport https://github.com/petrpavlu/valgrind-riscv64/pull/16 to try to fix some runtime errors
- Drop Arch Linux's 3.22.0 patches since they can't be applied

updpatch: valgrind 3.22.0-3

---

curl/riscv64.patch

Valgrind tests all failed due to lack of glibc debuginfo.

addpatch: curl 8.7.1-5

---

bats/riscv64.patch

Test suite hangs reproducibly on some builders with all cores full. Limit job count to 4 to mitigate this.

addpatch: bats 1.11.0-2

---

code/riscv64.patch

- Part of the patch upstreamed to Arch: https://gitlab.archlinux.org/archlinux/packaging/packages/code/-/merge_requests/3
- Remove node-gyp debug rebuild hack as it appears to be no longer relevant

updpatch: code 1.88.1-1

---

glycin/riscv64.patch

Extend test timeout due to test containing a Rust crate building process.

addpatch: glycin 1.0.1-1

---

rust/riscv-target-abi-fix.patch
rust/riscv64.patch

Backport https://github.com/rust-lang/rust/pull/123612 to fix cross-language LTO issues in advance.

updpatch: rust 1:1.77.2-1

---

electron30/Debian-fix-rust-linking.patch
electron30/riscv64.patch

Adapted from electon29 patches, modifications:
- electron30/chromium124 riscv patches: https://github.com/riscv-forks/electron/compare/d0f27bca7638a027f3067bfcd957e6d96447b7cc...riscv-forks:electron:v30.0.0-riscv
- Drop depot_tools changes because it supports riscv now.

addpatch: electron30

---

gcc11/PKGBUILD
gcc11/c89
gcc11/c99
gcc11/msgfmt-ld-preload-libstdc++.patch

Based on previous gcc11 in [community]: https://github.com/archlinux/svntogit-community/blob/a4514ecab4f2915d5d02678b43712a758a7f6dbb/gcc11/trunk/PKGBUILD.
- Patches Makefile.{am,in} to fix libstdc++ issue instead of directly exporting LD_PRELOAD in PKGBUILD, since it breaks GCC
- libitm and libtsan not included
- Atomic binary patch not applied

addpkg: gcc11 11.4.0-1

---

python-numpy/riscv64.patch

- Backport https://github.com/numpy/numpy/pull/26301 to fix meson-python version bound
- Will be fixed in release v1.26.5

addpatch: python-numpy 1.26.4-2

---

python-zict/python-zict-fix-map-size.patch
python-zict/riscv64.patch

- Temporarily vendor `fix-map-size.patch` to fix rotten
- Waiting for https://github.com/dask/zict/pull/111

updpatch: python-zict 3.0.0-1

---

python-toolz/riscv64.patch

Pick https://github.com/pytoolz/toolz/pull/578 to fix `test_inspect_wrapped_property`

addpatch: python-toolz 0.12.1-2

---

glibc/riscv64.patch

Fix rotten patch. Needs to build on main branch:
https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/bedd2d1077b924843071787b546cf3c0457d80f7

updpatch: glibc 2.39+r52+gf8e4623421-1

---

glibc/riscv64.patch

fixpatch: glibc

---

deno/riscv64.patch

Fix rotten patch again since upstream does not seem to update Chromium's build/ directory. Reported to https://github.com/denoland/rusty_v8/issues/1476.

updpatch: deno 1.43.3-1

---

gcc/riscv64.patch

Fix rotten.
Built from main branch as there are additional fixes:
commit ae17258e5726c1d920ce504496688053ccd07a76 (HEAD -> main, origin/main, origin/HEAD)
Author: Frederik Schwan <freswa@archlinux.org>
Date:   Thu May 9 15:12:50 2024 +0200
fix rust compile missing crab1 binary
fixes #11
commit 2008427fb8f910027ecf23ee0f3d5a031566e8dc
Author: Frederik Schwan <freswa@archlinux.org>
Date:   Thu May 9 09:48:34 2024 +0200
remove duplicate m2.info from gcc
fixes #10
commit b6ae46d51dc01102eb2189e7ec01316b42e7a226 (tag: 14.1.1+r1+g43b730b9134-1)
Author: Frederik Schwan <freswa@archlinux.org>
Date:   Tue May 7 22:16:52 2024 +0200
upgpkg: 14.1.1+r1+g43b730b9134-1

updpatch: gcc 14.1.1+r1+g43b730b9134-1

---

python-leather/riscv64.patch

fix checksum mismatch error.
successfully passing the tests.

addpatch: python-leather 0.4.0

---

csound/riscv64.patch

Backport fixes of incompatible pointer types. Upstreamed to https://github.com/csound/csound/pull/1887.

addpatch: csound 6.18.1-4

---

goocanvas/goocanvas-fix-incompatible-pointer-types.patch
goocanvas/riscv64.patch

Fix incompatible-pointer-types.
GNOME upstream archived.
[Arch Linux issue](https://gitlab.archlinux.org/archlinux/packaging/packages/goocanvas/-/issues/1)

addpatch: goocanvas 3.0.0-5

---

nodejs/fix-trap-handler.patch
nodejs/riscv64.patch

- Backport https://github.com/nodejs/node/pull/52888
- Seems crash when building with gcc had fixed, use GCC again.

updpatch: nodejs 22.2.0-1

---

python-cvxopt/riscv64.patch

- override `SUITESPARSE_INC_DIR` to fix the wrong guess of the include dir as there is no `/usr/lib64` in riscv `filesystem` package
- Upstreamed: https://github.com/cvxopt/cvxopt/pull/251

addpatch: python-cvxopt

---

qt6-webengine/riscv64.patch

Update patch so that there's only one prepare function. (Arch added prepare())

updpatch: qt6-webengine 6.7.1-1

---

rocm-smi-lib/riscv64.patch

https://bugs.gentoo.org/918709

addpatch: rocm-smi-lib 6.0.2-1

---

browserpass/riscv64.patch

Enable CGO on riscv64.
[Upstream PR](https://github.com/browserpass/browserpass-native/pull/148)

addpatch: browserpass 3.1.0-2

---

netdata/riscv64.patch

[`libbpf`](https://github.com/netdata/libbpf/blob/89aecd2188fa525718cb88d2777ba0e08defd286/src/Makefile#L83-L100) is installed in `/usr/lib64` by default on 64-bit machines, but [`bundle-libbpf.sh`](https://github.com/netdata/netdata/blob/10dd98a45d23b0267bb78d5c224ed3f446fc535f/packaging/bundle-libbpf.sh#L24-L25) looks for `libbpf` in `/usr/lib` on non-x86_64 platforms.
Fix by specifying `LIBDIR=/usr/lib`.

addpatch: netdata 1.45.5-2

---

electron28/riscv64.patch
electron29/riscv64.patch
electron30/riscv64.patch

Fix rotten, and
python3.12 breaks gsutils: https://gitlab.archlinux.org/archlinux/packaging/packages/electron30/-/issues/1
Arch switched to use bundled vpython. But unfortunately cipd only provides bare vpython 3.11 for riscv64, which doesn't include the required wheels. Those wheels are installed via pip.

updpatch: electron{28,29,30}

---

linux/riscv64.patch
linux/timer-sun4i-d1-regression.patch

Apply a patch to fix regression of sifive-plic which broke Allwinner D1.

updpatch: linux 6.9.4.arch1-1

---

chromium/riscv64.patch

Update chromium riscv patch set for 126
(also used in electron31 here: https://github.com/riscv-forks/electron/commit/c8e556ad7bd753f53b685edcdff58ea4417c8e4c)
Notably,
- Update sandbox patch to latest version in upstream gerrit to fix crash due to sandbox blocked riscv_hwprobe. (Actually this should be fixed in version 125)
- Retrieve fix-rust-target.patch from elsewhere due to GitHub patch checksum mismatch
- Fix v8 performance regression: https://github.com/riscv-forks/electron/issues/1

updpatch: chromium 126.0.6478.55-1

---

electron31/Debian-fix-rust-linking.patch
electron31/riscv64.patch

Fix rotten PKGBUILD patch(compared to electron30).
electron RISC-V patch set changes from electron30: https://github.com/riscv-forks/electron/compare/7a826aeef60f0aceaad5cbbcf4e526324e72dcc5...v31.0.1-riscv

addpatch: electron31 31.0.1-1

---

sharutils/riscv64.patch

Fix outdated `config.guess`.  
https://savannah.gnu.org/support/index.php?111077  
https://savannah.gnu.org/support/index.php?111078  
The previous pr was closed by accident.

addpatch: sharutils 4.15.2-5

---

eslint/riscv64.patch

We need `python` for `node-gyp` to build [node-re2](https://github.com/uhop/node-re2) for riscv64.
(Currently still need some workaround to upstream CI/CD for prebuilt riscv64 release.)

updpatch: eslint 9.5.0-1

---

libwacom/riscv64.patch

Increase test timeout due to a large number of hardware models checked in test_udev_rules.py.

addpatch: libwacom 2.12.1-1

---

js80p/riscv64.patch

disable sse2 or avx for riscv64 explicitly

addpatch: js80p

---

av1an/riscv64.patch

Temporarily vendor `ffmpeg-the-third` to fix signedness problem: https://github.com/shssoichiro/ffmpeg-the-third/pull/64

addpatch: av1an 0.4.2-2

---

qt5-webengine/riscv-v8-security-backport.patch
qt5-webengine/riscv64.patch

- Fix rotten
- Manually backport the following security fix(it also breaks compilation):
- [regexp] Fix stack check in native code when interrupt was requested
- QT Backport: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/523701
- V8: https://chromium-review.googlesource.com/c/v8/v8/+/4971832 
- V8 RISC-V: https://chromium-review.googlesource.com/c/v8/v8/+/4975715
- Arch re-enabled LTO in https://gitlab.archlinux.org/archlinux/packaging/packages/qt5-webengine/-/commit/fad05d485fed0dba24b71b4987d33002cdfd356b , but LTO on riscv64 is causing an undefined reference linker error that I can't find where the undef sym is used. Thus LTO is disabled.

updpatch: qt5-webengine 5.15.17-5

---

emovix/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://sourceforge.net/p/movix/discussion/207428/thread/7c4f6c96a4/ .

addpatch: emovix 0.9.0-9

---

fastjar/riscv64.patch

The outdated `config.guess` and `config.sub` file issue was reported in https://savannah.nongnu.org/bugs/index.php?65966 .

addpatch: fastjar 0.98-7

---

flite/riscv64.patch

Outdated `config.guess` was reported in https://github.com/festvox/flite/issues/113.

addpatch: flite 2.2-2

---

iml/riscv64.patch

Outdated `config.guess` issue was reported to upstream via email.

addpatch: iml 1.0.5-4

---

termscp/bump-ring.patch
termscp/riscv64.patch

- Bump ring upstreamed to https://github.com/veeso/termscp/pull/265
- Bump pavao with riscv64 support, thanks moui0

addpatch: termscp 0.13.0-2

---

afl++/change-test-timeout.patch
afl++/riscv64.patch

Patched a test-case timeout.  
https://github.com/AFLplusplus/AFLplusplus/issues/2145  
If upstream has no response in 2 days, please review this patch.

addpatch: afl++ 4.21c

---

festival/riscv64.patch

Outdated `config.guess` and `config.sub` in `festival` and `speech_tools` were reported to Arch Linux.  
The mail list of upstream seems down for several years. (Original upstream: http://festvox.org/maillists.html, I have tried to join and send mail.)
Issue: 
https://github.com/festvox/festival/issues/74
https://github.com/festvox/speech_tools/issues/56

addpatch: festival 2.5.0-5

---

trurl/riscv64.patch

Tests with Valgrind cannot be run due to lack of debug symbols, either from debuginfod (which we don't have now) or -debug packages (which is not enabled during build).

addpatch: trurl 0.13-1

---

bfs/riscv64.patch

Not all posix_spawn() implementations use errno to report execv() failures from the child process, such as qemu-user, OpenBSD and HPPA.
Link: https://github.com/tavianator/bfs/commit/8c130ca0117fd225c24569be2ec16c7dc2150a13

addpatch: bfs 3.3.1

---

ext3grep/riscv64.patch

Fixed cannot guess build type issue.  
The upstream code was hosted on Google Code which was archived in 2016, so it was unable to report to upstream.

addpatch: ext3grep 0.10.2-7

---

coin-or-data-sample/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://github.com/coin-or-tools/Data-Sample/issues/4 .

addpatch: coin-or-data-sample 1.2.12-2

---

protobuf/riscv64.patch

Temporarily use PyPI's source package to build python-protobuf instead of using Bazel to prevent loop makedepends. Will be reverted once Bazel is built (see https://github.com/bazelbuild/bazel/issues/23018)

updpatch: protobuf 27.2-1

---

abseil-cpp/riscv64.patch

- Backport two commits:
1. remove usage of rdcycle, which has become a privileged instruction since linux 6.6
2. Fix a test failure involving negative NaN
- Test AbslDeathTest/FailureSignalHandlerDeathTest.*/SIGBUS is flaky. The sigbus hander sometimes segfaults, which can't be easily reproduced under gdb. It appears that this test is no longer flaky if I disable all Arch specific compiler flags.

addpatch: abseil-cpp

---

percona-server/riscv64.patch

- Use generic memory barrier provided by upstream
- Port fix for missing unistd.h for `getpid()`; not reproducible on x86_64.

updpatch: percona-server 8.3.0_1-2

---

neovide/riscv64.patch

Skia fixes upstreamed to Arch. Need to revisit https://skia-review.googlesource.com/c/skia/+/765896 later.

updpatch: neovide 0.13.3-2

---

libnova/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://sourceforge.net/p/libnova/bugs/24/ .

addpatch: libnova 0.15.0-4

---

wireguard-vanity-address/riscv64.patch

Upgrade outdated libc, reported to https://github.com/warner/wireguard-vanity-address/issues/30.

addpatch: wireguard-vanity-address 0.4.0-3

---

libmng/riscv64.patch

Outdated `config.guess` issue couldn't be reported to upstream. Their GitHub repo is archived(https://github.com/LuaDist/libmng), SourceForge issue tracker is no longer available(http://sourceforge.net/tracker/?func=add&group_id=5635&atid=205635). and their website is empty.

addpatch: libmng 2.0.3-4

---

libidl2/riscv64.patch

Outdated `config.guess` issue can't be reported to upstream, gnome. This project is no longer available on their GitLab.

addpatch: libidl2 0.8.14-7

---

liblqr/riscv64.patch

Outdated `config.guess` issue was reported to upstream in http://liblqr.wikidot.com/forum/t-16886430/outdated-config-guess-and-config-sub-file-in-the-source-of-l .

addpatch: liblqr 0.4.2-4

---

libgovirt/riscv64.patch

Make patch rot less. Still waiting for new release.

updpatch: libgovirt 2:0.3.9-2

---

highway/riscv64.patch

Backport https://github.com/google/highway/commit/c95cc0237d2f7a0f5ca5dc3fb4b5961b2b1dcdfc into 1.2.0 to build.

updpatch: highway 1.2.0-1

---

rust/pin-cc-to-1-0-77.patch
rust/riscv64.patch

- Add back previously removed pin-cc-to-1-0-77.patch(and fix rotten).
- Remove this patch once https://github.com/rust-lang/rust/pull/122504 land in 1.80
- This package should be built from main branch and after wasi-libc 1:0+374+9e8c5423-2 is built.

updpatch: rust 1:1.79.0-3

---

ext4magic/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://sourceforge.net/p/ext4magic/tickets/16/ .

addpatch: ext4magic 0.3.2-5

---

libsmf/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://github.com/stump/libsmf/issues/13 .

addpatch: libsmf 1.3-12

---

fuseiso/riscv64.patch

Outdated `config.guess` issue was reported to upstream in https://sourceforge.net/p/fuseiso/patches/3/ .

addpatch: fuseiso 20070709-9

---

dart-bootstrap/DEPS.patch
dart-bootstrap/PKGBUILD
dart-bootstrap/dart-riscv-no-cross.patch
dart-bootstrap/package_config.json

For bootstrapping dart, which makedepends on itself.
The only part that requires dart is generating package_config.json. Thus package_config.json is generated on x86_64, added to source.
dart-riscv-no-croos.patch is needed because gcc package doesn't provide riscv64-linux-gnu-ar but riscv64-linux-gnu-gcc-ar.

addpkg: dart-bootstrap 3.4.4-1

---

musl/riscv64.patch

- Remove musl-riscv64 package as we are on native riscv64.
- There's no x86_64-linux-gnu-gcc package so musl-x86_64 is not built for now.

addpatch: musl 1.2.5-2

---

libwnck/riscv64.patch

Configure error `cannot guess build type; you must specify one` was not reported to upstream because it was replaced by libwnck3.

addpatch: libwnck 2.31.0-4

---

gnujump/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported in https://savannah.gnu.org/bugs/index.php?66028 .

addpatch: gnujump 1.0.8-7

---

libabw/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported in https://bugs.documentfoundation.org/show_bug.cgi?id=162204 .

addpatch: libabw 0.1.3-4

---

gtkmm/riscv64.patch

Configure error `cannot guess build type; you must specify one` was not reported to upstream because it was replaced by gtkmm4.

addpatch: gtkmm 2.24.5-5

---

libgringotts/riscv64.patch

Configure error `cannot guess build type; you must specify one` was not reported to upstream because can't get contact.

addpatch: libgringotts 1.2.1-15

---

cargo-deny/riscv64.patch

Increase test timeout to make build pass.
I have opened a PR upstream to add an environment variable to control the test timeout and asked if they can increase the timeout: https://github.com/EmbarkStudios/cargo-deny/pull/683. But it need some time for them to respond and make a new release. So I think it would be helpful to make a patch here and then we can estimate the appropriate timeout.
The 160s timeout is just an arbitrary large enough number I choose.

addpatch: cargo-deny

---

gcc/riscv64.patch

Pick a8f1b00ed69810ce7f000d385a60e148d0228d48 (tree-optimization/116057 - wrong code with CCP and vector CTORs) from releases/gcc-14 branch to fix https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116057 , which fixes miscompilation in V8.
It's serveral weird V8 bugs I reported last year:
- https://issues.chromium.org/issues/42203868
- https://issues.chromium.org/issues/42204492

updpatch: gcc 14.1.1+r58+gfc9fb69ad62-1

---

libpagemaker/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported to upstream in https://bugs.documentfoundation.org/show_bug.cgi?id=162311 .

addpatch: libpagemaker 0.0.4-4

---

guichan/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported to upstream in https://github.com/darkbitsorg/guichan/issues/3 .

addpatch: guichan 0.8.2-8

---

apcupsd/riscv64.patch

Configure error `cannot guess build type; you must specify one` was not reported due to the inability to contact upstream.

addpatch: apcupsd 3.14.14-8

---

dgen-sdl/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported to upstream in https://sourceforge.net/p/dgen/bugs/28/ .

addpatch: dgen-sdl 1.33-4

---

libstaroffice/riscv64.patch

Configure error `cannot guess build type; you must specify one` was reported to upstream in https://github.com/fosnola/libstaroffice/issues/10 .

addpatch: libstaroffice 0.0.7-3

---

sugar-toolkit-gtk3/riscv64.patch

Backport upstream fix https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/282ec05f655356bd53c2d812ed1b520696a8d4c8; flagged as outdated in Arch.

addpatch: sugar-toolkit-gtk3 0.120-2

---

tiny/riscv64.patch

Upgrade ring to 0.17, upstreamed to https://github.com/osa1/tiny/pull/433.

addpatch: tiny 0.12.0-3

---

ldc/riscv64.patch

LLVM 18 rebuild; also built successfully using lld so re-enable it as well.

updpatch: ldc 3:1.39.0-1

---

python-mitmproxy-rs/riscv64.patch

Upgrade ring to 0.17, upstreamed to https://github.com/mitmproxy/mitmproxy_rs/pull/168.

updpatch: python-mitmproxy-rs 0.6.3-1

---

atuin/riscv64.patch

This commit increases the SQLite operation timeout to 2s to make the test pass. Details see upstream: https://github.com/atuinsh/atuin/pull/2337.

updpatch: atuin 18.3.0-1

---

libfreehand/riscv64.patch

Fixed cannot guess build type issue, and reported to https://bugs.documentfoundation.org/show_bug.cgi?id=162393 .

addpatch: libfreehand 0.1.2-5

---

lidia/riscv64.patch

Fixed cannot guess build type issue, and reported to https://github.com/mkoeppe/LiDIA/issues/12 .

addpatch: lidia 2.3.0-5

---

gcc/riscv64.patch

- Drop cherry pick because 14.2.1 already includes it.
- Make the patch less likely to rot when upstream update pkgver.

updpatch: gcc 14.2.1+r32+geccf707e5ce-1

---

gmtk/riscv64.patch

Fixed cannot guess build type issue.  
The upstream code was hosted on Google Code which was archived in 2016, so it was unable to report to upstream.

addpatch: gmtk 1.0.9-7

---

qemu-user-blacklist.txt

absl_symbolize_test fails only in qemu-user
```
58/221 Testing: absl_symbolize_test
58/221 Test: absl_symbolize_test
Command: "/build/abseil-cpp/src/abseil-cpp-20240722.0/build/bin/absl_symbolize_test"
Directory: /build/abseil-cpp/src/abseil-cpp-20240722.0/build/absl/debugging
"absl_symbolize_test" start time: Aug 11 07:03 CEST
Output:
----------------------------------------------------------
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1723352599.379092     988 symbolize_test.cc:170] Check failed: symbol != nullptr ((null) vs. (null)) TestWithReturnAddress failed
*** Check failure stack trace: ***
@     0x7a440ac1f306  (unknown)
@     0x7a440ac1fcbc  (unknown)
@     0x555555562bd0  (unknown)
@     0x55555555b4b4  (unknown)
@ …
```

qemu-user-blacklist.txt: add abseil-cpp

---

nominatim-ui/longer-timeout.patch
nominatim-ui/riscv64.patch
qemu-user-blacklist.txt

Fix the check of nominatim-ui.  
The test code needs to launch a chromium which cannot run on qemu-user.  
The timeout is too short for RISC-V devices with extremely low performance, it might be discussed at https://github.com/osm-search/nominatim-ui/issues/253 .

addpatch: nominatim-ui 3.5.3-1

---

qt6-webengine/riscv64.patch

Pick up some chromium/v8 patches to
- Fix v8 performance regression (https://github.com/riscv-forks/electron/issues/1)
- Fix rdcycle SIGILL on linux >= 6.6 (https://github.com/riscv-forks/electron/issues/2)
There's no riscv specific security patch needs backporting for this release.
Fix rotten and use nodejs in makedepends again because it seems nodejs no longer hangs when building this package in qemu.

updpatch: qt6-webengine 6.7.2-2

---

glibc/riscv64.patch

Fix rotten and prevent it from rotting when Arch only updates pkgver.

updpatch: glibc 2.40+r16+gaa533d58ff-2

---

wdiff/riscv64.patch

This issue was reported to https://savannah.gnu.org/bugs/index.php?66092 .

addpatch: wdiff 1.2.2-5

---

mkinitcpio-busybox/riscv64.patch

config file for busybox don't need patching. PKGBUILD update the CONFIG_EXTRA_CFLAGS with the safeflags.

updpatch: mkinitcpio-busybox 1.36.1-1

---

laszip2/riscv64.patch

The outdated configure file issue was not reported because the upstream won't maintain outdated 2.2.0, the active version is 3.4.3.

addpatch: laszip2 2.2.0-2

---

mp3unicode/riscv64.patch

The outdated configure file issue was reported to https://github.com/alonbl/mp3unicode/issues/4 .

addpatch: mp3unicode 1.2.1-6

---

libgfshare/riscv64.patch

The outdated configure file issue couldn't be reported because their homepage was down.

addpatch: libgfshare 2.0.0-4

---

lbreakout2/riscv64.patch

The outdated configure file issue was reported to https://sourceforge.net/p/lgames/bugs/110/ .

addpatch: lbreakout2 2.6.5-4

---

libftdi-compat/riscv64.patch

The outdated configure file issue couldn't be reported because it was replaced by libftdi.

addpatch: libftdi-compat 0.20-9

---

xdg-desktop-portal-cosmic/riscv64.patch

Use gnu ld to workaround lld linker failure (https://archriscv.felixc.at/.status/logs/xdg-desktop-portal-cosmic/xdg-desktop-portal-cosmic-1.0.0.alpha.1-1.log)
That looks like a bug in lld but I am unsure.

addpatch: xdg-desktop-portal-cosmic 1.0.0.alpha.1-1

---

cosmic-settings/remove-generator-075.diff
cosmic-settings/riscv64.patch

Backport part of https://github.com/pop-os/cosmic-settings/commit/3ec53d7f8a7fa8cdb0a6e51dc9d94fe513518991 to get rid of dependency generator 0.7.5, which doesn't support riscv64 until 0.8.0

addpatch: cosmic-settings 1.0.0.alpha.1-1

---

kexec-tools/add-riscv64-support.patch
kexec-tools/riscv-hotplug.patch
kexec-tools/riscv64.patch

- Vendor add-riscv64-support.patch due to unreliable download
- Work around `arch_do_exclude_segment` on RISC-V, taken from openSUSE

updpatch: kexec-tools 2.0.29-2

---

libinsane/riscv64.patch

Disable Valgrind tests due to lack of debuginfod.

addpatch: libinsane 1.0.10-2

---

nix-busybox/riscv64.patch

- Remove CBQ support because 6.8 kernel header removed it
- https://bugs.busybox.net/show_bug.cgi?id=15931
- Arch doesn't need this because they are still using 4.19 musl kernel headers

updpatch: nix-busybox 1.35.0-2

---

llvm/JITLink-Always-unmap-standard-segments-in-InProcessM.patch
llvm/JITLink-RISCV-Use-hashmap-to-find-PCREL_HI20-edge-78.patch
llvm/riscv64.patch

- Backport 2 patches for fixing LLVMPipe ORCJIT; see https://github.com/AOSC-Dev/aosc-os-abbs/commit/a9a7ce6a740a4471e1562a1a50ae54cc3fbabec6
- Temporary checksum fix; upstreamed to https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/merge_requests/2

addpatch: llvm 18.1.8-4

---

radeontool/riscv64.patch

The outdated configure file issue was not reported because it was abandoned and the website was down.

addpatch: radeontool 1.6.3-5

---

box2d/remove-unsupported-cpu.patch
box2d/riscv64.patch

See https://github.com/erincatto/box2d/pull/790.
Also see https://github.com/hack3ric/box2d/tree/riscv for RISC-V pause implementation on future versions of Box2D, and possibly more; current pause is implemented by SIMDe.

addpatch: box2d 3.0.0-1

---

sdl_ttf/riscv64.patch

Configurate failed.  
Not reported, it was replaced by sdl2_ttf.

addpatch: sdl_ttf 2.0.11-6

---

arti/riscv64.patch
qemu-user-blacklist.txt

check phase failed dut to
```log
test channel::test::check_match ... ok
test circuit::sendme::test::recvwindow ... ok
test circuit::sendme::test::sendwindow_bad_put ... ok
test circuit::halfstream::test::halfstream_sendme ... ok
test circuit::halfstream::test::halfstream_other ... ok
test circuit::sendme::test::sendwindow_basic ... ok
test circuit::halfstream::test::halfstream_connected ... ok
test circuit::halfstream::test::halfstream_data ... ok
test circuit::sendme::test::sendwindow_erroring ... ok
test channel::circmap::test::circmap_basics ... ok
test circuit::sendme::test::what_counts ... ok
test circuit::streammap::test::test_wrapping_next_stream_id ... ok
test circuit::streammap::test::streammap_basics ... ok
qemu-riscv64-static: QEMU internal SIGSEGV {code=MAPERR, addr=0x20} …
```

addpatch: arti 1.2.7-1, qemu-user-blacklist.txt: add arti

---

sdl_net/riscv64.patch

Configuration failed.  
Not reported, it was replaced by sdl2_net.

addpatch: sdl_net 1.2.8-6

---

scponly/riscv64.patch

Configure failed.  
Reported in https://sourceforge.net/p/scponly/bugs/6/ .

addpatch: scponly 4.8-12

---

qemu-user-blacklist.txt

qemu-user does not handle prlimit64 with second argument set to RLIMIT_AS
correctly, failling `breezy/tests/blackbox/test_big_file.py`.
Reference: https://gitlab.com/qemu-project/qemu/-/blob/v9.1.0/linux-user/syscall.c?ref_type=tags#L13322-13351

qemu-user-blacklist.txt: add breezy

---

lbzip2/riscv64.patch

Arch Linux takes this package's source from [Debian](https://gitlab.archlinux.org/archlinux/packaging/packages/lbzip2/-/blob/main/PKGBUILD?ref_type=heads#L14)
Upstream is here: https://github.com/kjn/lbzip2/tree/master/build-aux , but it doesn't contains config.{guess, sub} at all.
I wonder where should I report it.

addpatch: lbzip2-2.5-6

---

rlog/riscv64.patch

[Upstream](https://code.google.com/archive/p/rlog/issues) has been inactive for a long time, and couldn't create issue.

addpatch: rlog 1.4-10

---

gd/riscv64.patch

Tests still fail at the moment, but x86_64 fails the same way: https://gitlab.archlinux.org/archlinux/packaging/packages/gd/-/issues/1

updpatch: gd 2.3.3-8

---

rocfft/riscv64.patch

Use `ld.bfd` to workaround `ld.lld: error: section size decrease is too large`

addpatch: rocfft 6.0.2-1

---

tracexec/riscv64.patch

- Fix rotten
- Use my fork of seccompiler for enabling seccomp-bpf feature, previous upstream PR: https://github.com/rust-vmm/seccompiler/pull/72

updpatch: tracexec 0.6.0-1

---

rocblas/riscv64.patch

The `msgpack-cxx` library is renamed since 6.0.0
https://gitlab.archlinux.org/archlinux/packaging/packages/rocblas/-/merge_requests/1

addpatch: rocblas 6.0.2-1

---

presenterm/riscv64.patch

Without a prebuilt sixel cargo package on riscv, building needs a libsixel.

addpatch: presenterm 0.8.0-2

---

yubico-c/riscv64.patch

Yubico-c has no newer release, arch linux still use the latest release in 2015, according to their [document](https://developers.yubico.com/yubico-c/), developers should pull from the latest commit, I have tried to [ask for a newer release](https://github.com/Yubico/yubico-c/issues/28), but no response. So we may have a vendor patch for that.

addpatch: yubico-c 1.13-7

---

yubico-c-client/riscv64.patch

The package was replaced by tie new api of Yubico: https://developers.yubico.com/OTP/ .

addpatch: yubico-c-client 2.15-6

---

dart/riscv64.patch

Fix rotten and make it less likely to rot

updpatch: dart 3.5.2-1

---

onnxruntime/riscv64.patch

Remove hardware support and AVX variants. ROCM support requires at least rccl and rocm-hip-sdk. Revisit once we have them.

addpatch: onnxruntime 1.18.0-3

---

electron28/riscv64.patch
electron29/riscv64.patch
electron30/riscv64.patch
electron31/riscv64.patch
electron32/riscv64.patch

- Sync 'is_clang=true' to old electrons, to work around (possibly a regression in gnu ld) relocation truncated to fit.
- Force override electron version with pkgver to fix https://github.com/riscv-forks/electron-riscv-releases/issues/4
- This is because electron determines its version by finding the nearest git tag. But in riscv fork, the upstream tags are not synced back.

updpatch: electron{28,29,30,31,32}

---

termusic/riscv64.patch

Without a prebuilt sixel cargo package on riscv, building needs a libsixel.

addpatch: termusic 0.9.1-1

---

dvdbackup/riscv64.patch

Upstream: https://bugs.launchpad.net/dvdbackup/+bug/2080338

addpatch: dvdbackup 0.4.2-7

---

freealut/riscv64.patch

We can patch this before https://gitlab.archlinux.org/archlinux/packaging/packages/freealut/-/issues/1 .

addpatch: freealut 1.1.0-9

---

colorhug-client/riscv64.patch

The upstream repo was archived in 2020. https://github.com/hughski/colorhug-client

addpatch: colorhug-client 0.2.8-4

---

drawio-desktop/riscv64.patch

The patch is similar to other electron applications.

addpatch: drawio-desktop 24.7.8-1

---

lxappearance-obconf/riscv64.patch

Old config.guess not reported due to outdated archlinux-packaging version.

addpatch: lxappearance-obconf 0.2.3-4

---

libtiff4/riscv64.patch

No reported to upstream, it was replaced by `libtiff`.

addpatch: libtiff4 3.9.7-6

---

onnxruntime/riscv64.patch

Enable -opt variant for RVV. Experimental.

updpatch: onnxruntime 1.18.0-3.1

---

nodejs/riscv64.patch
nodejs/v8-disable-trap-handler.patch

Disable v8's trap handler[^1] to workaround ENOMEM on sv39 systems[^2].
v8's OOB trap handler for wasm tries to allocate a 10 GB guard region[^3], but unfortunately on sv39 systems we only have 256GB virtual memory for userspace, which is usually already exhausted by the node process and leads to `WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance` errors
There is a second bug in [^2], which needs to be investigated separately and disabling trap handler won't fix it.
[^1]: https://chromium-review.googlesource.com/c/v8/v8/+/5227604
[^2]: https://github.com/riscv-forks/electron/issues/3#issuecomment-2391689815
[^3]: https://github.com/nodejs/node/blob/09a8440b45f69651ff52110cb1bc2dde9e14e2e8/deps/v8/src/objects/backing-store.cc#L38

updpatch: nodejs 22.9.0-1

---

lorem/longer-timeout.patch
lorem/riscv64.patch

Upstream: https://gitlab.gnome.org/World/design/lorem/-/issues/17

addpatch: lorem 1.4-2

---

qemu/riscv64.patch

Disable qemu-vmsr-helper package, which is not built for riscv64 and only supports intel host cpu: https://www.qemu.org/docs/master/specs/rapl-msr.html#current-limitations

updpatch: qemu 9.1.0-2

---

maxima/riscv64.patch

Fix outdated config.{guess,sub}, reported here: https://sourceforge.net/p/maxima/bugs/4382/
Disable sbcl backend. There are problems when building with sbcl backend enabled, like:
- Interactive questions
- A REPL pops up several times
I suspect this is sbcl bug on riscv64.

addpatch: maxima 5.47.0-14

---

fricas/riscv64.patch

Outdated config.guess issue reported: https://github.com/fricas/fricas/issues/182  
Use `clisp` instead of `sbcl`.

addpatch: fricas 1.3.11-1

---

sbcl/riscv-qemu-user.patch
sbcl/riscv64.patch

Add fix for sbcl's workaround for riscv qemu-user from opensuse[^1].
This fix [^2] in qemu-user.
[^1]: https://build.opensuse.org/projects/openSUSE:Factory:RISCV/packages/sbcl/files/riscv.patch?expand=1
[^2]: https://archriscv.felixc.at/.status/log.htm?url=logs/cl-alexandria/cl-alexandria-1.4.r17.g2f39fbf-3.log

addpatch: sbcl

---

zed/riscv64.patch

Use forked ring 0.16 since the dependencies are complicated and hard to upgrade to ring 0.17.

addpatch: zed 0.155.2-3

---

mangohud/riscv64.patch

Backport https://github.com/flightlessmango/MangoHud/commit/d0894fff38e033f5f0074efa975cfbe0069035b1 as requested.

updpatch: mangohud 0.7.2-2

---

criu/riscv64-support.patch
criu/riscv64.patch

The patch is fetched from https://github.com/Cryolitia-Forks/criu/compare/c2b48ff423aa663b3534a5ba96907366e4c1b408..fcac93c764fac7e283e33ac4cb4d9c95770c444a.patch
Originally based on https://github.com/checkpoint-restore/criu/pull/2234 , rebasing the PR on v4.0
- Change return page size to unsigned long for riscv64 \
Link: https://github.com/checkpoint-restore/criu/commit/28adebefb759306959df41acbe9cb74bfebd03ea
- dump+restore: Implement membarrier() registration c/r. for riscv64 \
Link: https://github.com/checkpoint-restore/criu/commit/e07155e194c914400c5dc574820d726a4d8f9fbd
- include: don't use GCC's __builtin_ffs on riscv64 to fix link failure

updpatch: criu 4.0

---

bitwarden/bitwarden-napi-riscv64.patch
bitwarden/riscv64.patch

- Fix rotten patches
- Remove npm lock file to workaround buggy `overrides`: https://github.com/npm/cli/issues/5443 https://github.com/npm/cli/issues/7660
- Add cargo fetch to `prepare()`

updpatch: bitwarden 2024.8.1-1

---

bitwarden/cl-ppcre/riscv64.patch

Bootstrap cl-ppcre by building without cl-unicode. Tests are disabled because run-tests.lisp requires cl-unicode.

addpatch: cl-ppcre 2.1.2-1

---

projectm/riscv64.patch

This PR should fix `dpf-plugins` building fault: https://archriscv.felixc.at/.status/log.htm?url=logs/dpf-plugins/dpf-plugins-1.7-2.log , although `projectm` itself can be built successfully with current riscv64 patch.
The current patch uses `autoreconf` to update the outdated `config.{guess,sub}` , while also updating `libtool` at the same time, which breaking the behavior of  `sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool` in the original PKGBUILD, which causes projectm to be overlinked, more specifically linking `libprojectm.so` to `libqt5gui.so` and `libqt5opengl.so`, meanwhile `projectm`'s depends not containing `qt5-base`.
Although, the `dpf-plugins` doesn't depend on `qt5-base` but `projectm`, then, boom.
We believe in that just update the `config.{guess,sub}` is enough …

fixpatch: projectm 3.1.12

---

stalwart-mail-server/riscv64.patch

Fix ring 0.16.20.
Two dependencies pull in ring 0.16.20, which has updated ring to 0.17 but no release is made yet:
- https://github.com/hickory-dns/hickory-dns/blob/main/Cargo.lock#L1663-L1668
- https://github.com/inejge/ldap3/blob/master/Cargo.toml#L33

addpatch: stalwart-mail-server 0.9.2-1

---

systemd/riscv64.patch

updpatch: systemd 256.7-1

---

rust/disable-f16-f128.diff
rust/riscv-musl-crt-default-static.diff
rust/riscv64.patch

Musl Patch
==========
riscv64gc-unknown-linux-musl gets promoted to tier 2 and `crt_static_default` is updated to false in https://github.com/rust-lang/rust/pull/122049, which triggers https://github.com/rust-lang/rust/issues/82521#issuecomment-786093169 when building stage2 library artifacts
(riscv64gc-unknown-linux-gnu -> riscv64gc-unknown-linux-musl).
I patched it to re-enable `crt_static_default` for `riscv64gc-unknown-linux-musl` to fix the build and align with the behavior on x86 Arch Linux, where `rust-musl` defaults to statically link musl.
Wasm compiler_builtins bug
==========================
Wasm compiler_builtins rlib from built `rust-wasm` package includes objects for host architecture(riscv64 in our case, and x86_64 for x86 Arch Linux). This is not reproducible for toolchains …

updpatch: rust 1:1.82.0-1

---

librustls/riscv64.patch

Pregenerated bindings for aws-lc-sys are not available for riscv64. Add make dependencies for binding generation.

addpatch: librustls 0.14.0-1

---

electron33/Debian-fix-rust-linking.patch
electron33/riscv64.patch

Changes at riscv-forks/electron:
Update patchset for electron33(chromium 130):
https://github.com/riscv-forks/electron/commit/c7dff70ce824285cf97ac77bbd9cc9a46580efd0
Packaging changes compared to electron 32:
Use native rollup instead of wasm rollup, to workaround wasm errors like:
```
RuntimeError: Command '/build/electron33/src/src/third_party/node/linux/node-linux-x64/bin/node /build/electron33/src/src/third_party/node/node_modules/@rollup/wasm-node/dist/bin/rollup /build/electron33/src/src/out/Release/gen/third_pa rty/lit/v3_0/lit.js --format esm --dir /build/electron33/src/src/out/Release/gen/third_party/lit/v3_0/bundled --entryFileNames [name].rollup.js --sourcemap --sourcemapExcludeSources --config ../../third_party/lit/v3_0/rollup.config.mjs'
failed …
```

addpatch: electron33 33.0.0-1

---

uv/riscv64.patch
uv/uv-platform-arch-riscv64.patch

Before:
```bash
> uv python list
> uv pip list
error: No virtual environment or system Python installation found; run `uv venv` to create an environment
```
After:
```bash
> uv python list
cpython-3.12.7-linux-riscv64-gnu    /usr/bin/python3.12
cpython-3.12.7-linux-riscv64-gnu    /usr/bin/python3 -> python3.12
cpython-3.12.7-linux-riscv64-gnu    /usr/bin/python -> python3
```
----
- May fix [check failure of `python-build`](https://archriscv.felixc.at/.status/log.htm?url=logs/python-build/python-build-1.2.2-1.log)
```
==> Starting check()...
...
process = <Popen: returncode: 2 args: ['/usr/bin/uv', 'pip', 'install', 'test-flit @ f...>
stdout = b'', stderr = b'error: No virtual environment found\n', retcode = 2
```

addpatch: uv 0.4.25-1

---

sg2042-blacklist.txt

gnutls' test-pthread-rwlock time outs on sg2042. Not sure if increasing timeout here is feasible since it's exponentially slower as more cores are used.

sg2042-blacklist: add gnutls and fix filename

---

fceux/riscv64.patch

1. The x265 updates its API in 4.0, and the new API breaks the compatibility \
https://bitbucket.org/multicoreware/x265_git/commits/c69c113960834400545bc4bce2830ff51dcb86b3
3. Arch Linux Package add a patch to pass compile but it's wrong and incomplete, which breaks over riscv64 build but not x86_64 \
https://gitlab.archlinux.org/archlinux/packaging/packages/fceux/-/commit/617d6299d83ad54c105c457f151ee340a6c71de8
5. The homebrew's opened a PR on fceux but also wrong and no maintainer response it \
https://github.com/TASEmulators/fceux/pull/766
7. The VLC implement the compatibility with the new API \
https://code.videolan.org/videolan/vlc/-/merge_requests/6167
9. I write a patch with my personal understanding with VLC's code, where the patch in the PR is from \ …

updpatch: fceux 2.6.6-3

---

python-pytorch/riscv64.patch

- Only keep the base python-pytorch package, disabling other variants that uses mkl, cuda, rocm.
- Backport https://github.com/shibatch/sleef/pull/602 that fixes RVV check for gcc 13.

addpatch: python-pytorch 2.5.1-3

---

onnxruntime/riscv64.patch

onnxruntime_USE_MPI was guarded with onnxruntime_USE_NCCL before, which is no longer the case now. The MPI path depends on AVX instrinsics for fp16, so we have to disable it for now.

updpatch: onnxruntime 1.19.2-2

---

java-rxtx/riscv64.patch

Even though fix-riscv64-build.patch is applied and sys/io.h is not included, src/RawImp.c still calls its functions but left unused. So we simply allow implicit function declaration to let linker ignore it.

updpatch: java-rxtx 2.2pre2-10

---

eslint/riscv64.patch

updpatch: eslint 9.15.0-1

---

oha/riscv64.patch

Add cmake and clang for aws-lc-sys crate to build from source.

updpatch: oha 1.4.7-1

---

ollama/ollama-riscv-support.patch
ollama/riscv64.patch

Refreshed upstream patch. CUDA and ROCm support have been split into individual packages on Arch x86.

updpatch: ollama 0.4.2-1

---

mongo-c-driver/riscv64.patch
qemu-user-blacklist.txt

The test timeout will only randomly occurs on qemu-user, for example, it once costs 51.17 sec on Intel Ultra 9 185H. On both SG2042 and LicheePi 4A, it finished in just several seconds.

addpatch: mongo-c-driver 1.29.0, qemu-user-blacklist: add mongo-c-driver

---

sh4d0wup/riscv64.patch

cmake is needed to generate bindgen for non pre-generated platforms.
1. https://github.com/aws/aws-lc-rs/blob/96484642d4f4b4c3572870629c6c830364f66483/aws-lc-sys/README.md#pregenerated-bindings-availability

updpatch: sh4d0wup 0.10.0

---

linux/riscv64.patch

This will allow users to use dt overlays more easily.
see https://patchwork.kernel.org/project/linux-kbuild/patch/20171214151240.14555-1-a.heider@gmail.com/ and https://github.com/archlinuxarm/PKGBUILDs/blob/76ffc6601776f8a8c15c6742467fe20e958d8ce6/core/linux-aarch64/PKGBUILD#L66
I haven't really tested if this works, hopefully someone can take a look :)
cc @felixonmars

Generate symbols for dtbs to support overlays

---

system76-scheduler/riscv64.patch

Bump generator crate which supports riscv64 in 0.8.x. Upstreamed to https://github.com/pop-os/system76-scheduler/pull/120.

addpatch: system76-scheduler 2.0.2-1

---

hedgedoc/riscv64.patch

- Switch to Node.js v20 because Hedgedoc uses Yarn v4.
- Add some makedepends for building native module

addpatch: hedgedoc 1.9.9-2

---

vamp-plugin-sdk/riscv64.patch

Ranlib might race with gcc. Limit make jobs to 1 to solve it.
Meanwhile I have opened an upstream PR to fix it: https://github.com/vamp-plugins/vamp-plugin-sdk/pull/16

addpatch: vamp-plugin-sdk 2.10.0-3

---

bitwarden-cli/riscv64.patch

Arch upstream uses system libargon2 now.

updpatch: bitwarden-cli 2024.11.0-3

---

python-flask-principal/riscv64.patch
python-flask-principal/sphinx-8.x.patch

Remove previous patch, new Sphinx 8.x compatibility patch upstreamed to https://github.com/pallets-eco/flask-principal/pull/109.

updpatch: python-flask-principle 0.4.0-11

---

azcopy/riscv64.patch

Fork https://github.com/wastore/keyctl to add riscv64 support.

addpatch: azcopy 10.27.1-1

---

scx-scheds/riscv64.patch

Fix non-x86 build, upstreamed to https://github.com/sched-ext/scx/pull/1005.

addpatch: scx-scheds 1.0.6-5

---

dpdk/riscv64.patch

RISC-V specific fast test timeout increase submitted in https://patches.dpdk.org/project/dpdk/patch/MW4PR11MB8289B816B08C6E19716B8F82D72C2@MW4PR11MB8289.namprd11.prod.outlook.com/.

updpatch: dpdk 24.07-1

---

pnpm/add-pnpm-linux-riscv64.patch
pnpm/riscv64.patch

Upstreamed to https://github.com/pnpm/pnpm/pull/8779. Use --no-frozen-lockfile because current pnpm complained about pnpmfileChecksum mismatch, but I have no idea why since the checksum does not change when I run `pnpm install` elsewhere.

updpatch: pnpm 9.12.3-1

---

python-plop/relax-time-restrictions.patch
python-plop/riscv64.patch

`test_collector`'s time restriction is a bit tight on riscv64, extend it.
```
FAIL: test_collector (plop.test.collector_test.CollectorTest.test_collector)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/build/python-plop/src/plop-0.4.0/plop/test/collector_test.py", line 77, in test_collector
self.assertTrue(time_per_sample < 0.000100, time_per_sample)
AssertionError: False is not true : 0.00010132487816146658
```

addpatch: python-plop 0.4.0-6

---

v2ray/riscv64.patch
v2ray/v2ray-InitializeServerConfig-sleep.patch

Sadly upstream does not really want to bump test timeout (see issues link in riscv64.patch), so refresh.

updpatch: v2ray 5.18.0-1

---

emovix/riscv64.patch

Two targets can race when make install. Limit make jobs to 1 to mitigate it.
Upstream bug report: https://sourceforge.net/p/movix/bugs/56/ (though it has been ten years after the last update on the upstream side: https://sourceforge.net/p/movix/activity/?page=0&limit=100 )

updpatch: emovix 0.9.0-9

---

premake/premake-riscv.patch
premake/riscv64.patch

Upstreamed: https://github.com/premake/premake-core/pull/2356
Apply unix2dos to patch files because of CRLF line endings in upstream release tarball.

addpatch: premake 5.0beta3-1

---

go/riscv64.patch

Explicitly set `GORISCV64` which is supported since Go 1.23.

upgpatch: go 2:1.23.4-1

---

python-aiohttp/riscv64.patch

updpatch: python-aiohttp 3.10.5-1

---

x86_64-linux-gnu-binutils/PKGBUILD

Based on aarch64-linux-gnu-binutils.

addpkg: x86_64-linux-gnu-binutils 2.43-1

---

mongo-c-driver/riscv64.patch

The sleep time to wait for spawn is not enough on TH1520
The upstream repo disables issue.

updpatch: mongo-c-driver 1.29.0-1

---

x86_64-linux-gnu-linux-api-headers/PKGBUILD

Based on aarch64-linux-gnu-linux-api-headers

addpkg: x86_64-linux-gnu-linux-api-headers 6.12-1

---

blacklist.txt

NDISwrapper is a Windows network driver wrapper.
It doesn't support anything beyond XP, and XP drivers are x86 which riscv64 can't use.

blacklist: Blacklist NDIS Wrapper

---

cataclysm-dda/riscv64.patch

updpatch: cataclysm-dda 0.H-2

---

x86_64-linux-gnu-gcc/PKGBUILD

A minimal gcc used to build full target glibc

addpkg: x86_64-linux-gnu-gcc 14.2.0-1

---

x86_64-linux-gnu-gcc/PKGBUILD

- multilib shouldn't be enabled.
- Fix lib dir
- Some potentially unnecessary sources files get installed, reported here: https://gitlab.archlinux.org/archlinux/packaging/packages/aarch64-linux-gnu-gcc/-/issues/3

fixpkg: x86_64-linux-gnu-gcc 14.2.0-2

---

niri/riscv64.patch

Fix rustix vDSO RISC-V getcpu not correctly named. Upstreamed to https://github.com/bytecodealliance/rustix/pull/1239.

addpatch: niri 0.1.10.1-1

---

coin-or-asl/riscv64.patch

Disable FPU control, as fedisableexcept will always fail (even when _GNU_SOURCE is defined): https://github.com/riscv-collab/riscv-gnu-toolchain/issues/417#issuecomment-475128185

addpatch: coin-or-asl 2.1.0-1

---

linux-tools/riscv64.patch

- Remove intel-speed-select
- Fix `<asm/fence.h> not found` issue by cherry-picking https://github.com/torvalds/linux/commit/710fbca820c721cdd60fa8c5bbe9deb4c0788aae and set SRCARCH explicitly

updpatch: linux-tools 6.12-8

---

openpgl/riscv64.patch

using simde, fetched from my own repo: https://github.com/Cryolitia-Forks/openpgl/commit/77074e2ff062a16ad20f071189dac56e6d075d52
Upstreamed: https://github.com/RenderKit/openpgl/issues/20
Still need to waiting openpgl upstream for their insights about porting it to riscv64
Actually the biggest challenge is its dependency embree. And openpgl just copy a part of embree's source code to itself's repo without any dependency management. I can not determine how to modify these part of codes on upstream though.
Plus, there is also a still-open PR on embree that port it to RISC-V V extension. Also keep an eye on it.
Link: https://github.com/RenderKit/embree/pull/503

addpkg: openpgl 0.7.0-1

---

zigbee2mqtt/riscv64.patch

- Add Python for building native Node modules
- Remove prebuilt binaries of other architectures

addpatch: zigbee2mqtt 1.42.0-1

---

rocm-llvm/riscv64.patch
rocm-llvm/rocm-llvm-fix-llvm-mc-abi.patch

Fix `rccl` build error about float abi.

upgpatch: rocm-llvm 6.2.4-1

---

hip-runtime/hip-runtime-clr-riscv-fence.patch
hip-runtime/hip-runtime-clr-riscv-hard-float.patch
hip-runtime/riscv64.patch

- RISC-V fence instruction
- Use lp64d for `llvm-mc`

addpatch: hip-runtime 6.2.4-1

---

python-proton-vpn-local-agent/riscv64.patch

`aws-lc-sys` crate needs `cmake` and `clang` without pregenerated bindgen.
The package force `-O0` which is incompatible with `_FORTIFY_SOURCE`.

addpatch: python-proton-vpn-local-agent 1.2.0-4

---

qt6-webengine/riscv64.patch

Needs to rebuild python-html5lib first.

updpatch: qt6-webengine 6.8.1-1

---

vue-language-tools/riscv64.patch

- Remove @vscode/vsce from project dependencies to avoid installing @vscode/vsce-sign(which is proprietary and doesn't support riscv)
- Double the test timeout.

addpatch: vue-language-tools 2.1.10-1

---

rocm-opencl-runtime/riscv64.patch
rocm-opencl-runtime/rocm-opencl-runtime-clr-riscv-fence.patch
rocm-opencl-runtime/rocm-opencl-runtime-clr-riscv-hard-float.patch

upgpatch: rocm-opencl-runtime 6.2.4-1

---

zettlr/electron-packager-riscv64.patch
zettlr/riscv64.patch

- Fix rotten patches
- Write a SHASUMS256 file for locally generated electron zip as electron-forge now checks that.
- Tested on centiskorch. It sometimes crashes on start.
when crashing:
```
Received signal 4 <unknown> 00004fa90ce0
#0 0x002abfa88f8e (/usr/lib/electron33/electron+0x16b6f8d)
#1 0x002ac219f6b6 (/usr/lib/electron33/electron+0x3dcd6b5)
#2 0x003f89405800 ([vdso]+0x7ff)
#3 0x003f63317274 <unknown>
#4 0x002ac06f0770 (/usr/lib/electron33/electron+0x231e76f)
#5 0x002ac06f0770 (/usr/lib/electron33/electron+0x231e76f)
#6 0x002ac06f0770 (/usr/lib/electron33/electron+0x231e76f)
#7 0x002ac06f0770 (/usr/lib/electron33/electron+0x231e76f)
#8 0x002ac07534e0 (/usr/lib/electron33/electron+0x23814df)
#9 0x002ac0887bec (/usr/lib/electron33/electron+0x24b5beb)
#10 0x002ac073d690 …
```

updpatch: zettlr 3.4.1-1

---

rccl/riscv64.patch

Build after `rocm-llvm` patch #4387

addpatch: rccl 6.2.4-1

---

hiprt/riscv64.patch

Overwrite x86_64 `easy-encryption` prebuilt.

addpatch: hiprt 2.3.bd75b7c.rc7-2

---

hiprt/riscv64.patch

fixpatch: hiprt 2.3.bd75b7c.rc7-2

---

hip-runtime/riscv64.patch

Fix `rocfft` build failure:
```text
stockham_aot: /usr/src/debug/hip-runtime/clr-rocm-6.2.4/rocclr/os/os_posix.cpp:321: static void amd::Os::currentStackInfo(unsigned char**, size_t*): Assertion `Os::currentStackPtr() >= *base - *size && Os::currentStackPtr() < *base && "just checking"' failed.
Error executing /build/rocfft/src/build/library/src/device/generator/stockham_aot
make[2]: *** [library/src/device/CMakeFiles/gen_headers_target.dir/build.make:75: library/src/device/function_pool.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:692: library/src/device/CMakeFiles/gen_headers_target.dir/all] Error 2
```
Build `rocfft` after upgrading this package.
Upstreamed: https://github.com/ROCm/clr/pull/117

upgpatch: hip-runtime 6.2.4-1.1

---

mongo-c-driver/riscv64.patch

updpatch: mongo-c-driver 1.29.1-1

---

rocm-opencl-runtime/riscv64.patch

Same as #4406
Fix `clinfo` runtime error:
```text
static void amd::Os::currentStackInfo(unsigned char**, size_t*): Assertion `Os::currentStackPtr() >= *base - *size && Os::currentStackPtr() < *base && "just checking"' failed.
```

upgpatch: rocm-opencl-runtime 6.2.4-1.1

---

chezmoi/riscv64.patch
qemu-user-blacklist.txt

Disable the test timeout, it's passed by args instead of hard encoding in the source, so may not report upstream.
It costs ~800s on `centiskorch` to finish, on qemu-user it will costs more than 1 hour (1 hour is the timeout set on upstream action CI) and I'm not able to wait it to finish, each step costs several minutes. But I believe it finally could be before the universe death hh
Just be patient, we are using RISC-V.

addpatch: chezmoi 2.57.0-1, qemu-user-blacklist: add chezmoi

---

rust/riscv64.patch

- Add rust-x86_64-musl and rust-x86_64-gnu packages as Arch adds rust-aarch64-{musl,gnu}

updpatch: rust 1:1.83.0-3

---

rspamd/riscv64.patch

Link: https://github.com/rspamd/rspamd/issues/5270

updpatch: rspamd 3.11.0-1

---

maturin/riscv64.patch

Tests seem to timeout (didn't run before), still needs investigation.

updpatch: maturin 1.8.1-2

---

miopen-hip/riscv64.patch

- Backport https://github.com/ROCm/rocMLIR/commit/b85ca4855e0f0214c2fd695e493c884cf08a3472
- Fix char signedness error, upstreamed https://github.com/ROCm/rocMLIR/pull/1709

addpatch: miopen-hip 6.2.4-1

---

anari-sdk/riscv64.patch

Disable BUILD_HELIDE_DEVICE because it depends on embree which we haven't ported yet (and which seems to require ispc).
This package is an opt&make dependency for vtk

addpatch: anari-sdk 0.11.1-1

---

hipblaslt/riscv64.patch

Add missing makedepends
Upstreamed https://gitlab.archlinux.org/archlinux/packaging/packages/hipblaslt/-/merge_requests/2

upgpatch: hipblaslt 6.2.4-1

---

element.io/riscv64.patch

- Rebase fork of electron-builder on top of v25.1.8
- Stop vendoring app-builder as this transitive dependency is updated to a version supporting riscv64.

updpatch: element.io 1.11.89-1

---

nzbget/riscv64.patch

fix: `lto1: fatal error: target specific builtin not available`

updpatch: nzbget 24.5-1

---

chromium/riscv-ffmpeg.patch
chromium/riscv64.patch

- Switch back to chromium source tarball
- Cherry-pick v8 patch to fix build: https://chromium-review.googlesource.com/c/v8/v8/+/6027486
- Regenerate ffmpeg patch
- Drop a sed hack as we have clang 19 now.
- PGO is enabled by Arch Linux as clang is upgraded to 19. It uses the bundled PGO profile generated for x86_64. Not sure about it's influence on riscv64.
- Tested on centiskorch

updpatch: chromium 132.0.6834.83-1

---

linux-tools/riscv64.patch

- Fix rotten
- Disable linux/tools/arch/x86/kcpuid

updpatch: linux-tools 6.12-11

---

qemu-user-blacklist.txt

The test `libvirt:script / qemu replies check` timeout 30s on qemu-user but finished in 5s on SG2042

qemu-user-blacklist: add libvirt

---

dioxus-cli/riscv64.patch

Skip test using prebuilt binaries on unsupported platforms. Upstreamed to https://github.com/DioxusLabs/dioxus/pull/3624.

updpatch: dioxus-cli 0.6.1-1

---

libpeas/riscv64.patch

The test costs around 100s on both qemu-user and SG2042
Additionally, meson itself has a default timeout for test that is 30s, and the upstream source is not hard encoding any timeout value, just keep it as meson's default. The timeout could be passed by args while building, so we may not need to report it upstream.

addpatch: libpeas 1.36.0-6

---

libpeas-2/riscv64.patch

The test costs around 100s on both qemu-user and SG2042
Additionally, meson itself has a default timeout for test that is 30s, and the upstream source is not hard encoding any timeout value, just keep it as meson's default. The timeout could be passed by args while building, so we may not need to report it upstream.

addpatch: libpeas-2 2.0.5-2

---

python-xarray/riscv64.patch

~~Skip `test_roundtrip_mask_and_scale` because failed on all non-`x86_64` platform.~~

updpatch: python-xarray 2025.01.1-2

---

electron34/Debian-fix-rust-linking.patch
electron34/riscv64.patch

Changes at riscv-forks/electron: https://github.com/riscv-forks/electron/commit/6f565472cb0509728311228041feb2b60db758c7
- Fix rotten patches
- Regenerate ffmpeg patch
- Pick V8 build fix patch
- ffmpeg: enable relocate for ff_h264_weight_funcs_8_rvv
- Add patch that adds riscv64 to `Study::CpuArchitecture` in chromium variations
Packaging changes compared to electron33:
- Replace rollup wasm module with native rollup at more places to workaround more issues as mentioned in https://github.com/felixonmars/archriscv-packages/pull/4252
- Disable the download of PGO profile and thus PGO beause it is hard to patch gsutil which is downloaded on the fly and a py3.8 vpython env is also created on the fly.

addpatch: electron34 34.0.0-3

---

nodejs/riscv64.patch

- Switch compiler to clang, this workarounds https://archriscv.felixc.at/.status/log.htm?url=logs/389-ds-base/389-ds-base-3.1.1-3.log See more details in https://github.com/riscv-forks/electron/issues/7
- Cherry-pick icache flush fix, upstreamed:
- https://github.com/nodejs/node/pull/56781
- https://github.com/nodejs/node/pull/56782
- Should still need nocheck

updpatch: nodejs 23.4.0-1

---

python-rpy2/riscv64.patch
python-rpy2/rpy2-fix-Rcomplex.diff

Fix Rcomplex definition, upstreamed https://github.com/rpy2/rpy2/pull/1147
The upstream PR doesn't apply to this release so store a patch here.

addpatch: python-rpy2 3.5.17-2

---

python-pexpect/riscv64.patch

Fix test failure, upstreamed: pexpect/pexpect#813

addpatch: python-pexpect 4.9.0-4

---

transmission/riscv64.patch

Now we don't need to remove `libb64` from makedepends.
This is because makedepends changes frequently and thus cannot be patched.

updpatch: transmission 4.0.6-9

---

cargo-tauri/riscv64.patch

Add riscv64 support to tauri cli.
I will upstream it later because upstream requires commits to be GPG signed but my key just expired.
Tested by build rqbit and running rqbit-desktop.

addpatch: cargo-tauri 2.2.5-1

---

python-graph-tool/riscv64.patch

Add riscv64 to 64 bit arches to fix https://archriscv.felixc.at/.status/logs/python-graph-tool/python-graph-tool-2.86-1.log
Upstream PR: https://git.skewed.de/count0/graph-tool/-/merge_requests/73

addpatch: python-graph-tool 2.86-2

---

python-executing/riscv64.patch

Fix rotten and make it less likely to rot

updpatch: python-executing 2.2.0-1

---

paraview-catalyst/char-signed-test.patch
paraview-catalyst/risc64.patch

fix test failed. upstreamed: [paraview-catalyst](https://gitlab.kitware.com/paraview/catalyst/-/issues/44)

addpatch: paraview-catalyst 2.0.0-2

---

boost/boost-fix-missing-cstdint.patch
boost/riscv64.patch

Backport https://github.com/boostorg/lockfree/pull/109, adding missing `<cstdint>` include, to fix `libuhd` compile error.
Build `libuhd` after this bump.

addpatch: boost 1.87.0-2

---

python-pytorch/riscv64.patch

- Enable ROCm variant
- Disable aotriton which requires CUDA, upsteamed https://github.com/pytorch/pytorch/pull/146406
- Enable RVV for -opt variant

upgpatch: python-pytorch 2.6.0-2

---

aom/riscv64.patch

Disable `lto` to fix `lto1: fatal error: target specific builtin not available`

addpatch: aom

---

cmake/riscv64.patch

Backport https://gitlab.kitware.com/utils/kwsys/-/merge_requests/328 to fix `MPIEXEC_MAX_NUMPROCS` enforced to `1`, which causes build error on `ginkgo-hpc`.

addpatch: cmake 3.31.5-1

---

postgresql/riscv64.patch

1. Remove `0003-Fix-timezone-test.patch` patch because patch has been appiled.
2. Delete '--with-llvm' still.

updpatch: postgresql 17.2-3

---

nodejs/riscv64.patch

- Fix rotten patch and drop upstreamed patch
- Should still need nocheck
- Note that simdjson needs to be built first before this PR.

updpatch: nodejs 23.8.0-4

---

webrtc-audio-processing-0.3/riscv64.patch
webrtc-audio-processing-0.3/webrtc-riscv64.patch

RISC-V support is present in upstream but not in this legacy version. Port it here.

addpatch: webrtc-audio-processing-0.3 0.3.1-6

---

vamp-aubio-plugins/riscv-fix.patch
vamp-aubio-plugins/riscv64.patch

- Add an else branch to set fallback value of local_vamp_lib to `/non-existent`. This variable is not used as we are using system vamp-plugin-sdk.
- Drop '-msse', '-msse2' compiler flags
Closes: https://archriscv.felixc.at/.status/log.htm?url=logs/vamp-aubio-plugins/vamp-aubio-plugins-0.5.1-6.log

addpatch: vamp-aubio-plugins 0.5.1-6

---

rust/riscv-musl-crt-default-static.diff
rust/riscv64.patch

Force musl target's `crt_static_default = true` after upstream switched to dynamic by default.

updpatch: rust 1:1.85.0-1

---

lact/riscv64.patch

Backport fix for https://github.com/ilya-zlobintsev/LACT/issues/475.

addpatch: lact 0.7.0-2

---

lib2geom/riscv64.patch

Disable failed test to build inkscape correctly
Upstreamed: https://gitlab.com/inkscape/lib2geom/-/issues/82

addpatch: lib2geom 1.4.0

---

glibc/riscv64.patch

Cherry-pick two patches:
- RISC-V: Fix IFUNC resolver cannot access gp pointer by cyy
- linux: prevent kernel choose addr by itself in mremap test by c10s

updpatch: glibc 2.41+r9+ga900dbaf70f0-1

---

gcc/riscv64.patch

Fix rotten patch and revert a commit that causes bootstrap failure.
Bug reports:
- https://github.com/Rust-GCC/gccrs/issues/3424
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119012
Reverted commit: https://patchwork.ozlabs.org/project/gcc/patch/mptzfk45brm.fsf@arm.com/
During bisection, the failure messages are mostly:
Comparing stages 2 and 3
Bootstrap comparison failure!
gcc/rust/rust-lex.o differs
or
Comparing stages 2 and 3
Bootstrap comparison failure!
gcc/builtins.o differs
or crash in RTL pass like:
*** stack smashing detected ***: terminated
during RTL pass: combine
/usr/src/debug/gcc/gcc/gcc/config/riscv/corev.md: In function ‘recog_84.isra’:
/usr/src/debug/gcc/gcc/gcc/config/riscv/corev.md:2557:1: internal compiler error: Aborted
0x9c9f05 crash_signal …

updpatch: gcc 14.2.1+r753+g1cd744a6828f-1

---

rustup/riscv64.patch

Add clang and cmake to makedepends until aws-lc-rs' pregenerated riscv64 binding is ready.

addpatch: rustup 1.28.1-1

---

spotify-player/riscv64.patch

Add clang and cmake to makedepends until aws-lc-rs' pregenerated riscv64 binding is ready.
The code builds with -O0 and conflicts with _FORTIFY_SOURCE.

addpatch: spotify-player 0.24.0-2

---

cargo-msrv/riscv64.patch

Extra makedepends to build aws-lc-sys without pre-generated binding.

addpatch: cargo-msrv 0.18.3-1

---

qt6-webengine/riscv64.patch

摸着Revy老师过河
Link: https://github.com/rockos-riscv/chromium-129.0.6668.100/commit/f699f4ed684e413e508e1f3c5e30d806473ff13b

updpatch: qt6-webengine 6.8.2-3

---

libseccomp/riscv64.patch

- We still need this patch even if we have valgrind now. Because running those valgrind tests need debug info, or we ship an unstripped dyld.
```
Test 02-sim-basic%%012-00001 valgrind output                                                                                                                                                                                                
==154369== Memcheck, a memory error detector                                                                                                                                                                                                
==154369== Copyright (C) 2002-2024, and GNU GPL'd, by Julian Seward et al. …
```

updpatch: libseccomp 2.5.6-1

---

xournalpp/riscv64.patch

Upstream hash mismatch
Link: https://gitlab.archlinux.org/archlinux/packaging/packages/xournalpp/-/merge_requests/1

addpatch: xournalpp 1.2.6-1

---

consul/riscv64.patch

Mistakenly removed the entire patch in https://github.com/felixonmars/archriscv-packages/pull/4600 (apologies for the mistake), even though only part of it was upstreamed, not all of it. Now it's been restored and rebased from https://github.com/felixonmars/archriscv-packages/commit/124a4675e37eff8f687c4fa6bde1691388c7a2ed.

addpatch: consul 1.20.5-1

---

bazel7/bazel7-riscv.diff
bazel7/riscv64.patch

Add riscv64 support to bazel7:
Upstreamed as https://github.com/bazelbuild/bazel/pull/25699
Upstream is currently not planning another bazel 7 release so we need to keep this patch at downstream for a while.

addpatch: bazel7 7.5.0-1

---

bazel/riscv64.patch

- Fix rotten
- Upstreamed (8.x backport): https://github.com/bazelbuild/bazel/pull/25732

updpatch: bazel 8.1.1-1

---

bazel7/bazel7-riscv.diff
bazel7/riscv64.patch

- Bump abseil-cpp for https://github.com/abseil/abseil-cpp/pull/1644 , which fixes RDCYCLE SIGILL on linux >= 6.6.
- Make the patch less likely to rot as we might keep it for a while.

updpatch: bazel7 7.5.0-1

---

apt-swarm/riscv64.patch

The compilation of cargo source code of package aws-lc-sys 0.27.1 does not support riscv64 assembly instructions, and only cmake build tool can be selected, so add cmake package.

addpatch: apt-swarm 0.5.1-1

---

deno/riscv64.patch

Backport patches to fix V8 build regression on riscv64.

addpatch: deno 2.2.3-1

---

ncnn/riscv64.patch

Disable LTO and xtheadvector due to:
- `-march=rv64gcv` conflicts with LTO: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110812
- xtheadvector compilation fails without LTO (fixed in GCC 15 branch): https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116590

addpatch: ncnn 20241226-5

---

mac/fix-rvv-build.patch
mac/riscv64.patch

- Fix undefined reference to RVV functions, to be upstreamed via email
- Disable LTO since mixing rv64gc and rv64gcv objects conflicts with it

addpatch: mac 11.03-1

---

qemu/riscv64.patch

Change depends of qemu-base to qemu-system-riscv and move qemu-system-x86 to optdepends.

updpatch: qemu 9.2.3-1.1

---

lapce/riscv64.patch

- Use large code model to workaround "relocation truncated to fit"
- Disable LTO because setting code model to anything other than medium fails to build with LTO.
- Bisected and reported as https://github.com/rust-lang/rust/issues/139479

addpatch: lapce 0.4.2-1

---

meson/riscv64.patch

- Add back java-environment=8
- Enable valgrind tests
- Add missing checkdepends vulkan-headers: https://gitlab.archlinux.org/archlinux/packaging/packages/meson/-/merge_requests/2

updpatch: meson 1.7.2-1

---

valkey/riscv64.patch

Backport https://github.com/valkey-io/valkey/commit/204097dac46730e9eb125c822c1dc2959c6572c5.

addpatch: valkey 8.1.0-3

---

libguestfs/fix-char-signedness.patch
libguestfs/riscv64.patch

- Remove syslinux dependency, only available on x86
- Backport https://github.com/libguestfs/libguestfs/commit/d7d5264ce8240fdbb712c110580b28b4913e38d2
- Should be built after linux-lts and qemu, possibly with nocheck since tests run qemu-system-riscv64, too slow for machines without H extension

addpatch: libguestfs 1.54.1-3

---

binutils/riscv64.patch

Set bugurl to our repo so user facing bug won't distrub Arch Linux.

addpatch: binutils 2.44-1

---

gitlab/riscv64.patch

- resolve conflict
- patch nokogiri
- original `rbtrace` patch is modified because compiling should not be in the prepare() part

updpatch: gitlab 17.10.1-1

---

brook/riscv64.patch

Update `github.com/phuslu/iploc` to support riscv64
Upstreamed: https://github.com/txthinking/brook/issues/1378

addpatch: brook 20230122-1

---

magma/riscv64.patch

Remove the `cmake_policy( SET CMP0037 OLD)` line to fix CMake 4.0 build error
Upstreamed: https://github.com/icl-utk-edu/magma/pull/48

upgpatch: magma 2.9.0-2

---

opensearch/opensearch-riscv.patch
opensearch/riscv64.patch

- Add support for riscv64 linux, upstreamed: https://github.com/opensearch-project/OpenSearch/pull/18156
- Backport patch to 2.19.1
- Vendor protoc becuase prebuilts are not available for riscv64 in maven repository
- Tested basic functionalities.

addpatch: opensearch 2.19.1-1

---

gdl/riscv64.patch

In gettext 0.24.1-1 the m4 files have moved from /usr/share/aclocal/ to /usr/share/gettext/m4.
https://gitlab.archlinux.org/archlinux/packaging/packages/gdl/-/merge_requests/1

addpatch: gdl 3.40.0-2

---

diffoscope/riscv64.patch

- Fix rotten
- check() fails due to missing libxml2.so.2. `--nocheck` is needed or just wait for libxml2 rebuild to be finished.

updpatch: diffoscope 294-1

---

chromium/riscv64.patch

- Update chromium riscv patchset for 136. See https://github.com/riscv-forks/electron/commit/abf9343fc68bf384126837e72da9fa9670784690 for more details
- Tested on centiskorch

updpatch: chromium 136.0.7103.59-1

---

apache-orc/riscv64.patch

rmvpatch: apache-orc 2.0.3-6

---

haskell-hadrian/riscv64.patch

Attempt to fix GHC 9.4.8's unable to runhaskell:
`<command line>: not built for interactive use`

addpatch: haskell-hadrian 0.1.0.0+9.4.8-97.1

---

zed/riscv64.patch

- Add cargo-about to makedepends: https://gitlab.archlinux.org/archlinux/packaging/packages/zed/-/merge_requests/9
- Build LiveKit's libwebrtc locally and natively (to be upstreamed): https://github.com/hack3ric/livekit-rust-sdks/commits/webrtc-native-riscv64/

addpatch: zed 0.185.15

---

ghc/0001-rts-posix-OSMem-Shrinking-allocation-size-when-it-s-.patch
ghc/riscv64.patch

This should solve random hangs in RTS when running GHC-compiled programs with newer Linux kernels. The RTS patch should be upstreamed after cleaning up.

updpatch: ghc 9.4.8-1

---

ghc/riscv64.patch

- Apply patch to fix build of gi-glib.
- Fix path for previous patch.

updpatch: ghc 9.4.8-1.3

---

rocm-llvm/riscv64.patch

- Refresh patch.
- Add new patch to fix narrowing conversion error from int to char

updpatch: rocm-llvm 6.4.0-4

---

go/riscv64.patch

Add a patch to fix recent linking failures.

updpatch: go 2:1.24.3-1.1

---

gcc14/riscv64.patch
gcc14/unfilter-default-library-path.patch

- Initialize patch for gcc14 based on gcc and gcc13 patches.
- Use `bootstrap-lto-lean` build config to workaround gcc self-miscompliation bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=119012).
- Previously reverting a commit could work around it, but now it is no longer the case.

addpatch: gcc14 14.2.1+r753+g1cd744a6828f-3

---

gcc13/riscv64.patch

Remove libgcc_s.so accidentally included in `gcc13`.

fixpatch: gcc13 13.3.1+r432+gfc8bd63119c0-3

---

qemu-user-blacklist.txt

qemu-user does not support SCTP protocol:
```
==> Starting check()...
./test_assoc_abort
test_assoc_abort.c  1 BROK : setsockopt(11): Protocol not available
DUMP_CORE ./sctputil.h: 257
test_assoc_abort fails
make: *** [Makefile:1770: v4test] Error 1
```

qemu-user-blacklist: add lksctp-tools

---

qemu-user-blacklist.txt

Seems lstopo and hwloc-gather-topology returns slightly different information on qemu-user:
```
Extracting tarball...
Saving tarball topology to XML...
Comparing XML outputs...
--- save1.xml   2025-05-23 04:07:24.771914250 +0000
+++ save2.xml   2025-05-23 04:11:10.844166135 +0000
@@ -21,7 +21,6 @@
<info name="hwlocVersion" value="2.12.1"/>
<info name="ProcessName" value="lstopo-no-graphics"/>
<object type="Package" os_index="0" cpuset="0xffffffff" complete_cpuset="0xffffffff" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3">
-      <info name="CPUModel" value="AMD Ryzen 9 5950X 16-Core Processor"/>
<object type="NUMANode" os_index="0" cpuset="0xffffffff" complete_cpuset="0xffffffff" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="118" …
```

qemu-user-blacklist: add hwloc

---

mattermost-desktop/riscv64.patch

- Use forked electron-builder and other npm packages
- Remove all explicit x64 mentions
- Manually call electron-builder so it uses system electron only (adopted from bitwarden)

addpatch: mattermost-desktop 5.12.0-1

---

drawio-desktop/riscv64.patch

- Refresh patch
- Upgrade forked electron-builder to stop vendoring app-builder

updpatch: drawio-desktop 27.0.5-1

---

binutils/riscv64.patch

Backport upstream commit that fixes `as` segfault while building nodejs-lts-jod.
Upstream bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=33029

updpatch: binutils 2.44+r94+gfe459e33c676-1

---

audacity/riscv64.patch

New added options explanations:
- `-std=gnu17`: audacity/audacity#8726
- [Upstreamed to Arch repo](https://gitlab.archlinux.org/archlinux/packaging/packages/audacity/-/merge_requests/2)
- `-ffp-contract=off`: audacity/audacity#8872
- Not sure of the upstream preferred solution, we can disable FMA for RISC-V 64-bit for now to make floating point results consistent with x86_64.

addpatch: audacity 3.7.3-2

---

libkrunfw/riscv64.patch

`cpio` makedepends is added to build `arch/riscv/boot/Image`
https://github.com/containers/libkrunfw/pull/94

addpatch: libkrunfw 4.9.0-2

---

libpng/riscv64.patch

- An ICE happens when not applying any patch. I have reported it to gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120674
- Enable RVV runtime dispatch.
- Remove our `-march=rv64gc` flag because some objects needs to be built with `-march=rv64gv` and our flags always overide it because our flags are appended to the commandline.
- Disable LTO due to another bug in GCC compiler: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110812

addpatch: libpng 1.6.49-1

---

adguardhome/riscv64.patch

Node.js 24 crashed while building it. I am tracking it at https://github.com/riscv-forks/electron/issues/9.
Temporarily use Node.js 20 as a workaround

addpatch: adguardhome 1:0.107.62-1

---

nodejs/riscv64.patch
nodejs/v8-riscv-fix-trampoline-release.patch
nodejs/v8-riscv-fix-trampoline.patch

Backport two V8 CL to fix
https://github.com/riscv-forks/electron/issues/9, upstreamed: https://github.com/nodejs/node/pull/58746

updpatch: nodejs 24.2.0-1

---

qemu-user-blacklist.txt

`check()` fails in qemu-user:
```text
!!! WARNING The following tests failed:
*** [err]: Process title set as expected in tests/unit/other.tcl
Expected 'TEST' to be equal to '/usr/bin/qemu-riscv64-staticsrc/valkey-server./tests/tmp/valkey.conf.18802.252' (context: type eval line 10 cmd {assert_equal "TEST" [lindex $cmdline 0]} proc ::test)
*** [err]: Test child sending info in tests/integration/rdb.tcl
Expected '1' to be more than or equal to '2' (context: type eval line 99 cmd {assert_morethan_equal $iteration 2} proc ::test)
```

qemu-user-blacklist: add valkey

---

sg2042-blacklist.txt
vaultwarden-web/riscv64.patch

- Add python to makedepends because some dependencies needs to be built
from source for riscv64.
- Drop other changes that has already been upstreamed to Arch.
- npm install busy spins indefinitely on sg2042, which does not occur in qemu-user. So add to sg2042 blacklist. (Might worth further investigation).

updpatch: vaultwarden-web 2025.5.1.1-1 

---

intel-graphics-compiler/riscv64.patch

- Fix incorrect arch detection regex: https://github.com/intel/intel-graphics-compiler/pull/369
- Silence some `-Werror`, partially upstreamed: https://github.com/intel/intel-graphics-compiler/pull/370, some others should be FP of the compiler.

addpatch: intel-graphics-compiler 1:2.12.5-1

---

sv39-blacklist.txt

Basically anything running WASM during build needs to be added here. I am only adding these two because they have been failing too much. Please add more if you encounter.
See
https://github.com/riscv-forks/electron/issues/3#issuecomment-2391689815 for the underlying issue.

sv39-blacklist: initialize list

---

python-pyjsparser/riscv64.patch

After a simple test in the container, it is believed that there is no problem with the functionality, but the lack of js2py dependency on riscv64 makes the official test impossible. So I will skip the test for now and wait for js2py to be ported.upstreamed: [arch](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pyjsparser/-/issues/1)

addpatch: python-pyjsparser 2.7.1-14

---

librustls/riscv64.patch

Create a cmake wrapper to add `-DCMAKE_POLICY_VERSION_MINIMUM=3.5` to avoid build failure with cmake 4.x.

updpatch: librustls 0.15.0-2

---

sv39-blacklist.txt

```
==> Starting build()...
Running webpack...
/build/gitea/src/gitea/node_modules/webpack/lib/util/hash/wasm-hash.js:166                                                                   
new WebAssembly.Instance(wasmModule),                                                                                        
^
RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance```

sv39-blacklist: add gitea

---

sv39-blacklist.txt

```
/build/forgejo/src/forgejo/node_modules/webpack/lib/util/hash/wasm-hash.js:166                                                               
new WebAssembly.Instance(wasmModule),                                                                                        
^
RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
```

sv39-blacklist: add forgejo

---

suitesparse/riscv64.patch

- Upstream uses Google's cpu_features package to implement RVV runtime detection so we can keep RVV enabled.
- Disable LTO because of `lto1: fatal error: target specific builtin not available`
- Disable debug because we hit my previously reported gcc bug again in a different senario: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=120674
- I have reduced the ICE testcase using cvise and added it to the bug report.

addpatch: suitesparse

---

sv39-blacklist.txt

```
➤ YN0001: │ RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance                                  
at Y ([worker eval]:1:284192)
at [worker eval]:1:287198
at I ([worker eval]:1:287215)
at [worker eval]:1:320275
at getInstance ([worker eval]:1:112099)
at new ZipFS ([worker eval]:1:296450)
at convertToZipWorker ([worker eval]:1:409038)
at MessagePort.<anonymous> ([worker eval]:1:410963)
at [nodejs.internal.kHybridDispatch] (node:internal/event_target:827:20)
at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
➤ YN0000: └ Completed in 38s 684ms
➤ YN0000: · Failed with errors in 41s 8ms
```

sv39-blacklist: add prettier

---

kirigami/riscv64.patch

Update checksum. Reported at
https://gitlab.archlinux.org/archlinux/packaging/packages/kirigami/-/issues/3

addpatch: kirigami 6.16.0-2

---

ldc/riscv64.patch

Refresh patch. Also add llvm19-libs for bootstrapping.

updpatch: ldc 3:1.41.0-1

---

sv39-blacklist.txt

```
✗ Build failed in 1m 4s
error during build:
[vite-plugin-pwa:build] WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
```

sv39-blacklist: add navidrome

---

gcc14/riscv64.patch

Remove libgcc_s.so from gcc14 which should belong to gcc14-libs.

fixpatch: gcc14 14.3.1+r25+g42e99e057bd7-1

---

glibc/riscv64.patch

- Refresh patch
- Drop obsolete cherry-pick
- Disable sframe because it only supports x86_64, aarch64 and s390x for now.
- Segmentation fault of statically-linked binaries built against this glibc is encountered, which is caused by compiler generated `memset` calls in `_dl_aux_init`. Reported to upstream at https://sourceware.org/bugzilla/show_bug.cgi?id=33261 As suggested by @ziyao233, it is caused by calling `memset` with uninitialized GOT entry. This could be fixed by
- Restore `-fno-tree-loop-distribute-patterns` for dl-support.c, which is removed in upstream commit [5355f9ca7b10][1]. This compiler flag is helpful for preventing gcc compiler from optimizing some loops into `memset` calls, which might not be available for loader code because memset might be implemented via ifunc. Since …

updpatch: glibc 2.42+r3+gbc13db739377-1

---

opensearch-sql-plugin/riscv64.patch

Skip `:integ-test:yamlRestTest` as it requires downloading an official release binary tarball, which does not exist for riscv64.
(OpenSearch now supports riscv64 only in source but not in binary releases)

addpatch: opensearch-sql-plugin 3.1.0.0-1

---

fceux/riscv64.patch
fceux/timestamp.patch

There is a function in timestamp and its call does not support riscv64.[upstreamed](https://github.com/TASEmulators/fceux/pull/804)

updpatch: fceux 2.6.6

---

rust/riscv64.patch

- Refresh patch
- Remove `0009-bootstrap-Workaround-for-1.90.0-stage0.patch` for now for bootstrapping Rust 1.90 with 1.89

updpatch: rust 1.90.0-2

---

zed/minidumper-riscv64.patch
zed/riscv64.patch

Add riscv64 support for Rust crash handling crates. Upstream status:
- crash-context, crash-handler: https://github.com/EmbarkStudios/crash-handling/pull/102, https://github.com/EmbarkStudios/crash-handling/pull/103, https://github.com/EmbarkStudios/crash-handling/pull/104
- minidump: https://github.com/rust-minidump/rust-minidump/pull/1124
- minidump-writer: waiting for minidump
- minidumper: waiting for minidump-writer

updpatch: zed 0.204.5-1

---

rust/riscv64.patch

Refresh patches. Re-enable 1.90.0 bootstrap workaround patch.

updpatch: rust 1:1.90.0-3
