- boinctui/riscv64.patch
Ref to https://github.com/samtools/htslib/pull/1198\#issuecomment-753875175
Can also get upstreamed to Arch Linux.
> addpkg: boinctui

- transmission/riscv64.patch
Borrowed from https://github.com/void-linux/void-packages/pull/22373
> addpkg: transmission

- vlc/riscv64.patch
Ref to https://code.videolan.org/videolan/vlc/-/issues/20683
> addpkg: vlc

- pam_wrapper/riscv64.patch
Could get upstreamed to Arch Linux.
> addpkg: pam_wrapper

- nx/riscv64.patch
ref to https://github.com/ArcticaProject/nx-libs/pull/1023
> addpkg: nx

- iagno/riscv64.patch
修了半天发现上游已经有 patch 了……
不过上游还没有发新的 release
> addpkg: iagno

- drumgizmo/riscv64.patch
Double-checked that the hash sum of the source tarball has changed...
> addpkg: drumgizmo

- firefox/makotokato-riscv64-support-and-zenithal-backported.patch
- firefox/riscv64.patch
> updpkg: firefox

- uqm/0000-link-math.patch
- uqm/riscv64.patch
上游基本上消失了，bug report 页面打不开，仓库地址找不到，我发了个邮件过去 https://pastebin.ubuntu.com/p/4mT6VhG3Rx/
> addpkg: uqm

- tali/riscv64.patch
Could get upstreamed to Arch Linux.
> addpkg: tali

- .github/workflows/rotten.yml
- find-rotten
Example run: https://github.com/hexchain/archriscv-packages/runs/4314956136
> Add a script to find rotten patches

- fwknop/riscv64.patch
mrash/fwknop#339
https://www.mail-archive.com/m4-patches@gnu.org/msg01151.html
> addpkg: fwknop

- cgmanager/riscv64.patch
Could get upstreamed to Arch Linux
> addpkg: cgmanager

- devtools/riscv64.patch
> updpkg: devtools

- devtools/riscv64.patch
change arch=('any') to arch=('x86_64')
revise pkgver = 1.1
> fix devtools

- gdmap/riscv64.patch
This package uses file input as the format string.
> addpkg: gdmap

- virtualgl/riscv.patch
- virtualgl/riscv64.patch
> updpkg: virtualgl

- skim/riscv64.patch
> updpkg: skim

- fd/disable-jemallocator.patch
- fd/riscv64.patch
https://github.com/sharkdp/fd/pull/904
> updpkg: fd

- stardict/riscv64.patch
This package uses user input as the format string.
> addpkg: stardict

- fzf/riscv64.patch
> fixpkg: fzf

- zeitgeist/riscv64.patch
Please see https://gitlab.freedesktop.org/zeitgeist/zeitgeist/-/commit/64ac3a6f94cd299e5e14945dc31b48f009dec152 for more information.
> addpkg: zeitgeist

- evince/riscv64.patch
> updpkg: evince

- epiphany/riscv64.patch
> updpkg: epiphany

- lua-language-server/add_riscv_support.patch
- lua-language-server/fix_luamake_pthread_linking.patch
- lua-language-server/fix_pthread_linking.patch
- lua-language-server/riscv64.patch
The `cpu_relax` implementation comes from https://github.com/torvalds/linux/blob/e7c124bd04631973a3cc0df19ab881b56d8a2d50/arch/riscv/include/asm/vdso/processor.h#L14
> addpkg: lua-language-server

- vlc/riscv64-atomic.patch
- vlc/riscv64.patch
* Update to version 3.16-5
* Split patch `riscv64-atomic.patch` from `riscv64.patch`
> updpkg: vlc

- goldendict/0001-Fix-gcc-7.3-compiler-warnings.patch
- goldendict/riscv64.patch
also FTBFS in x86_64. 
upstream patch https://github.com/goldendict/goldendict/commit/fd00e9d1, but can not apply directly.
> addpkg: goldendict

- gc/riscv64.patch
> updpkg: gc

- gnubg/riscv64.patch
> updpkg: gnubg

- pacman/riscv64.patch
> updpkg: pacman

- python-sphinx_rtd_theme/fix-for-new-nodejs.patch
- python-sphinx_rtd_theme/riscv64.patch
Co-authored-by: Felix Yan <felixonmars@archlinux.org>
> addpkg: python-sphinx_rtd_theme

- python-pybluez/riscv64.patch
https://github.com/pybluez/pybluez/issues/413
> addpkg: python-pybluez

- fail2ban/riscv64.patch
Related issue: https://github.com/fail2ban/fail2ban/issues/3098
> addpkg: fail2ban

- python-tempita/riscv64.patch
[FS#73418](https://bugs.archlinux.org/task/73418)
> addpkg: python-tempita

- rkcommon/0000-fix-intrinsic.patch
- rkcommon/riscv64.patch
see https://github.com/ospray/rkcommon/issues/7
> addpkg: rkcommon

- ffmpeg/riscv64.patch
Enabled optional `avresample` for `libopenshot`.
> updpkg: ffmpeg

- devtools-riscv64/PKGBUILD
- devtools-riscv64/makepkg-riscv64.conf
- devtools-riscv64/pacman-extra-riscv64.conf
> addpkg: devtools-riscv64

- freedesktop-docs/riscv64.patch
> addpkg: freedesktop-docs

- python-nose-cover3/remove-use_2to3.patch
- python-nose-cover3/riscv64.patch
https://bugs.archlinux.org/task/73511
Maintainers: Felix Yan
> addpkg: python-nose-cover3

- bonnie++/riscv64.patch
> updpkg: bonnie++

- erlang-cl/riscv64.patch
> updpkg: erlang-cl

- chicken-bootstrap-riscv64/PKGBUILD
> addpkg: chicken-bootstrap-riscv64

- ccls/riscv64.patch
Ref: https://bugs.llvm.org/show_bug.cgi?id=51247
> addpkg: ccls

- procs/riscv64.patch
Adapt to upstream `PKGBUILD` version `0.11.10-1`
> updpkg: procs

- ledger/0000-fix-regress-test.patch
- ledger/riscv64.patch
https://github.com/ledger/ledger/issues/2075
Caused by boost version bump.
> addpkg: ledger

- opendbx/riscv64.patch
http://bugs.linuxnetworks.de/index.php?do=details&id=43
https://en.cppreference.com/w/cpp/language/except_spec
> addpkg: opendbx

- libdispatch/riscv64.patch
Ref: https://lists.llvm.org/pipermail/llvm-dev/2020-January/138450.html
> upgpkg: libdispatch

- libretro-kronos/fix-unrecognized-command-line-option-msse.patch
- libretro-kronos/riscv64.patch
Reverts felixonmars/archriscv-packages#798
> Revert "rmpkg:  libretro-kronos"

- xdg-desktop-portal-bootstrap/PKGBUILD
Build order: `xdg-desktop-portal-bootstrap` -> `xdg-desktop-portal`
> addpkg: xdg-desktop-portal-bootstrap

- grpc/riscv64.patch
Update patch checksum from GitHub
> updpkg: grpc

- ttf-indic-otf/riscv64.patch
> addpkg: ttf-indic-otf

- mailman-bootstrap/PKGBUILD
- mailman-bootstrap/mailman-bootstrap.sysusers
first build this package on riscv64, then build mailman with this package.
Signed-off-by: Coelacanthus <coelacanthus@outlook.com>
> addpkg: mailman-bootstrap

- otf-ipafont/riscv64.patch
See FS#72001 and https://patchwork.openembedded.org/patch/180064/
> addpkg: otf-ipafont

- js78/0001-feature-riscv64-support-from-Debian-and-clang.patch
- js78/riscv64.patch
- js78/tests-skip-some-tests-on-rv64.patch
Reference https://github.com/felixonmars/archriscv-packages/pull/846
> updpkg: js78 to 78.15.0

- ppl/fix-int-conversion.patch
- ppl/riscv64.patch
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959623, and patch modified from https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=959623;filename=ppl-1.2-8.1-nmu.diff;msg=10
> addpkg: ppl

- profanity/riscv64.patch
> addpkg: profanity

- surfraw/riscv64.patch
> addpkg: surfraw

- pidgin-talkfilters/riscv64.patch
> addpkg: pidgin-talkfilters

- otf-ipaexfont/riscv64.patch
https://bugs.archlinux.org/task/72001
Signed-off-by: Coelacanthus <coelacanthus@outlook.com>
> addpkg: otf-ipaexfont

- rocksdb/0000-toku-time-riscv.patch
- rocksdb/riscv64.patch
```
==> WARNING: Sonames differ in rocksdb!
librocksdb.so=6.26-64 | librocksdb.so=6.28-64
```
> upgpkg: rocksdb

- otf-ipamjfont/riscv64.patch
FS#72001
Link grabbed from https://moji.or.jp/mojikiban/font/
> addpkg: otf-ipamjfont

- apper/riscv64.patch
https://bugs.archlinux.org/task/73921
Signed-off-by: Coelacanthus <coelacanthus@outlook.com>
> addpkg: apper

- gn/riscv64.patch
Ref: https://lists.llvm.org/pipermail/llvm-dev/2020-January/138450.html
> upgpkg: gn

- librime-data-bootstrap/PKGBUILD
add dummy package of librime-data to build librime.
> addpkg: librime-data-bootstrap

- devtools-riscv64/PKGBUILD
- devtools-riscv64/makepkg-riscv64.conf
> upgpkg: devtools-riscv64

- wireplumber/riscv64.patch
Issue: https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/216
> addpkg: wireplumber

- non-sequencer/riscv64.patch
* Adapt to upstream `PKGBUILD`
* Fixes FS#74097
> updpkg: non-sequencer

- non-sequencer/riscv64.patch
> updpkg: non-sequencer 1.10.0-2

- non-daw/riscv64.patch
> updpkg: non-daw 1.3.0-4

- gcc/riscv64.patch
This patch includes libatomic.a in package gcc-libs.
> upgpkg: gcc

- linux/riscv64.patch
1. Enable installing tools/bpf/resolve_btfids/resolve_btfids, needed by kmod.
2. Enable docs.
> upgpkg: linux

- bacon/riscv64.patch
According to https://riscv-notes.sh1mar.in/docs/record/rust-related#riscv64gc-unknown-linux-gnu
> addpkg: bacon

- xtrabackup/riscv64.patch
LTO plugin for clang is broken. Disable it.
> fixpkg: xtrabackup

- find-rotten
Fix order of the find-ghost and & operation.
> Fix find-ghost

- mdbook-linkcheck/riscv64.patch
Fix cargo arccording to https://riscv-notes.sh1mar.in/docs/record/rust-related#riscv64gc-unknown-linux-gnu
> addpkg: mdbook-linkcheck

- spike/riscv64.patch
Cherry-picked patches from riscv-software-src/riscv-isa-sim#966
> addpkg: spike

- libgweather-4/python-pylint/riscv64.patch
increase its test timeout, upstream change: https://github.com/PyCQA/pylint/pull/6241 (merged)
> addpkg: python-pylint

- .github/workflows/test.yml
ref: https://github.com/actions/checkout/issues/760
> try to make ci happy

- gegl/riscv64.patch
Fix the failed patch for PKGBUILD.
> updpkg: gegl

- qemu-user-blacklist.txt
> addpkg: fish

- krita/riscv64.patch
Upstream: https://invent.kde.org/graphics/krita/-/merge_requests/1416
> addpkg: krita

- krita/riscv64.patch
> fixpkg: krita

- cargo-depgraph/riscv64.patch
This should fix the target issue.
> addpkg: cargo-depgraph

- qt5-base/add-feature-forkfd_pidfd.patch
- qt5-base/riscv64.patch
This patch is modified from https://codereview.qt-project.org/c/qt/qtbase/+/313894.
> addpkg: qt5-base

- libblastrampoline/riscv64.patch
Cherry-picked an upstream PR https://github.com/JuliaLinearAlgebra/libblastrampoline/pull/68.
> addpkg: libblastrampoline

- xtmsplit/riscv64.patch
> updpkg: xtmsplit

- mesa/riscv64.patch
Approach taken from:
https://groups.google.com/g/linux.debian.maint.x/c/mLnL-WxLKe4/m/JFsp6ZY-AgAJ
> mesa: try to workaround LLVM JIT issues

- qemu-user-blacklist.txt
> addpkg: knot

- zoxide/riscv64.patch
> fixpkg: zoxide

- miller/riscv64.patch
Resolve check failures caused by test timeouts
> addpkg: miller

- bazel/riscv64.patch
> updpkg: bazel

- krita/riscv64.patch
> upgpkg: krita

- jwt-cli/riscv64.patch
This patch fixes the target issue related to rustc and build error from ring.
> addpkg: jwt-cli

- linux/riscv64.patch
> fixpkg: linux

- find-rotten
> fix(find-rotten): do not check testing

- shim/gnu-efi-riscv64.patch
- shim/riscv64.patch
- shim/shim-riscv64-check.patch
- shim/shim-riscv64.patch
Some patches are based on https://github.com/rhboot/shim/pull/420 and https://github.com/rhboot/gnu-efi/pull/3.
> addpkg: shim

- aiksaurus/riscv64.patch
> updpkg: aiksaurus

- toastify/riscv64.patch
> updpkg: toastify

- drone-runner-exec/riscv64.patch
> upgpkg: drone-runner-exec 1.0.0.beta.9-4

- gcc/riscv64.patch
Adapt to upstream confflags format change.
> updpkg: gcc 12.1.0-2

- libjpeg-turbo/riscv64.patch
> upgpkg: libjpeg-turbo 2.1.3-2

- qemu-user-blacklist.txt
All tests pass on Unmatched. The cause is yet to be discovered.
> Add tpm2-tss to qemu-user-blacklist

- rust/replace_patched_libc_cc.patch
- rust/riscv64.patch
> upgpkg: rust 1.61.0

- nzbget/riscv64.patch
https://github.com/nzbget/nzbget/issues/755
https://github.com/nzbget/nzbget/pull/765
> addpkg: nzbget

- cmake/riscv64.patch
> upgpkg: cmake to 3.23.2-1

- xine-lib/fix-david.patch
- xine-lib/riscv64.patch
Dav1d 1.0.0 break compatibility:
https://github.com/videolan/dav1d/commit/753eef833bdd8ff1585c5c858cafeca8fefbb16e
> addpkg: xine-lib

- README.md
This can help newcomer know how we work.
> Add wiki link into README

- qt6-webengine/riscv64.patch
:droplet: :droplet: :droplet: :droplet: :droplet: :droplet:
> fixpkg: qt6-webengine

- qt5-webengine/riscv64.patch
> updpkg: qt5-webengine 5.15.9

- terraform/riscv64.patch
This PR increases test timeout.
> fixpkg: terraform

- arpwatch/riscv64.patch
Fix trivial issue with config.guess and config.sub
> addpkg: arpwatch

- mkinitcpio-busybox/riscv64.patch
> upgpkg: mkinitcpio-busybox

- httplz/riscv64.patch
Fix trivial issue with cargo fetch
> addpkg: httplz

- qemu-user-blacklist.txt
- systemd/riscv64.patch
also add systemd into qemu-user-blacklist?
> upgpkg: systemd

- firefox/riscv64.patch
fixed `error: redefinition of 'ROOT_CLIP_CHAIN` , https://bugzilla.mozilla.org/show_bug.cgi?id=1773259 .
> upgpkg: firefox

- hdf5-openmpi/riscv64.patch
> addpkg: hdf5-openmpi

- ninjas2/remove-unsupported-mtune-flag.patch
- ninjas2/riscv64.patch
upstream has already updated the submodule, but idk when a new release will come :(
> addpkg: ninjas2

- grcov/riscv64.patch
Fix a trivial issue with `cargo fetch`
> addpkg: grcov

- rustscan/riscv64.patch
Fixed cargo target error and patched `ring` dep.
> addpkg: rustscan

- uqm/riscv64.patch
Fix checksum & source array mismatch.
> fixpatch: uqm

- qt6-webengine/riscv64.patch
fix it before it actually fails
> fixpatch: qt6-webengine

- telegram-desktop/riscv64.patch
Upstream PR: https://github.com/telegramdesktop/tdesktop/pull/24706
> addpkg: telegram-desktop

- openmpi/riscv64.patch
> upgpkg: openmpi

- wezterm/riscv64.patch
> updpatch: wezterm

- partclone/riscv64.patch
Update outdated `config.guess` file.
> addpatch: partclone

- curl/riscv64.patch
the upstream release is missing an include, fixed in https://github.com/curl/curl/commit/e2e7f54b7bea521fa8373095d0f43261a720cda0.patch
> addpatch: curl

- v2ray/riscv64.patch
> fixpatch: v2ray

- cargo-edit/riscv64.patch
> updpkg: cargo-edit.

- qt5-webkit/riscv64.patch
> upgpatch: qt5-webkit

- npm/riscv64.patch
> upgpatch: npm

- opentoonz/riscv64.patch
ref https://github.com/opentoonz/opentoonz/issues/4474
> addpatch: opentoonz

- liborcus/riscv64.patch
Fix trivial issue with config.guess and config.sub
FYI, I also filed an issue to notify upstream this issue.
https://gitlab.com/orcus/orcus/-/issues/161
> addpkg: liborcus

- exempi/riscv64.patch
another TRIVIAL fix, see: https://gitlab.freedesktop.org/libopenraw/exempi/-/issues/29
> addpatch: exempi

- llvm13/riscv64.patch
> addpatch: llvm13

- bupstash/riscv64.patch
Removed `--target "$CARCH-unknown-linux-gnu"`.
Build passed.
> addpkg: bupstash

- avldrums.lv2/riscv64.patch
> upgpatch: avldrums.lv2

- gnupg/riscv64.patch
Update autotool configurations.
This problem will be reported to upstream and updated here later, because my account is still waiting for approval.
> addpatch: gnupg

- maturin/riscv64.patch
Remove unnecessary error handling for the updated clean patch.
> fixpatch: maturin

- cmake/riscv64.patch
> upgpatch: cmake

- curl/riscv64.patch
[FS#75201](https://bugs.archlinux.org/task/75201)
> updpkg: curl

- libc++/riscv64.patch
> upgpatch: libc++

- bazel/riscv64.patch
- qemu-user-blacklist.txt
Able to build using qemu-user with https://github.com/bazelbuild/bazel/commit/d3435b09d89f25bf5008ef3b9c870c835d51a8da.
> upgpkg: bazel 5.2.0-1

- ldc/disable-static-NaN-tests.patch
- ldc/riscv64.patch
Require bootstrap before merging.
> addpkg: ldc

- git-grab/riscv64.patch
Removed `--target "$CARCH-unknown-linux-gnu"`
Build passed
> addpkg: git-grab

- gnupg/riscv64.patch
Fix warning:
```
NOTE: THIS IS A DEVELOPMENT VERSION!
It is only intended for test purposes and should NOT be
used in a production environment or with production keys!
```
> fixpatch: gnupg

- codeblocks/riscv64.patch
> upgpatch: codeblocks

- audacity/riscv64.patch
> upgpatch: audacity

- megaglest/riscv64.patch
> upgpatch: megaglest

- nilfs-utils/riscv64.patch
a nice trivial patch.
upstream issue at https://github.com/nilfs-dev/nilfs-utils/issues/20
> addpatch: nilfs-utils

- menyoki/riscv64.patch
> addpatch: menyoki

- libclastfm/riscv64.patch
> addpkg: libclastfm

- qemu-user-blacklist.txt
> qemu-user-blacklist: add menyoki

- zellij/riscv64.patch
> upgpatch: zellij

- element/riscv64.patch
> upgpatch: element

- kubo/riscv64.patch
go-ipfs is replaced by kubo
#423 #1535
> addpkg: kubo

- lame/riscv64.patch
> addpkg: lame

- ccls/riscv64.patch
> fixpatch: ccls

- namcap/riscv64.patch
> fixpatch: namcap

- zellij/riscv64.patch
> fixpatch: zellij

- cryptsetup/riscv64.patch
> addpkg: cryptsetup

- llvm13/riscv64.patch
> updpatch: llvm13

- marisa/riscv64.patch
> updpatch: marisa

- glibc/riscv64.patch
> fixpatch: glibc

- expect/riscv64.patch
> addpkg: expect

- harfbuzz/riscv64.patch
Fix signedness mismatch in a test.
> addpkg: harfbuzz

- namcap/fix-riscv64-test.patch
- namcap/riscv64.patch
fix test on riscv64, so it can pass all tests and be built **without** `--nocheck`.
> fixpkg: namcap

- aiksaurus/riscv64.patch
remove old patch and fix config.guess
> updpatch: aiksaurus

- zellij/riscv64.patch
> upgpatch: zellij 0.31.1-1

- haskell-cryptonite/riscv64.patch
delete  `sse` option from PKGBUILD
> addpatch: haskell-cryptonite

- libaio/riscv64.patch
Tests are still failing like before.
> fixpatch: libaio

- darktable/riscv64.patch
Upstreamed PR: https://github.com/darktable-org/darktable/pull/11797 and https://github.com/darktable-org/rawspeed/pull/363
> addpatch: darktable 2:4.0.0-1

- pass/riscv64.patch
> upgpatch: pass 1.7.4-3

- js91/Disable-floating-pointcontraction.patch
- js91/riscv64.patch
fix test , patch from https://bugzilla.mozilla.org/show_bug.cgi?id=1755531
> Updpatch: js91 to 91.12

- python-levenshtein/riscv64.patch
> addpatch: python-levenshtein

- rust/riscv64.patch
> updpatch: rust 1.63.0

- brltty/riscv64.patch
upstreamed at: https://github.com/brltty/brltty/pull/389
> addpatch: brltty

- mxml/0001-Update-config.guess-and-config.sub-Issue-296.patch
- mxml/riscv64.patch
This is a trivial issue. However, there's something wierd in upstream which makes me unable to `autoreconf`. See details here https://github.com/michaelrsweet/mxml/issues/296. So, I just backport upstream patch to fix.
> addpatch: mxml

- kubernetes/riscv64.patch
> upgpatch: kubernetes 1.24.3-2

- java17-openjdk/riscv64.patch
> upgpatch: java17-openjdk 17.0.4.u8-2

- graphviz/riscv64.patch
> upgpatch: graphviz 5.0.0-2

- ostree/riscv64.patch
> fixpatch: ostree

- most/riscv64.patch
Fix issue with outdated config.guess. Also filed an issue to upstream.
https://github.com/jedsoft/most/issues/13
> addpatch: most

- cmake/riscv64.patch
> updpatch: cmake

- tickrs/riscv64.patch
remove the `--target "$CARCH-unknown-linux-gnu"` option
> addpatch: tickrs

- cmake/riscv64.patch
Fix rotten. Update to cmake 3.24.1
> addpatch: cmake

- libspatialite/riscv64.patch
Fix build problem with config.guess and config.sub. Also filed an ticket to upstream.
https://www.gaia-gis.it/fossil/libspatialite/tktview?name=6faa96eb5d
> addpatch: libspatialite

- python-jsonpatch/riscv64.patch
Disable pypandoc until we have proper pandoc.
> addpatch: python-jsonpatch

- java17-openjdk/riscv64.patch
> upgpatch: java17-openjdk 17.0.4.1.u1-2

- typescript-language-server/riscv64.patch
> upgpatch: typescript-language-server 1.1.1-1

- dhcp/autoreconf-bind.patch
- dhcp/riscv64.patch
Fix rotten and update config.guess. Also filed two issues to notify upstream,
https://gitlab.isc.org/isc-projects/dhcp/-/issues/256
https://gitlab.isc.org/isc-projects/bind9/-/issues/3506
> updpatch: dhcp

- lldb/riscv64.patch
> upgpatch: lldb 14.0.6-1

- auth-tarball-from-git/riscv64.patch
Fix `--target "$CARCH-unknown-linux-gnu"` trivial.
> addpkg: auth-tarball-from-git

- x264/riscv64.patch
Fix an issue with config.guess and config.sub. Also filed an issue to notify upstream.
https://code.videolan.org/videolan/x264/-/issues/52
> updpatch: x264

- stylua/riscv64.patch
> fixpatch: stylua 0.14.3

- libgovirt/riscv64.patch
Upstream MR: https://gitlab.gnome.org/GNOME/libgovirt/-/merge_requests/21
> addpatch: libgovirt 1:0.3.9-1

- symengine/riscv64.patch
> fixpatch: symengine

- kubie/riscv64.patch
> upgpatch: kubie 0.19.0-1

- ffmpeg/riscv64.patch
> upgpatch: ffmpeg 2:5.1.1-3

- .github/workflows/test.yml
- tbb/riscv64.patch
- test.sh
> CI perform validity check for sources

- rz-ghidra/riscv64.patch
update add-riscv64-to-types.patch checksum
> updpatch: rz-ghidra

- gsoap/riscv64.patch
> addpkg: gsoap

- riff/riscv64.patch
remove `--target "$CARCH-unknown-linux-gnu"` for `cargo build`
> addpkg: riff

- glibc/riscv64.patch
Fix rotten. I'm still investigating tst-strfrom failure. I will upload test results when build finishes.
> updpatch: glibc

- libretro-ppsspp/riscv64.patch
Upstream PR: https://github.com/hrydgard/ppsspp/pull/16027
> addpatch: libretro-ppsspp 33325-1

- ibus-unikey/riscv64.patch
> addpatch: ibus-unikey

- firefox/riscv64.patch
> updpatch: firefox

- vtk/riscv64.patch
> updpatch: vtk

- flashrom/riscv64.patch
Update to latest master as cherry-picking isn't feasible here (too old release).
> addpatch: flashrom

- firefox/makotokato-riscv64-support-and-zenithal-backported.patch
- firefox/riscv64.patch
1. Porting partial JIT support from https://github.com/makotokato/gecko-dev/tree/riscv64
2. update firefox to 105.0
> updpatch:  firefox

- cargo-tauri/riscv64.patch
> updpatch: cargo-tauri

- qemu-user-blacklist.txt
Tests fail in qemu-user.
FAIL: stack-overflow
> addpatch: grep

- haskell-primitive-unaligned/riscv64.patch
Upstream PR:
https://github.com/haskell-primitive/primitive-unaligned/pull/11
> addpatch: haskell-primitive-unaligned

- opencv/riscv64.patch
Upstream fixed patch checksum in https://github.com/archlinux/svntogit-packages/commit/a83e8bc42850dd92162827b1bd8402e71dc3cc17
> updpatch: opencv

- gtk4/riscv64.patch
> addpatch: gtk4

- grafana-zabbix/riscv64.patch
> fixpatch: grafana-zabbix

- sqlc/riscv64.patch
Upstream PRs: 
+ pganalyze/pg_query_go#62
+ remyoudompheng/bigfft#19
> addpatch: sqlc

- hexyl/riscv64.patch
> addpkg: hexyl

- qemu-user-blacklist.txt
- sqlc/riscv64.patch
+ Use `JMP` primitive
+ Add to qemu-user-blacklist to prevent unrecoverable sleep on qemu-user
> updpatch: sqlc

- kcov/riscv64.patch
Upstream PR: SimonKagstrom/kcov#385
> addpatch: kcov

- qsopt-ex/riscv64.patch
> addpatch: qsopt-ex

- darktable/riscv64.patch
> upgpatch: darktable 2:4.0.1-1

- lsd/riscv64.patch
Fix the target not found issues.
> addpatch: lsd

- gtksourceview5/riscv64.patch
upstreamed at: https://gitlab.gnome.org/GNOME/gtksourceview/-/merge_requests/289
> addpatch: gtksourceview5

- sdl_sound/riscv64.patch
> addpatch: sdl_sound

- libatomic_ops/riscv64.patch
Update config.guess.
Issue reported: https://github.com/ivmai/libatomic_ops/issues/54
> addpkg: libatomic_ops

- mold/riscv64.patch
> updpatch: mold

- taplo-cli/riscv64.patch
> updpatch: taplo-cli

- vifm/riscv64.patch
> addpatch: vifm

- jpegoptim/riscv64.patch
> addpatch: jpegoptim

- qt6-webengine/riscv64.patch
> upgpatch: qt6-webengine 6.3.2-1

- ttf-ibm-plex/riscv64.patch
Update the package sums (also FTBFS in x86_64).
Bug reported: https://bugs.archlinux.org/task/75318
> addpkg: ttf-ibm-plex

- mupen64plus/riscv64.patch
> fixpatch: mupen64plus

- qemu-user-blacklist.txt
- many test failures due to reading /proc/self/exe
> addpatch: ihaskell

- exa/riscv64.patch
remove cargo argv: `--target "$CARCH-unknown-linux-gnu"`
> addpatch: exa

- qt6-quick3dphysics/physx-rv64.patch
- qt6-quick3dphysics/riscv64.patch
with `PX_SIMD_DISABLED` set to 1
> addpatch: qt6-quick3dphysics

- valgrind/riscv64.patch
> updpatch: valgrind

- cargo-audit/riscv64.patch
> upgpatch: cargo-audit 0.17.2-1

- kmon/riscv64.patch
> addpatch: kmon

- cargo-edit/riscv64.patch
> upgpatch: cargo-edit 0.11.5-1

- haskell-swagger2/riscv64.patch
> updpatch: haskell-swagger2

- libetonyek/riscv64.patch
The official contributing guide says, " (Some patch you created) These you can send to libreoffice@lists.freedesktop.org."
So can only send email.
And I has sent a issue email to the organization.
**Perhaps useful links**:
[Official website](https://wiki.documentfoundation.org/DLP/Libraries/libetonyek#Contributing)
TinySnow
Oct 17th, 2022.
> addpkg: libetonyek

- sequoia-wot/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu`.
TinySnow
Oct 18th, 2022.
> addpkg: sequoia-wot

- go/riscv64.patch
> upgpatch: go 2:1.19.2-1

- himalaya/riscv64.patch
> upgpatch: himalaya 0.6.1-1

- gfold/riscv64.patch
> updpkg: gfold

- opensbi/PKGBUILD
> upgpkg: opensbi 1.1-1

- mdcat/riscv64.patch
> upgpatch: mdcat 0.29.0-1

- cargo-depgraph/riscv64.patch
> updpkg: cargo-depgraph

- alacritty/riscv64.patch
> updpkg: alacritty

- m17n-lib/riscv64.patch
Just update config.guess by autoreconf.
Upstream: https://savannah.nongnu.org/bugs/index.php?63276
> addpatch: m17n-lib

- java11-openjdk/riscv64.patch
Disable broken shenandoahgc for now.
> upgpatch: java11-openjdk 11.0.17.u1-1

- libvisio/riscv64.patch
Fix incompatible config.guess file.
> addpatch: libvisio

- libzmf/riscv64.patch
Fix config.guess too old issue. Upstream report: https://bugs.documentfoundation.org/show_bug.cgi?id=151782
> addpatch: libzmf

- java17-openjdk/java17-riscv64.patch
- java17-openjdk/riscv64.patch
> upgpatch: java17-openjdk 17.0.5.u1-1

- highway/replace-rdcycle-with-rdtime.patch
- highway/riscv64.patch
Backport of
https://github.com/google/highway/commit/12ca8ff15390ccc4ef0a257ec095bb50e8b288c0.
> fixpkg: highway

- at/riscv64.patch
I will open a PR in upstream later, because my https://salsa.debian.org account is still pending approval.
> addpatch: at 3.2.5-2

- cargo-deny/riscv64.patch
> upgpatch: cargo-deny 0.13.1-1

- libe-book/riscv64.patch
Bug report is delayed because I forgot my SourceForge password.
> addpatch: libe-book

- gcc/libitm-riscv64.patch
- gcc/riscv64.patch
Add riscv support to libitm and enable it in PKGBUILD
> updpatch: gcc

- stylua/riscv64.patch
> updpkg: stylua

- wvstreams/riscv64.patch
Upstream: https://github.com/apenwarr/wvstreams/pull/4
But upstream has not released an update for 12 years.
> addpatch: wvstreams

- cmake/riscv64.patch
> upgpatch: cmake 3.24.3-1

- cargo-auditable/riscv64.patch
> addpkg: cargo-auditable

- dhall-docs/riscv64.patch
> updpatch: dhall-docs

- pixman/riscv64.patch
> updpatch: pixman

- golang-github-pmezard-go-difflib/riscv64.patch
Arch Linux bug report: https://bugs.archlinux.org/task/74825
> addpatch: golang-github-pmezard-go-difflib 1.0.0-2

- linux/riscv64.patch
Remove patch present in new release.
> updpatch: linux 6.0.7.arch1-1

- libshumate/riscv64.patch
> addpatch: libshumate

- nautilus/riscv64.patch
> addpatch: nautilus

- libgpod/riscv64.patch
- Disable mono bindings until we have mono
- Update config.guess etc.
> addpatch: libgpod

- mkinitcpio/riscv64.patch
Remove upstreamed spi patch. Supersedes #1892
> updpatch: mkinitcpio 32-2

- qemu-user-blacklist.txt
C++ compiler will fatal with segment fault error in qemu user. Everything works fine in unmatched board.
> noqemu: qbs

- hplip/riscv64.patch
> upgpatch: hplip 1:3.22.10-1

- moc/riscv64.patch
> addpatch: moc

- pueue/riscv64.patch
> upgpatch: pueue 2.1.0-1

- neovim/riscv64.patch
Use lua51 instead of luajit because it doesn't support RISC-V (https://github.com/LuaJIT/LuaJIT/issues/628)
> addpatch: neovim

- ostree/riscv64.patch
> upgpatch: ostree 2022.6-4

- libreoffice-fresh/riscv64-support.patch
- libreoffice-fresh/riscv64.patch
Based on
- https://git.libreoffice.org/core/+/bc9487f745befde6534fd46058e119256952323d
- https://github.com/FirebirdSQL/firebird/commit/1e8e7858db84750a77006d307bf28e9686f9414e
- https://github.com/FirebirdSQL/firebird/commit/8a5b97db3cb519363e5436eedafa763d093890eb
> addpkg: libreoffice-fresh

- ntp/riscv64.patch
> addpatch: ntp

- python-executing/fix-test-many-source-for-filename-calls-timeout.patch
- python-executing/riscv64.patch
> addpatch: python-executing

- clamav/riscv64.patch
The rust test need more time to finish on our machine.
> addpatch: clamav

- ams-lv2/riscv64.patch
Fix rotten.
Reported to upstream: https://github.com/blablack/ams-lv2/pull/47
> updpatch: ams-lv2

- libsecret/riscv64.patch
It is just another timeout problem :(
Tested on larvesta and reshiram.
> addpatch: libsecret

- hyphen/riscv64.patch
Fix config.guess cannot guess build type issues.
> addpatch: hyphen

- ijs/riscv64.patch
Fix config.guess cannot guess build type issue.
> addpatch: ijs

- glpk/riscv64.patch
Fix config.guess cannot guess build type issue.
> addpatch: glpk

- libepubgen/riscv64.patch
Fix config.guess cannot guess build type issue.
> addpatch: libepubgen

- libmwaw/riscv64.patch
Fix config.guess fail to figure build type issue.
> addpatch: libmwaw

- librevenge/riscv64.patch
> addpatch: librevenge

- pipewire/riscv64.patch
> updpatch: pipewire

- libwpg/riscv64.patch
Upstream: https://sourceforge.net/p/libwpd/tickets/21/
> addpatch: libwpg

- qt6-webengine/riscv64.patch
> upgpatch: qt6-webengine 6.4.1-1

- arch-audit-gtk/riscv64.patch
> addpkg: arch-audit-gtk

- libwps/riscv64.patch
Upstream URL: https://sourceforge.net/p/libwps/bugs/15/.
> addpkg: libwps

- opencv/riscv64.patch
> updpatch: opencv 4.6.0-6

- dateutils/riscv64.patch
> addpatch: dateutils

- dog/riscv64.patch
> upgpatch: dog 0.1.0-4

- xorg-fonts-100dpi/riscv64.patch
> addpatch: xorg-fonts-100dpi

- cargo-geiger/riscv64.patch
Fix Rust target not found issue.
> addpatch: cargo-geiger

- vnstat/riscv64.patch
https://github.com/vergoh/vnstat/issues/239
> addpatch: vnstat

- pidgin-otr/riscv64.patch
I've notified the upstream via mail list.
> addpatch: pidgin-otr

- cxxbridge/riscv64.patch
> addpatch: cxxbridge

- libxmlrpc/riscv64.patch
> addpatch: libxmlrpc

- libdiscid/riscv64.patch
https://tickets.metabrainz.org/browse/LIB-67
> addpatch: libdiscid

- eva/riscv64.patch
> upgpatch: eva 0.3.1-1

- darktable/riscv64.patch
> upgpatch: darktable 2:4.0.1-3

- namazu/riscv64.patch
FYI: Upstream bug tracker seems to be down (http://www.namazu.org/trac-namazu/trac.cgi/wiki/WikiStart.en)
> addpatch: namazu

- spotify-launcher/riscv64.patch
> addpatch: spotify-launcher

- typescript-language-server/riscv64.patch
> upgpatch: typescript-language-server 2.1.0-1

- whitedb/riscv64.patch
https://github.com/priitj/whitedb/issues/63
> addpatch: whitedb

- passenger/riscv64.patch
https://github.com/phusion/passenger/issues/2454
> addpatch: passenger

- mate-applet-streamer/riscv64.patch
https://github.com/assen-totin/mate-applet-streamer/issues/10
> addpatch: mate-applet-streamer

- libgdamm/riscv64.patch
https://gitlab.gnome.org/GNOME/libgdamm/-/issues/4
> addpatch: libgdamm

- coin-or-clp/riscv64.patch
This PR fix the config.guess issue.
> addpatch: coin-or-clp

- coin-or-mp/riscv64.patch
Upstream report: https://github.com/coin-or/CoinMP/issues/24
> addpatch: coin-or-mp

- spotifyd/riscv64.patch
> addpatch: spotifyd

- flatpak/riscv64.patch
> addpatch: flatpak

- js102/riscv64.patch
- js102/tests-skip-some-tests-on-rv64.patch
> fixpatch: js102

- smpeg/riscv64.patch
Fix config,guess issue.
Upstream has fixed this problem. You can check at https://github.com/icculus/smpeg/blob/main/config.guess
> updpatch: smpeg

- xplr/remove-luajit.patch
- xplr/riscv64.patch
Use lua51 instead of luajit until we have luajit.
> addpatch: xplr

- dra/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu"` and `ring` issue.
> addpkg: dra

- dub/riscv64.patch
> updpkg: dub

- cantor/riscv64.patch
Disable luajit & julia until we have them packaged.
> addpatch: cantor

- onefetch/riscv64.patch
Fixed rotten.
The maintainer's info has been changed, git diff contains it.
If that should not be included, please tell me.
> updpkg: onefetch

- ostree/riscv64.patch
> updpkg: ostree

- libwpd/riscv64.patch
Fixed `config.guess` issue.
Upstream url: http://bugzilla.abisource.com/show_bug.cgi?id=13971.
> addpkg: libwpd

- systemd/riscv64.patch
> updpatch: systemd

- ffcall/riscv64-pic.patch
- ffcall/riscv64.patch
Backport upstream commit: https://git.savannah.gnu.org/gitweb/?p=libffcall.git;a=commit;h=5376cb6cfdaa45401c78810cbd673be0f5cac543
> addpatch: ffcall

- guile1.8/riscv64.patch
> addpatch: guile1.8

- fillets-ng/riscv64.patch
> addpatch: fillets-ng

- netavark/riscv64.patch
> upgpatch: netavark 1.4.0-1

- sequoia-wot/riscv64.patch
> upgpatch: sequoia-wot 0.3.0-1

- skim/riscv64.patch
> upgpatch: skim 0.10.2-1

- dolphin-emu/riscv64.patch
> upgpatch: dolphin-emu 1:5.0.r17995.8bad821019-2

- bnfc/riscv64.patch
> upgpatch: bnfc 2.9.4.1-1

- uwsgi/riscv64.patch
> upgpatch: uwsgi 2.0.21-3

- devtools-riscv64/PKGBUILD
- devtools-riscv64/sogrep-riscv64
Based on the devtools version, modified to archriscv's paths.
Ref: https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/src/sogrep.in
> devtools-riscv64: add sogrep-riscv64

- libmodplug/riscv64.patch
https://sourceforge.net/p/modplug-xmms/bugs/22/
> addpatch: libmodplug

- a52dec/riscv64.patch
Fix config.guess issue. Reported to upstream via mailing list and
is currently waiting approval. So there is currently no URL to trace the
upstream status.
> addpatch: a52dec

- dmapi/riscv64.patch
> upgpatch: dmapi

- chmlib/riscv64.patch
> upgpatch: chmlib

- libtiger/riscv64.patch
Fix config.guess could not guess build type issue. This project was
turned down and archived. So there is no way to report the autotools
issue.
> addpatch: libtiger

- qrencode/riscv64.patch
Upstream: https://github.com/fukuchi/libqrencode/issues/202.
> addpkg: qrencode

- age-plugin-yubikey/riscv64.patch
> addpkg: age-plugin-yubikey

- bitcoin/riscv64.patch
> updpkg: bitcoin

- pacman-mirrorlist/PKGBUILD
- pacman-mirrorlist/mirrorlist
Add a real mirrorlist. Will adjust pacman & devtools too.
> updpkg: pacman-mirrorlist 20230111

- espflash/riscv64.patch
> addpkg: espflash

- cargo-tarpaulin/riscv64.patch
> addpkg: cargo-tarpaulin

- qt6-webengine/riscv64.patch
> upgpatch: qt6-webengine 6.4.2-1

- mastodon-twitter-sync/riscv64.patch
Fix:
* Cargo unknown target triple
* ring build.rs failure
> addpkg: mastodon-twitter-sync

- yasm/riscv64.patch
Backport: https://github.com/yasm/yasm/commit/3e74376b5653102a3957f59005969fcdbbe5a89d
> addpkg: yasm

- ldproxy/riscv64.patch
> addpkg: ldproxy

- pacman/riscv64.patch
> upgpatch: pacman

- spotifyd/riscv64.patch
> upgpatch: spotifyd

- .github/workflows/rotten.yml
- find-rotten
Avoid false negative reports for non-existent packages when using `asp list-all`.
Sending rmvpatch PR is untouched and untested, which should work. 🤔
> find-rotten: get package list from alpm

- newsboat/riscv64.patch
> addpkg: newsboat

- plumber/riscv64.patch
> updpatch: plumber

- espup/riscv64.patch
Fix broken rust target and ring.
> addpatch: espup

- exiv2/riscv64.patch
> updpatch: exiv2

- lldb/riscv64.patch
> updpatch: lldb

- partimage/riscv64.patch
> addpatch: partimage

- mesa/riscv64.patch
This patch only disables mesa intel.
> updpatch: mesa

- libirman/riscv64.patch
Upstream bug report: https://sourceforge.net/p/libirman/tickets/3/
> addpatch: libirman

- openpgp-card-tools/riscv64.patch
> addpatch: openpgp-card-tools

- linux-atm/riscv64.patch
Upstream bug report: https://sourceforge.net/p/linux-atm/bugs/26/
> addpatch: linux-atm

- reiserfsprogs/riscv64.patch
Fix config.guess can not guess build type error.
> addpatch: reiserfsprogs

- angband/riscv64.patch
upstream: https://github.com/angband/angband/issues/5617.
> addpkg: angband

- cargo-llvm-cov/riscv64.patch
> addpkg: cargo-llvm-cov

- cargo-about/riscv64.patch
Fix target tripple and ring issues.
> addpatch: cargo-about

- cargo-generate/riscv64.patch
> upgpatch: cargo-generate

- cargo-update/riscv64.patch
Fix rustc target triple issue.
> addpatch: cargo-update

- cargo-ndk/riscv64.patch
> addpatch: cargo-ndk

- find-rotten
Let's see if it has better uptime than rackspace!
> find-rotten: use official geo mirror

- cargo-edit/riscv64.patch
> upgpatch: cargo-edit

- qemu-user-blacklist.txt
Details: https://github.com/felixonmars/archriscv-packages/issues/2192
> noqemu: diffutils

- rust/riscv64.patch
+ Crate `cc` has been bumped in `rustc`
> updpatch: rust 1.67.1

- qemu/riscv64.patch
fix patch not applying to qemu 7.2.0-3
> updpatch: qemu 7.2.0-3

- xdp-tools/riscv64.patch
Fix undefined reference to floor, ceil...
> addpatch: xdp-tools 1.3.0-1

- dust/riscv64.patch
> updpatch: dust

- cocogitto/riscv64.patch
> updpatch: cocogitto

- boinc/riscv64.patch
> updpatch: boinc

- hm/riscv64.patch
> updpatch: hm

- barrage/riscv64.patch
Fix config.guess file.
upstream ticket: https://sourceforge.net/p/lgames/support-requests/4/
> updpatch: barrage

- libmad/riscv64.patch
Fix config.guess issue. Email has been sent to upstream but not in
archive yet.
> addpatch: libmad

- libjxl/riscv64.patch
upstream: https://github.com/libjxl/libjxl/pull/2211
> updpatch : libjxl

- lychee/riscv64.patch
Renamed from lychee-link-checker with minor adjustment.
> addpatch: lychee

- luajit/riscv64.patch
JIT disabled.
FFI is not available yet. Software which uses FFI may not work.
I will make a cleanup for luajit patches in a separate PR.
> addpatch: luajit

- sscg/riscv64.patch
Disable time limit due to known low performance.
> addpkg: sscg

- zita-resampler/riscv64.patch
> updpatch: zita-resampler

- love/riscv64.patch
Upstream report: https://github.com/love2d/love/issues/1907
> addpkg: love

- igrep/riscv64.patch
> addpkg: igrep

- mumble/riscv64.patch
1. fix rotten patch
2. fix signedness issue of char
> updpatch: mumble

- critter/riscv64.patch
Fix config.guess issue. I cannot find a way to report to upstream. No mailing list nor issue🥲
> updpatch: critter

- moosefs/riscv64.patch
Upstream issue: https://github.com/moosefs/moosefs/issues/525
> addpatch: moosefs

- spandsp/riscv64.patch
Fix config.guess could not guess build type issue. Issue has been
reported to upstream via email.
> addpatch: spandsp

- libgpod/riscv64.patch
> updpatch: libgpod

- consul/riscv64.patch
> addpkg: consul

- libjpeg-turbo/riscv64.patch
> updpatch: libjpeg-turbo

- gitoxide/riscv64.patch
This PR fixes the build error from ring.
> upgpatch: gitoxide 0.22.1-1

- xxhash/riscv64.patch
Disable the x86/x86_64 only option DISPATCH.
> addpkg: xxhash

- opensp/riscv64.patch
upstream: https://sourceforge.net/p/openjade/feature-requests/15/
> addpatch: opensp

- mcpp/riscv64.patch
upstream: https://sourceforge.net/p/mcpp/bugs/15/
> addpatch: mcpp

- cargo-deb/riscv64.patch
Fix rustc target triple issue.
> addpatch: cargo-deb

- luajit/riscv64.patch
> upgpatch: luajit

- libnids/riscv64.patch
> updpkg: libnids

- lldb/riscv64.patch
> updpkg: lldb

- mesa-dri1/riscv-mmio-barrier.patch
- mesa-dri1/riscv64.patch
Implements `MMIO_WMB` for RISC-V
> addpatch: mesa-dri1

- postgresql/riscv64.patch
> updpkg: postgresql

- cargo-auditable/riscv64.patch
> upgpatch: cargo-auditable 0.6.1-1

- privoxy/riscv64.patch
Update config.guess to support riscv64
> addpkg: privoxy

- chromium/riscv-angle.patch
- chromium/riscv-crashpad.patch
- chromium/riscv-sandbox.patch
- chromium/riscv64.patch
Update to the latest openSUSE patch.
> upgpatch: chromium 111.0.5563.64-2

- openpgp-ca/riscv64.patch
Removed `--target "$CARCH-unknown-linux-gnu"` from `prepare`.
> addpatch: openpgp-ca

- nodejs/riscv64.patch
> upgpatch: nodejs 19.7.0-1

- soundkonverter/riscv64.patch
> upgpatch: soundkonverter 3.0.1-6

- nzbget/riscv64.patch
> upgpatch: nzbget 21.1-2

- warzone2100/riscv64.patch
> upgpatch: warzone2100 4.3.3-1

- js102/riscv64.patch
> updpatch: js102 102.9.0

- java-rxtx/riscv64.patch
> upgpatch: java-rxtx 2.2pre2-9

- v2ray/riscv64.patch
> upgpatch: v2ray 5.3.0-1

- qt5-webengine/riscv64.patch
> updpatch: qt5-webengine 5.15.13-1

- avldrums.lv2/riscv64.patch
> fixpatch: avldrums.lv2

- cargo-make/riscv64.patch
- Replace `ring`
- Fix `cargo fetch`
> addpatch: cargo-make

- qt6-quick3dphysics/riscv64.patch
> fixpatch: qt6-quick3dphysics

- polkit-gnome/riscv64.patch
[Upstream repo](https://gitlab.gnome.org/Archive/policykit-gnome) has been archived.
> addpatch: polkit-gnome

- bluefish/riscv64.patch
Upstream bug report: https://sourceforge.net/p/bluefish/tickets/68/
> addpatch: bluefish

- linuxsampler/riscv64.patch
> upgpatch: linuxsampler

- rust-rage/riscv64.patch
> upgpatch: rust-rage

- calf/riscv64.patch
> upgpatch: calf

- fabla/riscv64.patch
> upgpatch: fabla

- galculator/riscv64.patch
Upstream report: https://github.com/galculator/galculator/issues/57
> addpatch: galculator

- python-tqdm/riscv64.patch
tests_perf.py can't finish within the default timeout.
> addpatch: python-tqdm

- cri-tools/riscv64.patch
Replace `amd64` with `$(go env GOARCH)`.
> addpatch: cri-tools

- bin86/bin86-riscv64.patch
- bin86/riscv64.patch
Add definition of `Long` as `int` for riscv64.
> addpatch: bin86

- nextcloud-app-notify_push/riscv64.patch
> upgpatch: nextcloud-app-notify_push

- patch-linux-config.sh
Remember do tests after NFC that you think...
> fix(linux-config-maintain): bash syntax error

- trippy/riscv64.patch
> addpatch: trippy

- psiconv/riscv64.patch
And fix the config.guess issue.
> updpkg: psiconv

- rust/riscv64.patch
> updpatch: rust 1.68.2

- systemc/riscv64.patch
> updpkg: systemc

- x42-plugins/riscv64.patch
> updpkg: x42-plugins

- simplescreenrecorder/riscv64.patch
> updpkg: simplescreenrecorder

- artyfx/riscv64.patch
> updpkg: artyfx

- uwsgi/riscv64.patch
> upgpatch: uwsgi

- eq10q/riscv64.patch
> updpkg: eq10q

- a2jmidid/riscv64.patch
> updpkg: a2jmidid

- ffmpeg/riscv64.patch
> updpatch: ffmpeg

- spectmorph/riscv64.patch
> upgpatch: spectmorph

- postgrest/riscv64.patch
> updpkg: postgrest

- web-ext/riscv64.patch
> upgpatch: web-ext

- python-pylint/riscv64.patch
> updpkg: python-pylint

- ripgrep-all/riscv64.patch
> updpkg: ripgrep-all

- opengv/riscv64.patch
Modify PKGBUILD and remove upstream patch which would break support for riscv64
> updpatch: opengv

- blop/riscv64.patch
> addpatch: blop

- libassuan/riscv64.patch
Fix old config.guess. Upstream has already updated their config.guess but they haven't made  a new release.
> addpatch: libassuan

- grafana/riscv64.patch
Modify PKGBUILD and update patch.
> updpatch: grafana

- ninjas2/riscv64.patch
> upgpatch: ninjas2

- drumgizmo/riscv64.patch
> updpkg: drumgizmo

- python-cmsis-pack-manager/riscv64.patch
> updpatch: python-cmsis-pack-manager

- elinks/riscv64.patch
https://github.com/rkd77/elinks/issues/209
> addpkg: elinks

- typst/riscv64.patch
> upgpatch: typst

- gifski/riscv64.patch
Backport unsigned char fix for ffmpeg-next@4.4.0.
> addpatch: gifski

- webkitgtk-6.0/fix-riscv64-build.patch
- webkitgtk-6.0/riscv64.patch
See https://github.com/felixonmars/archriscv-packages/pull/2459
> addpatch: webkitgtk-6.0

- webkit2gtk-4.1/fix-riscv64-build.patch
- webkit2gtk-4.1/riscv64.patch
See https://github.com/felixonmars/archriscv-packages/pull/2459
> addpatch: webkit2gtk-4.1

- kooha/riscv64.patch
> upgpatch: kooha

- hplip/riscv64.patch
> upgpatch: hplip

- sdl2_gfx/riscv64.patch
> updpkg: sdl2_gfx

- helix/riscv64.patch
> upgpatch: helix

- xplr/riscv64.patch
- xplr/use-system-luajit.patch
Also upstream: https://bugs.archlinux.org/task/78155
> upgpatch: xplr

- sdl_image/riscv64.patch
> addpkg: sdl_image

- sdl_mixer/riscv64.patch
> addpkg: sdl_mixer

- stylelint/riscv64.patch
> upgpatch: stylelint

- xsv/riscv64.patch
> addpatch: xsv

- svelte-language-server/increase-test-timeout.patch
- svelte-language-server/riscv64.patch
> addpatch: svelte-language-server

- projectm/riscv64.patch
Update config.guess
https://github.com/projectM-visualizer/projectm/issues/715
> addpkg: projectm

- sequoia-sq/riscv64.patch
> addpkg: sequoia-sq

- sugar-runner/riscv64.patch
Update config.guess
http://lists.sugarlabs.org/archive/sugar-devel/2023-April/059540.html
> addpkg: sugar-runner

- xcftools/riscv64.patch
Update config.guess
This project has been out of maintenance since 2009.
> addpkg: xcftools

- angle-grinder/riscv64.patch
> upgpatch: angle-grinder

- imagescan/riscv64.patch
[Upstream repo](https://gitlab.com/utsushi/imagescan/) has been archived.
Update config.{guess,sub}
> addpatch: imagescan

- toolbox/riscv64.patch
> upgpatch: toolbox

- newsflash/riscv64.patch
> addpkg: newsflash

- graphviz/riscv64.patch
> updpkg: graphviz

- virtiofsd/riscv64.patch
> upgpatch: virtiofsd

- dolphin-emu/riscv64.patch
> upgpatch: dolphin-emu

- libcddb/riscv64.patch
upstream: https://sourceforge.net/p/libcddb/bugs/13/
> addpkg: libcddb

- aalib/riscv64.patch
upstream: https://sourceforge.net/p/aa-project/bugs/15/
> addpkg: aalib

- cargo-release/riscv64.patch
> upgpatch: cargo-release 0.24.9-1

- ruby-x25519/riscv64.patch
Upstream: https://github.com/RubyCrypto/x25519/pull/36
> addpatch: ruby-x25519

- librdkafka/riscv64.patch
Disable LTO due to https://github.com/confluentinc/librdkafka/issues/2426
> addpatch: librdkafka

- neovide/riscv64.patch
> upgpatch: neovide

- libappindicator/riscv64.patch
fix multi-thread bug of make install
> addpkg: libappindicator

- sequoia-wot/riscv64.patch
> updpatch: sequoia-wot

- keycloak/frontend-plugins-riscv64.patch
- keycloak/replace-nodejs.patch
- keycloak/riscv64.patch
> addpkg: keycloak

- svelte-language-server/riscv64.patch
> upgpatch: svelte-language-server

- js102/riscv64.patch
> upgpatch: js102

- python-whatthepatch/riscv64.patch
> updpkg: python-whatthepatch

- coin-or-cbc/riscv64.patch
> updpkg: coin-or-cbc

- netavark/riscv64.patch
> updpkg: netavark

- virtiofsd/riscv64.patch
Patch merged by upstream.
https://gitlab.com/virtio-fs/virtiofsd/-/merge_requests/156
> updpatch: virtiofsd

- iverilog/riscv64.patch
> updpatch: iverilog

- meilisearch/riscv64.patch
> upgpatch: meilisearch

- gifski/riscv64.patch
GitHub seems to have modified their commit patch, so vendor it instead.
> upgpatch: gifski

- chromium/riscv64.patch
> updpkg: chromium

- sorcer/riscv64.patch
> upgpatch: sorcer

- java11-openjdk/riscv64.patch
> upgpatch: java11-openjdk

- ming/riscv64.patch
Upstream bug report: https://github.com/libming/libming/issues/272
> addpatch: ming

- gavl/riscv64.patch
Upstream reports have been sent to the mailing list.
> addpatch: gavl

- linux/riscv64.patch
Make sure options that are enabled in the previous PR into the package.
> updpatch: linux 6.2.13.arch1

- linux-zen/riscv64.patch
Make sure options that are enabled in the previous PR into the package.
> updpatch: linux-zen 6.2.13.zen1

- mysql-workbench/riscv64.patch
The build error that is fixed by #1270 does not occur in this version.
> upgpatch: mysql-workbench

- java17-openjdk/riscv64.patch
> upgpatch: java17-openjdk

- qemu/riscv64.patch
> upgpatch: qemu

- java8-openjdk/riscv64.patch
Add RISC-V support(use zero jvm).
> addpatch: java8-openjdk

- jupymake/riscv64.patch
See the [upstreamed PR](https://github.com/sebasguts/JuPyMake/pull/5) for more context.
> addpatch: jupymake

- clanlib/riscv64.patch
> updpatch: clanlib

- thunderbird/riscv64.patch
> upgpatch: thunderbird

- xtrabackup/riscv64.patch
> upgpatch: xtrabackup 8.0.32_26-2

- pyalpm/riscv64.patch
See https://gitlab.archlinux.org/archlinux/pyalpm/-/merge_requests/19 for more information.
> addpatch: pyalpm

- opencv/riscv64.patch
> upgpatch: opencv

- cri-tools/riscv64.patch
> upgpatch: cri-tools 1.27.0-1

- svelte-language-server/riscv64.patch
> upgpatch: svelte-language-server 0.15.10-1

- graphviz/riscv64.patch
> upgpatch: graphviz 8.0.5-2

- nss/riscv64.patch
> upgpatch: nss 3.89.1-1

- ffmpeg4.4/riscv64.patch
- Fix rotten patch.
- See https://bugs.archlinux.org/task/78473.
> upgpatch: ffmpeg4.4 4.4.3-2

- libgpod/riscv64.patch
> upgpatch: libgpod 0.8.3-15

- sonic-visualiser/riscv64.patch
> addpatch: sonic-visualiser

- valgrind/riscv64.patch
> upgpatch: valgrind

- ghidra/add-riscv64-build.patch
- ghidra/riscv64.patch
> upgpatch: ghidra 10.3-1

- gsl/riscv64.patch
Fix config.guess issue. Upstreamed in https://lists.gnu.org/archive/html/bug-gsl/2023-05/msg00000.html
> addpatch: gsl 2.7.1

- terraform/riscv64.patch
> updpatch: terraform

- erdtree/riscv64.patch
> addpkg: erdtree

- java-commons-lang/riscv64.patch
upstreamed to arch bug tracker: https://bugs.archlinux.org/task/78492
> addpatch: java-commons-lang

- python-alt-pytest-asyncio/riscv64.patch
Upstreamed: https://github.com/delfick/alt-pytest-asyncio/pull/13
> addpatch: python-alt-pytest-asyncio

- openmpi/riscv64.patch
> updpatch: openmpi 4.1.5-2

- lychee/riscv64.patch
Fix flaky test. Upstreamed: https://github.com/lycheeverse/lychee/pull/1079
> upgpatch: lychee

- atuin/riscv64.patch
- fix ring issue
- patch libsodium-sys to fix build: https://github.com/sodiumoxide/sodiumoxide/pull/474
> addpatch: atuin

- trippy/riscv64.patch
> updgpatch: trippy 0.8.0-1

- gitlab-exporter/riscv64.patch
> updgpatch: gitlab-exporter 0.4.0-1

- sequoia-sq/riscv64.patch
Features parameters were reset to default.
> updgpatch: sequoia-sq 0.30.0-3

- libopenshot/riscv64.patch
Patch upstreamed:
- https://github.com/OpenShot/libopenshot/pull/930
- https://github.com/OpenShot/libopenshot/pull/929
> upgpatch: libopenshot

- python-shapely/riscv64.patch
Replace `x86_64` with `$CARCH`.
> addpatch: python-shapely

- atuin/riscv64.patch
> upgpatch: atuin

- openpgp-card-tools/riscv64.patch
> updpatch: openpgp-card-tools 0.9.3-1

- python-webrtcvad/add-riscv64-build.patch
- python-webrtcvad/riscv64.patch
Upstream: https://github.com/wiseman/py-webrtcvad/pull/89
> addpatch: python-webrtcvad

- ntp/riscv64.patch
> updpatch: ntp 4.2.8p16-1

- dumb-bootstrap/PKGBUILD
> addpkg: dumb-bootstrap

- libmpeg2/riscv64.patch
Fix config.guess. Upstreamed to libmpeg2-devel mailing list.
> addpatch: libmpeg2

- coin-or-coinutils/riscv64.patch
> updpkg: coin-or-coinutils

- ffmpeg4.4/riscv64.patch
> updpatch: ffmpeg4.4 4.4.4-1

- cargo-pgrx/riscv64.patch
Fixed `--target "$CARCH-unknown-linux-gnu"` and `ring` issue.
> addpkg: cargo-pgrx

- js102/riscv64.patch
> updpatch: js102 102.11.0-1

- cargo-audit/riscv64.patch
> upgpatch: cargo-audit

- repgrep/riscv64.patch
> addpkg: repgrep

- kubo/riscv64.patch
> upgpatch: kubo

- cargo-tauri/riscv64.patch
> upgpatch: cargo-tauri

- cargo-machete/riscv64.patch
> addpkg: cargo-machete

- enca/riscv64.patch
Upstream: https://github.com/nijel/enca/issues/55.
> addpkg: enca

- passenger/riscv64.patch
> updpatch: passenger 6.0.18

- qt5-webengine/riscv64.patch
> updpatch: qt5-webengine 5.15.14-2

- python-sphinx_rtd_theme/riscv64.patch
> updpkg: python-sphinx_rtd_theme

- qt6-webengine/riscv64.patch
> updpatch: qt6-webengine 6.5.1-1

- xine-lib/riscv64.patch
> updpatch: xine-lib
